--- 
knit: "bookdown::preview_chapter"
---

# Introduction {-}

Something Something

I want to include:


Equivalence Testing
Equivalence tests versus Bayes factors:

https://daniellakens.blogspot.com/search/label/Power?updated-max=2018-03-08T21:07:00%2B01:00&max-results=20&start=4&by-date=false

Equivalence Testing ROPE
https://daniellakens.blogspot.com/2017/02/rope-and-equivalence-testing.html

Absence of evidence is not evidence of absence

https://daniellakens.blogspot.com/2016/05/absence-of-evidence-is-not-evidence-of.html#comment-form

Equivalence testing vs SGPV, bayesian estimation, and bayes factors.

EQuivalence testing vs MBI
http://daniellakens.blogspot.com/2018/05/moving-beyond-magnitude-based-inferences.html



One-sided tests, lopsided tests and halving F-tests
http://daniellakens.blogspot.com/2016/03/one-sided-tests-efficient-and-underused.html


One-sided F-tests and halving p-values 



Error control

Why you don't need to adjust your alpha level for all tests you'll do in your lifetime.
https://daniellakens.blogspot.com/2016/02/why-you-dont-need-to-adjust-you-alpha.html


What’s a family     in family-wise error control?

Error rates are long run, but vary in each limited subset:
http://daniellakens.blogspot.com/2020/01/observed-alpha-levels-why-statistical.html

Justify Your Alpha by Minimizing or Balancing Error Rates 
http://daniellakens.blogspot.com/2019/05/justifying-your-alpha-by-minimizing-or.html

Preregistration

http://daniellakens.blogspot.com/2019/11/the-value-of-preregistration-for.html




Other
confidence intervals SD? http://daniellakens.blogspot.com/2019/07/calculating-confidence-intervals-around.html

The New Heuristics  - Justify Everything
http://daniellakens.blogspot.com/2019/03/the-new-heuristics.html 

Prediction Validity Theories

http://daniellakens.blogspot.com/2018/03/prediction-and-validity-of-theories.html

Verisimilitude
http://daniellakens.blogspot.com/2017/06/verisimilitude-belief-and-progress-in.html

Alpha vs betea error more important (just to make a 3d plot, see comments)
https://daniellakens.blogspot.com/2016/12/why-type-1-errors-are-more-important.html

A page on what p-hacing does and looks like? 
https://daniellakens.blogspot.com/2014/09/what-p-hacking-really-looks-like.html

A page on justifying and lowering alpha levels
https://daniellakens.blogspot.com/2014/07/why-psychologists-should-ignore.html

Sequential Analysis

The null is always false (combined with CRUD?): 
https://daniellakens.blogspot.com/2014/06/the-null-is-always-false-except-when-it.html
