<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="9 Meta-analysis | Improving Your Statistical Inferences" />
<meta property="og:type" content="book" />
<meta property="og:url" content="http://themethodsection.com/ebook/" />
<meta property="og:image" content="http://themethodsection.com/ebook/images/cover.jpg" />
<meta property="og:description" content="Online textbook to Improve Your Statistical Inferences" />


<meta name="author" content="Daniel Lakens" />

<meta name="date" content="2020-08-04" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Online textbook to Improve Your Statistical Inferences">

<title>9 Meta-analysis | Improving Your Statistical Inferences</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="center.css" type="text/css" />
<link rel="stylesheet" href="custom-msmbstyle.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Improving Your Statistical Inferences<p><p class="author">Daniel Lakens</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html">Welcome</a>
<a href="contents.html">Contents</a>
<a href="preface.html">Preface</a>
<a href="introduction.html">Introduction</a>
<a href="pvalue.html"><span class="toc-section-number">1</span> What is a <em>p</em>-value</a>
<a href="power.html"><span class="toc-section-number">2</span> Sample size justification</a>
<a href="questions.html"><span class="toc-section-number">3</span> Asking Statistical Questions</a>
<a href="errorcontrol.html"><span class="toc-section-number">4</span> Error Control</a>
<a href="effectsizesCI.html"><span class="toc-section-number">5</span> Effect Sizes and Confidence Intervals</a>
<a href="equivalencetest.html"><span class="toc-section-number">6</span> Equivalence Testing</a>
<a href="severity.html"><span class="toc-section-number">7</span> Severe Tests and Risky Predictions</a>
<a href="sesoi.html"><span class="toc-section-number">8</span> Smallest Effect Size of Interest</a>
<a id="active-page" href="meta.html"><span class="toc-section-number">9</span> Meta-analysis</a><ul class="toc-sections">
<li class="toc"><a href="#random-variation"> Random Variation</a></li>
<li class="toc"><a href="#mixed"> Mixed Results</a></li>
<li class="toc"><a href="#introduction-to-meta-analysis"> Introduction to Meta-Analysis</a></li>
</ul>
<a href="bias.html"><span class="toc-section-number">10</span> Bias detection</a>
<a href="computationalreproducibility.html"><span class="toc-section-number">11</span> Computational Reproducibility</a>
<a href="prereg.html"><span class="toc-section-number">12</span> Preregistration and Transparency</a>
<a href="bayes.html"><span class="toc-section-number">13</span> Bayesian statistics</a>
<a href="references.html"><span class="toc-section-number">14</span> References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="meta" class="section level1">
<h1>
<span class="header-section-number">9</span> Meta-analysis</h1>
<p>You can use meta-analyses to combine results in a single paper, or to evaluate effects in the literature. When combining effects in the literature, one of the main goals of a meta-analysis is to test or develop theories that can explain the variability in effect size estimates. Performing meta-analyses is relatively easy whenever you have access to the effect sizes (or the necessary information to compute effect sizes) and the sample sizes for each study. By combining information, you can achieve a much higher precision in effect size estimates.
Excellent introductions to performing and interpreting meta-analyses can be found in Borenstein et al <span class="citation">(Borenstein, <label for="tufte-mn-55" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-55" class="margin-toggle">2009<span class="marginnote">Borenstein, M. (Ed.). (2009). <em>Introduction to meta-analysis</em>. John Wiley &amp; Sons.</span>)</span> and Cummings <span class="citation">Cumming (<label for="tufte-mn-56" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-56" class="margin-toggle">2013<span class="marginnote">Cumming, G. (2013). <em>Understanding the new statistics: Effect sizes, confidence intervals, and meta-analysis</em>. Routledge.</span>)</span>.</p>
<div id="random-variation" class="section level2">
<h2>
<span class="header-section-number">9.1</span> Random Variation</h2>
<p>People find it difficult to think about random variation. Our mind is more
strongly geared towards recognizing patterns than randomness. In this
assignment, we will learn what random variation looks like, and how to reduce
variation by running well-powered studies.</p>
<div id="variation-in-single-samples" class="section level3">
<h3>
<span class="header-section-number">9.1.1</span> Variation in single samples</h3>
<p>Intelligence tests have been designed such that the mean Intelligence Quotient of the entire population of adults is 100, with a standard deviation of 15. This will not be true for every sample we draw from the population. Let’s get a feel for what the IQ scores from a sample look like. Which IQ scores will people in our sample have?</p>
<p>We will start by manually calculating the mean and standard deviation of a random sample of 10 individuals. Their IQ scores are: 91.15, 86.52, 75.64, 115.72, 95.83, 105.44, 87.10, 100.81, 82.63, and 106.22. If we sum these 10 scores and divide them by 10, we get the mean of our sample: 94.71. We can also calculate the standard deviation from our sample. First, we subtract the overall mean (94.71) from each individual IQ score. Then, we square these differences and then sum these squared differences (giving 1374.79). We divide this sum of
the squared difference by the sample size minus 1 (10-1=9), and finally take the
square root of this value, which gives the standard deviation: 12.36. Open Simulate One Group.R, select all the code, and run it, to randomly simulate 10 IQ scores, and plot them.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:plot-hist-iq-1"></span>
<img src="Statistical_Inferences_files/figure-html/plot-hist-iq-1-1.png" alt="10 random datapoints with mean = 100 and sd = 15 in the population." width="672"><!--
<p class="caption marginnote">-->Figure 9.1: 10 random datapoints with mean = 100 and sd = 15 in the population.<!--</p>-->
<!--</div>--></span>
</p>
<p>Above is one example of a randomly simulated dataset of 10 points. The grey bars indicate the frequency with which each IQ score was observed. The red dotted line illustrates the normal distribution based on the mean and sd of the population. Both the observed mean (97), as well as the observed standard deviation (14), differ from the true population values. If we simulate 4 additional datasets, we see both the mean and the standard deviation vary.</p>
<p><img src="Statistical_Inferences_files/figure-html/sim-4-iq-1.png" width="672"></p>
<p>Imagine we did not yet know what the mean IQ was in our population (where M = 100), or the standard deviation (where SD = 15), and that we would only have access to one dataset. Our estimate might be rather far off. This type of variation is perfectly normal in small samples of 10 participants, given the current standard deviation. The variability in the means is determined by the standard deviation of the measurement. In real life, the standard deviation can be reduced by for example using multiple and reliable measurements (which is why an IQ test has not just one question, but many different questions). But we can make sure our sample mean is closer to the population mean by increasing the sample size.</p>
<p>A new simulated sample with 100 participants is plotted below. We are slowly seeing what is known as the <strong>normal distribution</strong> (and the frequency scores start to resemble the red dotted line illustrating the normal distribution of the population). This is the well-known
bell shaped curve that represents the distribution of many variables in scientific research (although some other types of distributions are quite common as well). The mean and standard deviation are much closer to the true mean and standard deviation, and this is true for most of the simulated samples.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:plot-hist-iq-2"></span>
<img src="Statistical_Inferences_files/figure-html/plot-hist-iq-2-1.png" alt="100 random datapoints with mean = 100 and sd = 15 in the population." width="672"><!--
<p class="caption marginnote">-->Figure 9.2: 100 random datapoints with mean = 100 and sd = 15 in the population.<!--</p>-->
<!--</div>--></span>
</p>
<p>For a final example, let’s simulate a really large sample of 1000 observation. Not every simulated study of 1000 people will yield the true mean and standard deviation, but it will happen quite often. And although the distribution is very close to a normal distribution, even with 1000 people it is not perfect.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:plot-hist-iq-3"></span>
<img src="Statistical_Inferences_files/figure-html/plot-hist-iq-3-1.png" alt="1000 random datapoints with mean = 100 and sd = 15 in the population." width="672"><!--
<p class="caption marginnote">-->Figure 9.3: 1000 random datapoints with mean = 100 and sd = 15 in the population.<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="variance-in-two-groups-and-their-difference." class="section level3">
<h3>
<span class="header-section-number">9.1.2</span> Variance in two groups, and their difference.</h3>
<p>Now, assume we have a new IQ training program that will increase peoples IQ score with 6 points. People in condition 1 are in the control condition – they do not get IQ training. People in condition 2 get IQ training. Let’s simulate 10 people in each group, assuming the IQ in the control condition is 100, and in the experimental group is 106 (the SD is still 15 in each group).</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:plot-group1"></span>
<img src="Statistical_Inferences_files/figure-html/plot-group1-1.png" alt="Simulated sample of independent groups." width="672"><!--
<p class="caption marginnote">-->Figure 9.4: Simulated sample of independent groups.<!--</p>-->
<!--</div>--></span>
</p>
<p>The two groups differ in how close they are to their true means, and as a consequence, the difference between groups varies as well. Note that this difference is the main variable in statistical analyses when comparing two groups in for example a <em>t</em>-test. In this specific simulation, we got quite extreme results, with a score of 96 (when the population mean is 100) and a score of 111 (when the population mean is 106). So in this sample, due to random variation, we would get an overestimate of the true effect. Let’s simulate 4 additional datasets to see the variation.</p>
<div class="figure">
<span id="fig:plot-group2"></span>
<p class="caption marginnote shownote">
Figure 9.5: Four simulated samples of independent groups.
</p>
<img src="Statistical_Inferences_files/figure-html/plot-group2-1.png" alt="Four simulated samples of independent groups." width="672">
</div>
<p>We see that there is quite some variation, up to the point that in one simulation the sample means are in the opposite direction of the population means. Again, increasing the sample size will mean that, in the long run, the sample means will get closer to the population means, and that we are more accurately estimation the difference between conditions. With 250 observations in each group, a randomly simulated set of observations for the two groups might look like Figure <a href="meta.html#fig:plotgroup3">9.6</a>. Note that this difference might not look impressive, but when you perform an independent <em>t</em>-test, the difference would pass a significance test with a very low alpha level. It is always recommended to plot your raw data.</p>
<div class="figure">
<span id="fig:plotgroup3"></span>
<p class="caption marginnote shownote">
Figure 9.6: Simulated sample of 250 independent observations
</p>
<img src="Statistical_Inferences_files/figure-html/plotgroup3-1.png" alt="Simulated sample of 250 independent observations" width="672">
</div>
</div>
<div id="correlations-between-two-groups" class="section level3">
<h3>
<span class="header-section-number">9.1.3</span> Correlations between two groups</h3>
<p>Now let’s simulate a correlation between two variables. We will continue with our example of IQ scores, but now we search for fraternal (so not identical) twins, and measure their IQ. From the literature, we know the true correlation of IQ scores between fraternal twins is around r = 0.55. We find 30 fraternal twins, measure their IQ’s, and plot the relation between the IQ of both individuals. In this simulation, we assume all twins have a mean IQ of 100 with a standard deviation of 15.</p>
<p>The correlation is calculated based on the IQ scores of one fraternal twin (x) and the IQ scores of the other fraternal twin (y) for each pair of twins, and the total number of pairs (N). In the numerator of the formula, the number of pairs is multiplied by the sum of the product of x and y, and from this value the sum of x multiplied by the sum of y is subtracted. In the denominator, the square root is taken from the number of pairs multiplied by the sum of x squared, from which the sum of x, which is then squared, is subtracted, and multiplied by the same calculation but now for y.</p>
<p><span class="math display">\[r=\frac{n \Sigma x y-(\Sigma x )(\Sigma y)}{\sqrt{[n \Sigma x^{2}-(\Sigma x)^{2}][n \Sigma y^{2}-(\Sigma y)^{2}]}}\]</span>
When we randomly simulate observations for 30 twins, we get the following result.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:plot-cor1"></span>
<img src="Statistical_Inferences_files/figure-html/plot-cor1-1.png" alt="Correlation based on 30 pairs." width="672"><!--
<p class="caption marginnote">-->Figure 9.7: Correlation based on 30 pairs.<!--</p>-->
<!--</div>--></span>
</p>
<p>On the x-axis, we see the IQ score of one twin, and one the y-axis we see the IQ score of the second twin. The black dotted diagonal line illustrates the true correlation (0.55), while the yellow line shows the observed correlation (in this case, r = 0.43). The slope of the yellow line is determined by the observed correlation, but the position of the line is influenced by the mean IQ scores in both groups (in this simulation, the mean on the y-axis is 105, somewhat below 100, and the mean on the x-axis is 102, also slightly above 100. The blue area is the 95% confidence interval around the observed correlation. As we saw in the section on <a href="effectsizesCI.html#confint">confidence intervals</a>, 95% of the time (in the long run) the blue area will contain the true correlation (the dotted black line). Increasing the sample size to 300 narrows the confidence interval considerably, and will guarantee that the sample correlation is much closer to the true correlation.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:plot-cor2"></span>
<img src="Statistical_Inferences_files/figure-html/plot-cor2-1.png" alt="Correlation based on 30 pairs." width="672"><!--
<p class="caption marginnote">-->Figure 9.8: Correlation based on 30 pairs.<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="confidence-intervals-around-standard-deviations." class="section level3">
<h3>
<span class="header-section-number">9.1.4</span> Confidence Intervals around Standard Deviations.</h3>
<p>If we calculate a standard deviation (SD) from a sample, this value is an estimate of the true value in the population. In small samples, our estimate can be quite far off (as we already saw when simulation single samples above). But due to the law of large numbers, as our sample size increases, we will be measuring the standard deviation more accurately. Since the sample standard deviation is an estimate with uncertainty, we can calculate a 95% confidence interval around it.</p>
<p>Expressing the uncertainty in our estimate of the standard deviation can be useful. When researchers plan to simulate data, or perform an a-priori power analysis, they need accurate estimates of the standard deviation. For simulations, the standard deviation needs to be accurate because we want to generate data that will look like the real data we will eventually collect. For power analyses, we often want to think about the smallest effect size of interest (SESOI), which can be specified as the difference in means which you care about. To perform a power analysis, we also need to specify the expected standard deviation of the data. Sometimes researchers will use pilot data to get an estimate of the standard deviation. Since the estimate of the population standard deviation based on a pilot study has some uncertainty, confidence intervals might be a useful way to quantify the amount of uncertainty. We can calculate the confidence interval around a standard deviation as follows:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="meta.html#cb86-1"></a>alpha_level &lt;-<span class="st"> </span><span class="fl">0.05</span> <span class="co">#set alpha level</span></span>
<span id="cb86-2"><a href="meta.html#cb86-2"></a>n &lt;-<span class="st"> </span><span class="dv">100</span> <span class="co">#set number of observations</span></span>
<span id="cb86-3"><a href="meta.html#cb86-3"></a>st_dev &lt;-<span class="st"> </span><span class="dv">15</span> <span class="co">#set true standard deviation</span></span>
<span id="cb86-4"><a href="meta.html#cb86-4"></a></span>
<span id="cb86-5"><a href="meta.html#cb86-5"></a><span class="co"># calculate lower and upper critical values c_l and c_u</span></span>
<span id="cb86-6"><a href="meta.html#cb86-6"></a>c_l &lt;-<span class="st"> </span><span class="kw">sqrt</span>((n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span><span class="kw">qchisq</span>(alpha_level<span class="op">/</span><span class="dv">2</span>, n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>))</span>
<span id="cb86-7"><a href="meta.html#cb86-7"></a>c_u &lt;-<span class="st"> </span><span class="kw">sqrt</span>((n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span><span class="kw">qchisq</span>(alpha_level<span class="op">/</span><span class="dv">2</span>, n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">TRUE</span>))</span>
<span id="cb86-8"><a href="meta.html#cb86-8"></a></span>
<span id="cb86-9"><a href="meta.html#cb86-9"></a><span class="co"># calculate lower and upper confidence interval for sd</span></span>
<span id="cb86-10"><a href="meta.html#cb86-10"></a><span class="kw">c</span>(st_dev <span class="op">*</span><span class="st"> </span>c_l, st_dev <span class="op">*</span><span class="st"> </span>c_u)</span></code></pre></div>
<pre><code>## [1] 13.17010 17.42513</code></pre>
<p>You can also use <a href="https://www.graphpad.com/quickcalcs/CISD1.cfm">this free GraphPad calculator</a> to calculate confidence intervals for standard deviations. If you need to estimate the standard deviation for an a-priori power analysis, the accuracy of the estimate of the standard deviation will depend on the sample size. Keep into account that <strong>estimates of the standard deviation have uncertainty</strong>. Use <strong>validated or existing measures for which accurate estimates of the standard deviation in your population of interest are available</strong>, so that you can rely on a better estimate of the standard deviation in power analyses.</p>
</div>
</div>
<div id="mixed" class="section level2">
<h2>
<span class="header-section-number">9.2</span> Mixed Results</h2>
<p>Science is a cumulative process, and we should evaluate lines of research, not single studies. Researchers are advised to design studies that will provide informative data, but sometimes you need to look at sets of studies before patterns become clear. A commonly used lower limit for statistical power is 80%, which means you will find a non-significant result in one out of five studies, when there is a true effect. Whenever you perform studies where power is not 99.99%, you should expect to find mixed results when examining true effects. Indeed, some researchers have pointed out that <em>not</em> finding mixed results can be very unlikely (or ‘too good to be true’) in a set of studies <span class="citation">(Francis, <label for="tufte-mn-57" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-57" class="margin-toggle">2014<span class="marginnote">Francis, G. (2014). The frequency of excess success for articles in Psychological Science. <em>Psychonomic Bulletin &amp; Review</em>, <em>21</em>(5), 1180–1187. <a href="https://doi.org/10.3758/s13423-014-0601-x">https://doi.org/10.3758/s13423-014-0601-x</a></span>; Schimmack, <label for="tufte-mn-58" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-58" class="margin-toggle">2012<span class="marginnote">Schimmack, U. (2012). The ironic effect of significant results on the credibility of multiple-study articles. <em>Psychological Methods</em>, <em>17</em>(4), 551–566. <a href="https://doi.org/10.1037/a0029487">https://doi.org/10.1037/a0029487</a></span>)</span>. We don’t have a very good feeling for what real patterns of studies look like, because we are continuously exposed to a scientific literature that does not reflect reality. Almost all multiple study papers in the scientific literature present only statistically significant results, even though this is unlikely.</p>
<div id="likelihoods-of-sets-of-studies" class="section level3">
<h3>
<span class="header-section-number">9.2.1</span> Likelihoods of sets of studies</h3>
<p>Let’s imagine we have two bags. There are twenty marbles in each bag. In one bag, we know there are 19 blue marbles, and one red marble. The red marble represents a Type 1 error, the blue marbles represent true negatives, and this bag represents a situation where we perform a statistical test where the null-hypothesis is true. In the other bag, there is a number of blue and red marbles. The red marbles represent true positives, blue marbles represent false negatives, and this bag represents a situation where the alternative hypothesis is true. We don’t know the true power, or the percentage of red marbles, but we can make a guess. For example, we might believe 16 out of 20 (or 80%) of the marbles are red.</p>
<p>We perform 3 studies, by drawing a marble three times (with replacement, so we can draw multiple red balls in a row from either bag) from one of the two bags. We don’t know which of the bags we are drawing from. We could be drawing from the bag where the null hypothesis is true or the bag where the alternative hypothesis is true. There are 4 possible outcomes. Either 0 out of 3, 1 out of 3, 2 out of 3, or 3 out of 3 red balls are drawn. We can plot these four likelihood curves (see the section on <a href="bayes.html#likelihoods">likelihoods</a>.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:likelihood4curves"></span>
<img src="Statistical_Inferences_files/figure-html/likelihood4curves-1.png" alt="Four likelihood curves for observing 0, 1, 2, or 3 out of 3 significant results in 3 studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.9: Four likelihood curves for observing 0, 1, 2, or 3 out of 3 significant results in 3 studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>Each curve has the maximum likelihood estimate at the outcome: θ = 0 for 0 out of 3 red balls, θ = 0.33 for 1 out of 3, θ = 0.66 for 2 out of 3, and θ = 1 for 3 out of 3. We know that for the bag where the null hypothesis is true, θ =0.05, or the Type 1 error rate. If we believe our studies would have 80% power when the alternative hypothesis is true, we can assume θ = 0.8. In Figure <a href="meta.html#fig:likelihood4curves">9.9</a> we see the four likelihood curves, and two vertical lines at θ = 0.05 and θ = 0.8. We can calculate likelihood ratios for θ = 0.05 vs. θ = 0.80 for the different outcomes. Below, the likelihood ratios are visualized for 1 out of 3 and 2 out of 3 red balls, or significant results. We see that only 1 out of 3 findings (below, left) is slightly more likely when the null hypothesis is true, but the likelihood ratio of 0.71 is not very far from 1. However, with 2 out of 3 significant results (below, right), it is clear that this result is much more likely when studies are performed with 80% power than if we assume we observed two out of three Type 1 errors. Indeed, when two out of three studies are significant, the likelihood ratio provides pretty strong relative evidence for a situation where the alternative hypothesis is true, even when the assumed power is much lower.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:likelihoodcurve1"></span>
<img src="Statistical_Inferences_files/figure-html/likelihoodcurve1-1.png" alt="Likelihood curves for observing 1 out of 3 significant results in 3 studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.10: Likelihood curves for observing 1 out of 3 significant results in 3 studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:likelihoodcurve2"></span>
<img src="Statistical_Inferences_files/figure-html/likelihoodcurve2-1.png" alt="Likelihood curves for observing 2 out of 3 significant results in 3 studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.11: Likelihood curves for observing 2 out of 3 significant results in 3 studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>Although we can’t formally evaluate the probability that the alternative hypothesis is true based on these likelihood ratios (we would need Bayesian statistics instead), we can see that when multiple studies are performed, but not all studies are statistically significant, we might still be gathering evidence for the hypothesis that we are examining a true effect. This might be surprising, because we never see what real research looks like due to publication bias, mixed results are both common and can be evidence for a true effect.</p>
<p>Figure <a href="meta.html#fig:likelihood4curves">9.9</a> also shows when a researcher is more likely to observe mixed results than consistent results. This occurs for all values of θ where the likelihood curve for mixed results is higher than the likelihood curves for 0 out of <em>n</em>, or <em>n</em> out of <em>n</em> significant results. More formally, mixed results are more likely than consistent results when power drops below <em>n</em>/(<em>n</em>+1) percent, or increases above 1-(<em>n</em>/(<em>n</em>+1)). For example, when performing three studies, it is more likely to observe mixed results than only significant or only non-significant effects when power is lower than 3/(3+1)=0.75, and higher than 1-(3/(3+1))=0.25.</p>
<p>To examine how often you should observe mixed results, open the online shiny app that will perform these binomial likelihood
calculations for you: <a href="http://shiny.ieis.tue.nl/mixed_results_likelihood/" class="uri">http://shiny.ieis.tue.nl/mixed_results_likelihood/</a>. The app displays binomial likelihoods for sets of studies. By default, the settings in the app show the results for a situation when 2 out of 3 studies are significant, a Type 1 error rate of 5% is used, and the power for the studies is assumed to be 80%. The text below the figure shows that 2 out of 3 significant results should happen 38% of the time when there is a true effect, and power is 80%. Scroll down, and take a look at the table. In the left column, you can see the probabilities of 0, 1, 2, or 3 significant results when there is no effect (so you only observe Type 1 errors), and in the right columns you can see these probabilities for when there is a true effect.</p>
<p>From this table, we can see that when you perform 3 studies, H1 is true, alpha = 0.05, and power = 0.80, it is only slightly more likely to observe 3 significant results out of 3 studies (51.2%) then it is to find mixed results (1 or 2 significant studies, 9.6 + 38.4 = 48%).</p>
<p>Sometimes in lines of three studies, you’ll find a significant effect in one study, but there is no effect in the other two related studies. Assume the two related studies were not exactly the same in every way (e.g., you have changed the manipulation, or the procedure, or some of the questions). It could be that the two other studies did not work because of minor differences that had some effect you do not fully understand yet. Or it could be that the single significant result was a Type 1 error, and H0 was true in all three studies. In the same table, we can see that All else being equal, the probability of a Type 1 error in one of three studies is 13.5% when there is no true effect in all three studies, and the probability of finding exactly 1 in three significant effects, assuming 80% power in all three studies (and thus a true effect), is 9.6%, which is slightly, but not substantially less likely. In other words, Finding only 1 out of 3 significant results is more likely when the null hypothesis is true.</p>
<p>However, if we find 2 out of 3 significant results, as indicated in Figure <a href="meta.html#fig:likelihoodcurve2">9.11</a> it is 0.384/0.007125 = 53.89 times more likely to have observed these results when H1 is true, than when H0 is true. When the observed results are equally likely under H0 and H1, the likelihood ratio is 1. Benchmarks to interpret Likelihood Ratios suggest that when 1&lt;LR&lt;8 there is weak evidence, when 8&lt;LR&lt;32 there is moderate evidence, and when LR&gt;32, there is strong evidence. Play around in the app to see how probable it is to find mixed results, and what the likelihood ratio is in favor of the alternative hypothesis, for different mixed results.</p>
<p>The main take home message of these calculations is to understand that 1) mixed results are supposed to happen, and 2) mixed results can contain strong evidence for a true effect, across a wide range of plausible power values. The app also tells you how much evidence, in a rough dichotomous way, you can expect. This is useful for our educational goal. But when you want to evaluate results from multiple studies, the formal way to do so is by performing a meta-analysis.</p>
<p>The above calculations make a very important assumption: The Type 1 error rate is controlled at 5%. If you try out many different tests in each study, and only report the result that yielded a p &lt; 0.05, these calculations no longer hold. Go back to the default settings of 2 out of 3 significant results, but now set the Type 1 error rate to 20%, to reflect a modest amount of p-hacking. Under these circumstances, the <strong>highest</strong> likelihood in favor of H1 you can get if you explore all possible values for the true power is approximately 4.63, which is not convincing evidence at all. As this shows, <em>p</em>-hacking makes studies extremely uninformative. <strong>If you inflate the error rate, you quickly destroy the evidence in the data.</strong> You can no longer determine whether the data is more likely when there is no effect, than when there is an effect.</p>
<p>Sometimes researchers complain that people who worry about <em>p</em>-hacking and try to promote better Type 1 error control are missing the point, and that other things (better measurement, better theory, etc.) are more important. I fully agree that these aspects of scientific research are at least as important as better error control. But better measures
and theories will require decades of work. Better error control can be
accomplished today, if researchers would stop inflating their error rates by flexibly analyzing their data. And as this assignment shows, inflated rates of false positives very quickly make it difficult to learn what is true from the data we collect. Because of the relative ease with which this part of scientific research can be improved, and because we can achieve this today (and not in a decade) I think it is worth stressing the importance of error control, and publish more realistic looking sets of studies.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
Some ‘prestigious’ journals (which, when examined in terms of scientific quality such as reproducibility, reporting standards, and policies concerning data and material sharing, are quite low quality despite their prestige) only publish manuscripts with a large number of studies, which should all be statistically significant. If we assume an average power in psychology of 50%, only 3.125% of 5 study articles should contain exclusively significant results. If you pick up a random issue from such a prestigious journal, and see 10 articles, each reporting 5 studies, and all manuscripts have exclusively significant results, would you trust the reported findings more, or less, than when all these articles had reported mixed results?
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Unless you will power all your studies at 99.99% for the rest of your career (which would be slightly inefficient, but great if you don’t like insecurity), you will observe mixed results in lines of research. One way to share mixed results is by performing a meta-analysis, which is what we will discuss next. The take-away message of this part is that you should expect mixed results under many circumstances, and that dichotomously ignoring non-significant results is not wise. A formal meta-analysis is the best way to evaluate sets of studies. Understanding what realistic patterns of results in research lines
should look like is hopefully a first step in making you realize you should think meta-analytically.</p>
</div>
</div>
<div id="introduction-to-meta-analysis" class="section level2">
<h2>
<span class="header-section-number">9.3</span> Introduction to Meta-Analysis</h2>
<p>Every single study is just a data-point in a future meta-analysis. If you draw small samples from a population, the mean and standard deviation in the sample can differ considerably from the mean and standard deviation in the population. There is great variability in small samples. Parameter estimates from small samples are very imprecise, and therefore the 95% confidence intervals around effect sizes are very wide. Indeed, this led Cohen (1994) to write “I suspect that the main reason [confidence intervals] are not reported is that they are so embarrassingly large!” If we want a more precise estimate of our parameter of interest, such as the mean difference or correlation in the population, we need either run extremely large single studies, or alternatively, combine data from several studies by performing a <strong>meta-analysis</strong>. The most common approach to combine studies is to perform a meta-analysis of effect size estimates.</p>
<p>You can perform a meta-analysis for a set of studies in a single article you plan to publish (often called an <strong>internal meta-analysis</strong>), or you can search the literature for multiple studies reported in as many different articles as possible, and perform a meta-analysis on all studies others have published. An excellent introduction to meta-analyses is provided in the book by Borenstein, Hedges, Higgins, and Rothstein <span class="citation">(Borenstein, <label for="tufte-mn-59" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-59" class="margin-toggle">2009<span class="marginnote">Borenstein, M. (Ed.). (2009). <em>Introduction to meta-analysis</em>. John Wiley &amp; Sons.</span>)</span>. There is commercial software you can use to perform meta-analyses, but I highly recommend <em>against</em> using such software. Almost all commercial software packages lack transparency, and do not allow you to share your analysis code and data with other researchers. In this assignment, we will be using R to perform a meta-analysis of effect sizes, using the <strong>metafor</strong> package by Viechtbauer <span class="citation">Viechtbauer (<label for="tufte-mn-60" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-60" class="margin-toggle">2010<span class="marginnote">Viechtbauer, W. (2010). Conducting meta-analyses in R with the metafor package. <em>J Stat Softw</em>, <em>36</em>(3), 1–48.</span>)</span>. An important benefit of using metafor is that your meta-analysis can be made completely reproducible.</p>
<div id="single-study-meta-analysis" class="section level3">
<h3>
<span class="header-section-number">9.3.1</span> Single study meta-analysis</h3>
<p>Let’s first begin with something you will hardly ever do in real life: a meta-analysis of a single study. This is a little silly, because a simple <em>t</em>-test or correlation will tell you the same thing – but it is educational to compare a <em>t</em>-test with a meta-analysis of a single
study, before we look at how to combine multiple studies into a meta-analysis.</p>
<p>A difference between an independent <em>t</em>-test and a meta-analysis is that a <em>t</em>-test is performed on the raw data, while a meta-analysis is performed on the effect size(s) of individual studies. The metafor R package contains a very useful function called <code>escalc</code> that can be used to calculate effect sizes, their variances, and confidence intervals around effect size estimates. So let’s start by calculating the effect size to enter into our meta-analysis. The code below (and in the R file under <strong>Part 1</strong>) can be used to calculate the <strong>standardized mean difference</strong> (SMD) from two independent groups from <strong>means</strong> (specified by m1i and m2i), <strong>standard deviations</strong> (sd1i and sd2i), and the number of observations in each group (n1i and n2i). By default, metafor calculates the effect size ‘<strong>Hedges’ g</strong>’ which is the unbiased version of Cohen’s d (see the section on <a href="effectsizesCI.html#cohend">Cohen’s d</a> in the chapter on Effect Sizes).</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="meta.html#cb88-1"></a><span class="kw">library</span>(metafor)</span>
<span id="cb88-2"><a href="meta.html#cb88-2"></a><span class="co"># We calculate the standardized mean difference</span></span>
<span id="cb88-3"><a href="meta.html#cb88-3"></a><span class="co"># We store it as the variable g (because by default, Hedges' g is computed)</span></span>
<span id="cb88-4"><a href="meta.html#cb88-4"></a>g &lt;-<span class="st"> </span><span class="kw">escalc</span>(<span class="dt">measure =</span> <span class="st">"SMD"</span>,</span>
<span id="cb88-5"><a href="meta.html#cb88-5"></a>            <span class="dt">n1i =</span> <span class="dv">50</span>, <span class="co"># sample size in group 1 is 50 </span></span>
<span id="cb88-6"><a href="meta.html#cb88-6"></a>            <span class="dt">m1i =</span> <span class="fl">5.6</span>, <span class="co"># observed mean in group 1 is 5.6</span></span>
<span id="cb88-7"><a href="meta.html#cb88-7"></a>            <span class="dt">sd1i =</span> <span class="fl">1.2</span>, <span class="co"># observed standard deviation in group 1 is 1.2</span></span>
<span id="cb88-8"><a href="meta.html#cb88-8"></a>            <span class="dt">n2i =</span> <span class="dv">50</span>, <span class="co"># sample size in group 2 is 50 </span></span>
<span id="cb88-9"><a href="meta.html#cb88-9"></a>            <span class="dt">m2i =</span> <span class="fl">4.9</span>, <span class="co"># observed mean in group 1 is 4.9 </span></span>
<span id="cb88-10"><a href="meta.html#cb88-10"></a>            <span class="dt">sd2i =</span> <span class="fl">1.3</span>) <span class="co"># observed standard deviation in group 2 is 1.3</span></span>
<span id="cb88-11"><a href="meta.html#cb88-11"></a></span>
<span id="cb88-12"><a href="meta.html#cb88-12"></a><span class="co"># print results</span></span>
<span id="cb88-13"><a href="meta.html#cb88-13"></a>g</span></code></pre></div>
<pre><code>##       yi     vi 
## 1 0.5553 0.0415</code></pre>
<p>The output gives you Hedge’s g (under the <code>yi</code> column, which always returns the effect size, in this case the standardized mean difference) and the variance of the effect size estimate (under <code>vi</code>).</p>
<p>As explained in Borenstein, Hedges, Higgins, and Rothstein (2009, formula 4.18 to 4.24) the standardized mean difference Hedges’ g is calculated by dividing the difference between means by the pooled standard deviation, multiplied by a correction factor, J:</p>
<p><span class="math display">\[
J = (1 - \ \ 3/(4df - 1))
\]</span></p>
<p><span class="math display">\[
g = J \times \ \left( \frac{{\overline{X}}_{1} - {\overline{X}}_{2}}{S_{\text{within}}} \right)
\]</span></p>
<p>and a very good approximation of the variance of the standardized mean
difference (SMD) Hedges’ g is provided by:</p>
<p><span class="math display">\[
Vg = J^{2} \times \left( \frac{n_{1} + n_{2}}{n_{1}n_{2}} + \frac{g^{2}}{2(n_{1} + n_{2})} \right)
\]</span></p>
<p>The variance of the standardized mean difference depends only on the sample size (n1 and n2) and the value of the standardized mean difference itself. <strong>To perform the required calculations for a meta-analysis, you need the effect sizes and their variance</strong>. This means that if you have coded the effect sizes and the sample sizes (per group) from studies in the literature, you have the information you need to perform a meta-analysis.</p>
<p>You do not need to manually calculate the effect size and its variance using the two formula above – the escalc function does this for you. We can now easily perform a single study meta-analysis using the rma function in the metafor package:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="meta.html#cb90-1"></a><span class="co"># Perform the meta-analysis</span></span>
<span id="cb90-2"><a href="meta.html#cb90-2"></a>meta_res &lt;-<span class="st"> </span><span class="kw">rma</span>(yi, vi, <span class="dt">data =</span> g)</span>
<span id="cb90-3"><a href="meta.html#cb90-3"></a>meta_res</span></code></pre></div>
<pre><code>## 
## Fixed-Effects Model (k = 1)
## 
## I^2 (total heterogeneity / total variability):   0.00%
## H^2 (total variability / sampling variability):  1.00
## 
## Test for Heterogeneity:
## Q(df = 0) = 0.0000, p-val = 1.0000
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.5553  0.2038  2.7243  0.0064  0.1558  0.9547  ** 
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Here, we see under Model Results the effect size Hedges’ g (0.5553) and the standard error (0.2038), the Z-test statistic testing the mean difference against the null-hypothesis (2.72), and the 95% confidence interval [ci.lb = 0.16; ci.ub = 0.95] around the effect size (the interval width can be specified using the ‘level =’ option). We also get the <em>p</em>-value for the test of the meta-analytic effect size against 0. In this case we can reject the null-hypothesis (<em>p</em> = 0.0064).</p>
<p>In a meta-analysis, a Z-test is used to examine whether the null-hypothesis can be rejected. This assumes a normally distributed random effect size model. Normally, you would analyze data from a single study with two groups using a <em>t</em>-test, which not surprisingly uses a <em>t</em>-distribution. If we directly compare a single-study meta-analysis, based on a Z-test, with a normal <em>t</em>-test, we will see some tiny differences in the results. We can directly calculate the effect size Hedges’ g, and the 95% confidence interval around the effect size, and the <em>t</em>-test using MOTE <span class="citation">(Buchanan et al., <label for="tufte-mn-61" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-61" class="margin-toggle">2017<span class="marginnote">Buchanan, E. M., Scofield, J., &amp; Valentine, K. D. (2017). <em>MOTE: Effect Size and Confidence Interval Calculator.</em></span>)</span>. The MOTE package uses the <em>t</em>-distribution when calculating confidence intervals around the effect size (and we can see this makes only a tiny difference compared to using the Z-distribution in a meta-analysis with 50 observations in each group).</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="meta.html#cb92-1"></a><span class="co"># Calculate Hedges g and perform t-test with MOTE </span></span>
<span id="cb92-2"><a href="meta.html#cb92-2"></a>MOTE_res &lt;-<span class="st"> </span>MOTE<span class="op">::</span><span class="kw">g.ind.t</span>(<span class="dt">m1 =</span> <span class="fl">5.6</span>, </span>
<span id="cb92-3"><a href="meta.html#cb92-3"></a>                          <span class="dt">m2 =</span> <span class="fl">4.9</span>, </span>
<span id="cb92-4"><a href="meta.html#cb92-4"></a>                          <span class="dt">sd1 =</span> <span class="fl">1.2</span>, </span>
<span id="cb92-5"><a href="meta.html#cb92-5"></a>                          <span class="dt">sd2 =</span> <span class="fl">1.3</span>, </span>
<span id="cb92-6"><a href="meta.html#cb92-6"></a>                          <span class="dt">n1 =</span> <span class="dv">50</span>, </span>
<span id="cb92-7"><a href="meta.html#cb92-7"></a>                          <span class="dt">n2 =</span> <span class="dv">53</span>, </span>
<span id="cb92-8"><a href="meta.html#cb92-8"></a>                          <span class="dt">a =</span> <span class="fl">0.05</span>)</span>
<span id="cb92-9"><a href="meta.html#cb92-9"></a>MOTE_res<span class="op">$</span>statistic</span></code></pre></div>
<pre><code>## [1] "$t$(101) = 2.83, $p$ = 0.00553819625499491"</code></pre>
<p>The <em>t</em>-value is 2.83, and the <em>p</em>-value is 0.0055. With large enough sample sizes (which is commonly true in a meta-analysis) the difference between a Z-test and <em>t</em>-test is not really meaningful, and for this reason the Z-test is used in meta-analyses.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="meta.html#cb94-1"></a><span class="co"># Calculate Hedges g with MOTE </span></span>
<span id="cb94-2"><a href="meta.html#cb94-2"></a>MOTE_res<span class="op">$</span>estimate</span></code></pre></div>
<pre><code>## [1] "$d_{g}$ = 0.55, 95\\% CI [0.16, 0.94]"</code></pre>
<p>The results are very similar to those from the meta-analysis, with g = 0.55, 95% CI[0.16;0.94], where the effect size and the upper bound for the confidence interval differ 0.01 after rounding, because the <em>t</em>-distribution is used instead of the Z-distribution.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:metaforest"></span>
<img src="Statistical_Inferences_files/figure-html/metaforest-1.png" alt="Forest plot for a single study." width="672"><!--
<p class="caption marginnote">-->Figure 9.12: Forest plot for a single study.<!--</p>-->
<!--</div>--></span>
</p>
<p>It is common to visualize the results of a meta-analysis using a forest plot. We see the effect size for Study 1 marked by the black square at 0.05, and the confidence interval is visualized by lines extending to –0.34 on the left and 0.44 on the right. The numbers are printed on the right-hand side of the forest plot. On the lower half of the forest plot, we see a stretched-out diamond. The diamond summarizes the meta-analytic effect size estimate, with the center being at the meta-analytic effect size estimate, and the left and right endpoints at the 95% confidence interval of the meta-analytic effect size estimate. Because we only have a single study, the meta-analytic effect size estimate is the same as the effect size estimate for our single study.</p>
<p>Meta-analyses get a bit more exciting when we are using them to analyze results
from multiple studies. When multiple studies are combined in a meta-analysis,
effect size estimates are not simply averaged, but they are <strong>weighted</strong> by the
<strong>precision</strong> of the effect size estimate, which is determined by the sample
size of the study. Thus, the larger the sample size of an individual study, the
more weight it gets in the meta-analysis, meaning that it has more influence on
the meta-analytic effect size estimate.</p>
</div>
<div id="simulating-meta-analyses-of-mean-standardized-differences" class="section level3">
<h3>
<span class="header-section-number">9.3.2</span> Simulating meta-analyses of mean standardized differences</h3>
<p>One intuitive way to learn about meta-analyses is to simulate single studies, and combine these in a meta-analysis.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:meta-sim"></span>
<img src="Statistical_Inferences_files/figure-html/meta-sim-1.png" alt="Forest plot for 12 simulated studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.13: Forest plot for 12 simulated studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>We see 12 rows, one for each study, each with their own effect size and confidence interval. If you look closely, you can see the squares that indicate the effect size estimate for each study differ in size. The larger the sample size, the bigger the square. Study 3 had a relatively small sample size, which can be seen both by the small square, and the relatively wide confidence interval. Study 2 had a larger sample size, and thus a slightly larger square
and narrower confidence interval. At the bottom of the graph we find the meta-analytic effect size and its confidence interval, both visualized by a diamond and numerically. The model is referred to as a FE Model, or <strong>Fixed Effect (FE) model</strong>. The alternative approach is a RE Model, or <strong>Random Effects (RE) model</strong> (the difference is discussed below).</p>
<p>You might notice that the first two studies in the meta-analysis were not statistically significant. Take a moment to think for yourself if you would have continued this research line, after not finding an effect twice in a row. If you feel like it, run the code above several times (remove the set.seed or you will get the same result each time) and see how often this happens with a population effect size and range of sample sizes in this simulation. As should be clear from the section on <a href="meta.html#mixed">mixed results</a>, it is important to think meta-analytically, because in the long run there will be situations where you will find one or two non-significant results early in a research line, even when there is a true effect.</p>
<p>Let’s also look at the result of the meta-analysis, which is a bit more interesting now that we have 12 studies:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="meta.html#cb96-1"></a>result</span></code></pre></div>
<pre><code>## 
## Fixed-Effects Model (k = 12)
## 
## I^2 (total heterogeneity / total variability):   0.00%
## H^2 (total variability / sampling variability):  0.83
## 
## Test for Heterogeneity:
## Q(df = 11) = 9.1824, p-val = 0.6051
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.3655  0.0564  6.4777  &lt;.0001  0.2549  0.4761  *** 
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>We see a test for <strong>heterogeneity</strong>, a topic we will return to <a href="meta.html#heterogeneity">below</a>. We see the model results, which in this specific simulation yielded a meta-analytic effect size estimate of 0.37. The confidence interval around the effect size estimate [0.25; 0.48] is much narrower than we saw before for a single study. This is because the 12 studies we simulated together have quite a large sample size, and the larger the sample size, the smaller the standard error, and thus the narrower the confidence interval is. The meta-analytic effect size estimate is statistically different from 0 (<em>p</em> &lt; 0.0001) so we can reject the null hypothesis if we use an alpha level of 0.05.</p>
</div>
<div id="fixed-effect-vs-random-effects" class="section level3">
<h3>
<span class="header-section-number">9.3.3</span> Fixed Effect vs Random Effects</h3>
<p>There are two possible models when performing a meta-analysis. One model, known as a fixed effect model, assumes there is one effect size that generates the data in all studies in the meta-analysis. This model assumes there is no variation between individual studies – all have exactly the same true effect size. The perfect example of this is the simulations we have done so far. We specified a single true effect in the population, and generated random samples
from this population effect.</p>
<p>Alternatively, one can use a model where the true effect differs in some way in each individual study. We don’t have a single true effect in the population, but a range of <strong>randomly distributed</strong> true effect sizes (hence the ‘random effects’ model). Studies differs in some way from each other (or some sets of studies differ from other sets), and their true effect sizes differ as well. Note the difference between a fixed effect model, and a random effect<strong>s</strong> model, in that the plural ‘effects’ is used only in the latter. Borenstein et al
(2009) state there are two reasons to use a fixed effect model: When all studies are functionally equivalent, and when your goal is <em>not</em> to generalize to other populations. This makes the random effects model generally the better choice, although some people have raised the concern that random-effects models give more weight to smaller studies, which can be more biased. By default, metafor will use a random effects model. We used the method=“FE” command to explicitly ask for a fixed effect model. In the meta-analyses we will simulate in the rest of this assignment we will leave out this command and simulate random effects meta-analyses.</p>
</div>
<div id="simulating-meta-analyses-for-dichotomous-outcomes" class="section level3">
<h3>
<span class="header-section-number">9.3.4</span> Simulating meta-analyses for dichotomous outcomes</h3>
<p>Although meta-analyses on mean differences are very common, a meta-analysis can be performed on many different effect sizes. To show a slightly less common example, let’s simulate a meta-analysis based on odds ratios. Sometimes the main outcome in an experiment is a dichotomous variable, such as the success or failure on a task. In such study designs we can calculate risk ratios, odds ratios, or risk differences as the effect size measure. Risk differences are sometimes judged easiest to interpret, but odds ratios are most often used for a meta-analysis because they have attractive statistical properties. An <strong>odds ratio</strong> is a ratio of two odds. To illustrate how an odds ratio is calculated, it is useful to consider the four possible outcomes in a 2 x 2 table of outcomes:</p>
<table>
<thead><tr class="header">
<th></th>
<th>Success</th>
<th>Failure</th>
<th>N</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Experimental</td>
<td><em>A</em></td>
<td><em>B</em></td>
<td><em>n1</em></td>
</tr>
<tr class="even">
<td>Control</td>
<td><em>C</em></td>
<td><em>D</em></td>
<td><em>n2</em></td>
</tr>
</tbody>
</table>
<p>The odds ratio is calculated as:
<span class="math display">\[OR = \ \frac{\text{AD}}{\text{BC}}\]</span>
The meta-analysis is performed on log transformed odds ratios (because log transformed odds ratios are symmetric around 1, see Borenstein et al., 2009), and thus the log of the odds ratio is used, which has a variance which is approximated by:
<span class="math display">\[\text{Var}\left( \log\text{OR} \right) = \ \frac{1}{A} + \frac{1}{B} + \frac{1}{C} + \frac{1}{D}\]</span></p>
<p>Let’s assume that we train students in using a spaced learning strategy (they work through a textbook every week instead of cramming the week before the exam). Without such training, 70 out of 100 students succeed in passing the course after the first exam, but with this training, 80 out of 100 students
pass.</p>
<table>
<thead><tr class="header">
<th></th>
<th>Success</th>
<th>Failure</th>
<th>N</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Experimental</td>
<td>80</td>
<td>20</td>
<td>100</td>
</tr>
<tr class="even">
<td>Control</td>
<td>70</td>
<td>30</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>The odds of passing in the experimental group is 80/20, or 4, while odds in the control condition are 70/30, or 2.333. The ratio of these two odds is then: 4/2.333 = 1.714, or:</p>
<p><span class="math display">\[
OR = \ \frac{80 \times 30}{20\  \times 70} = 1.714
\]</span></p>
<p>We can simulate studies with dichotomous outcomes, where we set the percentage of successes and
failures in the experimental and control condition. In the script below, by default the percentage of success in the experimental condition is 70%, and in the control condition it is 50%.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="meta.html#cb98-1"></a><span class="kw">library</span>(metafor)</span>
<span id="cb98-2"><a href="meta.html#cb98-2"></a><span class="kw">set.seed</span>(<span class="dv">5333</span>)</span>
<span id="cb98-3"><a href="meta.html#cb98-3"></a>nSims &lt;-<span class="st"> </span><span class="dv">12</span> <span class="co">#number of simulated experiments</span></span>
<span id="cb98-4"><a href="meta.html#cb98-4"></a></span>
<span id="cb98-5"><a href="meta.html#cb98-5"></a>pop.pr1 &lt;-<span class="st"> </span><span class="fl">0.7</span> <span class="co"># Set percentage of successes in Group 1</span></span>
<span id="cb98-6"><a href="meta.html#cb98-6"></a>pop.pr2 &lt;-<span class="st"> </span><span class="fl">0.5</span> <span class="co"># Set percentage of successes in Group 2</span></span>
<span id="cb98-7"><a href="meta.html#cb98-7"></a></span>
<span id="cb98-8"><a href="meta.html#cb98-8"></a>ai &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for successes group 1</span></span>
<span id="cb98-9"><a href="meta.html#cb98-9"></a>bi &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for failures group 1</span></span>
<span id="cb98-10"><a href="meta.html#cb98-10"></a>ci &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for successes group 2</span></span>
<span id="cb98-11"><a href="meta.html#cb98-11"></a>di &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for failures group 2</span></span>
<span id="cb98-12"><a href="meta.html#cb98-12"></a></span>
<span id="cb98-13"><a href="meta.html#cb98-13"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSims) { <span class="co">#for each simulated experiment</span></span>
<span id="cb98-14"><a href="meta.html#cb98-14"></a>  n &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">30</span><span class="op">:</span><span class="dv">80</span>, <span class="dv">1</span>)</span>
<span id="cb98-15"><a href="meta.html#cb98-15"></a>  x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, pop.pr1) <span class="co">#produce simulated participants (1 = success, 0 is failure)</span></span>
<span id="cb98-16"><a href="meta.html#cb98-16"></a>  y &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, pop.pr2) <span class="co">#produce simulated participants (1 = success, 0 is failure)</span></span>
<span id="cb98-17"><a href="meta.html#cb98-17"></a>  ai[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#Successes Group 1</span></span>
<span id="cb98-18"><a href="meta.html#cb98-18"></a>  bi[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co">#Failures Group 1</span></span>
<span id="cb98-19"><a href="meta.html#cb98-19"></a>  ci[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co">#Successes Group 2</span></span>
<span id="cb98-20"><a href="meta.html#cb98-20"></a>  di[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co">#Failures Group 2</span></span>
<span id="cb98-21"><a href="meta.html#cb98-21"></a>}</span>
<span id="cb98-22"><a href="meta.html#cb98-22"></a></span>
<span id="cb98-23"><a href="meta.html#cb98-23"></a><span class="co"># Combine data into dataframe</span></span>
<span id="cb98-24"><a href="meta.html#cb98-24"></a>metadata &lt;-<span class="st"> </span><span class="kw">cbind</span>(ai, bi, ci, di)</span>
<span id="cb98-25"><a href="meta.html#cb98-25"></a><span class="co"># Create escalc object from metadata dataframe </span></span>
<span id="cb98-26"><a href="meta.html#cb98-26"></a>metadata &lt;-<span class="st"> </span><span class="kw">escalc</span>(<span class="dt">measure =</span> <span class="st">"OR"</span>, </span>
<span id="cb98-27"><a href="meta.html#cb98-27"></a>                   <span class="dt">ai =</span> ai, <span class="dt">bi =</span> bi, <span class="dt">ci =</span> ci, <span class="dt">di =</span> di, </span>
<span id="cb98-28"><a href="meta.html#cb98-28"></a>                   <span class="dt">data =</span> metadata)</span>
<span id="cb98-29"><a href="meta.html#cb98-29"></a><span class="co"># Perform Meta-analysis</span></span>
<span id="cb98-30"><a href="meta.html#cb98-30"></a>result &lt;-<span class="st"> </span><span class="kw">rma</span>(yi, vi, <span class="dt">data =</span> metadata)</span>
<span id="cb98-31"><a href="meta.html#cb98-31"></a><span class="co"># Create forest plot. Using ilab and ilab.xpos arguments to add counts</span></span>
<span id="cb98-32"><a href="meta.html#cb98-32"></a><span class="kw">forest</span>(result, </span>
<span id="cb98-33"><a href="meta.html#cb98-33"></a>       <span class="dt">ilab =</span> <span class="kw">cbind</span>(metadata<span class="op">$</span>ai, metadata<span class="op">$</span>bi, metadata<span class="op">$</span>ci, metadata<span class="op">$</span>di), </span>
<span id="cb98-34"><a href="meta.html#cb98-34"></a>       <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">10</span>, <span class="dv">8</span>), </span>
<span id="cb98-35"><a href="meta.html#cb98-35"></a>       <span class="dt">ilab.xpos =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">7</span>, <span class="dv">-6</span>, <span class="dv">-5</span>, <span class="dv">-4</span>))</span>
<span id="cb98-36"><a href="meta.html#cb98-36"></a><span class="kw">text</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">7</span>,<span class="op">-</span><span class="dv">6</span>,<span class="op">-</span><span class="dv">5</span>,<span class="op">-</span><span class="dv">4</span>), <span class="fl">14.7</span>, <span class="kw">c</span>(<span class="st">"E+"</span>, <span class="st">"E-"</span>, <span class="st">"C+"</span>, <span class="st">"C-"</span>), <span class="dt">font =</span> <span class="dv">2</span>, <span class="dt">cex =</span> <span class="fl">.8</span>) <span class="co"># add labels</span></span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-48-1.png" width="672"></p>
<p>The forest plot presents the studies and four columns of data after the study label, which contain the number of successes and failures in the experimental groups (E+ and E-), and the number of successes and failures in the control group (C+ and C-). Imagine we study the percentage of people who get a job
within 6 months after a job training program, compared to a control condition. In Study 1, which had 50 participants in each condition, 29 people in the job training condition got a job within 6 months, and 21 did not get a job. In the control condition, 23 people got a job, but 27 did not. The effect size estimate for the random effects model is 0.65. Feel free to play around with the script, adjusting the number of studies, or the sample sizes in each study, to examine the effect it has on the meta-analytic effect size estimate.</p>
<p>We can also get the meta-analytic test results by printing the test output. We see that there was no heterogeneity in this meta-analysis. This is true (we simulated identical studies) but also highly unlikely to ever happen in real life, where variation in effect sizes between studies included in a meta-analysis is a much more realistic scenario.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="meta.html#cb99-1"></a><span class="co"># Print result meta-analysis</span></span>
<span id="cb99-2"><a href="meta.html#cb99-2"></a>result</span></code></pre></div>
<pre><code>## 
## Random-Effects Model (k = 12; tau^2 estimator: REML)
## 
## tau^2 (estimated amount of total heterogeneity): 0 (SE = 0.0645)
## tau (square root of estimated tau^2 value):      0
## I^2 (total heterogeneity / total variability):   0.00%
## H^2 (total variability / sampling variability):  1.00
## 
## Test for Heterogeneity:
## Q(df = 11) = 4.8886, p-val = 0.9364
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.6548  0.1132  5.7824  &lt;.0001  0.4328  0.8767  *** 
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div id="heterogeneity" class="section level3">
<h3>
<span class="header-section-number">9.3.5</span> Heterogeneity</h3>
<p>Although researchers often primarily use meta-analysis to compute a meta-analytic effect size estimate, and test whether this effect is statistically different from zero, <strong>an arguably much more important use of meta-analyses is to explain variation between (sets of) studies</strong>. This variation among (sets of) studies is referred to as <strong>heterogeneity</strong>. One goal of meta-analyses is not just to code effect sizes and estimate the meta-analytic effect size, but to code factors in studies that can explain heterogeneity, and examine which of these factors account for heterogeneity. This can help in theory evaluation or theory development. Tests have been developed to examine whether the studies included in a meta-analysis vary more than would be expected if the underlying true effect size in all
studies was the same, and measures have been developed to quantify this variation.</p>
<p>If all studies have the same true population effect size, the only source of variation is random error. If there are real differences between (sets of) studies, there are two sources of variation, namely random variation from study to study, <em>and</em> real differences in effect sizes in (sets of) studies.</p>
<p>A classical measure of heterogeneity is Cochran’s Q statistic, which is the weighted sum of the squared differences between effect size estimates in each study, and the meta-analytic effect size estimate. The Q statistic can be used to test whether the absence of heterogeneity can be statistically rejected (by
comparing it to the expected amount of variation, which is the degrees of freedom, <em>df</em>, or the number of studies -1, see Borenstein et al., 2009), but it can have low power if the number of studies in the meta-analysis is small <span class="citation">(Huedo-Medina et al., <label for="tufte-mn-62" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-62" class="margin-toggle">2006<span class="marginnote">Huedo-Medina, T. B., Sánchez-Meca, J., Marín-Martínez, F., &amp; Botella, J. (2006). Assessing heterogeneity in meta-analysis: Q statistic or I$2̂$ index? <em>Psychological Methods</em>, <em>11</em>(2), 193.</span>)</span>.</p>
<p>On theoretical grounds one might argue that some heterogeneity will always happen in a meta-analysis, and therefore it is more interesting to quantify the extent to which there is heterogeneity. The I² index measures the extent of true heterogeneity. It is calculated as follows: <span class="math display">\[I^{2} = \ \frac{(Q - k - 1)}{Q} \times 100\%\]</span>, where the k is the number of studies (and k-1 is the degrees of freedom). I² ranges from 0 to 100 and can be interpreted as the percentage of the total variability in a set of effect sizes that is due to heterogeneity. When I² = 0 all variability in the effect size estimates can be explained by within-study error, and when I² = 50 half of the total variability can be explained by true heterogeneity. I² values of 25%, 50%, and 75% can be interpreted as low, medium, and high heterogeneity.</p>
<p>The script below simulates a similar meta-analysis to the example for dichotomous outcomes above, but with a small variation. The first half of the simulated experiments are based on the population success
rates 0.7 and 0.2, but the second half of the simulated experiments are based on the population success rates 0.9 and 0.7. Thus, in this set of studies the odds ratio differs for the first half of the studies, compared to the second half (successes in Group 1 and 2 are set to 0.2 and 0.7 for the first half, but to 0.7 and 0.9 in the second half). There is true heterogeneity. We use the <code>confint</code> function in the metafor package to report both the I² statistic, and its confidence interval.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="meta.html#cb101-1"></a><span class="kw">library</span>(metafor)</span>
<span id="cb101-2"><a href="meta.html#cb101-2"></a><span class="kw">set.seed</span>(<span class="dv">2942</span>)</span>
<span id="cb101-3"><a href="meta.html#cb101-3"></a>nSims &lt;-<span class="st"> </span><span class="dv">12</span> <span class="co"># Number of simulated experiments</span></span>
<span id="cb101-4"><a href="meta.html#cb101-4"></a></span>
<span id="cb101-5"><a href="meta.html#cb101-5"></a>pop.pr1 &lt;-<span class="st"> </span><span class="fl">0.7</span> <span class="co"># Set percentage of successes in Group 1</span></span>
<span id="cb101-6"><a href="meta.html#cb101-6"></a>pop.pr2 &lt;-<span class="st"> </span><span class="fl">0.2</span> <span class="co"># Set percentage of successes in Group 2</span></span>
<span id="cb101-7"><a href="meta.html#cb101-7"></a></span>
<span id="cb101-8"><a href="meta.html#cb101-8"></a>ai &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for successes group 1</span></span>
<span id="cb101-9"><a href="meta.html#cb101-9"></a>bi &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for failures group 1</span></span>
<span id="cb101-10"><a href="meta.html#cb101-10"></a>ci &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for successes group 2</span></span>
<span id="cb101-11"><a href="meta.html#cb101-11"></a>di &lt;-<span class="st"> </span><span class="kw">numeric</span>(nSims) <span class="co"># set up empty vector for failures group 2</span></span>
<span id="cb101-12"><a href="meta.html#cb101-12"></a></span>
<span id="cb101-13"><a href="meta.html#cb101-13"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>nSims<span class="op">/</span><span class="dv">2</span>) { <span class="co"># for half (/2) of the simulated studies</span></span>
<span id="cb101-14"><a href="meta.html#cb101-14"></a>  n &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">30</span><span class="op">:</span><span class="dv">80</span>, <span class="dv">1</span>)</span>
<span id="cb101-15"><a href="meta.html#cb101-15"></a>  x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, pop.pr1) <span class="co"># produce simulated participants (1 = success, 0 is failure)</span></span>
<span id="cb101-16"><a href="meta.html#cb101-16"></a>  y &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, pop.pr2) <span class="co"># produce simulated participants (1 = success, 0 is failure)</span></span>
<span id="cb101-17"><a href="meta.html#cb101-17"></a>  ai[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co"># Successes Group 1</span></span>
<span id="cb101-18"><a href="meta.html#cb101-18"></a>  bi[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># Failures Group 1</span></span>
<span id="cb101-19"><a href="meta.html#cb101-19"></a>  ci[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co"># Successes Group 2</span></span>
<span id="cb101-20"><a href="meta.html#cb101-20"></a>  di[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># Failures Group 2</span></span>
<span id="cb101-21"><a href="meta.html#cb101-21"></a>}</span>
<span id="cb101-22"><a href="meta.html#cb101-22"></a></span>
<span id="cb101-23"><a href="meta.html#cb101-23"></a>pop.pr1 &lt;-<span class="st"> </span><span class="fl">0.9</span> <span class="co">#Set percentage of successes in Group 1</span></span>
<span id="cb101-24"><a href="meta.html#cb101-24"></a>pop.pr2 &lt;-<span class="st"> </span><span class="fl">0.7</span> <span class="co">#Set percentage of successes in Group 2</span></span>
<span id="cb101-25"><a href="meta.html#cb101-25"></a></span>
<span id="cb101-26"><a href="meta.html#cb101-26"></a><span class="cf">for</span> (i <span class="cf">in</span> (nSims<span class="op">/</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)<span class="op">:</span>(nSims)) { <span class="co">#for the other half (/2) of each simulated study</span></span>
<span id="cb101-27"><a href="meta.html#cb101-27"></a>  n &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">30</span><span class="op">:</span><span class="dv">80</span>, <span class="dv">1</span>)</span>
<span id="cb101-28"><a href="meta.html#cb101-28"></a>  x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, pop.pr1) <span class="co"># produce simulated participants (1 = success, 0 is failure)</span></span>
<span id="cb101-29"><a href="meta.html#cb101-29"></a>  y &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, pop.pr2) <span class="co"># produce simulated participants (1 = success, 0 is failure)</span></span>
<span id="cb101-30"><a href="meta.html#cb101-30"></a>  ai[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co"># Successes Group 1</span></span>
<span id="cb101-31"><a href="meta.html#cb101-31"></a>  bi[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># Failures Group 1</span></span>
<span id="cb101-32"><a href="meta.html#cb101-32"></a>  ci[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="co"># Successes Group 2</span></span>
<span id="cb101-33"><a href="meta.html#cb101-33"></a>  di[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(y <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># Failures Group 2</span></span>
<span id="cb101-34"><a href="meta.html#cb101-34"></a>}</span>
<span id="cb101-35"><a href="meta.html#cb101-35"></a></span>
<span id="cb101-36"><a href="meta.html#cb101-36"></a><span class="co"># Combine data into dataframe</span></span>
<span id="cb101-37"><a href="meta.html#cb101-37"></a>metadata &lt;-<span class="st"> </span><span class="kw">cbind</span>(ai, bi, ci, di)</span>
<span id="cb101-38"><a href="meta.html#cb101-38"></a><span class="co"># Create escalc object from metadata dataframe </span></span>
<span id="cb101-39"><a href="meta.html#cb101-39"></a>metadata &lt;-<span class="st"> </span><span class="kw">escalc</span>(<span class="dt">measure =</span> <span class="st">"OR"</span>, </span>
<span id="cb101-40"><a href="meta.html#cb101-40"></a>                   <span class="dt">ai =</span> ai, <span class="dt">bi =</span> bi, <span class="dt">ci =</span> ci, <span class="dt">di =</span> di, </span>
<span id="cb101-41"><a href="meta.html#cb101-41"></a>                   <span class="dt">data =</span> metadata)</span>
<span id="cb101-42"><a href="meta.html#cb101-42"></a><span class="co"># Perform Meta-analysis</span></span>
<span id="cb101-43"><a href="meta.html#cb101-43"></a>result &lt;-<span class="st"> </span><span class="kw">rma</span>(yi, vi, <span class="dt">data =</span> metadata)</span>
<span id="cb101-44"><a href="meta.html#cb101-44"></a><span class="co"># Print result meta-analysis</span></span>
<span id="cb101-45"><a href="meta.html#cb101-45"></a>result</span></code></pre></div>
<pre><code>## 
## Random-Effects Model (k = 12; tau^2 estimator: REML)
## 
## tau^2 (estimated amount of total heterogeneity): 0.3174 (SE = 0.2429)
## tau (square root of estimated tau^2 value):      0.5634
## I^2 (total heterogeneity / total variability):   56.53%
## H^2 (total variability / sampling variability):  2.30
## 
## Test for Heterogeneity:
## Q(df = 11) = 25.7650, p-val = 0.0070
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   1.8125  0.2190  8.2764  &lt;.0001  1.3833  2.2417  *** 
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="meta.html#cb103-1"></a><span class="kw">confint</span>(result) <span class="co"># Get confidence interval for indices of heterogeneity</span></span></code></pre></div>
<pre><code>## 
##        estimate   ci.lb   ci.ub 
## tau^2    0.3174  0.0355  1.2286 
## tau      0.5634  0.1883  1.1084 
## I^2(%)  56.5308 12.6888 83.4276 
## H^2      2.3005  1.1453  6.0341</code></pre>
<p>Based on the test for heterogeneity, we can reject the null hypothesis that there is no heterogeneity in the meta-analysis. Tests for heterogeneity themselves have Type 1 and Type 2 error rates, and with a small number of studies (such as in our example, n = 12) tests for heterogeneity can have low power. If you remove the set.seed command and run the code multiple times, you will see that the test for heterogeneity will often not be significant, even though there is true heterogeneity in the simulation. In large meta-analyses, power can be so high that the test always yields a <em>p</em>-value small enough to reject the null hypothesis, but then it is important to look at the I² estimate.</p>
</div>
<div id="improving-the-reproducibility-of-meta-analyses" class="section level3">
<h3>
<span class="header-section-number">9.3.6</span> Improving the reproducibility of meta-analyses</h3>
<p>Although meta-analyses do not provide definitive conclusions, they are typically interpreted as state-of-the-art empirical knowledge about a specific effect or research area. Large-scale meta-analyses often accumulate a massive number of citations and influence future research and theory development. It is therefore essential that published meta-analyses are of the highest possible quality.</p>
<p>At the same time, the conclusions from meta-analyses are often open for debate and are subject to change as new data becomes available. We recently proposed practical recommendations to increase the reproducibility of meta-analyses to facilitate quality control, improve reporting guidelines, allow researchers to re-analyze meta-analyses based on alternative inclusion criteria, and future-proof meta-analyses by making sure the collected meta-analytic data is shared so that continuously accumulating meta-analyses can be performed, and so that novel statistical techniques can be applied on the collected data as they become available <span class="citation">(Lakens et al., <label for="tufte-mn-63" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-63" class="margin-toggle">2016<span class="marginnote">Lakens, D., Hilgard, J., &amp; Staaks, J. (2016). On the reproducibility of meta-analyses: Six practical recommendations. <em>BMC Psychology</em>, <em>4</em>, 24. <a href="https://doi.org/10.1186/s40359-016-0126-3">https://doi.org/10.1186/s40359-016-0126-3</a></span>)</span>. The need for the improvement in reproducibility of meta-analysis is clear - a recent review of 150 meta-analyses in Psychological BUlletin revealed that only 1 meta-analysis shared the statistical code <span class="citation">(Polanin et al., <label for="tufte-mn-64" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-64" class="margin-toggle">2020<span class="marginnote">Polanin, J. R., Hennessy, E. A., &amp; Tsuji, S. (2020). Transparency and Reproducibility of Meta-Analyses in Psychology: A Meta-Review. <em>Perspectives on Psychological Science</em>, <em>15</em>(4), 1026–1041. <a href="https://doi.org/10.1177/1745691620906416">https://doi.org/10.1177/1745691620906416</a></span>)</span>. This is unacceptable in the current day and age. Following the recommendations summarized in Table <a href="meta.html#tab:table-rec1">9.1</a> should substantially improve the state-of-the-art in meta-analyses.</p>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:table-rec1">Table 9.1: </span>Six practical recommendations to improve the quality and reproducibility of meta-analyses.</span><!--</caption>--></p>
<table>
<thead><tr>
<th style="text-align:left;">
What?
</th>
<th style="text-align:left;">
How?
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Facilitate cumulative science
</td>
<td style="text-align:left;">
Disclose all meta-analytic data (effect sizes, sample sizes for each condition, test statistics and degrees of freedom, means, standard deviations, and correlations between dependent observations) for each data point. Quote relevant text from studies that describe the meta-analytic data to prevent confusion, such as when one effect size is selected from a large number of tests reported in a study. When analyzing subgroups, include quotes from the original study that underlie this classification, and specify any subjective decisions.
</td>
</tr>
<tr>
<td style="text-align:left;">
Facilitate quality control
</td>
<td style="text-align:left;">
Specify which effect size calculations are used and which assumptions are made for missing data (e.g., assuming equal sample sizes in each condition, imputed values for unreported effect sizes), if necessary for each effect size extracted from the literature. Specify who extracted and coded the data, knowing it is preferable that two researchers independently extract effect sizes from the literature.
</td>
</tr>
<tr>
<td style="text-align:left;">
Use reporting guidelines
</td>
<td style="text-align:left;">
A minimal requirement when reporting meta-analyses is to adhere to one of the reporting standards (e.g., PRISMA). The reporting guidelines ask authors of meta-analyses to report essential information that should be made available either in the main text of the article, or by providing a completed checklist as supplementary material during review and after publication.
</td>
</tr>
<tr>
<td style="text-align:left;">
Preregister
</td>
<td style="text-align:left;">
Whenever possible, pre-register the meta-analysis research protocol to distinguish between confirmatory and exploratory analyses. Perform a prospective meta-analysis where possible.
</td>
</tr>
<tr>
<td style="text-align:left;">
Facilitate reproducibility
</td>
<td style="text-align:left;">
Allow others to re-analyze the data to examine how sensitive the results are to subjective choices such as inclusion criteria. Always include a link to data files that can be directly analyzed with statistical software, either by providing completely reproducible scripts containing both the data and the reported analyses in free software (e.g., R), or at the very minimum a spreadsheet that contains all meta-analytic data that can easily analyzed in any statistical program.
</td>
</tr>
<tr>
<td style="text-align:left;">
Recruit expertise
</td>
<td style="text-align:left;">
Consider consulting a librarian before you start the literature search, and a statistician before coding the effect sizes, for advice on how make the literature search and effect size calculations reproducible.
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></body></html>

<p style="text-align: center;">
<a href="sesoi.html"><button class="btn btn-default">Previous</button></a>
<a href="bias.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2020-08-04
</p>
</div>
</div>

<div class="row" style="padding-top: 2em;">
<p style="text-align: center">
<img src="images/logo.png" style="width: 100px; padding: 0; display: inline; vertical-align: top">
<span style="display: inline-block; margin-left: 2em; margin-top: 16px; font-size: small">
<span style="font-weight: bold;">Daniel Lakens</span><br/>
<a href="https://statistical-inferences.com">statistical-inferences.com</a><br/>
page built  2020-08-04 21:55:36
</span>
</p>
</div>


</body>
</html>
