<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="14 Sequential Analysis | Improving Your Statistical Inferences" />
<meta property="og:type" content="book" />
<meta property="og:url" content="http://themethodsection.com/ebook/" />
<meta property="og:image" content="http://themethodsection.com/ebook/images/cover.jpg" />
<meta property="og:description" content="Online textbook to Improve Your Statistical Inferences" />


<meta name="author" content="Daniel Lakens" />

<meta name="date" content="2020-08-09" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Online textbook to Improve Your Statistical Inferences">

<title>14 Sequential Analysis | Improving Your Statistical Inferences</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="center.css" type="text/css" />
<link rel="stylesheet" href="custom-msmbstyle.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Improving Your Statistical Inferences<p><p class="author">Daniel Lakens</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html">Welcome</a>
<a href="contents.html">Contents</a>
<a href="preface.html">Preface</a>
<a href="introduction.html">Introduction</a>
<a href="pvalue.html"><span class="toc-section-number">1</span> What is a <em>p</em>-value</a>
<a href="power.html"><span class="toc-section-number">2</span> Sample size justification</a>
<a href="questions.html"><span class="toc-section-number">3</span> Asking Statistical Questions</a>
<a href="errorcontrol.html"><span class="toc-section-number">4</span> Error Control</a>
<a href="effectsizesCI.html"><span class="toc-section-number">5</span> Effect Sizes and Confidence Intervals</a>
<a href="equivalencetest.html"><span class="toc-section-number">6</span> Equivalence Testing</a>
<a href="severity.html"><span class="toc-section-number">7</span> Severe Tests and Risky Predictions</a>
<a href="sesoi.html"><span class="toc-section-number">8</span> Smallest Effect Size of Interest</a>
<a href="meta.html"><span class="toc-section-number">9</span> Meta-analysis</a>
<a href="bias.html"><span class="toc-section-number">10</span> Bias detection</a>
<a href="computationalreproducibility.html"><span class="toc-section-number">11</span> Computational Reproducibility</a>
<a href="prereg.html"><span class="toc-section-number">12</span> Preregistration and Transparency</a>
<a href="bayes.html"><span class="toc-section-number">13</span> Bayesian statistics</a>
<a id="active-page" href="sequential.html"><span class="toc-section-number">14</span> Sequential Analysis</a><ul class="toc-sections">
<li class="toc"><a href="#NA"> Choosing alpha levels for sequential analyses.</a></li>
<li class="toc"><a href="#comparing-spending-functions"> Comparing Spending Functions</a></li>
<li class="toc"><a href="#sample-size-for-sequential-designs"> Sample Size for Sequential Designs</a></li>
<li class="toc"><a href="#test-for-non-inferiority"> Test for (non-)inferiority</a></li>
<li class="toc"><a href="#stopping-for-futility"> Stopping for futility</a></li>
</ul>
<a href="references.html"><span class="toc-section-number">15</span> References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="sequential" class="section level1">
<h1>
<span class="header-section-number">14</span> Sequential Analysis</h1>
<p>Imagine you design a study, determine the sample size you will collect based on an a-priori power analysis with a desired 80% power, have collected data, analyzed the results, and you find a <em>p</em>-value for your primary hypothesis of <em>p</em> = 0.09. You believe this might be a Type 2 error, and you are willing to collect more data to examine your hypothesis. In the past, researchers would often use a practice called <strong>optional stopping</strong> where they would continue the data collection, without adjusting the alpha level for multiple comparisons <span class="citation">(Fiedler &amp; Schwarz, <label for="tufte-mn-86" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-86" class="margin-toggle">2015<span class="marginnote">Fiedler, K., &amp; Schwarz, N. (2015). Questionable Research Practices Revisited. <em>Social Psychological and Personality Science</em>, 1948550615612150. <a href="https://doi.org/10.1177/1948550615612150">https://doi.org/10.1177/1948550615612150</a></span>; John et al., <label for="tufte-mn-87" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-87" class="margin-toggle">2012<span class="marginnote">John, L. K., Loewenstein, G., &amp; Prelec, D. (2012). Measuring the prevalence of questionable research practices with incentives for truth telling. <em>Psychological Science</em>, <em>23</em>(5), 524–532.</span>)</span>. However, this inflates the Type 1 error rate. Luckily, there is a solution to be able to stop the data collection when an effect is significant, and continue up to the maximum sample size you are willing to collect when it is not significant: <strong>sequential analysis</strong>. In sequential analysis a researcher designs a study such that they are able to perform <strong>interim analyses</strong>, say when 25%, 50%, and 75% of the data is collected. At each interim analysis a test is performed at a corrected alpha level, that over all planned analyses maintains the desired Type 1 error rate. For example, each of four analyses might be performed using an alpha level of 0.0091. The analysis at the first interim analysis yields a <em>p</em> = 0.21, data collection would continue. If at the second interim analysis a <em>p</em> = 0.007 is observed, data collection is terminated, and the null hypothesis is rejected. Even though the researcher repeatedly analyses the data, the corrected alpha level guarantees that the Type 1 error rate remains at 5%.</p>
<p>Although the use of sequential analyses is not common, they have a long history. As early as 1929, Dodge and Romig realized that analyzing the data sequentially was more efficient than doing so once <span class="citation">(Dodge &amp; Romig, <label for="tufte-mn-88" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-88" class="margin-toggle">1929<span class="marginnote">Dodge, H. F., &amp; Romig, H. G. (1929). A Method of Sampling Inspection. <em>Bell System Technical Journal</em>, <em>8</em>(4), 613–631. <a href="https://doi.org/10.1002/j.1538-7305.1929.tb01240.x">https://doi.org/10.1002/j.1538-7305.1929.tb01240.x</a></span>)</span>. Wald, who popularized the idea of sequential tests of hypotheses in <span class="citation">(<label for="tufte-mn-89" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-89" class="margin-toggle">1945<span class="marginnote">Wald, A. (1945). Sequential tests of statistical hypotheses. <em>The Annals of Mathematical Statistics</em>, <em>16</em>(2), 117–186.</span>)</span>, performed his work during the second world war. He was only allowed to publish his findings after the war had ended, because as he writes in a historical note:</p>
<blockquote>
<p>Because of the substantial savings in the expected number of observations effected by the sequential probability ratio test, and because of the simplicity of this test procedure in practical applications, the National Defense Research Committee considered these developments sufficiently useful for the war effort to make it desirable to keep the results out of the reach of the enemy, at least for a certain period of time. The author was, therefore, requested to submit his findings in a restricted report which was dated September, 1943.</p>
</blockquote>
<p>In other words, we have a method that so substantially increases the efficiency of hypothesis tests that it would not be shared with the enemy during war time - yet few researchers outside of medicine currently use it! In medicine, efficiency is not just a matter of money, but also of saving lives. If a drug shows it substantially increases the probability that people will survive a disease, it is deemed ethical to terminate a trial early, and administer the treatment to patients enrolled in the control group as well. Sequential analyses are established procedures, and have been developed in great detail over the last decades <span class="citation">(Jennison &amp; Turnbull, <label for="tufte-mn-90" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-90" class="margin-toggle">2000<span class="marginnote">Jennison, C., &amp; Turnbull, B. W. (2000). <em>Group sequential methods with applications to clinical trials</em>. Chapman &amp; Hall/CRC.</span>; Proschan et al., <label for="tufte-mn-91" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-91" class="margin-toggle">2006<span class="marginnote">Proschan, M. A., Lan, K. K. G., &amp; Wittes, J. T. (2006). <em>Statistical monitoring of clinical trials: A unified approach</em>. Springer.</span>; Wassmer &amp; Brannath, <label for="tufte-mn-92" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-92" class="margin-toggle">2016<span class="marginnote">Wassmer, G., &amp; Brannath, W. (2016). <em>Group Sequential and Confirmatory Adaptive Designs in Clinical Trials</em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-319-32562-0">https://doi.org/10.1007/978-3-319-32562-0</a></span>)</span>. Here, we will explain the basics of how to control error rates in sequential analyses, and perform a-priori power analysis and compare when sequential designs will be more or less efficient than fixed designs.</p>
<div id="choosing-alpha-levels-for-sequential-analyses." class="section level2">
<h2>
<span class="header-section-number">14.1</span> Choosing alpha levels for sequential analyses.</h2>
<p>In sequential designs researchers will collect data with the plan to analyze the data at various times during the data collections. For example, a researcher plans to collect data from 200 participants and plans to analyse the data after 100 participants are collected, and once again after 200 participants are collected. Each analyses is called a <strong>look</strong>, so there are in total 2 looks at the data planned, with one interim analysis, and one final analysis. Not all looks have to occur in practice. If the analysis reveals a statistically significant result at look 1, data collection can be terminated. It is also possible to stop the data collection at look 1 because a predicted effect is absent, and continuing the data collection is not deemed worthwhile, which is called <strong>stopping for futility</strong>.</p>
<p>If one would analyze the data at multiple looks without correcting the alpha level, the Type 1 error rate would inflate <span class="citation">(Armitage et al., <label for="tufte-mn-93" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-93" class="margin-toggle">1969<span class="marginnote">Armitage, P., McPherson, C. K., &amp; Rowe, B. C. (1969). Repeated significance tests on accumulating data. <em>Journal of the Royal Statistical Society: Series A (General)</em>, <em>132</em>(2), 235–244.</span>)</span>. As Armitage and colleagues show, with equally spaced looks, the alpha level inflates to 0.142 after 5 looks, 0.374 after 100 looks, and 0.530 after 1000 looks. Looking at the data twice is conceptually similar to deciding if a result is significant if one of two dependent variables shows a statistically significant effect. However, an important difference is that in the case of sequential analyses the multiple tests are not independent, but dependent. A test at look to combines the old data collected at look 1 with the new data at look 2. This means the Type 1 error rate inflates less quickly compared to independent tests, and we will see below this enables more efficient and flexible solutions to controlling error rates.</p>
<p>The solution to control Type 1 error inflation is again conceptually similar to a multiple comparison problem. By lowering the alpha level at each look, the Type 1 error rate can be controlled. They way the alpha level is reduced differs, however. To control the Type 1 error rate, we would lower the alpha level for each test, for example using the Bonferroni procedure where each test would be performed at <span class="math inline">\(\alpha/2\)</span>. In sequential analyses we similarly adjust the alpha level. It is even possible to just use a Bonferroni correction <span class="citation">(Wassmer &amp; Brannath, <label for="tufte-mn-94" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-94" class="margin-toggle">2016<span class="marginnote">Wassmer, G., &amp; Brannath, W. (2016). <em>Group Sequential and Confirmatory Adaptive Designs in Clinical Trials</em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-319-32562-0">https://doi.org/10.1007/978-3-319-32562-0</a></span>)</span>. But because the data is dependent (at look 2 we combine the data we collected at look 1 with the new data, so the data covary) the way to correct alpha levels can be done more efficiently. If you combine multiple looks at the data with multiple comparisons, you would first correct the alpha level for multiple looks, and then correct the alpha level at each look for the multiple comparison correction. Because the alpha level is corrected, it does not matter which statistical test you perform at each look, all that matters is that the <em>p</em>-value is compared to the corrected alpha level.</p>
<div id="pocock-correction" class="section level3">
<h3>
<span class="header-section-number">14.1.1</span> Pocock correction</h3>
<p>We will start with the Pocock correction, which is the simplest way to correct the alpha level for multiple looks. Conceptually, it is very similar to the Bonferroni correction. We can see at the <a href="https://en.wikipedia.org/wiki/Pocock_boundary">Wikipedia page for the Pocock correction</a> that with 2 interim analyses the alpha level for each look is 0.0294, for three looks it is 0.0221, for 4 looks it is 0.0182, and for 5 looks it is 0.0158. We see the correction is slightly more efficient than using a Bonferroni correction (in which case the alpha levels would be 0.025, 0.0167, 0.0125, and 0.01). Applying the Pocock procedure requires 1) specifying the number of looks in advance, and 2) equally spaced looks, where each batch of observations has the same size (e.g., looking after 25, 50, 75 and 100 observations).</p>
<p>Note that we can accurately calculate the alpha levels that should be used to 4 digits after the decimal points, but the <a href="http://daniellakens.blogspot.com/2020/01/observed-alpha-levels-why-statistical.html">alpha level you will observe for all tests in your lifetime probably has too much variability</a> to worry too much about anything after 3 digits after the decimal point (and maybe even 2). We will compute alpha levels in this tutorial with higher precision than you need to care about in real life.</p>
<p>We will use multiple packages in R to compute corrected alpha levels for each look, such as <a href="https://cran.r-project.org/web/packages/gsDesign/index.html">gsDesign</a>, <a href="https://cran.r-project.org/web/packages/rpact/index.html">rpact</a>, and <a href="https://cran.r-project.org/web/packages/ldbounds/index.html">ldbounds</a>. RPact is also available as a <a href="https://rpact.shinyapps.io/public/">Shiny app</a>.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="sequential.html#cb134-1"></a><span class="co"># Use Rpact to specify a design with 2 looks and Pocock correction</span></span>
<span id="cb134-2"><a href="sequential.html#cb134-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb134-3"><a href="sequential.html#cb134-3"></a>design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb134-4"><a href="sequential.html#cb134-4"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb134-5"><a href="sequential.html#cb134-5"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb134-6"><a href="sequential.html#cb134-6"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb134-7"><a href="sequential.html#cb134-7"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb134-8"><a href="sequential.html#cb134-8"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb134-9"><a href="sequential.html#cb134-9"></a>)</span>
<span id="cb134-10"><a href="sequential.html#cb134-10"></a><span class="kw">summary</span>(design)</span></code></pre></div>
<pre><code>## Sequential analysis with a maximum of 2 looks (group sequential design)
## 
## Stage                                   1      2 
## Information rate                      50%   100% 
## Efficacy boundary (z-value scale)   2.178  2.178 
## Cumulative alpha spent             0.0294 0.0500 
## Two-sided local significance level 0.0294 0.0294</code></pre>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
What happens to the alpha level if you have 3 looks in total?
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
Solution<span id="sol-start-2" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-2', 'sol-start-2')"></span>
</p>
<div id="sol-body-2" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="sequential.html#cb136-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb136-2"><a href="sequential.html#cb136-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb136-3"><a href="sequential.html#cb136-3"></a>design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb136-4"><a href="sequential.html#cb136-4"></a>  <span class="dt">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb136-5"><a href="sequential.html#cb136-5"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb136-6"><a href="sequential.html#cb136-6"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb136-7"><a href="sequential.html#cb136-7"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb136-8"><a href="sequential.html#cb136-8"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb136-9"><a href="sequential.html#cb136-9"></a>)</span>
<span id="cb136-10"><a href="sequential.html#cb136-10"></a><span class="kw">summary</span>(design)</span></code></pre></div>
<pre><code>## Sequential analysis with a maximum of 3 looks (group sequential design)
## 
## Stage                                   1      2      3 
## Information rate                    33.3%  66.7%   100% 
## Efficacy boundary (z-value scale)   2.289  2.289  2.289 
## Cumulative alpha spent             0.0221 0.0379 0.0500 
## Two-sided local significance level 0.0221 0.0221 0.0221</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p><code>rpact</code> makes it easy to plot the boundaries (based on the critical values) for each look. We see the critical values are higher than the 1.96 we would use for a fixed design with a 5% alpha level, namely: 2.2894781, 2.2894781, 2.2894781.</p>
<div class="figure">
<span id="fig:boundplot1"></span>
<p class="caption marginnote shownote">
Figure 14.1: Plot of critical boundaries at each look for a 2 look design with a Pocock correction.
</p>
<img src="Statistical_Inferences_files/figure-html/boundplot1-1.png" alt="Plot of critical boundaries at each look for a 2 look design with a Pocock correction." width="672">
</div>
<p>We can also use the <code>gsDesign</code> package (not that the gsDesign package reports one-sided alpha levels, and thus returns a one-sided alpha level of 0.0147, instead of the two-sided alpha level 0.294. You will need to double the alpha level for a two-sided test (or just use rpact, which reports two-sided alpha levels when asked).</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="sequential.html#cb138-1"></a>seq_design &lt;-<span class="st"> </span><span class="kw">gsDesign</span>(</span>
<span id="cb138-2"><a href="sequential.html#cb138-2"></a>  <span class="dt">k =</span> <span class="dv">2</span>, <span class="co"># k = number of looks = 2</span></span>
<span id="cb138-3"><a href="sequential.html#cb138-3"></a>  <span class="dt">test.type =</span> <span class="dv">2</span>,</span>
<span id="cb138-4"><a href="sequential.html#cb138-4"></a>  <span class="dt">alpha =</span> <span class="fl">.025</span>, <span class="co"># gsDesign computes one-sided alpha levels, so we halve alpha</span></span>
<span id="cb138-5"><a href="sequential.html#cb138-5"></a>  <span class="dt">sfu =</span> <span class="st">"Pocock"</span></span>
<span id="cb138-6"><a href="sequential.html#cb138-6"></a>)</span>
<span id="cb138-7"><a href="sequential.html#cb138-7"></a></span>
<span id="cb138-8"><a href="sequential.html#cb138-8"></a><span class="kw">gsBoundSummary</span>(seq_design)</span></code></pre></div>
<pre><code>##                Analysis               Value Efficacy Futility
##               IA 1: 50%                   Z   2.1783  -2.1783
##  N/Fixed design N: 0.55         p (1-sided)   0.0147   0.0147
##                             ~delta at bound   0.9061  -0.9061
##                         P(Cross) if delta=0   0.0147   0.0147
##                         P(Cross) if delta=1   0.5893   0.0000
##                   Final                   Z   2.1783  -2.1783
##   N/Fixed design N: 1.1         p (1-sided)   0.0147   0.0147
##                             ~delta at bound   0.6407  -0.6407
##                         P(Cross) if delta=0   0.0250   0.0250
##                         P(Cross) if delta=1   0.9000   0.0000</code></pre>
<p>It is also possible to recreate these analyses in the GroupSeq package, which has a GUI based interface. Run ‘groupseq(mode = “g”)’ in R, and the three screenshots below create the same output.</p>
<div class="figure">
<span id="fig:groupseq1"></span>
<p class="caption marginnote shownote">
Figure 14.2: Screenshot of the GroupSeq GUI to choose a task.
</p>
<img src="images/groupseq1.png" alt="Screenshot of the GroupSeq GUI to choose a task." width="307">
</div>
<div class="figure">
<span id="fig:groupseq2"></span>
<p class="caption marginnote shownote">
Figure 14.3: Screenshot of the GroupSeq GUI to compute bounds.
</p>
<img src="images/groupseq2.png" alt="Screenshot of the GroupSeq GUI to compute bounds." width="364">
</div>
<div class="figure">
<span id="fig:groupseq3"></span>
<p class="caption marginnote shownote">
Figure 14.4: Screenshot of the output of the GroupSeq GUI.
</p>
<img src="images/groupseq3.png" alt="Screenshot of the output of the GroupSeq GUI." width="601">
</div>
<p>The analysis can also be performed in the rpact <a href="https://rpact.shinyapps.io/public/">shiny app</a> which also allows users to create all plots through simple menu options, and download a complete report of the analyses (e.g., for a preregistration document). The rpact shiny app is the easiest resource to use from all options discussed here.</p>
<div class="figure">
<span id="fig:rpactshiny"></span>
<p class="caption marginnote shownote">
Figure 14.5: Screenshot of rpact Shiny app.
</p>
<img src="images/rpact1.png" alt="Screenshot of rpact Shiny app." width="600">
</div>
</div>
</div>
<div id="comparing-spending-functions" class="section level2">
<h2>
<span class="header-section-number">14.2</span> Comparing Spending Functions</h2>
<p>It can be useful to explicitly compare different types of designs. As explained before, the Pocock correction maintains a fixed alpha level at each look. The O’Brien-Fleming correction uses a higher threshold for early looks, but has the advantage that the final look occurs closer to the uncorrected alpha level. Because the alpha level is very similar at the last look, so is the total required sample size. Lowering the alpha level means the sample size needs to be increased to maintain the same desired level of statistical power, so different spending functions also require a different increase in the final sample size (to compensate for the lower alpha level, while maintaining the same statistical power). Sequential designs always need to be planned for a slightly larger total sample size at the final look, although as we will see below, because we can expect to stop at earlier looks, on average sample size will be smaller when using sequential designs compared to fixed designs.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="sequential.html#cb140-1"></a><span class="co">#O'Brien &amp; Fleming design, 3 equally spaced stages</span></span>
<span id="cb140-2"><a href="sequential.html#cb140-2"></a>d1 &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(<span class="dt">typeOfDesign =</span> <span class="st">"OF"</span>, <span class="dt">kMax =</span> <span class="dv">5</span>) </span>
<span id="cb140-3"><a href="sequential.html#cb140-3"></a><span class="co"># Pocock design</span></span>
<span id="cb140-4"><a href="sequential.html#cb140-4"></a>d2 &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(<span class="dt">typeOfDesign =</span> <span class="st">"P"</span>, <span class="dt">kMax =</span> <span class="dv">5</span>)</span>
<span id="cb140-5"><a href="sequential.html#cb140-5"></a></span>
<span id="cb140-6"><a href="sequential.html#cb140-6"></a>designSet &lt;-<span class="kw">getDesignSet</span>(<span class="dt">designs =</span> <span class="kw">c</span>(d1, d2), </span>
<span id="cb140-7"><a href="sequential.html#cb140-7"></a>                         <span class="dt">variedParameters =</span> <span class="st">"typeOfDesign"</span>)</span>
<span id="cb140-8"><a href="sequential.html#cb140-8"></a><span class="kw">plot</span>(designSet, <span class="dt">type =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure">
<span id="fig:spending-comparison"></span>
<p class="caption marginnote shownote">
Figure 14.6: Comparison of the Pocock and O’Brien-Fleming boundaries.
</p>
<img src="Statistical_Inferences_files/figure-html/spending-comparison-1.png" alt="Comparison of the Pocock and O'Brien-Fleming boundaries." width="672">
</div>
<p>We see that at each of the 5 looks the critical value for our test is higher than 1.96 (the critical value without correcting for multiple looks, assuming a normal distribution, indicated by the black dashed line). The Pocock correction (P, blue line) has the same critical value at each look: 2.4131803, 2.4131803, 2.4131803, 2.4131803, 2.4131803, while the critical values decrease for each look with the O’Brien-Fleming correction (OF, red line): 4.5617423, 3.2256389, 2.6337232, 2.2808712, 2.0400732. The first three looks use an alpha level that is stricter than the Pocock spending function, but the last two use a much less strict threshold, and the last look occurs at a level quite close to an alpha level without any correction. As we will see below, this is quite efficient, without requiring a noticeable increase in the sample size due to a lower alpha level at the last look.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
Another design, not discussed in the rest of this test, is the design proposed by Haybittle and Peto. Adjust the plot code (changing OF to HP) to see what it looks like.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
Solution<span id="sol-start-3" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-3', 'sol-start-3')"></span>
</p>
<div id="sol-body-3" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="sequential.html#cb141-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb141-2"><a href="sequential.html#cb141-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb141-3"><a href="sequential.html#cb141-3"></a>d1 &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(<span class="dt">typeOfDesign =</span> <span class="st">"HP"</span>,</span>
<span id="cb141-4"><a href="sequential.html#cb141-4"></a>                               <span class="dt">kMax =</span> <span class="dv">5</span>) </span>
<span id="cb141-5"><a href="sequential.html#cb141-5"></a><span class="co"># Pocock</span></span>
<span id="cb141-6"><a href="sequential.html#cb141-6"></a>d2 &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(<span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb141-7"><a href="sequential.html#cb141-7"></a>                               <span class="dt">kMax =</span> <span class="dv">5</span>)</span>
<span id="cb141-8"><a href="sequential.html#cb141-8"></a></span>
<span id="cb141-9"><a href="sequential.html#cb141-9"></a>designSet &lt;-<span class="kw">getDesignSet</span>(<span class="dt">designs =</span> <span class="kw">c</span>(d1, d2), </span>
<span id="cb141-10"><a href="sequential.html#cb141-10"></a>                         <span class="dt">variedParameters =</span> <span class="st">"typeOfDesign"</span>)</span>
<span id="cb141-11"><a href="sequential.html#cb141-11"></a><span class="kw">plot</span>(designSet, <span class="dt">type =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-71-1.png" width="672"></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="sample-size-for-sequential-designs" class="section level2">
<h2>
<span class="header-section-number">14.3</span> Sample Size for Sequential Designs</h2>
<p>Sequential designs require somewhat more participants than a fixed design at the final look, depending on how much the alpha level at this look is lowered due to the correction for multiple comparisons. Due to early stopping, sequential designs will on average require less participants.</p>
<p>Let’s first examine how many participants we would need in a fixed design, where we only analyze our data once. We have an alpha level of 0.05, and a Type 2 (beta) error of 0.1 - in other words, the desired power is 90%. We will perform one test, and assuming a normal distribution our critical Z-score would be 1.96, for an alpha level of 5%.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="sequential.html#cb142-1"></a><span class="co"># specify the design</span></span>
<span id="cb142-2"><a href="sequential.html#cb142-2"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb142-3"><a href="sequential.html#cb142-3"></a>  <span class="dt">kMax =</span> <span class="dv">1</span>,</span>
<span id="cb142-4"><a href="sequential.html#cb142-4"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb142-5"><a href="sequential.html#cb142-5"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb142-6"><a href="sequential.html#cb142-6"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb142-7"><a href="sequential.html#cb142-7"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb142-8"><a href="sequential.html#cb142-8"></a>)</span>
<span id="cb142-9"><a href="sequential.html#cb142-9"></a><span class="co"># print a summary</span></span>
<span id="cb142-10"><a href="sequential.html#cb142-10"></a><span class="kw">summary</span>(seq_design)</span></code></pre></div>
<pre><code>## Fixed sample analysis
## 
## Stage                               Fixed 
## Efficacy boundary (z-value scale)   1.960 
## Two-sided local significance level 0.0500</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="sequential.html#cb144-1"></a><span class="co"># perform a power analysis using rpact</span></span>
<span id="cb144-2"><a href="sequential.html#cb144-2"></a><span class="co"># By setting the alternative to 0.5 and the stDev to 1, we assume a Cohen's d of 0.5 for the alternative hypothesis.</span></span>
<span id="cb144-3"><a href="sequential.html#cb144-3"></a>power_res &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb144-4"><a href="sequential.html#cb144-4"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb144-5"><a href="sequential.html#cb144-5"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb144-6"><a href="sequential.html#cb144-6"></a>  <span class="dt">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb144-7"><a href="sequential.html#cb144-7"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb144-8"><a href="sequential.html#cb144-8"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb144-9"><a href="sequential.html#cb144-9"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span>)</span>
<span id="cb144-10"><a href="sequential.html#cb144-10"></a></span>
<span id="cb144-11"><a href="sequential.html#cb144-11"></a>power_res</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1 
##   Two-sided power                              : FALSE 
##   Test                                         : two-sided 
## 
## User defined parameters:
##   Alternatives                                 : 0.5 
## 
## Default parameters:
##   Normal approximation                         : FALSE 
##   Mean ratio                                   : FALSE 
##   Theta H0                                     : 0 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Number of subjects fixed                     : 170.1 
##   Number of subjects fixed (1)                 : 85.0 
##   Number of subjects fixed (2)                 : 85.0 
##   Lower critical values (effect scale)         : -0.303 
##   Upper critical values (effect scale)         : 0.303 
##   Local two-sided significance levels          : 0.0500 
## 
## Legend:
##   (i): values of treatment arm i</code></pre>
<p>We see we need 85 participants in each group, (or 86, since we always round the number of observations up, as we can not collect 0.03 of a participant), and so we need 172 participants in total (see G*Power, which rounds up values correctly). Because this is a fixed design, we can also compute this sample size using the <code>pwr</code> package in R or any other power analysis software.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="sequential.html#cb146-1"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb146-2"><a href="sequential.html#cb146-2"></a>  <span class="dt">d =</span> <span class="fl">0.5</span>,</span>
<span id="cb146-3"><a href="sequential.html#cb146-3"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb146-4"><a href="sequential.html#cb146-4"></a>  <span class="dt">power =</span> <span class="fl">0.9</span>,</span>
<span id="cb146-5"><a href="sequential.html#cb146-5"></a>  <span class="dt">type=</span><span class="st">"two.sample"</span>,</span>
<span id="cb146-6"><a href="sequential.html#cb146-6"></a>  <span class="dt">alternative=</span><span class="st">"two.sided"</span></span>
<span id="cb146-7"><a href="sequential.html#cb146-7"></a>)<span class="op">$</span>n</span></code></pre></div>
<pre><code>## [1] 85.03128</code></pre>
<p>We can now examine our design above with 2 looks, a Pocock correction, a 2 sided test with an alpha of 0.05. We will look 2 times, and expect a true effect of d = 0.5.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="sequential.html#cb148-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb148-2"><a href="sequential.html#cb148-2"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb148-3"><a href="sequential.html#cb148-3"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb148-4"><a href="sequential.html#cb148-4"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb148-5"><a href="sequential.html#cb148-5"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb148-6"><a href="sequential.html#cb148-6"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb148-7"><a href="sequential.html#cb148-7"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb148-8"><a href="sequential.html#cb148-8"></a>  )</span>
<span id="cb148-9"><a href="sequential.html#cb148-9"></a></span>
<span id="cb148-10"><a href="sequential.html#cb148-10"></a><span class="co"># Compute the sample size we need</span></span>
<span id="cb148-11"><a href="sequential.html#cb148-11"></a>power_res &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb148-12"><a href="sequential.html#cb148-12"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb148-13"><a href="sequential.html#cb148-13"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb148-14"><a href="sequential.html#cb148-14"></a>  <span class="dt">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb148-15"><a href="sequential.html#cb148-15"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb148-16"><a href="sequential.html#cb148-16"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb148-17"><a href="sequential.html#cb148-17"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span>)</span>
<span id="cb148-18"><a href="sequential.html#cb148-18"></a></span>
<span id="cb148-19"><a href="sequential.html#cb148-19"></a><span class="kw">summary</span>(power_res)</span></code></pre></div>
<pre><code>## Sample size calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 2 looks (group sequential design).
## The sample size was calculated for a two-sample t-test (two-sided),
## alternative = 0.5, standard deviation = 1, allocation ratio = 1, and power 90%.
## 
## Stage                                         1      2 
## Information rate                            50%   100% 
## Efficacy boundary (z-value scale)         2.178  2.178 
## Number of subjects                           94    188 
## Cumulative alpha spent                   0.0294 0.0500 
## Cumulative power                         0.5893 0.9000 
## Two-sided local significance level       0.0294 0.0294 
## Lower efficacy boundary (t)              -0.458 -0.321 
## Upper efficacy boundary (t)               0.458  0.321 
## Exit probability for efficacy (under H0) 0.0294 
## Exit probability for efficacy (under H1) 0.5893 
## 
## Legend:
##   (t): approximate treatment effect scale</code></pre>
<p>It is important to know that <code>rpact</code> returns the <em>total</em> number of subjects at look 1 (94, so 94/2 = 47 in each group), and the total sample size at look 2 (188, so 188/2 = 94 in each group). This means that at the second look, we are now collecting 188 instead of 172 participants. This is a consequence of lowering our alpha level at each look (from 0.05 to 0.0294). To compensate for the loss of power, we need to increase our sample size. HOwever, this is compensated by the fact that sometimes we will stop after look 1, and thus on average we will collect less participants (even though we might sometimes collect more participants than we would have, had we not used a sequential design). <code>rpact</code> also computes the expected number of participants, in the long run, if the true effect size is d = 0.5.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="sequential.html#cb150-1"></a>power_res<span class="op">$</span>expectedNumberOfSubjectsH1</span></code></pre></div>
<pre><code>## [1] 131.9571</code></pre>
<p>So, in the long run, if the true effect size is d = 0.5, we will collect 132 observations (66 per condition), instead of 172 in total (or 86 per condition).</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
If we had expected an effect size of d = 0.4, what would the total sample size we needed to collect for 90% power be?
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
Solution<span id="sol-start-4" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-4', 'sol-start-4')"></span>
</p>
<div id="sol-body-4" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="sequential.html#cb152-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb152-2"><a href="sequential.html#cb152-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb152-3"><a href="sequential.html#cb152-3"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb152-4"><a href="sequential.html#cb152-4"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb152-5"><a href="sequential.html#cb152-5"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb152-6"><a href="sequential.html#cb152-6"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb152-7"><a href="sequential.html#cb152-7"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb152-8"><a href="sequential.html#cb152-8"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb152-9"><a href="sequential.html#cb152-9"></a>  )</span>
<span id="cb152-10"><a href="sequential.html#cb152-10"></a></span>
<span id="cb152-11"><a href="sequential.html#cb152-11"></a><span class="co"># Compute the sample size we need</span></span>
<span id="cb152-12"><a href="sequential.html#cb152-12"></a>power_res &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb152-13"><a href="sequential.html#cb152-13"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb152-14"><a href="sequential.html#cb152-14"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb152-15"><a href="sequential.html#cb152-15"></a>  <span class="dt">alternative =</span> <span class="fl">0.4</span>, </span>
<span id="cb152-16"><a href="sequential.html#cb152-16"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb152-17"><a href="sequential.html#cb152-17"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb152-18"><a href="sequential.html#cb152-18"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span>)</span>
<span id="cb152-19"><a href="sequential.html#cb152-19"></a></span>
<span id="cb152-20"><a href="sequential.html#cb152-20"></a>power_res<span class="op">$</span>expectedNumberOfSubjectsH1</span></code></pre></div>
<pre><code>## [1] 205.328</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Because power is a curve, and the true effect size is always unknown, it is useful to plot power across a range of possible effect sizes, so that we can explore the expected sample size, in the long run, if we use a sequential design, for different true effect sizes.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="sequential.html#cb154-1"></a><span class="co"># Use getPowerMeans and set max N to 188 based on analysis above</span></span>
<span id="cb154-2"><a href="sequential.html#cb154-2"></a>sample_res &lt;-<span class="st"> </span><span class="kw">getPowerMeans</span>(</span>
<span id="cb154-3"><a href="sequential.html#cb154-3"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb154-4"><a href="sequential.html#cb154-4"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb154-5"><a href="sequential.html#cb154-5"></a>  <span class="dt">alternative =</span> <span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.1</span>), </span>
<span id="cb154-6"><a href="sequential.html#cb154-6"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb154-7"><a href="sequential.html#cb154-7"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb154-8"><a href="sequential.html#cb154-8"></a>  <span class="dt">maxNumberOfSubjects =</span> <span class="dv">188</span>, <span class="co">#rounded up from 187.0829</span></span>
<span id="cb154-9"><a href="sequential.html#cb154-9"></a>  <span class="dt">normalApproximation =</span> <span class="ot">TRUE</span>)</span>
<span id="cb154-10"><a href="sequential.html#cb154-10"></a></span>
<span id="cb154-11"><a href="sequential.html#cb154-11"></a><span class="kw">plot</span>(sample_res, <span class="dt">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-81-1.png" width="672"></p>
<p>The blue line indicates the expected number of observations we need to collect. Not surprisingly, when the true effect size is 0, we will almost always continue data collection to the end. We will only stop if we observe a Type 1 error, which is rare, and thus the expected number of observations is very close to 120. On the other side of the graph we see the scenario for when the true effect size is d = 1. With such a large effect size, we will have high power at our first look, and we will almost always be able to stop at the first look. If the true effect size is 0.5, we see we can expect to collect 132 participants on average.</p>
<p>The Pocock correction leads to a substantially lower alpha level at the last look, which requires an increase in sample size to compensate. As we saw before, the O’Brien-Fleming spending function does not require such a severe reduction in the alpha level at the last look. Let’s see how well this performs. With 2 looks, this design would not need an increase in sample size at all, yet lower the expected number of observations we would collect to 145. However, let’s add 2 additional looks at the data, for 4 looks in total.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="sequential.html#cb155-1"></a><span class="co"># Now a 4 look OF design</span></span>
<span id="cb155-2"><a href="sequential.html#cb155-2"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb155-3"><a href="sequential.html#cb155-3"></a>  <span class="dt">kMax =</span> <span class="dv">4</span>,</span>
<span id="cb155-4"><a href="sequential.html#cb155-4"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"OF"</span>,</span>
<span id="cb155-5"><a href="sequential.html#cb155-5"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb155-6"><a href="sequential.html#cb155-6"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb155-7"><a href="sequential.html#cb155-7"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb155-8"><a href="sequential.html#cb155-8"></a>  )</span>
<span id="cb155-9"><a href="sequential.html#cb155-9"></a><span class="kw">summary</span>(seq_design)</span></code></pre></div>
<pre><code>## Sequential analysis with a maximum of 4 looks (group sequential design)
## 
## Stage                                    1       2       3       4 
## Information rate                       25%     50%     75%    100% 
## Efficacy boundary (z-value scale)    4.049   2.863   2.337   2.024 
## Cumulative alpha spent             &lt;0.0001  0.0042  0.0209  0.0500 
## Two-sided local significance level &lt;0.0001  0.0042  0.0194  0.0429</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="sequential.html#cb157-1"></a>power_res &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb157-2"><a href="sequential.html#cb157-2"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb157-3"><a href="sequential.html#cb157-3"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb157-4"><a href="sequential.html#cb157-4"></a>  <span class="dt">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb157-5"><a href="sequential.html#cb157-5"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb157-6"><a href="sequential.html#cb157-6"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb157-7"><a href="sequential.html#cb157-7"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span>)</span>
<span id="cb157-8"><a href="sequential.html#cb157-8"></a></span>
<span id="cb157-9"><a href="sequential.html#cb157-9"></a><span class="kw">summary</span>(power_res)</span></code></pre></div>
<pre><code>## Sample size calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 4 looks (group sequential design).
## The sample size was calculated for a two-sample t-test (two-sided),
## alternative = 0.5, standard deviation = 1, allocation ratio = 1, and power 90%.
## 
## Stage                                          1       2       3       4 
## Information rate                             25%     50%     75%    100% 
## Efficacy boundary (z-value scale)          4.049   2.863   2.337   2.024 
## Number of subjects                            44      87     131     174 
## Cumulative alpha spent                   &lt;0.0001  0.0042  0.0209  0.0500 
## Cumulative power                          0.0080  0.2930  0.6960  0.9000 
## Two-sided local significance level       &lt;0.0001  0.0042  0.0194  0.0429 
## Lower efficacy boundary (t)               -1.370  -0.631  -0.415  -0.309 
## Upper efficacy boundary (t)                1.370   0.631   0.415   0.309 
## Exit probability for efficacy (under H0) &lt;0.0001  0.0042  0.0167 
## Exit probability for efficacy (under H1)  0.0080  0.2850  0.4031 
## 
## Legend:
##   (t): approximate treatment effect scale</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="sequential.html#cb159-1"></a>sample_res &lt;-<span class="st"> </span><span class="kw">getPowerMeans</span>(</span>
<span id="cb159-2"><a href="sequential.html#cb159-2"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb159-3"><a href="sequential.html#cb159-3"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb159-4"><a href="sequential.html#cb159-4"></a>  <span class="dt">alternative =</span> <span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.1</span>), </span>
<span id="cb159-5"><a href="sequential.html#cb159-5"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb159-6"><a href="sequential.html#cb159-6"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb159-7"><a href="sequential.html#cb159-7"></a>  <span class="dt">maxNumberOfSubjects =</span> <span class="dv">174</span>, </span>
<span id="cb159-8"><a href="sequential.html#cb159-8"></a>  <span class="dt">normalApproximation =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p>We see that with 4 looks, we will not need to increase the maximum sample size a lot, as we only need 174 instead of 172 participants.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="sequential.html#cb160-1"></a>power_res<span class="op">$</span>maxNumberOfSubjects</span></code></pre></div>
<pre><code>## [1] 173.8317</code></pre>
<p>There is a noticeable reduction in the average number of samples we can expect to collect, if the true effect size is d = 0.5.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="sequential.html#cb162-1"></a>power_res<span class="op">$</span>expectedNumberOfSubjectsH1</span></code></pre></div>
<pre><code>## [1] 130.5056</code></pre>
<p>If we plot this expected sample size across different true effect sizes, we see that we become more efficient - only at the cost of 1) analyzing our data 4 times, and 2) needing to preregister our analysis plan. Preregistration is required, because sequential analyses give a lot of additional freedom that can possibly inflate error rates substantially. So performing computations as performed here, and preregistering your analysis plan, is required - but worth it.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="sequential.html#cb164-1"></a><span class="kw">plot</span>(sample_res, <span class="dt">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-85-1.png" width="672"></p>
<p>We can redo the power analysis in for the original 2 look design in gsDesign. The graph shows that if the true effect size is d = 0.5 we have approximately 59% power after the first look, and 90% power after the second look, given our adjusted alpha level.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="sequential.html#cb165-1"></a>seqdesign &lt;-<span class="st"> </span><span class="kw">gsDesign</span>(</span>
<span id="cb165-2"><a href="sequential.html#cb165-2"></a>  <span class="dt">k =</span> <span class="dv">2</span>, <span class="co"># k = number of looks = 2</span></span>
<span id="cb165-3"><a href="sequential.html#cb165-3"></a>  <span class="dt">test.type =</span> <span class="dv">2</span>,</span>
<span id="cb165-4"><a href="sequential.html#cb165-4"></a>  <span class="dt">alpha =</span> <span class="fl">.025</span>,</span>
<span id="cb165-5"><a href="sequential.html#cb165-5"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb165-6"><a href="sequential.html#cb165-6"></a>  <span class="dt">sfu =</span> <span class="st">"Pocock"</span>,</span>
<span id="cb165-7"><a href="sequential.html#cb165-7"></a>  <span class="co"># gsDesign calculates d as a within subjects d. </span></span>
<span id="cb165-8"><a href="sequential.html#cb165-8"></a>  <span class="co"># We need the /sqrt(2) to turn it from d_z into d</span></span>
<span id="cb165-9"><a href="sequential.html#cb165-9"></a>  <span class="dt">delta =</span> <span class="fl">0.5</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span>), </span>
<span id="cb165-10"><a href="sequential.html#cb165-10"></a>  <span class="dt">delta0 =</span> <span class="dv">0</span>,</span>
<span id="cb165-11"><a href="sequential.html#cb165-11"></a>  <span class="dt">delta1 =</span> <span class="fl">0.5</span></span>
<span id="cb165-12"><a href="sequential.html#cb165-12"></a>) <span class="co"># spending function = Pocock</span></span>
<span id="cb165-13"><a href="sequential.html#cb165-13"></a></span>
<span id="cb165-14"><a href="sequential.html#cb165-14"></a><span class="co"># All required info is in:</span></span>
<span id="cb165-15"><a href="sequential.html#cb165-15"></a>seqdesign</span></code></pre></div>
<pre><code>## Symmetric two-sided group sequential design with
## 90 % power and 2.5 % Type I Error.
## Spending computations assume trial stops
## if a bound is crossed.
## 
##              
##   Analysis N   Z   Nominal p  Spend
##          1 47 2.18    0.0147 0.0147
##          2 93 2.18    0.0147 0.0103
##      Total                   0.0250 
## 
## ++ alpha spending:
##  Pocock boundary.
## 
## Boundary crossing probabilities and expected sample size
## assume any cross stops the trial
## 
## Upper boundary (power or Type I Error)
##           Analysis
##    Theta      1      2 Total E{N}
##   0.0000 0.0147 0.0103 0.025 91.1
##   0.3536 0.5893 0.3107 0.900 65.2
## 
## Lower boundary (futility or Type II Error)
##           Analysis
##    Theta      1      2 Total
##   0.0000 0.0147 0.0103 0.025
##   0.3536 0.0000 0.0000 0.000</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="sequential.html#cb167-1"></a><span class="co"># We can look at the sample sizes as expected compared to a fixed design</span></span>
<span id="cb167-2"><a href="sequential.html#cb167-2"></a><span class="kw">plot</span>(seqdesign, <span class="dt">plottype =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-86-1.png" width="672"></p>
<div id="alpha-spending-functions" class="section level3">
<h3>
<span class="header-section-number">14.3.1</span> Alpha spending functions</h3>
<p>The Pocock and O’Brien-Fleming spending functions we discussed so far have an important limitation <span class="citation">(Proschan et al., <label for="tufte-mn-95" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-95" class="margin-toggle">2006<span class="marginnote">Proschan, M. A., Lan, K. K. G., &amp; Wittes, J. T. (2006). <em>Statistical monitoring of clinical trials: A unified approach</em>. Springer.</span>)</span>. They require a pre-specified number of looks (e.g., 4) that is equally spaced (e.g., after 25%, 50%, 75%, and 100%). It is not always possible to stop data collection exactly after for example the 50th participant, because you need to pause data collection to analyze the data, which might not be possible if additional sessions are scheduled on the day the 50th observation is collected. An important contribution to the sequential testing literature was made by Lan and DeMets <span class="citation">(<label for="tufte-mn-96" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-96" class="margin-toggle">1983<span class="marginnote">Lan, K. K. G., &amp; DeMets, D. L. (1983). Discrete Sequential Boundaries for Clinical Trials. <em>Biometrika</em>, <em>70</em>(3), 659. <a href="https://doi.org/10.2307/2336502">https://doi.org/10.2307/2336502</a></span>)</span> who created <strong>alpha spending functions</strong>, where the boundary at the decision time does not depend on the future decision times or the total number of decision times.</p>
<p>We see the O’Brien-Fleming-like alpha spending function is quite similar to the discrete O’Brien-Fleming bounds.</p>
<div class="figure">
<span id="fig:spending-comparison-2"></span>
<p class="caption marginnote shownote">
Figure 14.7: Comparison of the O’Brien-Fleming boundaries and the O’Brien-FLiming-like alpha spending function.
</p>
<img src="Statistical_Inferences_files/figure-html/spending-comparison-2-1.png" alt="Comparison of the O'Brien-Fleming boundaries and the O'Brien-FLiming-like alpha spending function." width="672">
</div>
<p>There is a wide range of alpha spending functions possible. In addition to a Pocock-type and O’Brien-Fleming-type alpha spending function <code>rpact</code> has the Kim &amp; DeMets alpha spending function and the Hwang, Shi &amp; DeCani alpha spending function, but users can also specify a custom spending function. Again, the main benefit of these spending functions is that neither the number nor the timing of the looks needs to be specified in advance, which makes alpha spending approaches much more flexible. However, it is important that the decision to perform an interim analysis is not based on collected data, as this can still increase the Type 1 error rate.</p>
<!-- ```{r spending-comparison-3, fig.margin=FALSE, echo=FALSE, fig.cap="Comparison of different alpha spending functions."} -->
<!-- #Pocock type -->
<!-- d1 <- getDesignGroupSequential(typeOfDesign = "asP", -->
<!--                                kMax = 5)  -->
<!-- # OF-like continuous spending function -->
<!-- d2 <- getDesignGroupSequential(typeOfDesign = "asOF", -->
<!--                                kMax = 5) -->
<!-- d3 <- getDesignGroupSequential(typeOfDesign = "asKD", -->
<!--                                kMax = 5) -->
<!-- d4 <- getDesignGroupSequential(typeOfDesign = "asHSD", -->
<!--                                kMax = 5) -->
<!-- designSet <-getDesignSet(designs = c(d1, d2, d3, d4),  -->
<!--                          variedParameters = "typeOfDesign") -->
<!-- plot(designSet, -->
<!--      type = 1) -->
<!-- ``` -->
</div>
<div id="updating-boundaries-during-an-experiment" class="section level3">
<h3>
<span class="header-section-number">14.3.2</span> Updating Boundaries During an Experiment</h3>
<p>Although alpha spending functions control the Type 1 error rate even when there are deviations from the pre-planned looks, this does require recalculating the boundaries based on the amount of information that has been observed. In this example, we follow an <a href="https://vignettes.rpact.org/html/rpact_boundary_update_example.html">rpact vignette</a>. Imagine a two-sided design with an O’Brien-Fleming-type alpha-spending function, and alpha of 0.025, a desired power of 90%, with 3 looks, planned when 50%, 75%, and 100% of our maximum sample has been collected.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="sequential.html#cb168-1"></a><span class="co"># Original design:</span></span>
<span id="cb168-2"><a href="sequential.html#cb168-2"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb168-3"><a href="sequential.html#cb168-3"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb168-4"><a href="sequential.html#cb168-4"></a>  <span class="dt">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb168-5"><a href="sequential.html#cb168-5"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb168-6"><a href="sequential.html#cb168-6"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb168-7"><a href="sequential.html#cb168-7"></a>  <span class="dt">informationRates =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb168-8"><a href="sequential.html#cb168-8"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"asOF"</span></span>
<span id="cb168-9"><a href="sequential.html#cb168-9"></a>)</span>
<span id="cb168-10"><a href="sequential.html#cb168-10"></a></span>
<span id="cb168-11"><a href="sequential.html#cb168-11"></a><span class="co"># Initial sample size calculation</span></span>
<span id="cb168-12"><a href="sequential.html#cb168-12"></a>sampleSizeResult &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb168-13"><a href="sequential.html#cb168-13"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb168-14"><a href="sequential.html#cb168-14"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb168-15"><a href="sequential.html#cb168-15"></a>  <span class="dt">alternative =</span> <span class="fl">0.5</span>,</span>
<span id="cb168-16"><a href="sequential.html#cb168-16"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb168-17"><a href="sequential.html#cb168-17"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb168-18"><a href="sequential.html#cb168-18"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span></span>
<span id="cb168-19"><a href="sequential.html#cb168-19"></a>)</span>
<span id="cb168-20"><a href="sequential.html#cb168-20"></a></span>
<span id="cb168-21"><a href="sequential.html#cb168-21"></a><span class="co"># Summarize design</span></span>
<span id="cb168-22"><a href="sequential.html#cb168-22"></a><span class="kw">summary</span>(sampleSizeResult)</span></code></pre></div>
<pre><code>## Sample size calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 3 looks (group sequential design).
## The sample size was calculated for a two-sample t-test (two-sided),
## alternative = 0.5, standard deviation = 1, allocation ratio = 1, and power 90%.
## 
## Stage                                         1      2      3 
## Information rate                            50%    75%   100% 
## Efficacy boundary (z-value scale)         2.963  2.359  2.014 
## Number of subjects                           87    130    174 
## Cumulative alpha spent                   0.0031 0.0193 0.0500 
## Cumulative power                         0.2580 0.6853 0.9000 
## Two-sided local significance level       0.0031 0.0183 0.0440 
## Lower efficacy boundary (t)              -0.656 -0.419 -0.308 
## Upper efficacy boundary (t)               0.656  0.419  0.308 
## Exit probability for efficacy (under H0) 0.0031 0.0162 
## Exit probability for efficacy (under H1) 0.2580 0.4273 
## 
## Legend:
##   (t): approximate treatment effect scale</code></pre>
<p>The a-priori power analysis shows that, assuming an effect size of 0.5, we plan to look after 87, 130, 174 observations. Now imagine that due to logistical issues, we do not have to ability to analyze the data until we have collected data from 95, instead of 87, participants. So our first look at the data does not occur at 50% of our sample, but at 95/174 = 54.6%. We can recalculate the alpha levels we should use for this and future looks, and update our sample size calculation. This reveals we should use an alpha level of 0.0048 for the current look (instead of 0.0031). and the next look should occur after 131 participants in total, not 130. We see the differences are not very substantial, but if the deviation from the planned looks increases, the changes might become more impactful. Note that even if the number of looks was not pre-planned, we would use similar calculations at each look, but instead increase the number of looks (e.g., perform an analysis with 1 interim look at time = 95/174, and if the second look occurs after 146 participants, we would run an analysis with two interim looks, one at 95/174 and a second at 146/174, see Proschan et al., 2006, chapter 5).</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="sequential.html#cb170-1"></a>seq_design_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb170-2"><a href="sequential.html#cb170-2"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb170-3"><a href="sequential.html#cb170-3"></a>  <span class="dt">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb170-4"><a href="sequential.html#cb170-4"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb170-5"><a href="sequential.html#cb170-5"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb170-6"><a href="sequential.html#cb170-6"></a>  <span class="dt">informationRates =</span> <span class="kw">c</span>(<span class="dv">95</span><span class="op">/</span><span class="dv">174</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb170-7"><a href="sequential.html#cb170-7"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"asOF"</span></span>
<span id="cb170-8"><a href="sequential.html#cb170-8"></a>)</span>
<span id="cb170-9"><a href="sequential.html#cb170-9"></a></span>
<span id="cb170-10"><a href="sequential.html#cb170-10"></a><span class="kw">summary</span>(seq_design_<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Sequential analysis with a maximum of 3 looks (group sequential design)
## 
## Stage                                   1      2      3 
## Information rate                    54.6%    75%   100% 
## Efficacy boundary (z-value scale)   2.818  2.370  2.015 
## Cumulative alpha spent             0.0048 0.0193 0.0500 
## Two-sided local significance level 0.0048 0.0178 0.0439</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="sequential.html#cb172-1"></a><span class="co"># Update power analysis</span></span>
<span id="cb172-2"><a href="sequential.html#cb172-2"></a></span>
<span id="cb172-3"><a href="sequential.html#cb172-3"></a>power_update_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">getPowerMeans</span>(</span>
<span id="cb172-4"><a href="sequential.html#cb172-4"></a>  <span class="dt">design =</span> seq_design_<span class="dv">2</span>,</span>
<span id="cb172-5"><a href="sequential.html#cb172-5"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb172-6"><a href="sequential.html#cb172-6"></a>  <span class="dt">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb172-7"><a href="sequential.html#cb172-7"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb172-8"><a href="sequential.html#cb172-8"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb172-9"><a href="sequential.html#cb172-9"></a>  <span class="dt">maxNumberOfSubjects =</span> <span class="dv">174</span>, </span>
<span id="cb172-10"><a href="sequential.html#cb172-10"></a>  <span class="dt">normalApproximation =</span> <span class="ot">TRUE</span>)</span>
<span id="cb172-11"><a href="sequential.html#cb172-11"></a><span class="kw">summary</span>(power_update_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Power calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 3 looks (group sequential design).
## The results were calculated for a two-sample t-test (two-sided),
## alternative = 0.5, standard deviation = 1, allocation ratio = 1.
## 
## Stage                                         1      2      3 
## Information rate                          54.6%    75%   100% 
## Efficacy boundary (z-value scale)         2.818  2.370  2.015 
## Number of subjects                           96    131    174 
## Cumulative alpha spent                   0.0048 0.0193 0.0500 
## Cumulative power                         0.3516 0.6917 0.9045 
## Two-sided local significance level       0.0048 0.0178 0.0439 
## Lower efficacy boundary (t)              -0.578 -0.415 -0.306 
## Upper efficacy boundary (t)               0.578  0.415  0.306 
## Exit probability for efficacy (under H0) 0.0048 0.0145 
## Exit probability for efficacy (under H1) 0.3516 0.3401 
## 
## Legend:
##   (t): approximate treatment effect scale</code></pre>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
What if we had look even later, after 105 participants? Which alpha level should we have used for the first interim test?
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
Solution<span id="sol-start-5" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-5', 'sol-start-5')"></span>
</p>
<div id="sol-body-5" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="sequential.html#cb174-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb174-2"><a href="sequential.html#cb174-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb174-3"><a href="sequential.html#cb174-3"></a>seq_design_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb174-4"><a href="sequential.html#cb174-4"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb174-5"><a href="sequential.html#cb174-5"></a>  <span class="dt">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb174-6"><a href="sequential.html#cb174-6"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb174-7"><a href="sequential.html#cb174-7"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb174-8"><a href="sequential.html#cb174-8"></a>  <span class="dt">informationRates =</span> <span class="kw">c</span>(<span class="dv">105</span><span class="op">/</span><span class="dv">174</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb174-9"><a href="sequential.html#cb174-9"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"asOF"</span></span>
<span id="cb174-10"><a href="sequential.html#cb174-10"></a>)</span>
<span id="cb174-11"><a href="sequential.html#cb174-11"></a></span>
<span id="cb174-12"><a href="sequential.html#cb174-12"></a><span class="co"># Update power analysis</span></span>
<span id="cb174-13"><a href="sequential.html#cb174-13"></a></span>
<span id="cb174-14"><a href="sequential.html#cb174-14"></a>power_update_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">getPowerMeans</span>(</span>
<span id="cb174-15"><a href="sequential.html#cb174-15"></a>  <span class="dt">design =</span> seq_design_<span class="dv">2</span>,</span>
<span id="cb174-16"><a href="sequential.html#cb174-16"></a>  <span class="dt">groups =</span> <span class="dv">2</span>,</span>
<span id="cb174-17"><a href="sequential.html#cb174-17"></a>  <span class="dt">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb174-18"><a href="sequential.html#cb174-18"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb174-19"><a href="sequential.html#cb174-19"></a>  <span class="dt">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb174-20"><a href="sequential.html#cb174-20"></a>  <span class="dt">maxNumberOfSubjects =</span> <span class="dv">174</span>, </span>
<span id="cb174-21"><a href="sequential.html#cb174-21"></a>  <span class="dt">normalApproximation =</span> <span class="ot">TRUE</span>)</span>
<span id="cb174-22"><a href="sequential.html#cb174-22"></a></span>
<span id="cb174-23"><a href="sequential.html#cb174-23"></a><span class="kw">summary</span>(power_update_<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Power calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 3 looks (group sequential design).
## The results were calculated for a two-sample t-test (two-sided),
## alternative = 0.5, standard deviation = 1, allocation ratio = 1.
## 
## Stage                                         1      2      3 
## Information rate                          60.3%    75%   100% 
## Efficacy boundary (z-value scale)         2.660  2.388  2.016 
## Number of subjects                          105    131    174 
## Cumulative alpha spent                   0.0078 0.0193 0.0500 
## Cumulative power                         0.4610 0.6894 0.9043 
## Two-sided local significance level       0.0078 0.0170 0.0438 
## Lower efficacy boundary (t)              -0.519 -0.418 -0.306 
## Upper efficacy boundary (t)               0.519  0.418  0.306 
## Exit probability for efficacy (under H0) 0.0078 0.0115 
## Exit probability for efficacy (under H1) 0.4610 0.2284 
## 
## Legend:
##   (t): approximate treatment effect scale</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="sequential.html#cb176-1"></a><span class="co"># So the answer is 0.0078</span></span></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="test-for-non-inferiority" class="section level2">
<h2>
<span class="header-section-number">14.4</span> Test for (non-)inferiority</h2>
<p>In an equivalence test, it is common to compare the observed effect against an upper and lower bound of the equivalence range. <code>rpact</code> supports <strong>non-inferiority and inferiority tests</strong>, where the null hypothesis is one of the equivalence bound (e.g., d = 0.5) and the alternative hypothesis is an effect of 0. In essence, this is a directional equivalence test where we consider an effect too small to be meaningful (inferior) if it is smaller than the upper bound of the equivalence range, for example d = 0.5 - also when the effect is on the opposite direction (e.g., d = 0.7). Alternatively, we can be interested in showing an effect is not smaller than the lower equivalence bound, for example d = -0.5, which allows us to conclude the effect is not more negative (non-inferior) than the smallest effect we care about. We can first examine a normal power analysis for a non-inferiority test for a fixed design for 90% power.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="sequential.html#cb177-1"></a><span class="co"># First for no sequential design</span></span>
<span id="cb177-2"><a href="sequential.html#cb177-2"></a><span class="co"># Corresponds to PASS software</span></span>
<span id="cb177-3"><a href="sequential.html#cb177-3"></a>sampleSizeNoninf &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb177-4"><a href="sequential.html#cb177-4"></a>  <span class="dt">thetaH0 =</span> <span class="fl">-0.5</span>,</span>
<span id="cb177-5"><a href="sequential.html#cb177-5"></a>  <span class="dt">alternative =</span> <span class="fl">0.0</span>,</span>
<span id="cb177-6"><a href="sequential.html#cb177-6"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb177-7"><a href="sequential.html#cb177-7"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb177-8"><a href="sequential.html#cb177-8"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb177-9"><a href="sequential.html#cb177-9"></a>  <span class="dt">sided =</span> <span class="dv">1</span>,</span>
<span id="cb177-10"><a href="sequential.html#cb177-10"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span></span>
<span id="cb177-11"><a href="sequential.html#cb177-11"></a>)</span>
<span id="cb177-12"><a href="sequential.html#cb177-12"></a>sampleSizeNoninf</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Theta H0                                     : -0.5 
##   Alternatives                                 : 0 
## 
## Default parameters:
##   Normal approximation                         : FALSE 
##   Mean ratio                                   : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Number of subjects fixed                     : 138.4 
##   Number of subjects fixed (1)                 : 69.2 
##   Number of subjects fixed (2)                 : 69.2 
##   Critical values (effect scale)               : -0.218 
##   Local one-sided significance levels          : 0.0500 
## 
## Legend:
##   (i): values of treatment arm i</code></pre>
<p>Now, we can repeat the analysis, but first specify our original sequential design, with the small deviation that we need to specify a one-sided test. In practice, this will yield identical results as a power analysis for an equivalence test with symmetrical equivalence bounds and an expected true effect size of zero. However, the use of one-sided test often also directly reflects our hypothesis interest, so it might often be the test that reflects your research question.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="sequential.html#cb179-1"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb179-2"><a href="sequential.html#cb179-2"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb179-3"><a href="sequential.html#cb179-3"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb179-4"><a href="sequential.html#cb179-4"></a>  <span class="dt">sided =</span> <span class="dv">1</span>,</span>
<span id="cb179-5"><a href="sequential.html#cb179-5"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb179-6"><a href="sequential.html#cb179-6"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb179-7"><a href="sequential.html#cb179-7"></a>)</span>
<span id="cb179-8"><a href="sequential.html#cb179-8"></a></span>
<span id="cb179-9"><a href="sequential.html#cb179-9"></a>sampleSizeNoninf &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb179-10"><a href="sequential.html#cb179-10"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb179-11"><a href="sequential.html#cb179-11"></a>  <span class="dt">thetaH0 =</span> <span class="fl">-0.5</span>,</span>
<span id="cb179-12"><a href="sequential.html#cb179-12"></a>  <span class="dt">alternative =</span> <span class="fl">0.0</span>,</span>
<span id="cb179-13"><a href="sequential.html#cb179-13"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb179-14"><a href="sequential.html#cb179-14"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span></span>
<span id="cb179-15"><a href="sequential.html#cb179-15"></a>)</span>
<span id="cb179-16"><a href="sequential.html#cb179-16"></a>sampleSizeNoninf</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Theta H0                                     : -0.5 
##   Alternatives                                 : 0 
## 
## Default parameters:
##   Normal approximation                         : FALSE 
##   Mean ratio                                   : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Information rates [1]                        : 0.500 
##   Information rates [2]                        : 1.000 
##   Maximum number of subjects                   : 153.6 
##   Maximum number of subjects (1)               : 76.8 
##   Maximum number of subjects (2)               : 76.8 
##   Number of subjects [1]                       : 76.8 
##   Number of subjects [2]                       : 153.6 
##   Expected number of subjects under H0         : 151.2 
##   Expected number of subjects under H0/H1      : 137.0 
##   Expected number of subjects under H1         : 106.0 
##   Reject per stage [1]                         : 0.62 
##   Reject per stage [2]                         : 0.28 
##   Early stop                                   : 0.62 
##   Critical values (effect scale) [1]           : -0.0654 
##   Critical values (effect scale) [2]           : -0.1950 
##   Local one-sided significance levels [1]      : 0.03037 
##   Local one-sided significance levels [2]      : 0.03037 
## 
## Legend:
##   (i): values of treatment arm i
##   [k]: values at stage k</code></pre>
<p>We see that compared to a fixed design, our maximum sample size has increased from 139 to 154. However, if there really is no effect (d = 0, the alternative hypothesis of our non-inferiority test is true) then we should expect to collect on average 106 observations, in the long run. Of course, as we have seen above, more efficient designs can be designed.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
If we had tested against a lower bound of d = -0.3, which sample size would we need?
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
Solution<span id="sol-start-6" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-6', 'sol-start-6')"></span>
</p>
<div id="sol-body-6" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="sequential.html#cb181-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb181-2"><a href="sequential.html#cb181-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb181-3"><a href="sequential.html#cb181-3"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb181-4"><a href="sequential.html#cb181-4"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb181-5"><a href="sequential.html#cb181-5"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb181-6"><a href="sequential.html#cb181-6"></a>  <span class="dt">sided =</span> <span class="dv">1</span>,</span>
<span id="cb181-7"><a href="sequential.html#cb181-7"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb181-8"><a href="sequential.html#cb181-8"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb181-9"><a href="sequential.html#cb181-9"></a>)</span>
<span id="cb181-10"><a href="sequential.html#cb181-10"></a></span>
<span id="cb181-11"><a href="sequential.html#cb181-11"></a>sampleSizeNoninf &lt;-<span class="st"> </span><span class="kw">getSampleSizeMeans</span>(</span>
<span id="cb181-12"><a href="sequential.html#cb181-12"></a>  <span class="dt">design =</span> seq_design,</span>
<span id="cb181-13"><a href="sequential.html#cb181-13"></a>  <span class="dt">thetaH0 =</span> <span class="fl">-0.3</span>,</span>
<span id="cb181-14"><a href="sequential.html#cb181-14"></a>  <span class="dt">alternative =</span> <span class="fl">0.0</span>,</span>
<span id="cb181-15"><a href="sequential.html#cb181-15"></a>  <span class="dt">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb181-16"><a href="sequential.html#cb181-16"></a>  <span class="dt">normalApproximation =</span> <span class="ot">FALSE</span></span>
<span id="cb181-17"><a href="sequential.html#cb181-17"></a>)</span>
<span id="cb181-18"><a href="sequential.html#cb181-18"></a>sampleSizeNoninf</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Theta H0                                     : -0.3 
##   Alternatives                                 : 0 
## 
## Default parameters:
##   Normal approximation                         : FALSE 
##   Mean ratio                                   : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Information rates [1]                        : 0.500 
##   Information rates [2]                        : 1.000 
##   Maximum number of subjects                   : 423.8 
##   Maximum number of subjects (1)               : 211.9 
##   Maximum number of subjects (2)               : 211.9 
##   Number of subjects [1]                       : 211.9 
##   Number of subjects [2]                       : 423.8 
##   Expected number of subjects under H0         : 417.4 
##   Expected number of subjects under H0/H1      : 378.0 
##   Expected number of subjects under H1         : 292.5 
##   Reject per stage [1]                         : 0.62 
##   Reject per stage [2]                         : 0.28 
##   Early stop                                   : 0.62 
##   Critical values (effect scale) [1]           : -0.0409 
##   Critical values (effect scale) [2]           : -0.1173 
##   Local one-sided significance levels [1]      : 0.03037 
##   Local one-sided significance levels [2]      : 0.03037 
## 
## Legend:
##   (i): values of treatment arm i
##   [k]: values at stage k</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="sequential.html#cb183-1"></a><span class="co"># So the answer is 424 in total, 212 in each group</span></span></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="stopping-for-futility" class="section level2">
<h2>
<span class="header-section-number">14.5</span> Stopping for futility</h2>
<p>To declare that a meaningful effect is absent, one should specify a smallest effect size of interest, and perform an equivalence test. However, sometimes you might not be able to justify a choice for a smallest effect size of interest. In such study designs, it is still possible to decide to stop a study at an interim look because continuing data collection is impossible of unlikely to yield a significant effect.</p>
<p>In the most extreme case, it will be impossible for the additional data you collect to lead to a statistically significant result. To illustrate this in a hypothetical scenario, imagine that after collecting 90 out of 100 observations, the observed effect size is very close to zero. The critical effect size in an independent <em>t</em>-test with 50 participants in each group and an alpha level of, say, 0.02, is d = 0.47. If your primary dependent variable is measured on a 7 point Likert scale, it might be that even if every of the remaining 5 participants in group 1 answer 1, and every of the remaining participants in group 2 answers 7, the effect size in the total group of 100 participants can never reach the critical effect size. If the goal of your study was to detect significant effect, at this point you know for a fact that goal will not be reached. Stopping a study at an interim analysis because the final result will not yield a significant effect is called <strong>curtailment</strong>.</p>
<p>In less extreme cases, it might still be possible for the study to observe a significant effect, but the probability is extremely low. The probability of finding a significant result, given the data that have been observed up to an interim analysis, is called <strong>conditional power</strong>. Let’s imagine that in our previous example, after 50 observations, we also observed an effect zero close to zero, and we would have 25% power to find a significant result, for some expected effect size. Wassmer and Brannath <span class="citation">(<label for="tufte-mn-97" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-97" class="margin-toggle">2016<span class="marginnote">Wassmer, G., &amp; Brannath, W. (2016). <em>Group Sequential and Confirmatory Adaptive Designs in Clinical Trials</em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-319-32562-0">https://doi.org/10.1007/978-3-319-32562-0</a></span>)</span> write, due to the direct relation between conditional power and p-values, stopping the trial if the conditional power is lower than some desired threshold is equivalent to stopping a study if the <em>p</em>-value is larger than some critical level. <code>rpact</code> allows us to compute conditional power. Let’s assume that in our 2-stage design, after the first interim analysis, we observe an effect of d = 0.1, while we expected d = 0.5. What is the probability that, if the true effect size is d = 0.5, we find a significant result after adding the second batch of 94 participants?</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="sequential.html#cb184-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb184-2"><a href="sequential.html#cb184-2"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb184-3"><a href="sequential.html#cb184-3"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb184-4"><a href="sequential.html#cb184-4"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb184-5"><a href="sequential.html#cb184-5"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb184-6"><a href="sequential.html#cb184-6"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb184-7"><a href="sequential.html#cb184-7"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb184-8"><a href="sequential.html#cb184-8"></a>)</span>
<span id="cb184-9"><a href="sequential.html#cb184-9"></a></span>
<span id="cb184-10"><a href="sequential.html#cb184-10"></a>dataMeans &lt;-<span class="st"> </span><span class="kw">getDataset</span>(</span>
<span id="cb184-11"><a href="sequential.html#cb184-11"></a>  <span class="dt">n1 =</span> <span class="kw">c</span>(<span class="dv">94</span>), </span>
<span id="cb184-12"><a href="sequential.html#cb184-12"></a>  <span class="dt">n2 =</span> <span class="kw">c</span>(<span class="dv">94</span>), </span>
<span id="cb184-13"><a href="sequential.html#cb184-13"></a>  <span class="dt">means1 =</span> <span class="kw">c</span>(<span class="fl">1.1</span>), <span class="co">#for directional test, means 1 &gt; means 2</span></span>
<span id="cb184-14"><a href="sequential.html#cb184-14"></a>  <span class="dt">means2 =</span> <span class="kw">c</span>(<span class="dv">1</span>),</span>
<span id="cb184-15"><a href="sequential.html#cb184-15"></a>  <span class="dt">stDevs1 =</span><span class="kw">c</span>(<span class="dv">1</span>), </span>
<span id="cb184-16"><a href="sequential.html#cb184-16"></a>  <span class="dt">stDevs2 =</span><span class="kw">c</span>(<span class="dv">1</span>))</span>
<span id="cb184-17"><a href="sequential.html#cb184-17"></a></span>
<span id="cb184-18"><a href="sequential.html#cb184-18"></a><span class="co"># Get analysis results</span></span>
<span id="cb184-19"><a href="sequential.html#cb184-19"></a><span class="co"># Effect sizes are raw effect sizes, not standardized.</span></span>
<span id="cb184-20"><a href="sequential.html#cb184-20"></a>stage_res &lt;-<span class="st"> </span><span class="kw">getStageResults</span>(seq_design, </span>
<span id="cb184-21"><a href="sequential.html#cb184-21"></a>                   <span class="dt">equalVariances =</span> <span class="ot">TRUE</span>,</span>
<span id="cb184-22"><a href="sequential.html#cb184-22"></a>                   <span class="dt">dataInput =</span> dataMeans)</span>
<span id="cb184-23"><a href="sequential.html#cb184-23"></a></span>
<span id="cb184-24"><a href="sequential.html#cb184-24"></a><span class="co"># Compute conditional power after the first look</span></span>
<span id="cb184-25"><a href="sequential.html#cb184-25"></a><span class="kw">getConditionalPower</span>(<span class="dt">design =</span> seq_design,</span>
<span id="cb184-26"><a href="sequential.html#cb184-26"></a>                    <span class="dt">stageResults =</span> stage_res, </span>
<span id="cb184-27"><a href="sequential.html#cb184-27"></a>                    <span class="dt">nPlanned =</span> <span class="kw">c</span>(<span class="dv">94</span>),</span>
<span id="cb184-28"><a href="sequential.html#cb184-28"></a>                    <span class="dt">thetaH1 =</span> <span class="fl">0.5</span>,</span>
<span id="cb184-29"><a href="sequential.html#cb184-29"></a>                    <span class="dt">assumedStDev =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## $nPlanned
## [1] NA 94
## 
## $conditionalPower
## [1]        NA 0.5109739</code></pre>
<p>We see the answer if that we have 51% power. At this point, one might decide to stop for <strong>futility</strong>. You might decide it is not worth continuing the data collection. One the one hand, 51% power is not nothing, but on the other hand, your expectation that the true effect size is d = 0.5 has become somewhat less likely. One might choose to perform a <strong>conditional power analysis</strong>, and increase the sample size you were willing to collect. Given that we have already collected data, it seems intuitive to calculate condition power not based on the effect size we originally expected, but by updating our prior belief about the true effect size given the observed data. This Bayesian alternative is called <strong>predictive power</strong> <span class="citation">(Spiegelhalter et al., <label for="tufte-mn-98" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-98" class="margin-toggle">1986<span class="marginnote">Spiegelhalter, D. J., Freedman, L. S., &amp; Blackburn, P. R. (1986). Monitoring clinical trials: Conditional or predictive power? <em>Controlled Clinical Trials</em>, <em>7</em>(1), 8–17.</span>)</span>. You will probably want to consult a statistician before making these choices.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>
Repeat the conditional power analysis above, assuming you now think the true effect size is d = 0.3, instead of d = 0.5.
</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
Solution<span id="sol-start-7" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility('sol-body-7', 'sol-start-7')"></span>
</p>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="sequential.html#cb186-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb186-2"><a href="sequential.html#cb186-2"></a><span class="kw">library</span>(rpact)</span>
<span id="cb186-3"><a href="sequential.html#cb186-3"></a><span class="co"># Our 2 look design</span></span>
<span id="cb186-4"><a href="sequential.html#cb186-4"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb186-5"><a href="sequential.html#cb186-5"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb186-6"><a href="sequential.html#cb186-6"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb186-7"><a href="sequential.html#cb186-7"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb186-8"><a href="sequential.html#cb186-8"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb186-9"><a href="sequential.html#cb186-9"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb186-10"><a href="sequential.html#cb186-10"></a>)</span>
<span id="cb186-11"><a href="sequential.html#cb186-11"></a></span>
<span id="cb186-12"><a href="sequential.html#cb186-12"></a>dataMeans &lt;-<span class="st"> </span><span class="kw">getDataset</span>(</span>
<span id="cb186-13"><a href="sequential.html#cb186-13"></a>  <span class="dt">n1 =</span> <span class="kw">c</span>(<span class="dv">94</span>), </span>
<span id="cb186-14"><a href="sequential.html#cb186-14"></a>  <span class="dt">n2 =</span> <span class="kw">c</span>(<span class="dv">94</span>), </span>
<span id="cb186-15"><a href="sequential.html#cb186-15"></a>  <span class="dt">means1 =</span> <span class="kw">c</span>(<span class="fl">1.1</span>), <span class="co">#for directional test, means 1 &gt; means 2</span></span>
<span id="cb186-16"><a href="sequential.html#cb186-16"></a>  <span class="dt">means2 =</span> <span class="kw">c</span>(<span class="dv">1</span>),</span>
<span id="cb186-17"><a href="sequential.html#cb186-17"></a>  <span class="dt">stDevs1 =</span><span class="kw">c</span>(<span class="dv">1</span>), </span>
<span id="cb186-18"><a href="sequential.html#cb186-18"></a>  <span class="dt">stDevs2 =</span><span class="kw">c</span>(<span class="dv">1</span>))</span>
<span id="cb186-19"><a href="sequential.html#cb186-19"></a></span>
<span id="cb186-20"><a href="sequential.html#cb186-20"></a><span class="co"># Get analysis results</span></span>
<span id="cb186-21"><a href="sequential.html#cb186-21"></a><span class="co"># Effect sizes are raw effect sizes, not standardized.</span></span>
<span id="cb186-22"><a href="sequential.html#cb186-22"></a>stage_res &lt;-<span class="st"> </span><span class="kw">getStageResults</span>(seq_design, </span>
<span id="cb186-23"><a href="sequential.html#cb186-23"></a>                   <span class="dt">equalVariances =</span> <span class="ot">TRUE</span>,</span>
<span id="cb186-24"><a href="sequential.html#cb186-24"></a>                   <span class="dt">dataInput =</span> dataMeans)</span>
<span id="cb186-25"><a href="sequential.html#cb186-25"></a></span>
<span id="cb186-26"><a href="sequential.html#cb186-26"></a><span class="co"># Compute conditional power after the first look</span></span>
<span id="cb186-27"><a href="sequential.html#cb186-27"></a><span class="kw">getConditionalPower</span>(<span class="dt">design =</span> seq_design,</span>
<span id="cb186-28"><a href="sequential.html#cb186-28"></a>                    <span class="dt">stageResults =</span> stage_res, </span>
<span id="cb186-29"><a href="sequential.html#cb186-29"></a>                    <span class="dt">nPlanned =</span> <span class="kw">c</span>(<span class="dv">94</span>),</span>
<span id="cb186-30"><a href="sequential.html#cb186-30"></a>                    <span class="dt">thetaH1 =</span> <span class="fl">0.3</span>,</span>
<span id="cb186-31"><a href="sequential.html#cb186-31"></a>                    <span class="dt">assumedStDev =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## $nPlanned
## [1] NA 94
## 
## $conditionalPower
## [1]        NA 0.1730899</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="sequential.html#cb188-1"></a><span class="co"># So the answer is conditional power is 17.31%</span></span></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Stopping for futility has benefits and downsides <span class="citation">(Schoenfeld &amp; Meade, <label for="tufte-mn-99" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-99" class="margin-toggle">2005<span class="marginnote">Schoenfeld, D. A., &amp; Meade, M. O. (2005). Pro/con clinical debate: It is acceptable to stop large multicentre randomized controlled trials at interim analysis for futility. <em>Critical Care</em>, <em>9</em>(1), 34–36. <a href="https://doi.org/10.1186/cc3013">https://doi.org/10.1186/cc3013</a></span>)</span>. The biggest problem with stopping for futility is that it makes it impossible to interpret negative results. We do not learn whether the effect is too small to be meaningful, as we would learn in an equivalence test. Clearly, designing a study is most informative if we specify a smallest effect of interest, and perform a formal equivalence test. However, when specifying a smallest effect size of interest is not possible, stopping for futility might be an alternative to carefully consider. Stopping for futility does not impact the Type 1 error rate of a study because we are not declaring an effect if no effect is present.</p>
<p>As an illustration of a simple stopping rule for futility. let’s imagine a researcher is willing to stop for futility because the observed effect size is zero or in the wrong direction. This is only possible in a directional (one-sided) test. In other words, if we predict an effect larger than zero (e.g., d = 0.5), and we observe an effect ≤ 0, we will stop the data collection . Note that it is perfectly possible, due to random variation, that we observe an effect size smaller than 0, especially in small noisy samples where the true effect size is large. But this simple stopping rule will illustrate the basic idea of stopping for futility. In Figure <a href="sequential.html#fig:futility1">14.8</a> the red line indicates critical values to declare a significant effect. For example if we observe a <em>Z</em>-value larger than 2.134 at the second interim analysis, we can stop the study and reject the null hypothesis. However, if at the second interim analysis we observe a <em>Z</em>-score smaller than or equal to 0, the observed effect size is either 0 or smaller, and we can stop the trial for futility.</p>
<div class="figure">
<span id="fig:futility1"></span>
<p class="caption marginnote shownote">
Figure 14.8: O’Brien-Fleming-type boundaries for 3 looks to declare a significant effect (red line) or to stop for futility (blue line).
</p>
<img src="Statistical_Inferences_files/figure-html/futility1-1.png" alt="O'Brien-Fleming-type boundaries for 3 looks to declare a significant effect (red line) or to stop for futility (blue line)." width="672">
</div>
<p>Instead of setting the <em>z</em>-scores for futility manually, we can also compute bounds based on a beta-spending function. At the last look in our sequential design, which we designed to have 90% power, we are willing to accept the null-hypothesis with a 10% error rate. Just as we are willing to distribute our Type 1 error rate across interim analyses, we might be willing to stop for futility at earlier looks, even if we are then making a Type 2 error. If there actually is no effect, such designs are more efficient. One can choose binding and non-binding beta-spending functions (meaning one has to stop, or one can continue on) - the latter is typically recommended. Adding futility bounds based on beta-spending functions reduce power, and increase the required sample size to reach a desired power, but this is on average compensated by the fact you studies stop earlier due to futility, and can thus make designs more efficient. In the plot below, we use an O’Brien-Fleming type design for both the alpha-spending function and the beta-spending function.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="sequential.html#cb189-1"></a><span class="co"># Formal beta spending function</span></span>
<span id="cb189-2"><a href="sequential.html#cb189-2"></a>design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb189-3"><a href="sequential.html#cb189-3"></a>  <span class="dt">sided =</span> <span class="dv">1</span>,</span>
<span id="cb189-4"><a href="sequential.html#cb189-4"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb189-5"><a href="sequential.html#cb189-5"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb189-6"><a href="sequential.html#cb189-6"></a>  <span class="dt">informationRates =</span> <span class="kw">c</span>(<span class="fl">0.33</span>, <span class="fl">0.67</span>, <span class="dv">1</span>),</span>
<span id="cb189-7"><a href="sequential.html#cb189-7"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"asOF"</span>,</span>
<span id="cb189-8"><a href="sequential.html#cb189-8"></a>  <span class="dt">typeBetaSpending=</span><span class="st">"bsOF"</span>,</span>
<span id="cb189-9"><a href="sequential.html#cb189-9"></a>  <span class="dt">bindingFutility =</span> <span class="ot">FALSE</span></span>
<span id="cb189-10"><a href="sequential.html#cb189-10"></a>)</span>
<span id="cb189-11"><a href="sequential.html#cb189-11"></a></span>
<span id="cb189-12"><a href="sequential.html#cb189-12"></a><span class="kw">plot</span>(design)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-104-1.png" width="672"></p>
<div id="reporting-results-after-a-sequential-analysis." class="section level3">
<h3>
<span class="header-section-number">14.5.1</span> Reporting results after a sequential analysis.</h3>
<p>When reporting results for a sequential analyses, there are two things to keep in mind. First, whenever we stop a study early because of a significant effect, there is a risk that we stopped on a random high estimate. This means the effect sizes is larger than the true effect size. Approaches have been developed to correct effect size estimates for single studies. These correction aim to retrieve an accurate effect size estimate from a study that was designed with the goal to examine whether the null hypothesis could be rejected. As <span class="citation">Schönbrodt et al. (<label for="tufte-mn-100" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-100" class="margin-toggle">2017<span class="marginnote">Schönbrodt, F. D., Wagenmakers, E.-J., Zehetleitner, M., &amp; Perugini, M. (2017). Sequential hypothesis testing with Bayes factors: Efficiently testing mean differences. <em>Psychological Methods</em>, <em>22</em>(2), 322–339. <a href="https://doi.org/10.1037/MET0000061">https://doi.org/10.1037/MET0000061</a></span>)</span> show, a meta-analysis of studies that used sequential designs will yield an accurate effect size, because studies that stop early, and have smaller sample sizes, are weighed less and are compensated by the larger studies that did not stop early. Although researchers are free to report adjusted effect size estimates after a sequential design, it might be more important not to confuse the question a study is designed to answer. If you want to accurately estimate an effect size, design a study based on parameter accuracy. If you want to efficiently examined whether you can reject the null hypothesis, design a study where you perform a sequential analysis.</p>
<p>The same issue occurs when reporting <em>p</em>-values. A <em>p</em>-value is the probability of observing a result at least as extreme as the result that was observed, given that the null hypothesis is true. When using sequential analyses, more than
one analysis is performed, and the definition of a result “at least as extreme” needs to be redefined. The recommended procedure to determine what “at least as extreme” means is to order the outcomes of a series of sequential analyses in terms of the stage at which the study was stopped, where earlier stopping is more extreme than later stopping, and where studies with higher Z-values are more extreme, when different studies are stopped at the same time <span class="citation">(Proschan et al., <label for="tufte-mn-101" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-101" class="margin-toggle">2006<span class="marginnote">Proschan, M. A., Lan, K. K. G., &amp; Wittes, J. T. (2006). <em>Statistical monitoring of clinical trials: A unified approach</em>. Springer.</span>)</span>. This is referred to as <strong>stagewise ordering</strong>. Similalry, procedures exist to compute adjusted confidence intervals for sequential designs. <code>rpact</code> allows one to compute stagewise ordered <em>p</em>-values for some designs (e.g., <em>t</em>-tests). For practical purposes, reporting these adjusted estimates might be less important in studies design to test a hypothesis efficiently, while controlling error rates, and reporting a normal <em>p</em>-value, effect size estimate, and confidence interval will most likely suffice, as long as one keeps in mind that the sequential design has a small impact on these values, and that accurate effect size estimates require a meta-analytic estimate from multiple studies, some of which stopped earlier, and some at the final look.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="sequential.html#cb190-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb190-2"><a href="sequential.html#cb190-2"></a>seq_design &lt;-<span class="st"> </span><span class="kw">getDesignGroupSequential</span>(</span>
<span id="cb190-3"><a href="sequential.html#cb190-3"></a>  <span class="dt">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb190-4"><a href="sequential.html#cb190-4"></a>  <span class="dt">typeOfDesign =</span> <span class="st">"P"</span>,</span>
<span id="cb190-5"><a href="sequential.html#cb190-5"></a>  <span class="dt">sided =</span> <span class="dv">2</span>,</span>
<span id="cb190-6"><a href="sequential.html#cb190-6"></a>  <span class="dt">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb190-7"><a href="sequential.html#cb190-7"></a>  <span class="dt">beta =</span> <span class="fl">0.1</span></span>
<span id="cb190-8"><a href="sequential.html#cb190-8"></a>)</span>
<span id="cb190-9"><a href="sequential.html#cb190-9"></a></span>
<span id="cb190-10"><a href="sequential.html#cb190-10"></a><span class="co"># Specify our observed data after N = 188</span></span>
<span id="cb190-11"><a href="sequential.html#cb190-11"></a><span class="co"># Note, you enter the means and sd for each batch.</span></span>
<span id="cb190-12"><a href="sequential.html#cb190-12"></a><span class="co"># So for the second look, you ignore the 94 observations from look 1</span></span>
<span id="cb190-13"><a href="sequential.html#cb190-13"></a><span class="co"># Alternatively use overallN1 etc, see help file</span></span>
<span id="cb190-14"><a href="sequential.html#cb190-14"></a></span>
<span id="cb190-15"><a href="sequential.html#cb190-15"></a>dataMeans &lt;-<span class="st"> </span><span class="kw">getDataset</span>(</span>
<span id="cb190-16"><a href="sequential.html#cb190-16"></a>  <span class="dt">n1 =</span> <span class="kw">c</span>(<span class="dv">94</span>,<span class="dv">94</span>), </span>
<span id="cb190-17"><a href="sequential.html#cb190-17"></a>  <span class="dt">n2 =</span> <span class="kw">c</span>(<span class="dv">94</span>,<span class="dv">94</span>), </span>
<span id="cb190-18"><a href="sequential.html#cb190-18"></a>  <span class="dt">means1 =</span> <span class="kw">c</span>(<span class="fl">1.1</span>,<span class="fl">1.5</span>), <span class="co">#for directional test, means 1 &gt; means 2</span></span>
<span id="cb190-19"><a href="sequential.html#cb190-19"></a>  <span class="dt">means2 =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb190-20"><a href="sequential.html#cb190-20"></a>  <span class="dt">stDevs1 =</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb190-21"><a href="sequential.html#cb190-21"></a>  <span class="dt">stDevs2 =</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb190-22"><a href="sequential.html#cb190-22"></a></span>
<span id="cb190-23"><a href="sequential.html#cb190-23"></a><span class="co"># Get analysis results</span></span>
<span id="cb190-24"><a href="sequential.html#cb190-24"></a><span class="co"># Effect sizes are raw effect sizes, not standardized.</span></span>
<span id="cb190-25"><a href="sequential.html#cb190-25"></a><span class="kw">getAnalysisResults</span>(seq_design, </span>
<span id="cb190-26"><a href="sequential.html#cb190-26"></a>                   <span class="dt">equalVariances =</span> <span class="ot">TRUE</span>,</span>
<span id="cb190-27"><a href="sequential.html#cb190-27"></a>                   <span class="dt">dataInput =</span> dataMeans)</span></code></pre></div>
<pre><code>## [PROGRESS] Stage results calculated [0.027 secs] 
## [PROGRESS] Conditional power calculated [0 secs] 
## [PROGRESS] Conditional rejection probabilities (CRP) calculated [0.002 secs] 
## [PROGRESS] Repeated confidence interval of stage 1 calculated [0.4747 secs] 
## [PROGRESS] Repeated confidence interval of stage 2 calculated [0.5163 secs] 
## [PROGRESS] Repeated confidence interval calculated [0.993 secs] 
## [PROGRESS] Overall repeated p-values of stage 1 calculated [0.2918 secs] 
## [PROGRESS] Overall repeated p-values of stage 2 calculated [0.2709 secs] 
## [PROGRESS] Repeated p-values calculated [0.5647 secs] 
## [PROGRESS] Final p-value calculated [0.003 secs] 
## [PROGRESS] Final confidence interval calculated [0.067 secs]</code></pre>
<pre><code>## Analysis results (group sequential design):
##   Stages                                       : 1, 2 
##   Information rates                            : 0.500, 1.000 
##   Critical values                              : 2.178, 2.178 
##   Futility bounds (non-binding)                : -Inf 
##   Cumulative alpha spending                    : 0.02939, 0.05000 
##   Stage levels                                 : 0.01469, 0.01469 
##   Effect sizes                                 : 0.1, 0.3 
##   Test statistics                              : 0.686, 3.428 
##   p-values                                     : 0.2469204, 0.0003745 
##   Overall test statistics                      : 0.686, 2.887 
##   Overall p-values                             : 0.246920, 0.002055 
##   Actions                                      : continue, reject 
##   Theta H0                                     : 0 
##   Cond. rejection probability                  : 0.01656, NA 
##   Planned sample size                          : NA, NA 
##   Planned allocation ratio                     : 1 
##   Assumed effect                               : 0.3 
##   Assumed standard deviation                   : 1.007 
##   Conditional power                            : NA, NA 
##   RCIs (lower)                                 : -0.2202, 0.0728 
##   RCIs (upper)                                 : 0.4202, 0.5272 
##   Repeated p-values                            : &gt;0.5, 0.007427 
##   Final stage                                  : 2 
##   Final p-value                                : NA, 0.03132 
##   Final CIs (lower)                            : NA, 0.02666 
##   Final CIs (upper)                            : NA, 0.4864 
##   Median unbiased estimate                     : NA, 0.2702</code></pre>

</div>
</div>
</div></body></html>

<p style="text-align: center;">
<a href="bayes.html"><button class="btn btn-default">Previous</button></a>
<a href="references.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2020-08-09
</p>
</div>
</div>

<div class="row" style="padding-top: 2em;">
<p style="text-align: center">
<img src="images/logo.png" style="width: 100px; padding: 0; display: inline; vertical-align: top">
<span style="display: inline-block; margin-left: 2em; margin-top: 16px; font-size: small">
<span style="font-weight: bold;">Daniel Lakens</span><br/>
<a href="https://statistical-inferences.com">statistical-inferences.com</a><br/>
page built  2020-08-09 15:45:44
</span>
</p>
</div>


</body>
</html>
