<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="9 Meta-analysis | Improving Your Statistical Inferences" />
<meta property="og:type" content="book" />
<meta property="og:url" content="http://themethodsection.com/ebook/" />
<meta property="og:image" content="http://themethodsection.com/ebook/images/cover.jpg" />
<meta property="og:description" content="Online textbook to Improve Your Statistical Inferences" />


<meta name="author" content="Daniel Lakens" />

<meta name="date" content="2020-07-21" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Online textbook to Improve Your Statistical Inferences">

<title>9 Meta-analysis | Improving Your Statistical Inferences</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="center.css" type="text/css" />
<link rel="stylesheet" href="custom-msmbstyle.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Improving Your Statistical Inferences<p><p class="author">Daniel Lakens</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html">Welcome</a>
<a href="contents.html">Contents</a>
<a href="preface.html">Preface</a>
<a href="introduction.html">Introduction</a>
<a href="pvalue.html"><span class="toc-section-number">1</span> What is a <em>p</em>-value</a>
<a href="power.html"><span class="toc-section-number">2</span> Power analysis.</a>
<a href="questions.html"><span class="toc-section-number">3</span> Asking Statistical Questions</a>
<a href="errorcontrol.html"><span class="toc-section-number">4</span> Error Control</a>
<a href="effectsizesCI.html"><span class="toc-section-number">5</span> Effect Sizes and Confidence Intervals</a>
<a href="equivalencetest.html"><span class="toc-section-number">6</span> Equivalence Testing</a>
<a href="severity.html"><span class="toc-section-number">7</span> Severe Tests and Risky Predictions</a>
<a href="sesoi.html"><span class="toc-section-number">8</span> Smallest Effect Size of Interest</a>
<a id="active-page" href="meta.html"><span class="toc-section-number">9</span> Meta-analysis</a><ul class="toc-sections">
<li class="toc"><a href="#random-variation"> Random Variation</a></li>
<li class="toc"><a href="#mixed-results"> Mixed Results</a></li>
<li class="toc"><a href="#introduction-to-meta-analysis"> Introduction to Meta-Analysis</a></li>
</ul>
<a href="bias.html"><span class="toc-section-number">10</span> Bias detection</a>
<a href="computationalreproducibility.html"><span class="toc-section-number">11</span> Computational Reproducibility</a>
<a href="bayes.html"><span class="toc-section-number">12</span> Bayesian statistics</a>
<a href="references.html"><span class="toc-section-number">13</span> References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="meta" class="section level1">
<h1>
<span class="header-section-number">9</span> Meta-analysis</h1>
<p>Something something</p>
<div id="random-variation" class="section level2">
<h2>
<span class="header-section-number">9.1</span> Random Variation</h2>
</div>
<div id="mixed-results" class="section level2">
<h2>
<span class="header-section-number">9.2</span> Mixed Results</h2>
<p>Science is a cumulative process, and we should evaluate lines of research, not single studies. Researchers are advised to design studies that will provide informative data, but sometimes you need to look at sets of studies before patterns become clear. A commonly used lower limit for statistical power is 80%, which means you will find a non-significant result in one out of five studies, when there is a true effect. Whenever you perform studies where power is not 99.99%, you should expect to find mixed results when examining true effects. Indeed, some researchers have pointed out that <em>not</em> finding mixed results can be very unlikely (or ‘too good to be true’) in a set of studies (Francis, 2014; Schimmack, 2012). We don’t have a very good feeling for what real patterns of studies look like, because we are continuously exposed to a scientific literature that does not reflect reality. Almost all multiple study papers in the scientific literature present only statistically significant results, even though this is unlikely.</p>
<p><strong>Likelihoods of sets of studies</strong></p>
<p>Let’s imagine we have two bags. There are twenty marbles in each bag. In one bag, we know there are 19 blue marbles, and one red marble. The red marble represents a Type 1 error, the blue marbles represent true negatives, and this bag represents a situation where we perform a statistical test where the null-hypothesis is true. In the other bag, there is a number of blue and red marbles. The red marbles represent true positives, blue marbles represent false
negatives, and this bag represents a situation where the alternative hypothesis is true. We don’t know the true power, or the percentage of red marbles, but we can make a guess. For example, we might believe 16 out of 20 (or 80%) of the marbles are red.</p>
<p>We perform 3 studies, by drawing a marble three times (with replacement, so we can draw multiple red balls in a row from either bag) from one of the two bags. We don’t know which of the bags we are drawing from. We could be drawing from the bag where the null hypothesis is true or the bag where the alternative hypothesis is true. There are 4 possible outcomes. Either 0 out of 3, 1 out of 3, 2 out of 3, or 3 out of 3 red balls are drawn. We can plot these four likelihood curves.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:likelihood4curves"></span>
<img src="Statistical_Inferences_files/figure-html/likelihood4curves-1.png" alt="Four likelihood curves for observing 0, 1, 2, or 3 out of 3 significant results in 3 studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.1: Four likelihood curves for observing 0, 1, 2, or 3 out of 3 significant results in 3 studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>Each curve has the maximum likelihood estimate at the outcome: θ = 0 for 0 out
of 3 red balls, θ = 0.33 for 1 out of 3, θ = 0.66 for 2 out of 3, and θ = 1 for
3 out of 3. We know that for the bag where the null hypothesis is true, θ =
0.05, or the Type 1 error rate. If we believe our studies would have 80% power
when the alternative hypothesis is true, we can assume θ = 0.8. In the plot
below, we see the four likelihood curves, and two vertical lines at θ = 0.05 and
θ = 0.8.</p>
<p>We can calculate likelihood ratios for θ = 0.05 vs. θ = 0.80 for the different
outcomes. Below, the likelihood ratios are visualized for 1 out of 3 and 2 out
of 3 red balls, or significant results. We see that only 1 out of 3 findings
(below, left) is slightly more likely when the null hypothesis is true, but the
likelihood ratio of 0.71 is not very far from 1. However, with 2 out of 3
significant results (below, right), it is clear that this result is much more
likely when studies are performed with 80% power than if we assume we observed
two out of three Type 1 errors. Indeed, when two out of three studies are
significant, the likelihood ratio provides pretty strong relative evidence for a
situation where the alternative hypothesis is true, even when the assumed power
is much lower.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:likelihoodcurve1"></span>
<img src="Statistical_Inferences_files/figure-html/likelihoodcurve1-1.png" alt="Likelihood curves for observing 1 out of 3 significant results in 3 studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.2: Likelihood curves for observing 1 out of 3 significant results in 3 studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:likelihoodcurve2"></span>
<img src="Statistical_Inferences_files/figure-html/likelihoodcurve2-1.png" alt="Likelihood curves for observing 2 out of 3 significant results in 3 studies." width="672"><!--
<p class="caption marginnote">-->Figure 9.3: Likelihood curves for observing 2 out of 3 significant results in 3 studies.<!--</p>-->
<!--</div>--></span>
</p>
<p>Although we can’t formally evaluate the probability that the alternative hypothesis is true based on these likelihood ratios (we would need Bayesian statistics instead), we can see that when multiple studies are performed, but not all studies are statistically significant, we are gathering more and more evidence for the hypothesis that a true effect is examined, rather than that all significant studies are Type 1 errors.</p>
<p>The graphs above with the four likelihood curves also shows when a researcher is more likely to observe mixed results than consistent results. This occurs for all values of θ where the likelihood curve for mixed results is higher than the likelihood curves for 0 out of <em>n</em>, or <em>n</em> out of <em>n</em> significant results. More formally, mixed results are more likely than consistent results when power drops below <em>n</em>/(<em>n</em>+1) percent, or increases above 1-(<em>n</em>/(<em>n</em>+1)). For example, when performing three studies, it is more likely to observe mixed results than only significant or only non-significant effects when power is lower than
3/(3+1)=0.75, and higher than 1-(3/(3+1))=0.25.</p>
<div id="section" class="section level6">
<h6>
<span class="header-section-number">9.2.0.0.0.1</span> </h6>
<p>The probability of observing a significant or non-significant result in a study
depends on the Type 1 error rate (α), the statistical power of the test (1-β),
and the probability that the null-hypothesis is true (cf. Ioannidis, 2005;
Wacholder, Chanock, Garcia-Closas, El ghormli, &amp; Rothman, 2004). A study might
examine a <em>true effect</em>, which means the alternative hypothesis (H1) is true
(e.g., a correlation that differs from zero) or it might examine a <em>null
effect</em>, which means the null-hypothesis (H0) is true (e.g., a correlation that
is zero). When performing a statistical test on data, the test result might be
statistically significant at a specified alpha level (<em>p</em> &lt; α) or not. Thus,
there are four possible outcomes of a study:</p>
<ol style="list-style-type: decimal">
<li><p>False positives or Type 1 errors (you observe a significant test result when
H0 is true)</p></li>
<li><p>False negatives or Type 2 errors (you observe a non-significant result when
H1 is true)</p></li>
<li><p>True negatives (a non-significant result when H0 is true)</p></li>
<li><p>True positives (a significant test result when H1 is true)</p></li>
</ol>
<p><img src="media/4caa29c43b43172aa6fc224fd601ee66.png"></p>
<p>To get a feeling for which results you can expect in the long run, we will use
binomial probabilities. As an example of a binomial probability, consider the
probability of observing <em>k</em> heads when flipping a coin <em>n</em> times. The observed
data are generated by a statistical distribution determined by the unknown
parameter θ, which ranges from 0 to 1, and is the true probability of getting
heads (e.g., 0.5 for a fair coin). A logical question in a coin-flipping example
would be to determine the probability of observing <em>k</em> number of heads in <em>n</em>
coin flips, assuming a fair coin (θ = 0.5). The probability of observing <em>k</em>
significant results in <em>n</em> studies is:</p>
<table>
<colgroup>
<col width="3%">
<col width="92%">
<col width="5%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>\frac{n!}{k!\left( n - k \right)!}*\theta^{k}*\left( 1 - \theta \right)^{n - k}</th>
<th>(1)</th>
</tr></thead>
<tbody></tbody>
</table>
<p>The first term indicates the number of possible combinations of results (e.g.,
when two out of three studies are significant, either the first, the second, or
the third study is non-significant, which gives three combinations), which is
multiplied by the probability of observing significant results in each of the
<em>k</em> significant studies, which is then multiplied by the probability of
observing non-significant results in the remaining studies. This is known as the
binomial likelihood function. When H0 is true, the probability of significant
results equals the alpha level, and thus when the alpha level is carefully
controlled (e.g., in pre-registered studies) θ = 0.05. When H1 is true, the
probability of observing a significant result depends on the power, e.g., θ =
0.80 for studies with 80% power.</p>
<p>Open the online shiny app made in R which will perform these binomial likelihood
calculations for you: <a href="http://shiny.ieis.tue.nl/mixed_results_likelihood/" class="uri">http://shiny.ieis.tue.nl/mixed_results_likelihood/</a>. The
app displays binomial likelihoods for sets of studies.</p>
<p>By default, the settings in the app show the results for a situation when 2 out
of 3 studies are significant, a Type 1 error rate of 5% is used, and the power
for the studies is assumed to be 80%. The text below the figure shows that 2 out
of 3 significant results should happen 38% of the time when there is a true
effect, and power is 80%. Scroll down, and take a look at the table. In the left
column, you can see the probabilities of 0, 1, 2, or 3 significant results when
there is no effect (so you only observe Type 1 errors), and in the right columns
you can see these probabilities for when there is a true effect.</p>
<p><strong>Q1:</strong> Which statement is correct when you perform 3 studies?</p>
<ol style="list-style-type: upper-alpha">
<li><p>When H1 is true, alpha = 0.05, and power = 0.80, it is almost as likely to
observe one or more non-significant results (48.8%) as it is to observe only
significant results (51.2%).</p></li>
<li><p>When alpha = 0.05 and power = 0.80, it is extremely rare that you will find 3
significant results (0.0125%), regardless of whether H0 is true or H1 is true.</p></li>
<li><p>When alpha = 0.05 and power = 0.80, 2 out of 3 statistically significant
results is the most likely outcome overall (38.4%) when H1 is true.</p></li>
<li><p>When alpha = 0.05 and power = 0.80, the probability of finding at least one
false positive (a significant result when H0 is true) in three studies is 5%.</p></li>
</ol>
<p><strong>Q2:</strong> Sometimes in lines of three studies, you’ll find a significant effect in
one study, but there is no effect in the other two related studies. Assume the
two related studies were not exactly the same in every way (e.g., you have
changed the manipulation, or the procedure, or some of the questions). It could
be that the two other studies did not work because of minor differences that had
some effect you do not fully understand yet. Or it could be that the single
significant result was a Type 1 error, and H0 was true in all three studies.
Which statement below is correct, assuming a 5% Type 1 error rate and 80% power?</p>
<ol style="list-style-type: upper-alpha">
<li><p>All else being equal, the probability of a Type 1 error in one of three
studies is 5% when there is no true effect in all three studies, and the
probability of finding exactly 1 in three significant effects, assuming 80%
power in all three studies, is 80%, which is substantially more likely.</p></li>
<li><p>All else being equal, the probability of a Type 1 error in one of three
studies is 13.5% when there is no true effect in all three studies, and the
probability of finding exactly 1 in three significant effects, assuming 80%
power in all three studies (and thus a true effect), is 9.6%, which is slightly,
but not substantially less likely.</p></li>
<li><p>All else being equal, the probability of a Type 1 error in one of three
studies is 85.7% when there is no true effect in all three studies, and the
probability of finding exactly 1 in three significant effects, assuming 80%
power in all three studies (and thus a true effect) (and thus a true effect), is
0.8%, which is substantially less likely.</p></li>
<li><p>It is not possible to know the probability you will observe a Type 1 error if
you perform 3 studies.</p></li>
</ol>
<p>The idea that most studies have 80% power is slightly optimistic. <strong>Examine the
correct answer to the previous question across a range of power values</strong> (e.g.,
50% power, and 30% power).</p>
<p><strong>Q3:</strong> Several papers suggest it is a reasonable assumption that the power in
the psychological literature might be around 50%. Set the number of studies to
4, the number of successes also to 4, and the assumed power slider to 50%, and
look at the table at the bottom of the app. How likely is it to observe 4
significant results in 4 studies, assuming there is a true effect?</p>
<ol style="list-style-type: upper-alpha">
<li><p>6.25%</p></li>
<li><p>12.5%</p></li>
<li><p>25%</p></li>
<li><p>37.5%</p></li>
</ol>
<p>Imagine you perform 4 studies, and 3 show a significant result. <strong>Change these
numbers in the online app. Leave the power at 50%</strong>. The output in the text
tells you:</p>
<p><em>When the observed results are equally likely under H0 and H1, the likelihood
ratio is 1. Benchmarks to interpret Likelihood Ratios suggest that when 1&lt;LR&lt;8
there is weak evidence, when 8&lt;LR&lt;32 there is moderate evidence, and when
LR&gt;32, there is strong evidence.</em></p>
<p><em>The data are more likely under the alternative hypothesis than the null
hypothesis with a likelihood ratio of 526.32</em></p>
<p>These calculations show that, assuming you have observed three significant
results out of four studies, and assuming each study had 50% power, it is 526
times more likely to have observed these data when the alternative hypothesis is
true, than when the null hypothesis is true. In other words, it is 526 times
more likely to find a significant effect in three studies when you have 50%
power, than to find three Type 1 errors in a set of four studies.</p>
<p><strong>Q4</strong>: Maybe you don’t think 50% power is a reasonable assumption. How low can
the power be (rounded to 2 digits), for the likelihood to remain higher than 32
in favor of H1 when observing 3 out of 4 significant results?</p>
<ol style="list-style-type: upper-alpha">
<li><p>5% power</p></li>
<li><p>17% power</p></li>
<li><p>34% power</p></li>
<li><p>44% power</p></li>
</ol>
<p>The main take home message of these calculations is to understand that 1) mixed
results are supposed to happen, and 2) mixed results can contain strong evidence
for a true effect, across a wide range of plausible power values. The app also
tells you how much evidence, in a rough dichotomous way, you can expect. This is
useful for our educational goal. But when you want to evaluate results from
multiple studies, the formal way to do so is by performing a meta-analysis.</p>
<p>The above calculations make a very important assumption: The Type 1 error rate
is controlled at 5%. If you try out many different tests in each study, and only
report the result that yielded a p &lt; 0.05, these calculations no longer hold.</p>
<p><strong>Q5</strong>: Go back to the default settings of 2 out of 3 significant results, but
now set the Type 1 error rate to 20%, to reflect a modest amount of p-hacking.
Under these circumstances, what is the <strong>highest</strong> likelihood in favor of H1 you
can get if you explore all possible values for the true power?</p>
<ol style="list-style-type: upper-alpha">
<li><p>Approximately 1</p></li>
<li><p>Approximately 4.63</p></li>
<li><p>Approximately 6.70</p></li>
<li><p>Approximately 62.37</p></li>
</ol>
<p>As the scenario above shows, <em>p</em>-hacking makes studies extremely uninformative.
<strong>If you inflate the error rate, you quickly destroy the evidence in the data.</strong>
You can no longer determine whether the data is more likely when there is no
effect, than when there is an effect. Sometimes researchers complain that people
who worry about <em>p</em>-hacking and try to promote better Type 1 error control are
missing the point, and that other things (better measurement, better theory,
etc.) are more important. I fully agree that these aspects of scientific
research are at least as important as better error control. But better measures
and theories will require decades of work. Better error control can be
accomplished today, if researchers would stop inflating their error rates by
flexibly analyzing their data. And as this assignment shows, inflated rates of
false positives very quickly make it difficult to learn what is true from the
data we collect. Because of the relative ease with which this part of scientific
research can be improved, and because we can achieve this today (and not in a
decade) I think it is worth stressing the importance of error control, and
publish more realistic looking sets of studies.</p>
<p><strong>Q6</strong>: Some ‘prestigious’ journals (which, when examined in terms of scientific
quality such as reproducibility, reporting standards, and policies concerning
data and material sharing, are quite low quality despite their prestige) only
publish manuscripts with a large number of studies, which should all be
statistically significant. If we assume an average power in psychology of 50%,
only 3.125% of 5 study articles should contain exclusively significant results.
If you pick up a random issue from such a prestigious journal, and see 10
articles, each reporting 5 studies, and all manuscripts have exclusively
significant results, would you trust the reported findings more, or less, than
when all these articles had reported mixed results? Why?</p>
<p><strong>Q7</strong>: Unless you will power all your studies at 99.99% for the rest of your
career (which would be slightly inefficient, but great if you don’t like
insecurity), you will observe mixed results in lines of research. How do you
plan to deal with mixed results in lines of research?</p>
<p>The take-away message of this assignment is that you should expect mixed results
under many circumstances, and that dichotomously ignoring non-significant
results is not wise. A formal meta-analysis is the best way to evaluate sets of
studies. But understanding what realistic patterns of results in research lines
should look like is hopefully a first step in making you realize you should
think meta-analytically.</p>
</div>
</div>
<div id="introduction-to-meta-analysis" class="section level2">
<h2>
<span class="header-section-number">9.3</span> Introduction to Meta-Analysis</h2>
<p>Every single study is just a data-point in a future meta-analysis. If you draw small samples from a population, the mean and standard deviation in the sample can differ considerably from the mean and standard deviation in the population. There is great variability in small samples. Parameter estimates from small samples are very imprecise, and therefore the 95% confidence intervals around effect sizes are very wide. Indeed, this led Cohen (1994) to write “I suspect that the main reason [confidence intervals] are not reported is that they are so
embarrassingly large!” If we want a more precise estimate of our parameter of interest, such as the mean difference or correlation in the population, we need either run extremely large single studies, or alternatively, combine data from several studies by performing a <strong>meta-analysis</strong>. The most common approach to combine studies is to perform a meta-analysis of effect size estimates.</p>
<p>You can perform a meta-analysis for a set of studies in a single article you plan to publish (often called an <strong>internal meta-analysis</strong>), or you can search the literature for multiple studies reported in as many different articles as possible, and perform a meta-analysis on all studies others have published. An excellent introduction to meta-analyses is provided in the book by Borenstein, Hedges, Higgins, and Rothstein <span class="citation">(Borenstein, <label for="tufte-mn-21" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-21" class="margin-toggle">2009<span class="marginnote">Borenstein, M. (Ed.). (2009). <em>Introduction to meta-analysis</em>. John Wiley &amp; Sons.</span>)</span>. There is commercial software you can use to perform meta-analyses, but I highly recommend <em>against</em> using such software. Almost all commercial software packages lack transparency, and do not allow you to share your analysis code and data with other researchers. In this assignment, we will be using R to perform a meta-analysis of effect sizes, using the <strong>metafor</strong> package by Viechtbauer <span class="citation">Viechtbauer (<label for="tufte-mn-22" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-22" class="margin-toggle">2010<span class="marginnote">Viechtbauer, W. (2010). Conducting meta-analyses in R with the metafor package. <em>J Stat Softw</em>, <em>36</em>(3), 1–48.</span>)</span>. An important benefit of using metafor is that your meta-analysis can be made completely reproducible.</p>
<div id="single-study-meta-analysis" class="section level3">
<h3>
<span class="header-section-number">9.3.1</span> Single study meta-analysis</h3>
<p>Let’s first begin with something you will hardly ever do in real life: a meta-analysis of a single study. This is a little silly, because a simple <em>t</em>-test or correlation will tell you the same thing – but it is educational to compare a <em>t</em>-test with a meta-analysis of a single
study, before we look at how to combine multiple studies into a meta-analysis.</p>
<p>A difference between an independent <em>t</em>-test and a meta-analysis is that a <em>t</em>-test is performed on the raw data, while a meta-analysis is performed on the effect size(s) of individual studies. The metafor R package contains a very useful function called <code>escalc</code> that can be used to calculate effect sizes, their variances, and confidence intervals around effect size estimates. So let’s start by calculating the effect size to enter into our meta-analysis. The code below (and in the R file under <strong>Part 1</strong>) can be used to calculate the <strong>standardized mean difference</strong> (SMD) from two independent groups from <strong>means</strong> (specified by m1i and m2i), <strong>standard deviations</strong> (sd1i and sd2i), and the number of observations in each group (n1i and n2i). By default, metafor calculates the effect size ‘<strong>Hedges’ g</strong>’ which is the unbiased version of Cohen’s d (see the section on <a href="effectsizesCI.html#cohend">Cohen’s d</a> in the chapter on Effect Sizes).</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="meta.html#cb83-1"></a><span class="kw">library</span>(metafor)</span>
<span id="cb83-2"><a href="meta.html#cb83-2"></a><span class="co"># We calculate the standardized mean difference</span></span>
<span id="cb83-3"><a href="meta.html#cb83-3"></a><span class="co"># We store it as the variable g (because by default, Hedges' g is computed)</span></span>
<span id="cb83-4"><a href="meta.html#cb83-4"></a>g &lt;-<span class="st"> </span><span class="kw">escalc</span>(<span class="dt">measure =</span> <span class="st">"SMD"</span>,</span>
<span id="cb83-5"><a href="meta.html#cb83-5"></a>            <span class="dt">n1i =</span> <span class="dv">50</span>, <span class="co"># sample size in group 1 is 50 </span></span>
<span id="cb83-6"><a href="meta.html#cb83-6"></a>            <span class="dt">m1i =</span> <span class="fl">5.6</span>, <span class="co"># observed mean in group 1 is 5.6</span></span>
<span id="cb83-7"><a href="meta.html#cb83-7"></a>            <span class="dt">sd1i =</span> <span class="fl">1.2</span>, <span class="co"># observed standard deviation in group 1 is 1.2</span></span>
<span id="cb83-8"><a href="meta.html#cb83-8"></a>            <span class="dt">n2i =</span> <span class="dv">50</span>, <span class="co"># sample size in group 2 is 50 </span></span>
<span id="cb83-9"><a href="meta.html#cb83-9"></a>            <span class="dt">m2i =</span> <span class="fl">4.9</span>, <span class="co"># observed mean in group 1 is 4.9 </span></span>
<span id="cb83-10"><a href="meta.html#cb83-10"></a>            <span class="dt">sd2i =</span> <span class="fl">1.3</span>) <span class="co"># observed standard deviation in group 2 is 1.3</span></span>
<span id="cb83-11"><a href="meta.html#cb83-11"></a></span>
<span id="cb83-12"><a href="meta.html#cb83-12"></a><span class="co"># print results</span></span>
<span id="cb83-13"><a href="meta.html#cb83-13"></a>g</span></code></pre></div>
<pre><code>##       yi     vi 
## 1 0.5553 0.0415</code></pre>
<p>The output gives you Hedge’s g (under the <code>yi</code> column, which always returns the
effect size, in this case the standardized mean difference) and the variance of
the effect size estimate (under <code>vi</code>).</p>
<p>As explained in Borenstein, Hedges, Higgins, and Rothstein (2009, formula 4.18
to 4.24) the standardized mean difference Hedges’ g is calculated by dividing
the difference between means by the pooled standard deviation, multiplied by a
correction factor, J:</p>
<p><span class="math display">\[
J = (1 - \ \ 3/(4df - 1))
\]</span></p>
<p><span class="math display">\[
g = J \times \ \left( \frac{{\overline{X}}_{1} - {\overline{X}}_{2}}{S_{\text{within}}} \right)
\]</span></p>
<p>and a very good approximation of the variance of the standardized mean
difference (SMD) Hedges’ g is provided by:</p>
<p><span class="math display">\[
Vg = J^{2} \times \left( \frac{n_{1} + n_{2}}{n_{1}n_{2}} + \frac{g^{2}}{2(n_{1} + n_{2})} \right)
\]</span></p>
<p>The variance of the standardized mean difference depends only on the sample size (n1 and n2) and the value of the standardized mean difference itself. <strong>To perform the required calculations for a meta-analysis, you need the effect sizes and their variance</strong>. This means that if you have coded the effect sizes and the sample sizes (per group) from studies in the literature, you have the information you need to perform a meta-analysis.</p>
<p>You do not need to manually calculate the effect size and its variance using the two formula above – the escalc function does this for you. We can now easily perform a single study meta-analysis using the rma function in the metafor package:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="meta.html#cb85-1"></a><span class="co"># Perform the meta-analysis</span></span>
<span id="cb85-2"><a href="meta.html#cb85-2"></a>meta_res &lt;-<span class="st"> </span><span class="kw">rma</span>(yi, vi, <span class="dt">data =</span> g)</span>
<span id="cb85-3"><a href="meta.html#cb85-3"></a>meta_res</span></code></pre></div>
<pre><code>## 
## Fixed-Effects Model (k = 1)
## 
## I^2 (total heterogeneity / total variability):   0.00%
## H^2 (total variability / sampling variability):  1.00
## 
## Test for Heterogeneity:
## Q(df = 0) = 0.0000, p-val = 1.0000
## 
## Model Results:
## 
## estimate      se    zval    pval   ci.lb   ci.ub 
##   0.5553  0.2038  2.7243  0.0064  0.1558  0.9547  ** 
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Here, we see under Model Results the effect size Hedges’ g (0.5553) and the standard error (0.2038), the Z-test statistic testing the mean difference against the null-hypothesis (2.72), and the 95% confidence interval [ci.lb = 0.16; ci.ub = 0.95] around the effect size (the interval width can be specified using the ‘level =’ option). We also get the <em>p</em>-value for the test of the meta-analytic effect size against 0. In this case we can reject the null-hypothesis (<em>p</em> = 0.0064).</p>
<p>In a meta-analysis, a Z-test is used to examine whether the null-hypothesis can be rejected. This assumes a normally distributed random effect size model. Normally, you would analyze data from a single study with two groups using a <em>t</em>-test, which not surprisingly uses a <em>t</em>-distribution. If we directly compare a single-study meta-analysis, based on a Z-test, with a normal <em>t</em>-test, we will see some tiny differences in the results. We can directly calculate the effect size Hedges’ g, and the 95% confidence interval around the effect size, and the <em>t</em>-test using MOTE <span class="citation">(Buchanan et al., <label for="tufte-mn-23" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-23" class="margin-toggle">2017<span class="marginnote">Buchanan, E. M., Scofield, J., &amp; Valentine, K. D. (2017). <em>MOTE: Effect Size and Confidence Interval Calculator.</em></span>)</span>. The MOTE package uses the <em>t</em>-distribution when calculating confidence intervals around the effect size (and we can see this makes only a tiny difference compared to using the Z-distribution in a meta-analysis with 50 observations in each group).</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="meta.html#cb87-1"></a><span class="co"># Calculate Hedges g and perform t-test with MOTE </span></span>
<span id="cb87-2"><a href="meta.html#cb87-2"></a>MOTE_res &lt;-<span class="st"> </span>MOTE<span class="op">::</span><span class="kw">g.ind.t</span>(<span class="dt">m1 =</span> <span class="fl">5.6</span>, </span>
<span id="cb87-3"><a href="meta.html#cb87-3"></a>                          <span class="dt">m2 =</span> <span class="fl">4.9</span>, </span>
<span id="cb87-4"><a href="meta.html#cb87-4"></a>                          <span class="dt">sd1 =</span> <span class="fl">1.2</span>, </span>
<span id="cb87-5"><a href="meta.html#cb87-5"></a>                          <span class="dt">sd2 =</span> <span class="fl">1.3</span>, </span>
<span id="cb87-6"><a href="meta.html#cb87-6"></a>                          <span class="dt">n1 =</span> <span class="dv">50</span>, </span>
<span id="cb87-7"><a href="meta.html#cb87-7"></a>                          <span class="dt">n2 =</span> <span class="dv">53</span>, </span>
<span id="cb87-8"><a href="meta.html#cb87-8"></a>                          <span class="dt">a =</span> <span class="fl">0.05</span>)</span>
<span id="cb87-9"><a href="meta.html#cb87-9"></a>MOTE_res<span class="op">$</span>statistic</span></code></pre></div>
<pre><code>## [1] "$t$(101) = 2.83, $p$ = 0.00553819625499491"</code></pre>
<p>The <em>t</em>-value is 2.83, and the <em>p</em>-value is 0.0055. With large enough sample sizes (which is commonly true in a meta-analysis) the difference between a Z-test and <em>t</em>-test is not really meaningful, and for this reason the Z-test is used in meta-analyses.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="meta.html#cb89-1"></a><span class="co"># Calculate Hedges g with MOTE </span></span>
<span id="cb89-2"><a href="meta.html#cb89-2"></a>MOTE_res<span class="op">$</span>estimate</span></code></pre></div>
<pre><code>## [1] "$d_{g}$ = 0.55, 95\\% CI [0.16, 0.94]"</code></pre>
<p>The results are very similar to those from the meta-analysis, with g = 0.55, 95% CI[0.16;0.94], where the effect size and the upper bound for the confidence interval differ 0.01 after rounding, because the <em>t</em>-distribution is used instead of the Z-distribution.</p>
<p>It is common to visualize the results of a meta-analysis using a forest plot, which is presented in below. We see the effect size for Study 1 marked by the black square at 0.05, and the confidence interval is visualized by lines extending to –0.34 on the left and 0.44 on the right. The numbers are printed on the right-hand side of the forest plot. On the lower half of the forest plot, we see a stretched-out diamond. The diamond summarizes the meta-analytic effect size estimate, with the center being at the meta-analytic effect size estimate, and the left and right endpoints at the 95% confidence interval of the meta-analytic effect size estimate. Because we only have a single study, the meta-analytic effect size estimate is the same as the effect size estimate for our single study.</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:metaforest"></span>
<img src="Statistical_Inferences_files/figure-html/metaforest-1.png" alt="Forest plot for a single study." width="672"><!--
<p class="caption marginnote">-->Figure 9.4: Forest plot for a single study.<!--</p>-->
<!--</div>--></span>
</p>
<p>Meta-analyses get a bit more exciting when we are using them to analyze results
from multiple studies. When multiple studies are combined in a meta-analysis,
effect size estimates are not simply averaged, but they are <strong>weighted</strong> by the
<strong>precision</strong> of the effect size estimate, which is determined by the sample
size of the study. Thus, the larger the sample size of an individual study, the
more weight it gets in the meta-analysis, meaning that it has more influence on
the meta-analytic effect size estimate.</p>
</div>
<div id="simulating-meta-analyses-of-mean-standardized-differences" class="section level3">
<h3>
<span class="header-section-number">9.3.2</span> Simulating meta-analyses of mean standardized differences</h3>
<p><strong>Open the file simulating_meta_analyses_smd.R</strong>. In this file we again simulate
data for two groups, one with a mean of 100, and one with a mean of 106, both
groups with a standard deviation of 15 (lines 7 to 10). To perform a
meta-analysis, we need to calculate the effect size for each study, and the
variance of the effect size. An empty dataframe with the column names yi and vi
is created in line 11. We then simulate studies (the number of simulated studies
is 12, which you can change in line 5).</p>
<p>Both groups of participants have the same size in the simulation. To simulate
studies with some variation in the sample sizes, the sample size in each group
(n) is determined by randomly drawing a value between 30 and 80 (line 14). If in
your field sample sizes are much larger of smaller, feel free to change these
numbers to something more realistic in your field. Two normally distributed
samples are simulated (lines 15 and 16), and the escalc function is used to
calculate and store the effect size (yi) and variance (vi) for each simulated
study in a dataframe called metadata. We can then perform the meta-analysis,
print the results, and plot the forest plot (lines 21 to 23).</p>
<p>Run all lines of code. Note that we are simulating studies, without setting a
seed – so your results will differ from the results described below. but should
be somewhat similar.</p>
<p>Fixed-Effects Model (k = 12)</p>
<p>Test for Heterogeneity:</p>
<p>Q(df = 11) = 7.2803, p-val = 0.7759</p>
<p>Model Results:</p>
<p>estimate se zval pval ci.lb ci.ub</p>
<p>0.4044 0.0551 7.3383 &lt;.0001 0.2964 0.5124 ***</p>
<p>-–</p>
<p>Signif. codes: 0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</p>
<p>We see a test for <strong>heterogeneity</strong>. We will return to heterogeneity tests
later. We see the model results, which in this specific simulation yielded a
meta-analytic effect size estimate of 0.40 (your result could be smaller or
larger, but should be close – feel free to run all lines of code multiple times
to explore the amount of variation you can expect). The confidence interval
around the effect size estimate [0.30; 0.51] is much narrower than we saw before
for a single study. This is because the 12 studies we simulated together have
quite a large sample size, and the larger the sample size, the smaller the
standard error, and thus the narrower the confidence interval is. The
meta-analytic effect size estimate is statistically different from 0 (<em>p</em> &lt;
0.0001) so we can reject the null hypothesis if we use an alpha level of 0.05.
The forest plot provides a more detailed overview of the individual studies.</p>
<p><img src="media/db00e43009f9bef59a86490e6da2837b.png"></p>
<p>We see 12 rows, one for each study, each with their own effect size and
confidence interval. If you look closely, you can see the squares that indicate
the effect size estimate for each study differ in size. The larger the sample
size, the bigger the square. Study 4 had a relatively small sample size, which
can be seen both by the small square, and the relatively wide confidence
interval. Study 1 had a larger sample size, and thus a slightly larger square
and narrower confidence interval. At the bottom of the graph we find the
meta-analytic effect size and its confidence interval, both visualized by a
diamond and numerically. The model is referred to as a FE Model, or <strong>Fixed
Effect (FE) model</strong>. The alternative approach is a RE Model, or <strong>Random Effects
(RE) model</strong>.</p>
</div>
<div id="fixed-effect-vs-random-effects" class="section level3">
<h3>
<span class="header-section-number">9.3.3</span> Fixed Effect vs Random Effects</h3>
<p>There are two possible models when performing a meta-analysis. One model, known
as a fixed effect model, assumes there is one effect size that generates the
data in all studies in the meta-analysis. This model assumes there is no
variation between individual studies – all have exactly the same true effect
size. The perfect example of this is the simulations we have done so far. We
specified a single true effect in the population, and generated random samples
from this population effect.</p>
<p>Alternatively, one can use a model where the true effect differs in some way in
each individual study. We don’t have a single true effect in the population, but
a range of <strong>randomly distributed</strong> true effect sizes (hence the ‘random
effects’ model). Studies differs in some way from each other (or some sets of
studies differ from other sets), and their true effect sizes differ as well.
Note the difference between a fixed effect model, and a random effect<strong>s</strong>
model, in that the plural ‘effects’ is used only in the latter. Borenstein et al
(2009) state there are two reasons to use a fixed effect model: When all studies
are functionally equivalent, and when your goal is <em>not</em> to generalize to other
populations. This makes the random effects model generally the better choice,
although some people have raised the concern that random-effects models give
more weight to smaller studies, which can be more biased. By default, metafor
will use a random effects model. We used the method=“FE” command to explicitly
ask for a fixed effect model. In the meta-analyses we will simulate in the rest
of this assignment we will leave out this command and simulate random effects
meta-analyses.</p>
<p><strong>Q1</strong>: Run the code 20 times. Compare the effect size estimate for Study 1 (the
first simulated study in the meta-analysis) with the meta-analytic effect size
estimate. Which statement is true?</p>
<ol style="list-style-type: upper-alpha">
<li><p>The effect size estimate for Study 1 is <strong>less</strong> variable, and <strong>less</strong> often
statistically significant, than the meta-analytic effect size estimate.</p></li>
<li><p>The effect size estimate for Study 1 is <strong>less</strong> variable, and <strong>more</strong> often
statistically significant, than the meta-analytic effect size estimate.</p></li>
<li><p>The effect size estimate for Study 1 is <strong>more</strong> variable, and <strong>less</strong> often
statistically significant, than the meta-analytic effect size estimate.</p></li>
<li><p>The effect size estimate for Study 1 is <strong>more</strong> variable, and <strong>more</strong> often
statistically significant, than the meta-analytic effect size estimate.</p></li>
</ol>
</div>
<div id="simulating-meta-analyses-for-dichotomous-outcomes" class="section level3">
<h3>
<span class="header-section-number">9.3.4</span> Simulating meta-analyses for dichotomous outcomes</h3>
<p>Although meta-analyses on mean differences are very common, a meta-analysis can
be performed on many different effect sizes. To show a slightly less common
example, let’s simulate a meta-analysis based on odds ratios. Sometimes the main
outcome in an experiment is a dichotomous variable, such as the success or
failure on a task. In such study designs we can calculate risk ratios, odds
ratios, or risk differences as the effect size measure. Risk differences are
sometimes judged easiest to interpret, but odds ratios are most often used for a
meta-analysis because they have attractive statistical properties. An <strong>odds
ratio</strong> is a ratio of two odds. To illustrate how an odds ratio is calculated,
it is useful to consider the four possible outcomes in a 2 x 2 table of
outcomes:</p>
<table>
<thead><tr class="header">
<th></th>
<th>Success</th>
<th>Failure</th>
<th>N</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Experimental</td>
<td><em>A</em></td>
<td><em>B</em></td>
<td><em>n1</em></td>
</tr>
<tr class="even">
<td>Control</td>
<td><em>C</em></td>
<td><em>D</em></td>
<td><em>n2</em></td>
</tr>
</tbody>
</table>
<p>The odds ratio is calculated as: <span class="math display">\[OR = \ \frac{\text{AD}}{\text{BC}}\]</span>.</p>
<p>The meta-analysis is performed on log transformed odds ratios (because log
transformed odds ratios are symmetric around 1, see Borenstein et al., 2009),
and thus the log of the odds ratio is used, which has a variance which is
approximated by: <span class="math display">\[\text{Var}\left( \log\text{OR} \right) = \ \frac{1}{A} +
\frac{1}{B} + \frac{1}{C} + \frac{1}{D}\]</span>.</p>
<p>Let’s assume that we train students in using a spaced learning strategy (they
work through a textbook every week instead of cramming the week before the
exam). Without such training, 70 out of 100 students succeed in passing the
course after the first exam, but with this training, 80 out of 100 students
pass.</p>
<table>
<thead><tr class="header">
<th></th>
<th>Success</th>
<th>Failure</th>
<th>N</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Experimental</td>
<td>80</td>
<td>20</td>
<td>100</td>
</tr>
<tr class="even">
<td>Control</td>
<td>70</td>
<td>30</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>The odds of passing in the experimental group is 80/20, or 4, while odds in the
control condition are 70/30, or 2.333. The ratio of these two odds is then:
4/2.333 = 1.714, or:</p>
<p><span class="math display">\[
OR = \ \frac{80 \times 30}{20\  \times 70} = 1.714
\]</span></p>
<p><strong>Open the file simulating_meta_analyses_or.R</strong>. This script simulates studies
with dichotomous outcomes, where you can set the percentage of successes and
failures in the experimental and control condition (lines 7 and 8). In the
script, by default the percentage of success in the experimental condition is
70%, and in the control condition it is 50%. Run the script.</p>
<p><img src="media/369d29b2433a0f1c9925100d79fc851e.png"></p>
<p>The forest plot presents the studies and four columns of data after the study
label, which contain the number of successes and failures in the experimental
groups (E+ and E-), and the number of successes and failures in the control
group (C+ and C-). Imagine we study the percentage of people who get a job
within 6 months after a job training program, compared to a control condition.
In Study 1, which had 34 participants in each condition, 23 people in the job
training condition got a job within 6 months, and 11 did not get a job. In the
control condition, 14 people got a job, but 20 did not. The effect size estimate
for the random effects model is 0.88. Feel free to adjust the number of studies,
or the sample sizes in each study, to examine the effect it has on the
meta-analytic effect size estimate (in general, the more data, the more accurate
the estimate).</p>
</div>
<div id="heterogeneity" class="section level3">
<h3>
<span class="header-section-number">9.3.5</span> Heterogeneity</h3>
<p>Although researchers often primarily use meta-analysis to compute a
meta-analytic effect size estimate, and test whether this effect is
statistically different from zero, <strong>an arguably much more important use of
meta-analyses is to explain variation between (sets of) studies</strong>. This
variation among (sets of) studies is referred to as <strong>heterogeneity</strong>. Tests
have been developed to examine whether the studies included in a meta-analysis
vary more than would be expected if the underlying true effect size in all
studies was the same, and measures have been developed to quantify this
variation.</p>
<p>If all studies have the same true population effect size, the only source of
variation is random error. If there are real differences between (sets of)
studies, there are two sources of variation, namely random variation from study
to study, <em>and</em> real differences in effect sizes in (sets of) studies.</p>
<p>A classical measure of heterogeneity is Cochran’s Q statistic, which is the
weighted sum of the squared differences between effect size estimates in each
study, and the meta-analytic effect size estimate. The Q statistic can be used
to test whether the absence of heterogeneity can be statistically rejected (by
comparing it to the expected amount of variation, which is the degrees of
freedom, <em>df</em>, or the number of studies -1, see Borenstein et al., 2009), but it
can have low power if the number of studies in the meta-analysis is small
(Huedo-Medina, Sánchez-Meca, Marín-Martínez, &amp; Botella, 2006).</p>
<p>On theoretical grounds one might argue that some heterogeneity will always
happen in a meta-analysis, and therefore it is more interesting to quantify the
extent to which there is heterogeneity. The I² index measures the extent of true
heterogeneity. It is calculated as follows: <span class="math display">\[I^{2} = \ \frac{(Q - k - 1)}{Q}
\times 100\%\]</span>, where the k is the number of studies (and k-1 is the degrees of
freedom). I² ranges from 0 to 100 and can be interpreted as the percentage of
the total variability in a set of effect sizes that is due to heterogeneity.
When I² = 0 all variability in the effect size estimates can be explained by
within-study error, and when I² = 50 half of the total variability can be
explained by true heterogeneity. I² values of 25%, 50%, and 75% can be
interpreted as low, medium, and high heterogeneity.</p>
<p><strong>Open the file heterogeneity.R</strong>. This script simulates a similar meta-analysis
to the example for dichotomous outcomes above, but with a small variation. The
first half of the simulated experiments are based on the population success
rates specified in lines 7 and 8, but the second half of the simulated
experiments are based on the population success rates specified in lines 25 and
26. Thus, in this set of studies the odds ratio differs for the first half of
the studies, compared to the second half (successes in Group 1 and 2 are set to
0.2 and 0.7 for the first half, but to 0.7 and 0.9 in the second half). There is
true heterogeneity. In line 46 we use the ‘confint’ function in the metafor
package to report both the I² statistic, and its confidence interval.</p>
<p>Run the script 20 times, each time noting the I² statistic and the 95%
confidence interval around it. You will see widely varying estimates for I².
Because we are simulating only 12 studies, estimates of heterogeneity have large
variability. Increase the number of simulated experiments in line 5 from 12 to
200.</p>
<p><strong>Q2</strong>: Re-run the simulation 20 times. Compare the I² value and its 95% CI when
simulating meta-analyses of 12 and 200 studies. Which statement is true?</p>
<ol style="list-style-type: upper-alpha">
<li><p>The I² values are <strong>more</strong> variable when simulating 200 studies, and the 95%
CI is <strong>wider</strong>.</p></li>
<li><p>The I² values are <strong>more</strong> variable when simulating 200 studies, and the 95%
CI is <strong>narrower</strong>.</p></li>
<li><p>The I² values are <strong>less</strong> variable when simulating 200 studies, and the 95%
CI is <strong>wider</strong>.</p></li>
<li><p>The I² values are <strong>less</strong> variable when simulating 200 studies, and the 95%
CI is <strong>narrower</strong>.</p></li>
</ol>
<p>In this assignment, you’ve learned the basics of combining studies in a
meta-analysis.</p>
</div>
<div id="improving-the-reproducibility-of-meta-analyses" class="section level3">
<h3>
<span class="header-section-number">9.3.6</span> Improving the reproducibility of meta-analyses</h3>
<p>Although meta-analyses do not provide definitive conclusions, they are typically interpreted as state-of-the-art empirical knowledge about a specific effect or research area. Large-scale meta-analyses often accumulate a massive number of citations and influence future research and theory development. It is therefore essential that published meta-analyses are of the highest possible quality.</p>
<p>At the same time, the conclusions from meta-analyses are often open for debate and are subject to change as new data becomes available. We recently proposed practical recommendations to increase the reproducibility of meta-analyses to facilitate quality control, improve reporting guidelines, allow researchers to re-analyze meta-analyses based on alternative inclusion criteria, and future-proof meta-analyses by making sure the collected meta-analytic data is shared so that continuously cumulating meta-analyses can be performed, and so that novel statistical techniques can be applied on the collected data as they become available <span class="citation">(Lakens et al., <label for="tufte-mn-24" class="margin-toggle">⊕</label><input type="checkbox" id="tufte-mn-24" class="margin-toggle">2016<span class="marginnote">Lakens, D., Hilgard, J., &amp; Staaks, J. (2016). On the reproducibility of meta-analyses: Six practical recommendations. <em>BMC Psychology</em>, <em>4</em>, 24. <a href="https://doi.org/10.1186/s40359-016-0126-3">https://doi.org/10.1186/s40359-016-0126-3</a></span>)</span>. These recommendations are summarized in Table @ref(tab:table_rec).</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="meta.html#cb91-1"></a>table_rec &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">c</span>(<span class="st">"Facilitate cumulative science"</span>, <span class="st">"Facilitate quality control"</span>, <span class="st">"Use reporting guidelines"</span>, <span class="st">"Preregister"</span>, <span class="st">"Facilitate reproducibility"</span>, <span class="st">"Recruit expertise"</span>), <span class="kw">c</span>(<span class="st">"Disclose all meta-analytic data (effect sizes, sample sizes for each condition, test statistics and degrees of freedom, means, standard deviations, and correlations between dependent observations) for each data point. Quote relevant text from studies that describe the meta-analytic data to prevent confusion, such as when one effect size is selected from a large number of tests reported in a study. When analyzing subgroups, include quotes from the original study that underlie this classification, and specify any subjective decisions."</span>, <span class="st">"Specify which effect size calculations are used and which assumptions are made for missing data (e.g., assuming equal sample sizes in each condition, imputed values for unreported effect sizes), if necessary for each effect size extracted from the literature. Specify who extracted and coded the data, knowing it is preferable that two researchers independently extract effect sizes from the literature."</span>, <span class="st">"A minimal requirement when reporting meta-analyses is to adhere to one of the reporting standards (e.g., PRISMA). The reporting guidelines ask authors of meta-analyses to report essential information that should be made available either in the main text of the article, or by providing a completed checklist as supplementary material during review and after publication."</span>, <span class="st">"Whenever possible, pre-register the meta-analysis research protocol to distinguish between confirmatory and exploratory analyses. Perform a prospective meta-analysis where possible."</span>, <span class="st">"Allow others to re-analyze the data to examine how sensitive the results are to subjective choices such as inclusion criteria. Always include a link to data files that can be directly analyzed with statistical software, either by providing completely reproducible scripts containing both the data and the reported analyses in free software (e.g., R), or at the very minimum a spreadsheet that contains all meta-analytic data that can easily analyzed in any statistical program."</span>, <span class="st">"Consider consulting a librarian before you start the literature search, and a statistician before coding the effect sizes, for advice on how make the literature search and effect size calculations reproducible."</span>))</span>
<span id="cb91-2"><a href="meta.html#cb91-2"></a><span class="kw">colnames</span>(table_rec) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">"What?"</span>, <span class="st">"How?"</span>)</span>
<span id="cb91-3"><a href="meta.html#cb91-3"></a></span>
<span id="cb91-4"><a href="meta.html#cb91-4"></a>knitr<span class="op">::</span><span class="kw">kable</span>(table_rec, <span class="dt">caption =</span> <span class="st">"Six practical recommendations to improve the quality and reproducibility of meta-analyses."</span>)</span></code></pre></div>
<p><!--
<caption>--><span class="marginnote shownote">(#tab:table_rec)Six practical recommendations to improve the quality and reproducibility of meta-analyses.</span><!--</caption>--></p>
<table>
<thead><tr>
<th style="text-align:left;">
What?
</th>
<th style="text-align:left;">
How?
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Facilitate cumulative science
</td>
<td style="text-align:left;">
Disclose all meta-analytic data (effect sizes, sample sizes for each condition, test statistics and degrees of freedom, means, standard deviations, and correlations between dependent observations) for each data point. Quote relevant text from studies that describe the meta-analytic data to prevent confusion, such as when one effect size is selected from a large number of tests reported in a study. When analyzing subgroups, include quotes from the original study that underlie this classification, and specify any subjective decisions.
</td>
</tr>
<tr>
<td style="text-align:left;">
Facilitate quality control
</td>
<td style="text-align:left;">
Specify which effect size calculations are used and which assumptions are made for missing data (e.g., assuming equal sample sizes in each condition, imputed values for unreported effect sizes), if necessary for each effect size extracted from the literature. Specify who extracted and coded the data, knowing it is preferable that two researchers independently extract effect sizes from the literature.
</td>
</tr>
<tr>
<td style="text-align:left;">
Use reporting guidelines
</td>
<td style="text-align:left;">
A minimal requirement when reporting meta-analyses is to adhere to one of the reporting standards (e.g., PRISMA). The reporting guidelines ask authors of meta-analyses to report essential information that should be made available either in the main text of the article, or by providing a completed checklist as supplementary material during review and after publication.
</td>
</tr>
<tr>
<td style="text-align:left;">
Preregister
</td>
<td style="text-align:left;">
Whenever possible, pre-register the meta-analysis research protocol to distinguish between confirmatory and exploratory analyses. Perform a prospective meta-analysis where possible.
</td>
</tr>
<tr>
<td style="text-align:left;">
Facilitate reproducibility
</td>
<td style="text-align:left;">
Allow others to re-analyze the data to examine how sensitive the results are to subjective choices such as inclusion criteria. Always include a link to data files that can be directly analyzed with statistical software, either by providing completely reproducible scripts containing both the data and the reported analyses in free software (e.g., R), or at the very minimum a spreadsheet that contains all meta-analytic data that can easily analyzed in any statistical program.
</td>
</tr>
<tr>
<td style="text-align:left;">
Recruit expertise
</td>
<td style="text-align:left;">
Consider consulting a librarian before you start the literature search, and a statistician before coding the effect sizes, for advice on how make the literature search and effect size calculations reproducible.
</td>
</tr>
</tbody>
</table>
<p>You can use meta-analyses to combine results in a single paper, or to evaluate
effects in the literature. When combining effects in the literature, one of the
main goals of a meta-analysis is to test or develop theories that can explain
the variability in effect size estimates. Performing meta-analyses is relatively
easy whenever you have access to the effect sizes (or the necessary information
to compute effect sizes) and the sample sizes for each study. By combining
information, you can achieve a much higher precision in effect size estimates.
Excellent introductions to performing and interpreting meta-analyses can be
found in Borenstein et al (2009) and Cummings (2013).</p>
<p>Borenstein, M., Hedges, L. V., Higgins, J., &amp; Rothstein, H. R. (2009).
Introduction to meta-analysis. Chichester, United Kingdom: John Wiley &amp; Sons,
Ltd.</p>
<p>Cumming, G. (2013). Understanding the new statistics: Effect sizes, confidence
intervals, and meta-analysis. New York, NY: Routledge.</p>
<p>Huedo-Medina, T. B., Sánchez-Meca, J., Marín-Martínez, F., &amp; Botella, J. (2006).
Assessing heterogeneity in meta-analysis: Q statistic or I2 index? Psychological
Methods, 11(2), 193.</p>
<p>Kelley, K. (2007). Methods for the behavioral, educational, and social sciences:
An R package. Behavior Research Methods, 39(4), 979–984.</p>
<p>Viechtbauer, W. (2010). Conducting meta-analyses in R with the metafor package.
Journal of Statistical Software, 36(3), 1–48.</p>

</div>
</div>
</div></body></html>

<p style="text-align: center;">
<a href="sesoi.html"><button class="btn btn-default">Previous</button></a>
<a href="bias.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2020-07-21
</p>
</div>
</div>

<div class="row" style="padding-top: 2em;">
<p style="text-align: center">
<img src="images/logo.png" style="width: 100px; padding: 0; display: inline; vertical-align: top">
<span style="display: inline-block; margin-left: 2em; margin-top: 16px; font-size: small">
<span style="font-weight: bold;">Daniel Lakens</span><br/>
<a href="https://statistical-inferences.com">statistical-inferences.com</a><br/>
page built  2020-07-21 22:32:35
</span>
</p>
</div>


</body>
</html>
