<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Sample size justification | Improving Your Statistical Inferences</title>
  <meta name="description" content="Online textbook to Improve Your Statistical Inferences" />
  <meta name="generator" content="bookdown 0.20.1 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Sample size justification | Improving Your Statistical Inferences" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://themethodsection.com/ebook/" />
  <meta property="og:image" content="http://themethodsection.com/ebook/images/cover.jpg" />
  <meta property="og:description" content="Online textbook to Improve Your Statistical Inferences" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Sample size justification | Improving Your Statistical Inferences" />
  
  <meta name="twitter:description" content="Online textbook to Improve Your Statistical Inferences" />
  <meta name="twitter:image" content="http://themethodsection.com/ebook/images/cover.jpg" />

<meta name="author" content="Daniel Lakens" />


<meta name="date" content="2020-08-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="pvalue.html"/>
<link rel="next" href="questions.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Improving Your Statistical Inferences</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="pvalue.html"><a href="pvalue.html"><i class="fa fa-check"></i><b>1</b> What is a <em>p</em>-value</a><ul>
<li class="chapter" data-level="1.1" data-path="pvalue.html"><a href="pvalue.html#what-is-a-p-value"><i class="fa fa-check"></i><b>1.1</b> What is a <em>p</em>-value?</a></li>
<li class="chapter" data-level="1.2" data-path="pvalue.html"><a href="pvalue.html#fisher-vs.-neyman"><i class="fa fa-check"></i><b>1.2</b> Fisher vs. Neyman</a></li>
<li class="chapter" data-level="1.3" data-path="pvalue.html"><a href="pvalue.html#preventing-common-misconceptions-about-p-values"><i class="fa fa-check"></i><b>1.3</b> Preventing common misconceptions about <em>p</em>-values</a><ul>
<li class="chapter" data-level="1.3.1" data-path="pvalue.html"><a href="pvalue.html#misconception1"><i class="fa fa-check"></i><b>1.3.1</b> Misunderstanding 1: A non-significant <em>p</em>-value means that the null hypothesis is true</a></li>
<li class="chapter" data-level="1.3.2" data-path="pvalue.html"><a href="pvalue.html#misunderstanding-2-a-significant-p-value-means-that-the-null-hypothesis-is-false."><i class="fa fa-check"></i><b>1.3.2</b> Misunderstanding 2: A significant <em>p</em>-value means that the null hypothesis is false.</a></li>
<li class="chapter" data-level="1.3.3" data-path="pvalue.html"><a href="pvalue.html#misunderstanding-3-a-significant-p-value-means-that-a-practically-important-effect-has-been-discovered"><i class="fa fa-check"></i><b>1.3.3</b> Misunderstanding 3: A significant <em>p</em>-value means that a practically important effect has been discovered</a></li>
<li class="chapter" data-level="1.3.4" data-path="pvalue.html"><a href="pvalue.html#misunderstanding-4-if-you-have-observed-a-significant-finding-the-probability-that-you-have-made-a-type-1-error-a-false-positive-is-5."><i class="fa fa-check"></i><b>1.3.4</b> Misunderstanding 4: If you have observed a significant finding, the probability that you have made a Type 1 error (a false positive) is 5%.</a></li>
<li class="chapter" data-level="1.3.5" data-path="pvalue.html"><a href="pvalue.html#misunderstanding-5-one-minus-the-p-value-is-the-probability-that-the-effect-will-replicate-when-repeated."><i class="fa fa-check"></i><b>1.3.5</b> Misunderstanding 5: One minus the <em>p</em>-value is the probability that the effect will replicate when repeated.</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="pvalue.html"><a href="pvalue.html#which-p-values-can-you-expect"><i class="fa fa-check"></i><b>1.4</b> Which <em>p</em>-values can you expect?</a><ul>
<li class="chapter" data-level="1.4.1" data-path="pvalue.html"><a href="pvalue.html#lindleys-paradox"><i class="fa fa-check"></i><b>1.4.1</b> Lindley’s paradox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="power.html"><a href="power.html"><i class="fa fa-check"></i><b>2</b> Sample size justification</a><ul>
<li class="chapter" data-level="2.1" data-path="power.html"><a href="power.html#measuring-the-entire-population"><i class="fa fa-check"></i><b>2.1</b> Measuring the Entire Population</a></li>
<li class="chapter" data-level="2.2" data-path="power.html"><a href="power.html#feasibility"><i class="fa fa-check"></i><b>2.2</b> Feasibility</a><ul>
<li class="chapter" data-level="2.2.1" data-path="power.html"><a href="power.html#the-smallest-effect-size-that-can-be-statistically-significant"><i class="fa fa-check"></i><b>2.2.1</b> The smallest effect size that can be statistically significant</a></li>
<li class="chapter" data-level="2.2.2" data-path="power.html"><a href="power.html#compute-the-width-of-the-confidence-interval-around-the-effect-size"><i class="fa fa-check"></i><b>2.2.2</b> Compute the width of the confidence interval around the effect size</a></li>
<li class="chapter" data-level="2.2.3" data-path="power.html"><a href="power.html#sensitivitypower"><i class="fa fa-check"></i><b>2.2.3</b> Plot a sensitivity power analysis</a></li>
<li class="chapter" data-level="2.2.4" data-path="power.html"><a href="power.html#reporting-a-feasibility-justification."><i class="fa fa-check"></i><b>2.2.4</b> Reporting a feasibility justification.</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="power.html"><a href="power.html#a-priori-power-analysis"><i class="fa fa-check"></i><b>2.3</b> A-priori power analysis</a><ul>
<li class="chapter" data-level="2.3.1" data-path="power.html"><a href="power.html#performing-a-power-analysis."><i class="fa fa-check"></i><b>2.3.1</b> Performing a power analysis.</a></li>
<li class="chapter" data-level="2.3.2" data-path="power.html"><a href="power.html#justifyeffectsize"><i class="fa fa-check"></i><b>2.3.2</b> Justifying the effect size used in an a-priori power analysis</a></li>
<li class="chapter" data-level="2.3.3" data-path="power.html"><a href="power.html#justifying-the-error-rates-used-in-an-a-priori-power-analysis"><i class="fa fa-check"></i><b>2.3.3</b> Justifying the error rates used in an a-priori power analysis</a></li>
<li class="chapter" data-level="2.3.4" data-path="power.html"><a href="power.html#some-advice-when-using-gpower"><i class="fa fa-check"></i><b>2.3.4</b> Some advice when using G*Power</a></li>
<li class="chapter" data-level="2.3.5" data-path="power.html"><a href="power.html#powerforabsence"><i class="fa fa-check"></i><b>2.3.5</b> A-priori power analysis for the absence of an effect</a></li>
<li class="chapter" data-level="2.3.6" data-path="power.html"><a href="power.html#reporting-an-a-priori-power-analysis."><i class="fa fa-check"></i><b>2.3.6</b> Reporting an a-priori power analysis.</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="power.html"><a href="power.html#compromisepower"><i class="fa fa-check"></i><b>2.4</b> Compromise power analysis</a><ul>
<li class="chapter" data-level="2.4.1" data-path="power.html"><a href="power.html#reporting-a-compromise-power-analysis"><i class="fa fa-check"></i><b>2.4.1</b> Reporting a compromise power analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="power.html"><a href="power.html#observedpower"><i class="fa fa-check"></i><b>2.5</b> Observed (post-hoc) power analysis</a><ul>
<li class="chapter" data-level="2.5.1" data-path="power.html"><a href="power.html#what-to-do-if-your-editor-asks-for-post-hoc-power"><i class="fa fa-check"></i><b>2.5.1</b> What to do if your editor asks for post-hoc power?</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="power.html"><a href="power.html#designing-efficient-studies"><i class="fa fa-check"></i><b>2.6</b> Designing efficient studies</a><ul>
<li class="chapter" data-level="2.6.1" data-path="power.html"><a href="power.html#use-directional-tests-where-relevant."><i class="fa fa-check"></i><b>2.6.1</b> Use directional tests where relevant.</a></li>
<li class="chapter" data-level="2.6.2" data-path="power.html"><a href="power.html#use-sequential-analysis-whenever-possible"><i class="fa fa-check"></i><b>2.6.2</b> Use sequential analysis whenever possible</a></li>
<li class="chapter" data-level="2.6.3" data-path="power.html"><a href="power.html#increase-your-alpha-level"><i class="fa fa-check"></i><b>2.6.3</b> Increase your alpha level</a></li>
<li class="chapter" data-level="2.6.4" data-path="power.html"><a href="power.html#use-within-designs-where-possible"><i class="fa fa-check"></i><b>2.6.4</b> Use within designs where possible</a></li>
<li class="chapter" data-level="2.6.5" data-path="power.html"><a href="power.html#remove-statistical-variation-where-possible"><i class="fa fa-check"></i><b>2.6.5</b> Remove statistical variation where possible</a></li>
<li class="chapter" data-level="2.6.6" data-path="power.html"><a href="power.html#use-bayesian-statistics-with-informed-priors"><i class="fa fa-check"></i><b>2.6.6</b> Use Bayesian statistics with informed priors</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="power.html"><a href="power.html#what-to-do-if-best-practices-in-study-design-wont-save-you"><i class="fa fa-check"></i><b>2.7</b> What to do if best practices in study design won’t save you?</a><ul>
<li class="chapter" data-level="2.7.1" data-path="power.html"><a href="power.html#ask-for-a-lot-more-money-in-your-grant-proposals"><i class="fa fa-check"></i><b>2.7.1</b> Ask for a lot more money in your grant proposals</a></li>
<li class="chapter" data-level="2.7.2" data-path="power.html"><a href="power.html#improve-management"><i class="fa fa-check"></i><b>2.7.2</b> Improve management</a></li>
<li class="chapter" data-level="2.7.3" data-path="power.html"><a href="power.html#change-what-is-expected-from-phd-students"><i class="fa fa-check"></i><b>2.7.3</b> Change what is expected from PhD students</a></li>
<li class="chapter" data-level="2.7.4" data-path="power.html"><a href="power.html#think-about-the-questions-we-collectively-want-answered-instead-of-the-questions-we-can-individually-answer"><i class="fa fa-check"></i><b>2.7.4</b> Think about the questions we collectively want answered, instead of the questions we can individually answer</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="power.html"><a href="power.html#planning-for-precision"><i class="fa fa-check"></i><b>2.8</b> Planning for precision</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="questions.html"><a href="questions.html"><i class="fa fa-check"></i><b>3</b> Asking Statistical Questions</a><ul>
<li class="chapter" data-level="3.1" data-path="questions.html"><a href="questions.html#do-you-really-want-to-test-a-hypothesis"><i class="fa fa-check"></i><b>3.1</b> Do You Really Want to Test a Hypothesis?</a></li>
<li class="chapter" data-level="3.2" data-path="questions.html"><a href="questions.html#goals-of-tests"><i class="fa fa-check"></i><b>3.2</b> Goals of tests</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="errorcontrol.html"><a href="errorcontrol.html"><i class="fa fa-check"></i><b>4</b> Error Control</a><ul>
<li class="chapter" data-level="4.1" data-path="errorcontrol.html"><a href="errorcontrol.html#why-you-dont-need-to-adjust-your-alpha-level-for-all-tests-youll-do-in-your-lifetime."><i class="fa fa-check"></i><b>4.1</b> Why you don’t need to adjust your alpha level for all tests you’ll do in your lifetime.</a></li>
<li class="chapter" data-level="4.2" data-path="errorcontrol.html"><a href="errorcontrol.html#why-banning-p-values-might-not-solve-our-problems."><i class="fa fa-check"></i><b>4.2</b> Why banning p-values might not solve our problems.</a></li>
<li class="chapter" data-level="4.3" data-path="errorcontrol.html"><a href="errorcontrol.html#error-control-in-exploratory-anovas-the-how-and-the-why"><i class="fa fa-check"></i><b>4.3</b> Error Control in Exploratory ANOVA’s: The How and the Why</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="effectsizesCI.html"><a href="effectsizesCI.html"><i class="fa fa-check"></i><b>5</b> Effect Sizes and Confidence Intervals</a><ul>
<li class="chapter" data-level="5.1" data-path="effectsizesCI.html"><a href="effectsizesCI.html#effect-sizes"><i class="fa fa-check"></i><b>5.1</b> Effect sizes</a><ul>
<li class="chapter" data-level="5.1.1" data-path="effectsizesCI.html"><a href="effectsizesCI.html#the-facebook-experiment"><i class="fa fa-check"></i><b>5.1.1</b> The Facebook experiment</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="effectsizesCI.html"><a href="effectsizesCI.html#cohend"><i class="fa fa-check"></i><b>5.2</b> Cohen’s <em>d</em></a><ul>
<li class="chapter" data-level="5.2.1" data-path="effectsizesCI.html"><a href="effectsizesCI.html#correcting-for-bias"><i class="fa fa-check"></i><b>5.2.1</b> Correcting for Bias</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="effectsizesCI.html"><a href="effectsizesCI.html#r-correlations"><i class="fa fa-check"></i><b>5.3</b> <em>r</em> (correlations)</a></li>
<li class="chapter" data-level="5.4" data-path="effectsizesCI.html"><a href="effectsizesCI.html#confint"><i class="fa fa-check"></i><b>5.4</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="5.4.1" data-path="effectsizesCI.html"><a href="effectsizesCI.html#population-vs.-samples"><i class="fa fa-check"></i><b>5.4.1</b> Population vs. Samples</a></li>
<li class="chapter" data-level="5.4.2" data-path="effectsizesCI.html"><a href="effectsizesCI.html#relatCIp"><i class="fa fa-check"></i><b>5.4.2</b> The relation between confidence intervals and <em>p</em>-values</a></li>
<li class="chapter" data-level="5.4.3" data-path="effectsizesCI.html"><a href="effectsizesCI.html#the-standard-error-and-95-confidence-intervals"><i class="fa fa-check"></i><b>5.4.3</b> The Standard Error and 95% Confidence Intervals</a></li>
<li class="chapter" data-level="5.4.4" data-path="effectsizesCI.html"><a href="effectsizesCI.html#overlapping-confidence-intervals"><i class="fa fa-check"></i><b>5.4.4</b> Overlapping Confidence Intervals</a></li>
<li class="chapter" data-level="5.4.5" data-path="effectsizesCI.html"><a href="effectsizesCI.html#prediction-intervals"><i class="fa fa-check"></i><b>5.4.5</b> Prediction Intervals</a></li>
<li class="chapter" data-level="5.4.6" data-path="effectsizesCI.html"><a href="effectsizesCI.html#capture-percentages"><i class="fa fa-check"></i><b>5.4.6</b> Capture Percentages</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="effectsizesCI.html"><a href="effectsizesCI.html#computing-confidence-intervals-around-effect-sizes"><i class="fa fa-check"></i><b>5.5</b> Computing Confidence Intervals around Effect Sizes</a><ul>
<li class="chapter" data-level="5.5.1" data-path="effectsizesCI.html"><a href="effectsizesCI.html#mote"><i class="fa fa-check"></i><b>5.5.1</b> MOTE</a></li>
<li class="chapter" data-level="5.5.2" data-path="effectsizesCI.html"><a href="effectsizesCI.html#jasp"><i class="fa fa-check"></i><b>5.5.2</b> JASP</a></li>
<li class="chapter" data-level="5.5.3" data-path="effectsizesCI.html"><a href="effectsizesCI.html#esci-software"><i class="fa fa-check"></i><b>5.5.3</b> ESCI software</a></li>
<li class="chapter" data-level="5.5.4" data-path="effectsizesCI.html"><a href="effectsizesCI.html#mbess"><i class="fa fa-check"></i><b>5.5.4</b> MBESS</a></li>
<li class="chapter" data-level="5.5.5" data-path="effectsizesCI.html"><a href="effectsizesCI.html#why-should-you-report-90-ci-for-eta-squared"><i class="fa fa-check"></i><b>5.5.5</b> Why should you report 90% CI for eta-squared?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="equivalencetest.html"><a href="equivalencetest.html"><i class="fa fa-check"></i><b>6</b> Equivalence Testing</a><ul>
<li class="chapter" data-level="6.1" data-path="equivalencetest.html"><a href="equivalencetest.html#absence-of-evidence-is-not-evidence-of-absence."><i class="fa fa-check"></i><b>6.1</b> Absence of evidence is not evidence of absence.</a></li>
<li class="chapter" data-level="6.2" data-path="equivalencetest.html"><a href="equivalencetest.html#justifysesoi"><i class="fa fa-check"></i><b>6.2</b> JUstifying a smallest effect size of interest</a><ul>
<li class="chapter" data-level="6.2.1" data-path="equivalencetest.html"><a href="equivalencetest.html#rejecting-the-presence-of-a-meaningful-effect"><i class="fa fa-check"></i><b>6.2.1</b> Rejecting the presence of a meaningful effect</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="equivalencetest.html"><a href="equivalencetest.html#bayesian-estimation-using-rope-and-equivalence-tests."><i class="fa fa-check"></i>Bayesian estimation using ROPE and equivalence tests.</a><ul>
<li class="chapter" data-level="6.2.2" data-path="equivalencetest.html"><a href="equivalencetest.html#hdi-vs-90-ci"><i class="fa fa-check"></i><b>6.2.2</b> 95% HDI vs 90% CI</a></li>
<li class="chapter" data-level="6.2.3" data-path="equivalencetest.html"><a href="equivalencetest.html#powerequiv"><i class="fa fa-check"></i><b>6.2.3</b> Power analysis for Equivalence Tests</a></li>
<li class="chapter" data-level="6.2.4" data-path="equivalencetest.html"><a href="equivalencetest.html#use-of-prior-information"><i class="fa fa-check"></i><b>6.2.4</b> Use of prior information</a></li>
<li class="chapter" data-level="6.2.5" data-path="equivalencetest.html"><a href="equivalencetest.html#conclusion"><i class="fa fa-check"></i><b>6.2.5</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="severity.html"><a href="severity.html"><i class="fa fa-check"></i><b>7</b> Severe Tests and Risky Predictions</a><ul>
<li class="chapter" data-level="7.1" data-path="severity.html"><a href="severity.html#testing-range-predictions"><i class="fa fa-check"></i><b>7.1</b> Testing Range Predictions</a><ul>
<li class="chapter" data-level="7.1.1" data-path="severity.html"><a href="severity.html#risky-predictions"><i class="fa fa-check"></i><b>7.1.1</b> Risky Predictions</a></li>
<li class="chapter" data-level="7.1.2" data-path="severity.html"><a href="severity.html#systematic-noise"><i class="fa fa-check"></i><b>7.1.2</b> Systematic Noise</a></li>
<li class="chapter" data-level="7.1.3" data-path="severity.html"><a href="severity.html#range-predictions"><i class="fa fa-check"></i><b>7.1.3</b> Range Predictions</a></li>
<li class="chapter" data-level="7.1.4" data-path="severity.html"><a href="severity.html#directional-tests"><i class="fa fa-check"></i><b>7.1.4</b> Directional Tests</a></li>
<li class="chapter" data-level="7.1.5" data-path="severity.html"><a href="severity.html#minimal-effect-tests"><i class="fa fa-check"></i><b>7.1.5</b> Minimal Effect Tests</a></li>
<li class="chapter" data-level="7.1.6" data-path="severity.html"><a href="severity.html#range-predictions-in-practice"><i class="fa fa-check"></i><b>7.1.6</b> Range Predictions in PRactice</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="severity.html"><a href="severity.html#verisimilitude-belief-and-progress-in-psychological-science"><i class="fa fa-check"></i><b>7.2</b> Verisimilitude, Belief, and Progress in Psychological Science</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="sesoi.html"><a href="sesoi.html"><i class="fa fa-check"></i><b>8</b> Smallest Effect Size of Interest</a><ul>
<li class="chapter" data-level="8.1" data-path="sesoi.html"><a href="sesoi.html#what-would-falsify-your-theory"><i class="fa fa-check"></i><b>8.1</b> What would falsify your theory?</a></li>
<li class="chapter" data-level="8.2" data-path="sesoi.html"><a href="sesoi.html#what-would-falsify-your-theory-in-practice"><i class="fa fa-check"></i><b>8.2</b> What would falsify your theory in practice?</a></li>
<li class="chapter" data-level="8.3" data-path="sesoi.html"><a href="sesoi.html#specifying-a-sesoi-based-on-theory-or-costs-and-benefits"><i class="fa fa-check"></i><b>8.3</b> Specifying a SESOI based on theory or costs and benefits</a><ul>
<li class="chapter" data-level="8.3.1" data-path="sesoi.html"><a href="sesoi.html#example-of-a-theoretically-predicted-sesoi"><i class="fa fa-check"></i><b>8.3.1</b> Example of a theoretically predicted SESOI</a></li>
<li class="chapter" data-level="8.3.2" data-path="sesoi.html"><a href="sesoi.html#anchor-based-methods-to-set-a-sesoi"><i class="fa fa-check"></i><b>8.3.2</b> Anchor based methods to set a SESOI</a></li>
<li class="chapter" data-level="8.3.3" data-path="sesoi.html"><a href="sesoi.html#cost-benefit-analysis"><i class="fa fa-check"></i><b>8.3.3</b> Cost benefit analysis</a></li>
<li class="chapter" data-level="8.3.4" data-path="sesoi.html"><a href="sesoi.html#setting-the-sesoi-based-on-effects-feasible-to-study"><i class="fa fa-check"></i><b>8.3.4</b> Setting the SESOI based on effects feasible to study</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sesoi.html"><a href="sesoi.html#smalltelescopes"><i class="fa fa-check"></i><b>8.4</b> The small telescopes approach</a></li>
<li class="chapter" data-level="8.5" data-path="sesoi.html"><a href="sesoi.html#setting-the-sesoi-based-on-resources."><i class="fa fa-check"></i><b>8.5</b> Setting the SESOI based on resources.</a></li>
<li class="chapter" data-level="8.6" data-path="sesoi.html"><a href="sesoi.html#setting-the-smallest-effect-size-of-interest-in-replication-studies"><i class="fa fa-check"></i><b>8.6</b> Setting the smallest effect size of interest in replication studies</a><ul>
<li class="chapter" data-level="8.6.1" data-path="sesoi.html"><a href="sesoi.html#setting-the-sesoi-based-on-theoretical-predictions"><i class="fa fa-check"></i><b>8.6.1</b> Setting the SESOI based on theoretical predictions</a></li>
<li class="chapter" data-level="8.6.2" data-path="sesoi.html"><a href="sesoi.html#setting-the-smallest-effect-size-of-interest-based-on-resources"><i class="fa fa-check"></i><b>8.6.2</b> Setting the smallest effect size of interest based on resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="meta.html"><a href="meta.html"><i class="fa fa-check"></i><b>9</b> Meta-analysis</a><ul>
<li class="chapter" data-level="9.1" data-path="meta.html"><a href="meta.html#random-variation"><i class="fa fa-check"></i><b>9.1</b> Random Variation</a><ul>
<li class="chapter" data-level="9.1.1" data-path="meta.html"><a href="meta.html#variation-in-single-samples"><i class="fa fa-check"></i><b>9.1.1</b> Variation in single samples</a></li>
<li class="chapter" data-level="9.1.2" data-path="meta.html"><a href="meta.html#variance-in-two-groups-and-their-difference."><i class="fa fa-check"></i><b>9.1.2</b> Variance in two groups, and their difference.</a></li>
<li class="chapter" data-level="9.1.3" data-path="meta.html"><a href="meta.html#correlations-between-two-groups"><i class="fa fa-check"></i><b>9.1.3</b> Correlations between two groups</a></li>
<li class="chapter" data-level="9.1.4" data-path="meta.html"><a href="meta.html#confidence-intervals-around-standard-deviations."><i class="fa fa-check"></i><b>9.1.4</b> Confidence Intervals around Standard Deviations.</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="meta.html"><a href="meta.html#mixed"><i class="fa fa-check"></i><b>9.2</b> Mixed Results</a><ul>
<li class="chapter" data-level="9.2.1" data-path="meta.html"><a href="meta.html#likelihoods-of-sets-of-studies"><i class="fa fa-check"></i><b>9.2.1</b> Likelihoods of sets of studies</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="meta.html"><a href="meta.html#introduction-to-meta-analysis"><i class="fa fa-check"></i><b>9.3</b> Introduction to Meta-Analysis</a><ul>
<li class="chapter" data-level="9.3.1" data-path="meta.html"><a href="meta.html#single-study-meta-analysis"><i class="fa fa-check"></i><b>9.3.1</b> Single study meta-analysis</a></li>
<li class="chapter" data-level="9.3.2" data-path="meta.html"><a href="meta.html#simulating-meta-analyses-of-mean-standardized-differences"><i class="fa fa-check"></i><b>9.3.2</b> Simulating meta-analyses of mean standardized differences</a></li>
<li class="chapter" data-level="9.3.3" data-path="meta.html"><a href="meta.html#fixed-effect-vs-random-effects"><i class="fa fa-check"></i><b>9.3.3</b> Fixed Effect vs Random Effects</a></li>
<li class="chapter" data-level="9.3.4" data-path="meta.html"><a href="meta.html#simulating-meta-analyses-for-dichotomous-outcomes"><i class="fa fa-check"></i><b>9.3.4</b> Simulating meta-analyses for dichotomous outcomes</a></li>
<li class="chapter" data-level="9.3.5" data-path="meta.html"><a href="meta.html#heterogeneity"><i class="fa fa-check"></i><b>9.3.5</b> Heterogeneity</a></li>
<li class="chapter" data-level="9.3.6" data-path="meta.html"><a href="meta.html#metareporting"><i class="fa fa-check"></i><b>9.3.6</b> Improving the reproducibility of meta-analyses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="bias.html"><a href="bias.html"><i class="fa fa-check"></i><b>10</b> Bias detection</a><ul>
<li class="chapter" data-level="10.1" data-path="bias.html"><a href="bias.html#bias-detection"><i class="fa fa-check"></i><b>10.1</b> Bias Detection</a><ul>
<li class="chapter" data-level="10.1.1" data-path="bias.html"><a href="bias.html#funnel-plots"><i class="fa fa-check"></i><b>10.1.1</b> Funnel Plots</a></li>
<li class="chapter" data-level="10.1.2" data-path="bias.html"><a href="bias.html#trim-and-fill"><i class="fa fa-check"></i><b>10.1.2</b> Trim and Fill</a></li>
<li class="chapter" data-level="10.1.3" data-path="bias.html"><a href="bias.html#pet-peese"><i class="fa fa-check"></i><b>10.1.3</b> PET-PEESE</a></li>
<li class="chapter" data-level="10.1.4" data-path="bias.html"><a href="bias.html#p-curve-analysis"><i class="fa fa-check"></i><b>10.1.4</b> P-curve Analysis</a></li>
<li class="chapter" data-level="10.1.5" data-path="bias.html"><a href="bias.html#tiva"><i class="fa fa-check"></i><b>10.1.5</b> TIVA</a></li>
<li class="chapter" data-level="10.1.6" data-path="bias.html"><a href="bias.html#lets-detect-some-bias"><i class="fa fa-check"></i><b>10.1.6</b> Let’s Detect Some Bias!</a></li>
<li class="chapter" data-level="10.1.7" data-path="bias.html"><a href="bias.html#introducing-bias"><i class="fa fa-check"></i><b>10.1.7</b> Introducing bias</a></li>
<li class="chapter" data-level="10.1.8" data-path="bias.html"><a href="bias.html#bias-detection-techniques"><i class="fa fa-check"></i><b>10.1.8</b> Bias detection techniques</a></li>
<li class="chapter" data-level="10.1.9" data-path="bias.html"><a href="bias.html#tiva-1"><i class="fa fa-check"></i><b>10.1.9</b> TIVA</a></li>
<li class="chapter" data-level="10.1.10" data-path="bias.html"><a href="bias.html#z-curve-analysis"><i class="fa fa-check"></i><b>10.1.10</b> Z-curve analysis</a></li>
<li class="chapter" data-level="10.1.11" data-path="equivalencetest.html"><a href="equivalencetest.html#conclusion"><i class="fa fa-check"></i><b>10.1.11</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html"><i class="fa fa-check"></i><b>11</b> Computational Reproducibility</a><ul>
<li class="chapter" data-level="11.1" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-1-setting-up-a-github-repository"><i class="fa fa-check"></i><b>11.1</b> Step 1: Setting up a GitHub repository</a></li>
<li class="chapter" data-level="11.2" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-2-cloning-your-github-repository-into-rstudio"><i class="fa fa-check"></i><b>11.2</b> Step 2: Cloning your GitHub repository into RStudio</a></li>
<li class="chapter" data-level="11.3" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-3-creating-an-r-markdown-file"><i class="fa fa-check"></i><b>11.3</b> Step 3: Creating an R Markdown file</a></li>
<li class="chapter" data-level="11.4" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-4-reproducible-data-analysis-in-r-studio"><i class="fa fa-check"></i><b>11.4</b> Step 4: Reproducible Data Analysis in R Studio</a></li>
<li class="chapter" data-level="11.5" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-5-committing-and-pushing-to-github"><i class="fa fa-check"></i><b>11.5</b> Step 5: Committing and Pushing to GitHub</a></li>
<li class="chapter" data-level="11.6" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-6-reproducible-data-analysis"><i class="fa fa-check"></i><b>11.6</b> Step 6: Reproducible Data Analysis</a><ul>
<li class="chapter" data-level="11.6.1" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#extra-apa-formatted-manuscripts-in-papaja"><i class="fa fa-check"></i><b>11.6.1</b> Extra: APA formatted manuscripts in papaja</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-7-organizing-your-data-and-code"><i class="fa fa-check"></i><b>11.7</b> Step 7: Organizing Your Data and Code</a></li>
<li class="chapter" data-level="11.8" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#step-8-archiving-your-data-and-code"><i class="fa fa-check"></i><b>11.8</b> Step 8: Archiving Your Data and Code</a><ul>
<li class="chapter" data-level="11.8.1" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#extra-sharing-reproducible-code-on-code-ocean"><i class="fa fa-check"></i><b>11.8.1</b> EXTRA: Sharing Reproducible Code on Code Ocean</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="computationalreproducibility.html"><a href="computationalreproducibility.html#some-points-for-improvement-in-computational-reproducibility"><i class="fa fa-check"></i><b>11.9</b> Some points for improvement in computational reproducibility</a></li>
<li class="chapter" data-level="11.10" data-path="equivalencetest.html"><a href="equivalencetest.html#conclusion"><i class="fa fa-check"></i><b>11.10</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="prereg.html"><a href="prereg.html"><i class="fa fa-check"></i><b>12</b> Preregistration and Transparency</a><ul>
<li class="chapter" data-level="12.1" data-path="prereg.html"><a href="prereg.html#trust-in-scientists"><i class="fa fa-check"></i><b>12.1</b> Trust in scientists</a></li>
<li class="chapter" data-level="12.2" data-path="prereg.html"><a href="prereg.html#the-value-of-preregistration"><i class="fa fa-check"></i><b>12.2</b> The value of preregistration</a></li>
<li class="chapter" data-level="12.3" data-path="prereg.html"><a href="prereg.html#registered-reports"><i class="fa fa-check"></i><b>12.3</b> Registered Reports</a></li>
<li class="chapter" data-level="12.4" data-path="prereg.html"><a href="prereg.html#preregister-your-study"><i class="fa fa-check"></i><b>12.4</b> Preregister your study?</a><ul>
<li class="chapter" data-level="12.4.1" data-path="prereg.html"><a href="prereg.html#how-to-preregister"><i class="fa fa-check"></i><b>12.4.1</b> How to preregister</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="prereg.html"><a href="prereg.html#what-does-a-formalized-test-of-a-prediction-look-like"><i class="fa fa-check"></i><b>12.5</b> What Does a Formalized Test of a Prediction Look Like?</a></li>
<li class="chapter" data-level="12.6" data-path="prereg.html"><a href="prereg.html#are-you-ready-to-preregister-a-hypothesis-test"><i class="fa fa-check"></i><b>12.6</b> Are you ready to preregister a hypothesis test?</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="bayes.html"><a href="bayes.html"><i class="fa fa-check"></i><b>13</b> Bayesian statistics</a><ul>
<li class="chapter" data-level="13.1" data-path="bayes.html"><a href="bayes.html#likelihoods"><i class="fa fa-check"></i><b>13.1</b> Likelihoods</a></li>
<li class="chapter" data-level="13.2" data-path="bayes.html"><a href="bayes.html#bayes-factors"><i class="fa fa-check"></i><b>13.2</b> Bayes factors</a><ul>
<li class="chapter" data-level="13.2.1" data-path="bayes.html"><a href="bayes.html#updating-our-belief"><i class="fa fa-check"></i><b>13.2.1</b> Updating our belief</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="bayes.html"><a href="bayes.html#bayesest"><i class="fa fa-check"></i><b>13.3</b> Bayesian Estimation</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sequential.html"><a href="sequential.html"><i class="fa fa-check"></i><b>14</b> Sequential Analysis</a><ul>
<li class="chapter" data-level="14.1" data-path="sequential.html"><a href="sequential.html#choosing-alpha-levels-for-sequential-analyses."><i class="fa fa-check"></i><b>14.1</b> Choosing alpha levels for sequential analyses.</a><ul>
<li class="chapter" data-level="14.1.1" data-path="sequential.html"><a href="sequential.html#pocock-correction"><i class="fa fa-check"></i><b>14.1.1</b> Pocock correction</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="sequential.html"><a href="sequential.html#comparing-spending-functions"><i class="fa fa-check"></i><b>14.2</b> Comparing Spending Functions</a></li>
<li class="chapter" data-level="14.3" data-path="sequential.html"><a href="sequential.html#sample-size-for-sequential-designs"><i class="fa fa-check"></i><b>14.3</b> Sample Size for Sequential Designs</a><ul>
<li class="chapter" data-level="14.3.1" data-path="sequential.html"><a href="sequential.html#alpha-spending-functions"><i class="fa fa-check"></i><b>14.3.1</b> Alpha spending functions</a></li>
<li class="chapter" data-level="14.3.2" data-path="sequential.html"><a href="sequential.html#updating-boundaries-during-an-experiment"><i class="fa fa-check"></i><b>14.3.2</b> Updating Boundaries During an Experiment</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="sequential.html"><a href="sequential.html#test-for-non-inferiority"><i class="fa fa-check"></i><b>14.4</b> Test for (non-)inferiority</a></li>
<li class="chapter" data-level="14.5" data-path="sequential.html"><a href="sequential.html#stopping-for-futility"><i class="fa fa-check"></i><b>14.5</b> Stopping for futility</a><ul>
<li class="chapter" data-level="14.5.1" data-path="sequential.html"><a href="sequential.html#sequential-analyses-using-bayes-factors."><i class="fa fa-check"></i><b>14.5.1</b> Sequential analyses using Bayes factors.</a></li>
<li class="chapter" data-level="14.5.2" data-path="sequential.html"><a href="sequential.html#reporting-results-after-a-sequential-analysis."><i class="fa fa-check"></i><b>14.5.2</b> Reporting results after a sequential analysis.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>15</b> References</a></li>
<li class="divider"></li>
<li><a href="https://sites.google.com/site/lakens2/Home" target="blank">Daniel Lakens</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Improving Your Statistical Inferences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="power" class="section level1">
<h1><span class="header-section-number">2</span> Sample size justification</h1>
<p>When you perform an experiment, you want it to provide an answer to your research question that is as informative as possible. However, since all scientists are faced with resource limitations, you need to balance the cost of collecting each additional datapoint against the increase in information that datapoint provides. In economics, this is known as the Value of Information <span class="citation">(Eckermann et al., <a href="#ref-eckermann_value_2010" role="doc-biblioref">2010</a>)</span>. Calculating the value of information is notoriously difficult. You need to specify the costs and benefits of possible outcomes of the study, and quantifying a utility function for scientific research is not easy.</p>
<p>Because of the difficulty of quantifying the value of information, scientists use less formal approaches to justify the amount of data they set out to collect. That is, if they provide a justification for the number of observations to begin with. Even though in some fields a justification for the number of observations is required when submitting a grant proposal to a science funder, a research proposal to an ethical review board, or a manuscript for submission to a journal. In some research fields, the number of observations is <em>stated</em>, but not <em>justified</em>. This makes it difficult to evaluate how informative the study was. Referees can’t just assume the number of observations is sufficient to provide an informative answer to your research question, so leaving out a justification for the number of observations is not best practice, and a reason reviewers can criticize your submitted article.</p>
<p>Researchers often find it difficult to justify their sample size, and a simple and efficient alternative is to only specify a maximum sample size, and analyse results as data comes in using <a href="sequential.html#sequential">sequential analyses</a> instead. Below, several possible justifications to decide upon a specific sample size when designing an experiment are discussed.</p>
<table>
<caption>
<span id="tab:table-pow-just">Table 2.1: </span>Overview of recommendations when reporting an a-prior power analysis.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Type of Justification
</th>
<th style="text-align:left;">
In which situations is this justification relevant?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Measure the entire population
</td>
<td style="text-align:left;">
You can specify the entire population, it is finite, and you are able to measure every entity in the population.
</td>
</tr>
<tr>
<td style="text-align:left;">
Feasibility
</td>
<td style="text-align:left;">
Limited resources are the primary reason for your choice of the sample size you can collect.
</td>
</tr>
<tr>
<td style="text-align:left;">
Accuracy
</td>
<td style="text-align:left;">
Your research question focusses on the size of a parameter, and you plan to collect sufficient data to have an estimate with a desired level of accuracy.
</td>
</tr>
<tr>
<td style="text-align:left;">
A-priori power analysis
</td>
<td style="text-align:left;">
Your research question focusses on rejecting certain effect sizes (e.g., effects = 0 in a directional NHST) and you want to achieve a desired probability of a correct rejection.
</td>
</tr>
<tr>
<td style="text-align:left;">
Heuristics
</td>
<td style="text-align:left;">
You rely on a benchmark, heuristic, general rule, or other convention that is either described in the literature or communicated orally.
</td>
</tr>
<tr>
<td style="text-align:left;">
No justification
</td>
<td style="text-align:left;">
You do not have any reason to choose a specific sample size, and you are simply collecting some data that seems sufficient to increase your understanding of the topic you are studying.
</td>
</tr>
</tbody>
</table>
<p>All of these sample size justification, even the ‘no justification’ category, are valid justifications in the sense that they give others insight into the underlying reasons that lead to your decision for a sample size in your study. However, it should not be surprising that the ‘heuristics’ and ‘no justification’ categories are unlikely to impress other scholars. What is perhaps more surprising is that, except for measuring the entire population, the other justifications might also not impress other scholars. The extent to which these justifications make other researchers judge the data you have collected as <em>informative</em> depends on the details of the question you aimed to answer, and the parameters you choose when determining the sample size for your study.</p>
<div id="measuring-the-entire-population" class="section level2">
<h2><span class="header-section-number">2.1</span> Measuring the Entire Population</h2>
<p>In some instances it might be possible to collect data from the entire population under examination. For example, you might be interested in the average amount of time people spend on the moon, whenever they visit it. Since there are only 12 people who have ever been on the moon, we can calculate the average time people have spent on the moon by collecting data from the entire population. Whenever it is possible to measure the entire population, the justification for the sample size is that you collected all the data that is available. This is the simplest, and most straightforward, justification for the sample size. However, it is also quite rare that we are able to measure the entire population.</p>
<p>The the entire population is measured, there is no need to perform a hypothesis test. After all, there is no population to generalize to, and any differences between two populations are, except for the possibility of measurement inaccuracy, true differences. In these cases, the question whether there is a true difference, or if the difference is noise becomes uninteresting, and we should mainly be interested in whether the observed difference is large enough to be meaningful.</p>
<p>If we have sampled the entire population, the mean is measured with absolute precision, and there is no confidence interval. If the total population size is known, but not measured completely, then the confidence interval width interval should shrink to zero the closer we get to measuring the entire population. This is known as the <strong>finite population correction factor</strong> for the variance of the estimator <span class="citation">(Thompson, <a href="#ref-thompson_sampling_2012" role="doc-biblioref">2012</a>)</span>. The variance of a sample mean is <span class="math inline">\(\frac{\sigma^2}{n}\)</span>, and the finite population correction factor is <span class="math inline">\(1 - \frac{n}{N}\)</span>. When N is massively larger than n, the correction factor will be close to 1, and not have a noticeable effect on the variance. However, is the total population is measured, the correction factor is 0. The <code>superb</code> R package can compute population corrected confidence intervals <span class="citation">(Cousineau &amp; Chiasson, <a href="#ref-cousineau_superb_2019" role="doc-biblioref">2019</a>)</span>.</p>
</div>
<div id="feasibility" class="section level2">
<h2><span class="header-section-number">2.2</span> Feasibility</h2>
<p>A common reason why a specific number of observations is collected is because collecting more data was not feasible. Note that all decisions for the sample size we collect in a study are based on the resources we have available in some way. A <strong>feasibility justification</strong> makes these resource limitations the primary reason for the sample size that is collected. Because we always have resource limitations in science, even when feasibility is not our primary justification for the number of observations we plan to collect, it is always a secondary reason. Despite the omnipresence of resource limitations, the topic often receives very little attention in texts on experimental design. This might make it feel like a feasibility justification is not appropriate, and you should perform an a-priori power analysis or plan for a desired precision instead. But feasibility always plays a secondary role, and therefore regardless of which justification for the sample size you provide, you will almost always need to include a feasibility justification as well.</p>
<p>Time and money are the two main resource limitations a scientist faces. Our master students write their thesis in 6 months, and therefore their data collection is necessarily limited in whatever can be collected in 6 months, minus the time needed to formulate a research question, design an experiment, analyze the data, and write up the thesis. A PhD student at our department would have 4 years to complete their thesis, but is also expected to complete multiple research lines in this time. In addition to limitations on time, we have limited financial resources. Although nowadays it is possible to collect data online quickly, if you offer participants a decent pay (as you should) most researchers do not have the financial means to collect thousands of datapoints.</p>
<p>A feasibility justification puts the limited resources at the center of the justification for the sample size that will be collected. For example, one might argue that 120 observations is the most that can be collected in the three weeks a master student has available to collect data, when each observation takes an hour to collect. A PhD student might collect data until the end of the academic year, and then needs to write up the results over the summer to stay on track to complete the thesis in time.</p>
<p>A feasibility justification thus <em>starts</em> with the expected number of observations (N) that a researcher expects to be able to collect. The challenge is to evaluate whether collecting N observations is worthwhile. The answer should sometimes be that data collection is <em>not</em> worthwhile. For example, assume I plan to manipulate the mood of participants using funny cartoons and then measure the effect of mood on some dependent variable - say the amount of money people donate to charity. I should expect an effect size around d = 0.31 for the mood manipulation <span class="citation">(Joseph et al., <a href="#ref-joseph_manipulation_2020" role="doc-biblioref">2020</a>)</span>, and seems unlikely that the effect on donations will be larger than the effect size of the manipulation. If I can only collect mood data from 30 participants in total, how do we decide if this study will be informative?</p>
<p>If we want to evaluate whether the feasibility limitations make data collection uninformative, we need to think about what the goal of data collection is. First of all, having data always provide more knowledge than not having data, so in an absolute sense, all additional data that is collected is better than not collecting data. However, in line with the idea that we need to take into account costs and benefits, it is possible that the cost of data collection outweighs the benefits. To determine this, one needs to think about what the benefits of having the data are. The benefits are clearest when we know for certain that someone is going to make a decision, with or without data. If this is the case, then any data you collect will reduce the error rates of a well-calibrated decision process, even if only ever so slightly. In these cases, the value of information might be positive, as long as the reduction in error rates is more beneficial than the costs of data collection. If your sample size is limited and you know you will make a decision anyway, perform a <a href="power.html#compromisepower">compromise power analysis</a>, where you balance the error rates, given a specified effect size and sample size.</p>
<p>Another way in which a small dataset can be valuable is if its existence makes it possible to combine several small datasets into a meta-analysis. This argument in favor of collecting a small dataset requires 1) that you share the results in a way that a future meta-analyst can find them, and 2) that there is a decent probability that someone will perform a meta-analysis in the future which inclusion criteria would contain your study, because a sufficient number of small studies exist. The uncertainty about whether there will ever be such a meta-analysis should be weighed against the costs of data collection. One way to increase the probability of a future meta-analysis is if you commit to performing this yourself in the future. For example, you might plan to repeat a study for the next 12 years in a class you teach, with the expectation that a meta-analysis of 360 participants would be sufficient to achieve around 90% power for d = 0.31. If it is not plausible you will collect all the required data by yourself, you can attempt to set up a collaboration, where fellow researchers in your field commit to collecting similar data, with identical measures, over the next years. If it is not likely sufficient data will emerge over time, we will not be able to draw informative conclusions from the data, and it might be more beneficial to not collect the data to begin with, and examine an alternative research question with a larger effect size instead.</p>
<p>Even if you believe over time sufficient data will emerge, you will most likely compute statistics after collecting a small sample size. Before embarking on a study where your main justification for the sample size is based on feasibility, you can expect. I propose that a feasibility justification for the sample size is always accompanied by three statistics, detailed in the following three sections.</p>
<div id="the-smallest-effect-size-that-can-be-statistically-significant" class="section level3">
<h3><span class="header-section-number">2.2.1</span> The smallest effect size that can be statistically significant</h3>
<p>In Figure <a href="power.html#fig:power-effect1">2.1</a> the distribution of Cohen’s d given 15 participants per group is plotted when the true effect size is 0 (or the null-hypothesis is true), and when the true effect size is d = 0.5. The blue area is the Type 2 error rate (the probability of not finding p &lt; α, when there is a true effect, and α = 0.05). 1 - Type 2 error is the <strong>statistical power</strong>, or the probability of a test to yield a statistically significant result if the alternative hypothesis is true <span class="citation">(Aberson, <a href="#ref-aberson_applied_2019" role="doc-biblioref">2019</a>; Cohen, <a href="#ref-cohen_statistical_1988" role="doc-biblioref">1988</a>)</span>. Power depends on the Type 1 error rate (α), the true effect size in the population, and the number of observations.</p>
<div class="figure"><span id="fig:power-effect1"></span>
<img src="Statistical_Inferences_files/figure-html/power-effect1-1.png" alt="Null and alternative distribution, assuming d = 0.5, alpha = 0.05, and N = 15 per group." width="672" />
<p class="caption">
Figure 2.1: Null and alternative distribution, assuming d = 0.5, alpha = 0.05, and N = 15 per group.
</p>
</div>
<p>Because the true effect size is typically unknown, it makes most sense to speak about the power function. In Figure <a href="power.html#fig:power-1">2.2</a> you see a power curve for an independent <em>t</em>-test, with an alpha level of 0.05. We see that as the effect size (in Cohen’s d) increases, power increases. If the effect you study has an effect size of 0.5, you would have almost 70% power with 50 observations in each independent group (indicated by the red dot). If the true effect size is smaller, power is lower, and as the effect size is larger, power is larger.</p>
<div class="figure"><span id="fig:power-1"></span>
<img src="Statistical_Inferences_files/figure-html/power-1-1.png" alt="Power curve for an independent *t*-test as a function of the true effect size." width="672" />
<p class="caption">
Figure 2.2: Power curve for an independent <em>t</em>-test as a function of the true effect size.
</p>
</div>
<p><strong>Power analysis</strong> is the practice of computing the effect size, desired power, sample size, or alpha level from the other three values. Computing the required sample size is commonly referred to as <strong>a-priori</strong> power analysis, computing the smallest effect size you have the desired power for is called <strong>sensitivity</strong> power analysis, computing the alpha level is called <strong>criterion</strong> power analysis, and computing the achieved power is called <strong>post-hoc</strong> power analysis.</p>
<p>You might seen graphs like Figure <a href="power.html#fig:power-effect1">2.1</a> before. The only thing I have done is to transform the <em>t</em>-value distribution that is commonly used in these graphs, and calculated the distribution for Cohen’s d. This is a straightforward transformation, but instead of presenting the critical <em>t</em>-value the figure provides the critical <em>d</em>-value. For a two-sided independent <em>t</em>-test, this is calculated as:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="power.html#cb1-1"></a><span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>(a <span class="op">/</span><span class="st"> </span><span class="dv">2</span>), (n1 <span class="op">+</span><span class="st"> </span>n2) <span class="op">-</span><span class="st"> </span><span class="dv">2</span>) <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n2)</span></code></pre></div>
<p>where ‘a’ is the alpha level (e.g., 0.05) and N is the sample size in each independent group. For the example above, where alpha is 0.05 and n = 15:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="power.html#cb2-1"></a><span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>(<span class="fl">0.05</span> <span class="op">/</span><span class="st"> </span><span class="dv">2</span>), (<span class="dv">15</span> <span class="op">*</span><span class="st"> </span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="dv">2</span>) <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">15</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="dv">15</span>)</span></code></pre></div>
<pre><code>## [1] 0.7479725</code></pre>
<p>The critical <em>t</em>-value (2.0484071) is also provided in commonly used power analysis software such as G*Power. We can compute the critical Cohen’s d from the <em>t</em>-value and sample size using: <span class="math inline">\(d = t{\sqrt{1/n_1 + 1/n_2}}\)</span>.</p>
<div class="figure"><span id="fig:gcrit1"></span>
<img src="images/gpowcrit.png" alt="The critical *t*-value is provided by G\*Power software." width="378" />
<p class="caption">
Figure 2.3: The critical <em>t</em>-value is provided by G*Power software.
</p>
</div>
<p>When you will test an association between variables with a correlation, G*Power will directly provide you with the critical effect size. When you compute a correlation based on a two-sided test, your alpha level is 0.05, and you have 30 observations, only effects larger than r = 0.361 will be statistically significant. In other words, the effect needs to be quite large to even have the mathematical possibility of becoming statistically significant.</p>
<div class="figure"><span id="fig:gcrit2"></span>
<img src="images/gpowcrit2.png" alt="The critical r is provided by G\*Power software." width="378" />
<p class="caption">
Figure 2.4: The critical r is provided by G*Power software.
</p>
</div>
<p>The critical effect size gives you information about the smallest effect size that, if observed, would by statistically significant. If you observe a smaller effect size, the <em>p</em>-value will be larger than your significance threshold. You always have some probability of observing effects larger than the critical effect size. After all, even if the null hypothesis is true, 5% of your tests will yield a significant effect. But what you should ask yourself is whether the effect sizes that could be statistically significant are realistically what you would expect to find. If this is not the case, it should be clear that there is little (if any) use in performing a significance test. Mathematically, when the critical effect size is larger than effects you expect, your statistical power will be less than 50% (see the section on <a href="power.html#observedpower">observed power</a>). If you perform a statistical test with less than 50% power, your single study is not very informative. Reporting the critical effect size in a feasibility justification should make you reflect on whether a hypothesis test will yield an informative answer to your research question.</p>
</div>
<div id="compute-the-width-of-the-confidence-interval-around-the-effect-size" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Compute the width of the confidence interval around the effect size</h3>
<p>The second statistic to report alongside a feasibility justification is the width of the 95% confidence interval around the effect size. As we saw in the section on <a href="effectsizesCI.html#confint">confidence intervals</a> they represent a range that is wide enough so that in the long run in 95% of repetitions of the same experiment the true population parameter falls within each confidence interval calculated around the observed effect size. Cumming <span class="citation">(<a href="#ref-cumming_understanding_2013" role="doc-biblioref">2013</a>)</span> calls the difference between the observed effect size and the upper 95% confidence interval (or the lower 95% confidence interval) the margin of error (MOE).</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="power.html#cb4-1"></a><span class="co"># Compute the effect size d and 95% CI</span></span>
<span id="cb4-2"><a href="power.html#cb4-2"></a>res &lt;-<span class="st"> </span><span class="kw">d.ind.t</span>(<span class="dt">m1 =</span> <span class="dv">0</span>, <span class="dt">m2 =</span> <span class="dv">0</span>, <span class="dt">sd1 =</span> <span class="dv">1</span>, <span class="dt">sd2 =</span> <span class="dv">1</span>, <span class="dt">n1 =</span> <span class="dv">15</span>, <span class="dt">n2 =</span> <span class="dv">15</span>, <span class="dt">a =</span> <span class="fl">.05</span>)</span>
<span id="cb4-3"><a href="power.html#cb4-3"></a><span class="co"># Print the result</span></span>
<span id="cb4-4"><a href="power.html#cb4-4"></a>res<span class="op">$</span>estimate</span></code></pre></div>
<pre><code>## [1] &quot;$d_s$ = 0.00, 95\\% CI [-0.72, 0.72]&quot;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="power.html#cb6-1"></a><span class="co"># Compute the average Margin of Error (MOE)</span></span>
<span id="cb6-2"><a href="power.html#cb6-2"></a>(res<span class="op">$</span>dhigh <span class="op">-</span><span class="st"> </span>res<span class="op">$</span>dlow)<span class="op">/</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.7156777</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="power.html#cb8-1"></a><span class="co"># For non-zero effects the CI is based on the non-central t</span></span>
<span id="cb8-2"><a href="power.html#cb8-2"></a><span class="co"># The MOE is then asymmetric (but differences are very small)</span></span>
<span id="cb8-3"><a href="power.html#cb8-3"></a>(res<span class="op">$</span>d <span class="op">-</span><span class="st"> </span>res<span class="op">$</span>dlow)</span></code></pre></div>
<pre><code>## [1] 0.7156777</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="power.html#cb10-1"></a>(res<span class="op">$</span>dhigh <span class="op">-</span><span class="st"> </span>res<span class="op">$</span>d)</span></code></pre></div>
<pre><code>## [1] 0.7156777</code></pre>
<p>If we compute the 95% CI for an effect size of 0, we see that with 15 observations in each condition of an independent <em>t</em>-test the 95% CI ranges from -0.72 to 0.72. The MOE is half the width of the 95% CI, 0.72. This clearly shows we have a very imprecise estimate. A Bayesian estimator who uses an uninformative prior would compute a credible interval with the same upper and lower bound <span class="citation">(Albers et al., <a href="#ref-albers_credible_2018" role="doc-biblioref">2018</a>)</span>, and might conclude they personally believe there is a 95% chance the true effect size lies in this interval. A frequentist would reason more hypothetically: If the observed effect size in the data I plan to collect is 0, I could only reject effects more extreme than d = 0.72 in an equivalence test with a 5% alpha level (even though if such a test would be performed, power might be low, depending on the true effect size). Regardless of the statistical philosophy you plan to rely on when analyzing the data, our evaluation of what we can conclude based on the width of our interval tells us we will not learn a lot. Effect sizes in the range of d = 0.7 are findings such as “People become aggressive when they are provoked”, “People prefer their own group to other groups”, and “Romantic partners resemble one another in physical attractiveness” <span class="citation">(Richard et al., <a href="#ref-richard_one_2003" role="doc-biblioref">2003</a>)</span>. The width of the confidence interval tells you that you can only reject the presence of effects that are so large, if they existed, you would probably already have noticed them. It might still be important to establish these large effects in a well-controlled experiment. But since most effect sizes in we should realistically expect are much smaller, we do not learn something we didn’t already know from the data that plan to collect. Even without data, we would exclude effects larger than d = 0.7 in most research lines.</p>
<p>We see this the MOE is almost, but not exactly, the same as the critical effect size d we observed above (d = 0.7479725). The reason for this is that the 95% confidence interval is calculated based on the <em>t</em>distribution. If the true effect size is not zero, the confidence interval is calculated based on the non-central <em>t</em>distribution, and the 95% CI is asymmetric. Figure <a href="power.html#fig:noncentralt">2.5</a> vizualizes three <em>t</em>-distributions, one symmetric at 0, and two asymmetric distributions with a noncentrality parameter of 2 and 3. The asymmetry is most clearly visible in very small samples (the distribution in the plot have 5 degrees of freedom) but remain noticeable when calculating confidence intervals and statistical power. For example, for a true effect size of d = 0.5 the 95% CI is <span class="math inline">\(d_s\)</span> = 0.50, 95\% CI [-0.23, 1.22]. The MOE based on the lower bound is 0.7317584 and based on the upper bound is 0.7231479. If we compute the 95% CI around the critical effect size (d = 0.7479725) we see the 95% CI ranges from exactly 0.00 to 1.48. As explained in the section on the relation between a <a href="effectsizesCI.html#relatCIp">confidence interval and a <em>p</em>-value</a>, if the 95% CI excludes zero, the test is statistically significant. In this case the lowerbound of the confidence interval exactly touches 0, which means we would observe a <em>p</em> = 0.05 if we exactly observed the critical effect size.</p>
<div class="figure"><span id="fig:noncentralt"></span>
<img src="Statistical_Inferences_files/figure-html/noncentralt-1.png" alt="Central (black) and 2 non-central (red and blue) *t*-distributions." width="672" />
<p class="caption">
Figure 2.5: Central (black) and 2 non-central (red and blue) <em>t</em>-distributions.
</p>
</div>
<p>Where computing the critical effect size can make it clear that a <em>p</em>-value is of little interest, computing the 95% CI around the effect size can make it clear that the effect size estimate is of little value. It will often be so uncertain, and the range of effect sizes you will not be able to reject if there is no effect is so large, the effect size estimate is not very useful. This is also the reason why performing a pilot study to estimate an effect size for an a-priori power analysis is not a sensible strategy <span class="citation">(Albers &amp; Lakens, <a href="#ref-albers_when_2018" role="doc-biblioref">2018</a>; Leon et al., <a href="#ref-leon_role_2011" role="doc-biblioref">2011</a>)</span>. However, it is possible that the sample size is large enough to exclude some effect sizes that are still a-priori plausible. For example, with 50 observations in each independent group, you have 82% <a href="equivalencetest.html#powerequiv">power for an equivalence test</a> with bounds of -0.6 and 0.6, and if effect larger than 0.6 can be rejected, this might be sufficient to tentatively start to question claims of even larger effects in the literature.</p>
</div>
<div id="sensitivitypower" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Plot a sensitivity power analysis</h3>
<p>In a <strong>sensitivity power analysis</strong> the sample size and the alpha level are fixed, and you compute the effect size you have the desired statistical power to detect. For example, in Figure <a href="power.html#fig:gsens0">2.6</a> the sample size in each group is set to 15, the alpha level is 0.05, and the desired power is set to 90%. The sensitivity power analysis shows we have 90% power to detect an effect of d = 1.23.</p>
<div class="figure"><span id="fig:gsens0"></span>
<img src="images/sensitivity0.png" alt="Sensitivity power analysis in G\*Power software." width="378" />
<p class="caption">
Figure 2.6: Sensitivity power analysis in G*Power software.
</p>
</div>
<p>Perhaps you feel a power of 90% is a bit high, and you would be happy with 80% power. We can plot a sensitivity curve across all possible levels of statistical power. In Figure <a href="power.html#fig:gsens1">2.7</a> we see that if we desire 80% power, the effect size should be d = 1.06. The smaller the true effect size, the lower the power we have. This plot should again remind us not to put too much faith in a significance test when are sample size is small, since for 15 observations in each condition, statistical power is very low for anything but extremely large effect sizes.</p>
<div class="figure"><span id="fig:gsens1"></span>
<img src="images/sensitivity1.png" alt="Plot of the effect size against the desired power when n = 15 per group and alpha = 0.05." width="485" />
<p class="caption">
Figure 2.7: Plot of the effect size against the desired power when n = 15 per group and alpha = 0.05.
</p>
</div>
<p>If we look at the effect size that we would have 50% power for, we see it is d = 0.7411272. This is very close to our critical effect size of d = 0.7479725 (the smallest effect size that, if observed, would be significant). The difference is due to the non-central <em>t</em>-distribution (see Figure <a href="power.html#fig:noncentralt">2.5</a>. If the distribution was symmetric, observing an effect size exactly on the critical value would mean half of the distribution is smaller than the critical effect size, and half of the distribution is larger, and we would have exactly 50% power for the critical effect size. Because the distribution is not symmetrical, we need to find the critical effect size for which it <em>is</em> true that half the distribution falls below it, and half the distribution falls above it. This value can’t be calculated directly, and requires an iterative procedure that optimizes the values of the non-centrality parameter such that power is exactly 50% <span class="citation">(Smithson, <a href="#ref-smithson_confidence_2003" role="doc-biblioref">2003</a>)</span>. The <code>pwr</code> package in R can calculate this effect size in a sensitivity analysis where we enter the sample size (per group), the alpha level, and the desired power for a two-sided independent <em>t</em>-test, which will return d = 0.7411272. We can check this true effect size would indeed give with 50% power.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="power.html#cb12-1"></a><span class="co"># Sensitivity power analysis</span></span>
<span id="cb12-2"><a href="power.html#cb12-2"></a>pwr<span class="op">::</span><span class="kw">pwr.t.test</span>(<span class="dt">n =</span> <span class="dv">15</span>, </span>
<span id="cb12-3"><a href="power.html#cb12-3"></a>                <span class="dt">sig.level =</span> <span class="fl">0.05</span>, </span>
<span id="cb12-4"><a href="power.html#cb12-4"></a>                <span class="dt">power =</span> <span class="fl">0.5</span>, </span>
<span id="cb12-5"><a href="power.html#cb12-5"></a>                <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,</span>
<span id="cb12-6"><a href="power.html#cb12-6"></a>                <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 15
##               d = 0.7411272
##       sig.level = 0.05
##           power = 0.5
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="power.html#cb14-1"></a><span class="co"># d = 0.7411272 - let&#39;s check this indeed gives 50% power</span></span>
<span id="cb14-2"><a href="power.html#cb14-2"></a><span class="co"># We compute the non-centrality parameter delta as 2.0296604</span></span>
<span id="cb14-3"><a href="power.html#cb14-3"></a><span class="co"># delta &lt;- 0.7411272 * sqrt(15/2)</span></span>
<span id="cb14-4"><a href="power.html#cb14-4"></a></span>
<span id="cb14-5"><a href="power.html#cb14-5"></a><span class="co"># For a 2-sided test power is the probability of finding a result that is</span></span>
<span id="cb14-6"><a href="power.html#cb14-6"></a><span class="co"># 1) larger than the critical value of 2.0484071, which is: 0.4999563</span></span>
<span id="cb14-7"><a href="power.html#cb14-7"></a><span class="co"># 2) We need to add the tiny probability that we find a significant result in</span></span>
<span id="cb14-8"><a href="power.html#cb14-8"></a><span class="co"># the opposite direction. This will rarely happen: 0.00004372648</span></span>
<span id="cb14-9"><a href="power.html#cb14-9"></a><span class="co"># Together these two probabilities make exactly 50%:</span></span>
<span id="cb14-10"><a href="power.html#cb14-10"></a><span class="co"># 1-pt(2.0484071, 28, 2.0296604) + pt(-2.0484071, 28, 2.0296604)</span></span></code></pre></div>
</div>
<div id="reporting-a-feasibility-justification." class="section level3">
<h3><span class="header-section-number">2.2.4</span> Reporting a feasibility justification.</h3>
<p>To summarize, I recommend addressing the following components in a feasibility sample size justification. Addressing these points explicitly will allow you to evaluate for yourself if collecting the data will have scientific value. If not, there might be other reasons to collect the data. For example, at our department, students often collect data as part of their education. However, if the primary goal of data collection is educational, the sample size that is collected can be very small. It is often educational to collect data from a small number of participants to experience what data collection looks like in practice, but there is often no educational value in collecting data from more than 10 participants. Despite the small sample size, we often require students to report statistical analyses as part of their education, which is fine as long as it is clear the numbers that are calculated can not meaningfully be interpreted. Table <a href="power.html#tab:table-pow-rec">2.2</a> should help to evaluate if the interpretation of statistical tests has any value, or not.</p>
<table>
<caption>
<span id="tab:table-pow-rec">Table 2.2: </span>Overview of recommendations when reporting a sample size justification based on feasibility.
</caption>
<thead>
<tr>
<th style="text-align:left;">
What to address
</th>
<th style="text-align:left;">
Example?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Will a future meta-analysis be performed?
</td>
<td style="text-align:left;">
Consider the plausibility that sufficient highly similar studies will be performed in the future to, eventually, make a meta-analysis possible
</td>
</tr>
<tr>
<td style="text-align:left;">
Will a decision be made, regardless of the amount of data that is available?
</td>
<td style="text-align:left;">
If it is known that a decision will be made, with or without data, then any data you collect will reduce error rates.
</td>
</tr>
<tr>
<td style="text-align:left;">
What is the critical effect size?
</td>
<td style="text-align:left;">
Report and interpret the critical effect size, with a focus on whether a hypothesis test would even be significant for expected effect sizes. If not, indicate you will not interpret the data based on <em>p</em>-values.
</td>
</tr>
<tr>
<td style="text-align:left;">
What is the width of the confidence interval?
</td>
<td style="text-align:left;">
Report and interpret the width of the confidence interval. What will an estimate with this much uncertainty be useful for? If the null hypothesis is true, would rejecting effects outside of the confidence interval be worthwhile (ignoring you might have low power to actually test against these values)?
</td>
</tr>
<tr>
<td style="text-align:left;">
Which effect sizes would you have decent power to detect?
</td>
<td style="text-align:left;">
Report a sensitivity power analysis, and report the effect sizes you could detect across a range of desired power levels (e.g., 80%, 90%, and 95%), or plot a sensitivity curve of effect sizes against desired power.
</td>
</tr>
</tbody>
</table>
<p>If the study is not performed for educational purposes, but the goal is answer a research question, the feasibility justification might indicate that there is no value in collecting the data. If it wasn’t possible to conclude that one should not proceed with the data collection, there is no use of justifying the sample size. There should be cases where it is unlikely there will ever be enough data to perform a meta-analysis (for example because of a lack of general interest in the topic), the information will not be used to make any decisions, and the statistical tests do not allow you to test a hypothesis or estimate an effect size estimate with any useful accuracy. It should be a feasibility justification - not a feasibility excuse. If there is no good justification to collect the maximum number of observations that is feasible, performing the study nevertheless is a waste of participants time, and/or a waste of money if data collection has associated costs. Collecting data without a good justification why the planned sample size will yield worthwhile information has an ethical component. As Button and colleagues <span class="citation">Button et al. (<a href="#ref-button_power_2013" role="doc-biblioref">2013</a>)</span> write:</p>
<blockquote>
<p>Low power therefore has an ethical dimension — unreliable research is inefficient and wasteful. This applies to both human and animal research.</p>
</blockquote>
<p>Think carefully if you can defend data collection based on a feasibility justification. Sometimes data collection is just not feasible, and we should accept this.</p>
</div>
</div>
<div id="a-priori-power-analysis" class="section level2">
<h2><span class="header-section-number">2.3</span> A-priori power analysis</h2>
<p>When designing a study where the goal is to observe a statistically significant effect, researchers often want to make sure their sample size is large enough to have sufficient power to detect effects they expect, or effects they are interested in observing. This is done by performing an <em>a-priori</em> power analysis. Given a specified effect size, alpha level, and desired power, an a-priori power analysis will inform you about the sample size you need to collect. In Figure <a href="power.html#fig:power-2">2.8</a> you see how the statistical power increases as the number of observations (per group) in an independent <em>t</em>-test with an alpha level of 0.05 increases.</p>
<p>It is important to highlight what the goal of a power analysis is, and what isn’t the goal. The goal of an a-priori power analysis is not to achieve sufficient power for the true effect size. The true effect size is unknown. <strong>The goal of an a-priori power analysis to achieve sufficient power given a specific assumption of the true effect size</strong>. Researchers often complain that a-priori power analysis is impossible given uncertainty about the true effect size. But when we design a study, we are uncertain about many things. We are not sure our data will be normally distributed, whether there will be a floor or ceiling effect, whether our manipulation works in a specific population, or whether our theory is true. We design studies based on assumptions. If our assumptions are wrong, we learn from our data.</p>
<p>This goal of a-priori power analysis is perhaps best illustrated by the useful recommendation to make sure your study is well powered to demonstrate the presence, <a href="power.html#powerforabsence">and the absence</a>, of an effect. For example, you might want to perform an a-priori power analysis for an equivalence test that has has sufficient power to reject an effect size observed in an earlier study using the <a href="sesoi.html#smalltelescopes">small telescopes approach</a>, while also having sufficient power for a smallest effect size that would theoretically be predicted. We compute power, assuming either of these two effect sizes are the true effect size, and aim to collect the largest sample size that either of these analyses indicate. This does not guarantee we have sufficient power for the true effect size - it simply means we have sufficient power given an assumption of what the true effect size might be. After collecting the data, we draw inferences about what we have learn, under the assumption of a true effect of a specific size. We do not draw conclusions about the (always unknown) ‘true’ effect size. Therefore, an a-priori power analysis is useful, as long as we have interesting assumptions about what effect sizes we might be interested in.</p>
<div class="figure"><span id="fig:power-2"></span>
<img src="Statistical_Inferences_files/figure-html/power-2-1.png" alt="Power curve for an independent *t*-test as a function of the sample size." width="672" />
<p class="caption">
Figure 2.8: Power curve for an independent <em>t</em>-test as a function of the sample size.
</p>
</div>
<p>A-priori power calculations are performed under the assumption that there is an effect. In practice, it is of course also possible that there is no effect (e.g., d = 0). If there is no true effect, and you want to use formally correct language, power is <em>undefined</em>. Statistical power is a concept that can only be computed assuming there is a true effect. If there is no true effect, you will still observe significant effects, but these ar <em>Type 1 errors</em>, or false positives. These occur at your chosen alpha level (e.g., 5% of the time). If you perform a hypothesis test, there are four possible outcomes:</p>
<ol style="list-style-type: decimal">
<li>False positives or Type 1 errors, indicated by α (you observe a significant test result when H0 is true)</li>
<li>False negatives or Type 2 errors, indicated by β (you observe a non-significant result when H1 is true)</li>
<li>True negatives, indicated by 1-α (a non-significant result when H0 is true)</li>
<li>True positives, indicated by 1-β (a significant test result when H1 is true)</li>
</ol>
<div class="figure"><span id="fig:NHST-outcomes"></span>
<img src="images/2.1.1.png" alt="Four possible outcomes in a null hypothesis significance test." width="961" />
<p class="caption">
Figure 2.9: Four possible outcomes in a null hypothesis significance test.
</p>
</div>
<p>The goal of an a-priori power analysis is to increase the sample size up to the level that the desired power, the probability of finding a significant result if there is a true effect, or 1-β, is at a desired level for an effect size one is interested in detecting, given a specific alpha level.</p>
<p>In Figure <a href="power.html#fig:power-3">2.10</a> you see two distributions. The left (grey) distribution is centered at 0. This is our model for the null hypothesis. If the null hypothesis is true we can find statistically significant results if the effect size is extreme enough (in a two-sided test either in the positive or negative direction), but these would be Type 1 errors (the red areas under the curve).</p>
<p>The right (black) distribution is centered at an effect of d = 0.5. This is our model for the alternative hypothesis, where we expect a true effect in the population of d = 0.5. Even though there is a true effect, we will not always find a statistically significant result. This happens when, due to random variation, the observed effect size is too close to 0 to be statistically significant. These results would be false negative results (the blue area under the curve).</p>
<div class="figure"><span id="fig:power-3"></span>
<img src="Statistical_Inferences_files/figure-html/power-3-1.png" alt="Null and alternative distribution, assuming d = 0.5, alpha = 0.05, and N = 86 per group." width="672" />
<p class="caption">
Figure 2.10: Null and alternative distribution, assuming d = 0.5, alpha = 0.05, and N = 86 per group.
</p>
</div>
<p>If we want to increase the statistical power, we are trying to reduce the size of the blue area. One way to do this would be to increase the effect size. This would shift the entire distribution to the right, and reduce the size of the blue area. Although there are ways in controlled experiments to increase the standardized effect size (e.g., by reducing statistical variation in the data), often the effect size is what it is. All we can do is increase the sample size. This will make the distribution around 0.5 more narrow, and this reduces the blue area. You can check this in an online shiny app that <a href="http://shiny.ieis.tue.nl/d_p_power/">reproduces the plot</a>.</p>
<div id="performing-a-power-analysis." class="section level3">
<h3><span class="header-section-number">2.3.1</span> Performing a power analysis.</h3>
<p>There is a wide range of software tools that can help you to perform an a-priori power analysis. Sometimes statistical power can be analytically computed based on closed formulas, and in other situations power can be computed by performing simulations. If we simulate thousands of studies, and count the percentage of studies that are statistically significant, we have an estimate of the statistical power of the test. The code below computes the statistical power (using the <code>power.t.test</code> in base R) assuming an effect size of d = 0.5, and alpha level of 0.05, and a desired power of 90%.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="power.html#cb15-1"></a><span class="kw">power.t.test</span>(<span class="dt">delta =</span> <span class="fl">0.5</span>, </span>
<span id="cb15-2"><a href="power.html#cb15-2"></a>             <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb15-3"><a href="power.html#cb15-3"></a>             <span class="dt">power =</span> <span class="fl">0.9</span>,</span>
<span id="cb15-4"><a href="power.html#cb15-4"></a>             <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,</span>
<span id="cb15-5"><a href="power.html#cb15-5"></a>             <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 85.03129
##           delta = 0.5
##              sd = 1
##       sig.level = 0.05
##           power = 0.9
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>The output tells us we need to collect 85.03 observations. Because observations do not come in decimals (we can hardly cut 0.03 from a participant) we need to collect 86 observations. We could also get this answer through simulations.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="power.html#cb17-1"></a><span class="kw">set.seed</span>(<span class="dv">600746</span>) <span class="co">#set a seed for reproducible simulations</span></span>
<span id="cb17-2"><a href="power.html#cb17-2"></a>p &lt;-<span class="st"> </span><span class="kw">numeric</span>(<span class="dv">100000</span>) <span class="co">#set up empty variable to store all simulated p-values</span></span>
<span id="cb17-3"><a href="power.html#cb17-3"></a></span>
<span id="cb17-4"><a href="power.html#cb17-4"></a><span class="co">#Run simulation</span></span>
<span id="cb17-5"><a href="power.html#cb17-5"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">100000</span>){ <span class="co">#for each simulated experiment</span></span>
<span id="cb17-6"><a href="power.html#cb17-6"></a>  x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">85</span>, <span class="dt">mean =</span> <span class="dv">0</span>, <span class="dt">sd =</span> <span class="dv">1</span>) <span class="co">#Simulate data group 1</span></span>
<span id="cb17-7"><a href="power.html#cb17-7"></a>  y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">85</span>, <span class="dt">mean =</span> <span class="fl">0.5</span>, <span class="dt">sd =</span> <span class="dv">1</span>) <span class="co">#Simulate data group 2</span></span>
<span id="cb17-8"><a href="power.html#cb17-8"></a>  z &lt;-<span class="st"> </span><span class="kw">t.test</span>(x, y) <span class="co">#perform the t-test</span></span>
<span id="cb17-9"><a href="power.html#cb17-9"></a>  p[i] &lt;-<span class="st"> </span>z<span class="op">$</span>p.value <span class="co">#get the p-value and store it</span></span>
<span id="cb17-10"><a href="power.html#cb17-10"></a>}</span>
<span id="cb17-11"><a href="power.html#cb17-11"></a></span>
<span id="cb17-12"><a href="power.html#cb17-12"></a><span class="co">#Calculate power: sum significant p-values, divide by 100000 simulations</span></span>
<span id="cb17-13"><a href="power.html#cb17-13"></a>(<span class="kw">sum</span>(p <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>)<span class="op">/</span><span class="dv">100000</span>) <span class="co">#power</span></span></code></pre></div>
<pre><code>## [1] 0.90015</code></pre>
<p>We see that after 100000 simulations with 85 participants, the estimated power is 0.90015 with 85 participants in each group. The analytic solution tells us power is 0.899894. The more simulations you perform, the more accurate the power estimate will be (as we see, 100000 simulations gives very accurate results).</p>
<p>The way you perform the power analysis depends on the software you use. There are excellent software packages for power analysis, such as <a href="https://www.ncss.com/software/pass/">PASS</a> or <a href="https://stats.idre.ucla.edu/sas/seminars/proc-power/">SAS</a>, but these solutions are rather expensive. There are also freeware solutions, such as the widely used <a href="https://gpower.hhu.de">G*Power</a>, <a href="https://wiki.usask.ca/pages/viewpageattachments.action?pageId=420413544">MorePower</a> by Campbell and Thompson, and <a href="https://jakewestfall.shinyapps.io/pangea/">PANGEA</a> by Jake Westfall.
There is also a range of options in R. The default <code>stats</code> package has power functions for <em>t</em>-tests, proportions, and ANOVA, the <code>pwr</code> package has a wider range of options, <code>pwr2ppl</code> by Chris Aberson accompanies his excellent book on power analyses <span class="citation">(Aberson, <a href="#ref-aberson_applied_2019" role="doc-biblioref">2019</a>)</span>, <code>powerlmm</code> by Kristoffer Magnusson performs power analyses for <a href="https://github.com/rpsychologist/powerlmm">two- and three-level linear mixed models</a>, and <a href="https://aaroncaldwell.us/SuperpowerBook/">Superpower</a> created by Aaron Caldwell and myself does power analyses for complex ANOVA designs.</p>
<p>It takes time to learn to use this software correctly. You will need to sit down for a few hours and go through vignettes or read the accompanying publications, before you know what to do. In our online manual for Superpower, we compare Superpower against G*Power, <code>pwr</code>, <code>pwr2ppl</code> and MorePower. Each software package will have slightly different design philosophies. In G*Power you are expected to enter the standardized effect size d, while in MorePower we enter the mean difference and the standard deviation, and in Superpower we need to enter the means and standard deviations for each condition. In general I recommend to always think about the raw pattern of means you expect, before you perform a power analysis. This typically leads to more realistic effect sizes estimates than the use of standardized effect sizes (where researchers all too often ‘expect’ a d = 0.5 just because that is the default value in G*Power).</p>
<div class="figure"><span id="fig:powerex1"></span>
<img src="images/powerex1.png" alt="Example of a power analysis in G\*Power." width="378" />
<p class="caption">
Figure 2.11: Example of a power analysis in G*Power.
</p>
</div>
<div class="figure"><span id="fig:powerex2"></span>
<img src="images/powerex2.png" alt="Example of a power analysis in MorePower." width="222" />
<p class="caption">
Figure 2.12: Example of a power analysis in MorePower.
</p>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="power.html#cb19-1"></a>pwr<span class="op">::</span><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.5</span>, </span>
<span id="cb19-2"><a href="power.html#cb19-2"></a>                <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb19-3"><a href="power.html#cb19-3"></a>                <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb19-4"><a href="power.html#cb19-4"></a>                <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,</span>
<span id="cb19-5"><a href="power.html#cb19-5"></a>                <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 63.76561
##               d = 0.5
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="power.html#cb21-1"></a>design_result &lt;-<span class="st"> </span>Superpower<span class="op">::</span><span class="kw">ANOVA_design</span>(<span class="dt">design =</span> <span class="st">&quot;2b&quot;</span>,</span>
<span id="cb21-2"><a href="power.html#cb21-2"></a>                                          <span class="dt">n =</span> <span class="dv">86</span>,</span>
<span id="cb21-3"><a href="power.html#cb21-3"></a>                                          <span class="dt">mu =</span> <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="dv">0</span>),</span>
<span id="cb21-4"><a href="power.html#cb21-4"></a>                                          <span class="dt">sd =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb21-5"><a href="power.html#cb21-5"></a>                                          <span class="dt">plot =</span> <span class="ot">FALSE</span>)</span>
<span id="cb21-6"><a href="power.html#cb21-6"></a></span>
<span id="cb21-7"><a href="power.html#cb21-7"></a><span class="co"># Plot power curve (from 5 to 200)</span></span>
<span id="cb21-8"><a href="power.html#cb21-8"></a>Superpower<span class="op">::</span><span class="kw">plot_power</span>(design_result, <span class="dt">max_n =</span> <span class="dv">200</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<div class="figure"><span id="fig:powerex3"></span>
<img src="Statistical_Inferences_files/figure-html/powerex3-1.png" alt="Example of a power analysis plot in Superpower." width="672" />
<p class="caption">
Figure 2.13: Example of a power analysis plot in Superpower.
</p>
</div>
</div>
<div id="justifyeffectsize" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Justifying the effect size used in an a-priori power analysis</h3>
<p>One challenge in power analysis is that you never know the true effect size. This leads to the ‘sample size samba’ <span class="citation">(Schulz &amp; Grimes, <a href="#ref-schulz_sample_2005" role="doc-biblioref">2005</a>)</span>. Researchers go back and forth between the effect size they expect, and the sample size they are willing to collect, until they ‘expect’ the effect size that, in an a-priori power analysis, leads to the sample size they are willing to collect. This practice obviously makes a power analysis a useless procedure. If you perform an a-priori power analysis, it is essential that you have a good justification for the effect size you rely on, or the result of the power analysis has no value.</p>
<div id="using-a-smallest-effect-size-of-interest" class="section level4">
<h4><span class="header-section-number">2.3.2.1</span> Using a smallest effect size of interest</h4>
<p>Best practice is to justify an a-priori power analysis based on a smallest effect size of interest. Because the population effect size is always uncertain (indeed, estimating this is typically one of the goals of the study) this means there is considerable uncertainty about the achieved power in any study (see Figure <a href="power.html#fig:power-1">2.2</a>). However, there the smallest effect size of interest is not uncertain. A smallest effect of interest may be subjective (one researcher might find effect sizes smaller than d = 0.3 meaningless, while another researcher might still be interested in effects up to d = 0.1), but it does not have uncertainty. This means that if you enter it in an a-priori power analyses, you will be guaranteed to have the desired power (or higher power) for the smallest effect size you care about. The topic of how to justify a smallest effect size of interest is discussed in a <a href="sesoi.html#sesoi">dedicated chapter</a>.</p>
</div>
<div id="using-an-estimate-of-a-meta-analysis" class="section level4">
<h4><span class="header-section-number">2.3.2.2</span> Using an estimate of a meta-analysis</h4>
<p>As we will see in the chapter on <a href="bias.html#bias">bias</a> it is regrettably not true that effect size estimates from meta-analyses are always accurate. They can be biased, sometimes substantially so. Furthermore, meta-analyses typically have considerable <a href="meta.html#heterogeneity">heterogeneity</a>, which means that the meta-analytic effect size estimate differs for subsets of studies that make up the meta-analysis. So, although it might seem useful to enter a meta-analytic effect size estimate in your power analysis, you need to take great care before doing so.</p>
<p>If you want to enter a meta-analytic effect size estimate in an a-priori power analysis, you need to consider three things. First, the studies included in the meta-analysis should be similar enough to the study you are performing that it is reasonable to expect a similar effect size. In essence, this requires evaluating the generalizability of the effect size estimate to your study. Carefully consider differences between the meta-analysed studies and your study, with respect to the manipulation, the measure, the population, and any other relevant variables. Second, check whether the effect sizes reported in the meta-analysis are homogeneous. If not, and there is considerable heterogeneity in the meta-analysis, it means not all included studies can be expected to have the same true effect size estimate. This is almost always true. Choose the meta-analytic estimate for the subset of studies that most closely represent your planned study (this is why it is important to make sure others can <a href="meta.html#metareporting">reproduce your meta-analysis</a>. Third, the meta-analytic effect size estimate should not be biased. Check the bias detection tests that are reported in the meta-analysis, and consider bias corrected effect size estimates (even though these estimates might still be biased, and not reflect the true population effect size).</p>
<table>
<caption>
<span id="tab:tablemetajust">Table 2.3: </span>Overview of recommendations when justifying the use of a meta-analytic effect size estimate for a power analysis.
</caption>
<thead>
<tr>
<th style="text-align:left;">
What to take into account
</th>
<th style="text-align:left;">
How to take it into account?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Are the studies in the meta-analysis similar?
</td>
<td style="text-align:left;">
Are the studies in the meta-analyses very similar in design, measure, an population to the study you are planning? Evalaute the generalizability of the effect size estimate to your study.
</td>
</tr>
<tr>
<td style="text-align:left;">
Are the studies in the meta-analysis homogeneous?
</td>
<td style="text-align:left;">
Is there heterogeneity in the meta-analysis? If so, use the meta-analytic effect size estimate of the most relevant homogenous subsample.
</td>
</tr>
<tr>
<td style="text-align:left;">
Is the effect size estimate unbiased?
</td>
<td style="text-align:left;">
Did the original study report bias detection tests, and was there bias? If so, it might be wise to use a more conservative effect size estimate, based on bias correction techniques (e.g., PET-PEESE) while acknowledging these corrected effect size estimates might not represent the true meta-analytic effect size estimate.
</td>
</tr>
</tbody>
</table>
</div>
<div id="using-an-estimate-from-a-previous-study" class="section level4">
<h4><span class="header-section-number">2.3.2.3</span> Using an estimate from a previous study</h4>
<p>Statisticians have warned against using effect size estimates from small samples in power analyses. Leon, Davis, and Kraemer <span class="citation">(<a href="#ref-leon_role_2011" role="doc-biblioref">2011</a>)</span> write:</p>
<blockquote>
<p>Contrary to tradition, a pilot study does not provide a meaningful effect size estimate for planning subsequent studies due to the imprecision inherent in data from small samples.</p>
</blockquote>
<p>The two main reasons researchers should be careful when using effect sizes from the published literature in power analyses is that effect size estimates from small studies are inaccurate, and that publication bias inflates effect sizes. Bias can even emerge when researchers do not take an effect size estimate from the literature, but perform the pilot study themselves, due to <strong>follow-up bias</strong> <span class="citation">(Albers &amp; Lakens, <a href="#ref-albers_when_2018" role="doc-biblioref">2018</a>)</span>. Figure <a href="power.html#fig:follow-up-bias">2.14</a> illustrates that for a 3 group ANOVA with 15 participants in each group, only effects with a partial eta squared larger than 0.133 will be statistically significant. But even if researchers are willing to follow up on smaller effect sizes, entering an effect size estimate of <span class="math inline">\(\eta_p^2\)</span> = 0.01 in an a-priori power analysis would require a total sample size of 957 observations for 80% power. If researchers only follow up on pilot studies when they leads to feasible sample sizes, their effect size estimates will be biased.</p>
<div class="figure"><span id="fig:follow-up-bias"></span>
<p class="caption">
Figure 2.14: Distribution of partial eta squared under H0 (grey curve) and a true effect of 0.0588 (black curve).
</p>
<img src="Statistical_Inferences_files/figure-html/follow-up-bias-1.png" alt="Distribution of partial eta squared under H0 (grey curve) and a true effect of 0.0588 (black curve)." width="672"  />
</div>
<p>In essence, the problem illustrated in Figure <a href="power.html#fig:follow-up-bias">2.14</a> is that the effect sizes we end up using four our power analysis do not come from a full <em>f</em>-distribution, but that we ignore small effect sizes, and thus perform power analyses based on a <strong>truncated <em>F</em>-distribution</strong>. It is possible to correct for bias, using some assumptions about bias. For example, imagine we observe a result in the literature for a One-Way ANOVA with 3 conditions, reported as <em>F</em>(2, 42) = 0.017, <span class="math inline">\(\eta_p^2\)</span> = 0.176. Taking this effect size at face value, entering it in an a-priori power analysis would suggest we need to collect 27 observations in each condition. However, using the <code>BUCSS</code> R package <span class="citation">(Anderson et al., <a href="#ref-anderson_sample-size_2017" role="doc-biblioref">2017</a>)</span>, we can perform a power analysis that attempts to correct for bias.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="power.html#cb22-1"></a><span class="kw">library</span>(BUCSS)</span>
<span id="cb22-2"><a href="power.html#cb22-2"></a><span class="kw">ss.power.ba</span>(</span>
<span id="cb22-3"><a href="power.html#cb22-3"></a>  <span class="dt">F.observed =</span> <span class="fl">4.5</span>,</span>
<span id="cb22-4"><a href="power.html#cb22-4"></a>  <span class="dt">N =</span> <span class="dv">45</span>,</span>
<span id="cb22-5"><a href="power.html#cb22-5"></a>  <span class="dt">levels.A =</span> <span class="dv">3</span>,</span>
<span id="cb22-6"><a href="power.html#cb22-6"></a>  <span class="dt">effect =</span> <span class="kw">c</span>(<span class="st">&quot;factor.A&quot;</span>),</span>
<span id="cb22-7"><a href="power.html#cb22-7"></a>  <span class="dt">alpha.prior =</span> <span class="fl">0.05</span>,</span>
<span id="cb22-8"><a href="power.html#cb22-8"></a>  <span class="dt">alpha.planned =</span> <span class="fl">0.05</span>,</span>
<span id="cb22-9"><a href="power.html#cb22-9"></a>  <span class="dt">assurance =</span> <span class="fl">0.5</span>,</span>
<span id="cb22-10"><a href="power.html#cb22-10"></a>  <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb22-11"><a href="power.html#cb22-11"></a>  <span class="dt">step =</span> <span class="fl">0.001</span></span>
<span id="cb22-12"><a href="power.html#cb22-12"></a>)</span></code></pre></div>
<pre><code>## [[1]]
## [1] 73
## 
## [[2]]
## [1] 2.012</code></pre>
<p>This analysis suggests collecting 73 participants in each condition, based on a bias corrected (under a specific model of publication bias assuming only significant effects ( with <em>p</em> &lt; 0.05) being published) non-centrality parameter of 2.012. It is possible that the bias corrected non-centrality parameter is zero, in which case it is not possible to correct for bias (or the true effect size might be 0).</p>
<p>Instead of formally modeling a correction for publication bias, researchers can simply use a more conservative effect size estimate, for example by computing power based on the lower limit of 60% two-sided confidence interval around the effect size estimate <span class="citation">(Perugini et al., <a href="#ref-perugini_safeguard_2014" role="doc-biblioref">2014</a>)</span>, which they refer to as <strong>safeguard power</strong>.</p>
<p>Both these approaches lead to a more conservative power analysis, but not necessarily a more accurate power analysis. It is simply not possible to perform an accurate power analysis on the basis of an effect size estimate from a study that might be biased and had a small sample size.</p>
<p>A sample size from a single study can be used if two conditions are met. First, there was a low risk of bias (e.g., the effect size estimate comes from a Registered Report, or from an analysis which results would not have impacted the likelihood of publication). Second, the sample size is large enough to yield relatively accurate effect size estimate, based on the width of a 95% CI around the observed effect size estimate. There is always uncertainty around the effect size estimate, and entering the upper and lower limit of the 95% CI around the effect size estimate might be educational about the consequences of the uncertainty that is present for an a-priori power analysis.</p>
<table>
<caption>
<span id="tab:table-es-just">Table 2.4: </span>Overview of recommendations when justifying the use of an effect size estimate from a single study.
</caption>
<thead>
<tr>
<th style="text-align:left;">
What to take into account
</th>
<th style="text-align:left;">
How to take it into account?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Is there a risk of bias?
</td>
<td style="text-align:left;">
Evaluate the possibility that you would not have used, or had access to, the effect size estimate if had been smaller. Examine the difference when entering the reported, and a bias corrected, effect sizes estimate in a power analysis.
</td>
</tr>
<tr>
<td style="text-align:left;">
How large is the uncertainty?
</td>
<td style="text-align:left;">
Studies with a small number of observations have large uncertainty. Consider the possibility of using a more conservative effect sizes estimate to reduce the possibility of an underpowered study for the true effect size (such as a safeguard power analysis).
</td>
</tr>
</tbody>
</table>
</div>
<div id="using-a-heuristic" class="section level4">
<h4><span class="header-section-number">2.3.2.4</span> Using a heuristic</h4>
<p>The most commonly entered effect size estimate in an a-priori power analysis for an independent <em>t</em>-test is d = 0.5. The reason is that it is the default in G*Power. It is also an effect size that Cohen <span class="citation">(<a href="#ref-cohen_statistical_1988" role="doc-biblioref">1988</a>)</span> referred to as a ‘medium’ effect size, which seems less pretentious than expecting a ‘large’ effect size (d = 0.8) and leads to a required sample size that is substantially more manageable than when entering a ‘small’ effect size (d = 0.2). Cohen would probably not have chosen d = 0.5 as a default option for a power analysis tool designed for psychologists, as he wrote (1988, p. 13):</p>
<blockquote>
<p>Many effects sought in personality, social, and clinical-psychological research are likely to be small effects as here defined, both because of the attenutation in validity of the measures employed and the subtlety of the issues frequently involved.</p>
</blockquote>
<p>The large variety in research topics in psychology means that any ‘default’ or ‘heuristic’ you use in an a-priori power analysis is wrong, and more importantly, it is likely to be more substantially wrong than using any of the other strategies outlines here. Cohen’s benchmarks should not be used in a-priori power analysis <span class="citation">(Correll et al., <a href="#ref-correll_avoid_2020" role="doc-biblioref">2020</a>)</span>.</p>
<p>Some researchers have wondered what a better default would be, if researchers have no other basis to decide upon an effect size for an a-priori power analysis. For example, sometimes it is recommended to perform a power analysis based on an average effect size in psychology. For example, Brysbaert <span class="citation">(<a href="#ref-brysbaert_how_2019-1" role="doc-biblioref">2019</a>)</span> recommends d = 0.4 as a default, which is approximately the average effect size in meta-meta-analyses, analysing effect sizes in entire scientific disciplines. However, such meta-analytic effect sizes estimated might be inflated due to publication bias, and there is huge heterogeneity in each field, so the average will often not be close to the effect size in the research line your are performing. As such, the use of such estimates is also not recommended.</p>
</div>
</div>
<div id="justifying-the-error-rates-used-in-an-a-priori-power-analysis" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Justifying the error rates used in an a-priori power analysis</h3>
<p>TOO BE COMPLETED</p>
</div>
<div id="some-advice-when-using-gpower" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Some advice when using G*Power</h3>
<p>G*Power is one of the most widely used software tools for power analysis <span class="citation">(Bakker et al., <a href="#ref-bakker_recommendations_2020" role="doc-biblioref">2020</a>)</span>. The option for power analysis for a Pearson’s correlation coefficient is under the Exact test family (Correlation: Bivariate normal model). The “Correlation: Point biserial model” option under the <em>t</em>-tests family is for correlations where one variable is dichotomous. The difference is small, but the required sample size is typically a few observations larger for Pearson’s correlation coefficient.</p>
<div class="figure"><span id="fig:gpowcor"></span>
<img src="images/gpowcor.png" alt="The options for a power analysis for Pearson's correlation(above) and the point biserial correlation (when one variable is dichotomous)." width="377" />
<p class="caption">
Figure 2.15: The options for a power analysis for Pearson’s correlation(above) and the point biserial correlation (when one variable is dichotomous).
</p>
</div>
<p>Although the effect size for an independent <em>t</em>-test and dependent <em>t</em>-test are often both referred to as Cohen’s d, they differ, and are calculated in different ways. Cohen himself distinguished between <span class="math inline">\(d_s\)</span> and <span class="math inline">\(d_z\)</span> <span class="citation">(Lakens, <a href="#ref-lakens_calculating_2013" role="doc-biblioref">2013</a>)</span>. You should not enter Cohen’s d for a power analysis for a dependent <em>t</em>-test (nor should you directly compared Cohen’s d from a between design with Cohen’s d for a within design, nor should you use the benchmarks Cohen provided for a small (0.2), medium (0.5), and large (0.8) effect be used for Cohen’s <span class="math inline">\(d_z\)</span>). Make sure you are entering the correct effect size. Cohen’s <span class="math inline">\(d_z\)</span> can be calculated from the <em>t</em>-value for a dependent <em>t</em>-test and the sample size as follows:</p>
<p><span class="math display">\[d_z = {\frac{t}{\sqrt{n}}} \]</span></p>
<div class="figure"><span id="fig:gpowdzd"></span>
<img src="images/gpowdzd.png" alt="Power for a dependent and independent *t*-test require entering Cohen's dz and d, respectively." width="377" />
<p class="caption">
Figure 2.16: Power for a dependent and independent <em>t</em>-test require entering Cohen’s dz and d, respectively.
</p>
</div>
<p>The third issue that researchers often miss is that G*Power has a very unfortunate default setting for power analyses for within subject ANOVA tests. In Figure <a href="power.html#fig:gpowdwithin2">2.17</a> we see on the left how we can directly calculate Cohen’s <span class="math inline">\(f\)</span> (the effect size one needs to enter for ANOVA power analyses) from partial eta squared. A medium effect size for <span class="math inline">\(\eta^2_p\)</span> of 0.588 equals a Cohen’s <span class="math inline">\(f\)</span> of 0.25. If we specify an expected correlation between dependent variables of 0.8, have 3 repeated measurements, one condition, and want to achieve 95% power with an alpha level of 0.05, we need a sample size of 19. However, if out value for <span class="math inline">\(\eta^2_p\)</span> comes from the scientific literature or statistical software such as SPSS, this effect size measure already has the correlation between observation incorporated. If we would simply enter it in G*Power, we take into account the correlation twice, which leads to a massively smaller sample size. Instead, we need to click on the “Options” button and check the radiobutton before “As in SPSS”. We see that “Effect size f” changes into “Effect size f(U)”, and the box “Corr among rep measures” has disappeared on the right. This is because the correlation no longer needs to be entered separately - it is already taken into account in the <span class="math inline">\(\eta^2_p\)</span> as SPSS computes it. Most importantly, we now see that the sample size we need to achieve 95% power has changed to 127. This is a big difference, and I have seen people make this mistake very often. If you use G*power for power analyses for ANOVA designs, I recommend always double checking the Options setting (and maybe repeat your analysis in software such as Superpower just to double check).</p>
<div class="figure"><span id="fig:gpowdwithin2"></span>
<img src="images/gpowwithin2.png" alt="Power analysis for repeated ANOVA in G\*Power by default expects a partial eta squared effect size that does not take the correlation between measurements into account." width="956" />
<p class="caption">
Figure 2.17: Power analysis for repeated ANOVA in G*Power by default expects a partial eta squared effect size that does not take the correlation between measurements into account.
</p>
</div>
</div>
<div id="powerforabsence" class="section level3">
<h3><span class="header-section-number">2.3.5</span> A-priori power analysis for the absence of an effect</h3>
<p>It is</p>
</div>
<div id="reporting-an-a-priori-power-analysis." class="section level3">
<h3><span class="header-section-number">2.3.6</span> Reporting an a-priori power analysis.</h3>
<p>As with all the analyses you rely on in your work, make sure the power analysis is computationally reproducible. If you performed power analyses in R, you can store the script. In G*Power, you can save the several power analyses you performed consecutively in the app under the ‘protocol of power analysis’ tab by saving them as a .rtf file or printing them as a pdf file.</p>
<div class="figure"><span id="fig:gpowprotocol"></span>
<img src="images/gpowprotocol.png" alt="G\*Power allows you to easily save all details about the power analysis you performed." width="375" />
<p class="caption">
Figure 2.18: G*Power allows you to easily save all details about the power analysis you performed.
</p>
</div>
<p>If you use the <a href="https://arcstats.io/shiny/anova-exact/">Superpower Shiny app</a> for more complex ANOVA designs, you can print a pdf file with all detailed about the power analysis you performed. Sharing the code or a printout of the power analysis will capture all required information about the power analysis you performed, which is often preferable over attempting to communicate all this information verbally.</p>
<div class="figure"><span id="fig:superpowerreport"></span>
<img src="images/superpowerreport.png" alt="Superpower allows you to print a report with all information about the power analysis you performed." width="738" />
<p class="caption">
Figure 2.19: Superpower allows you to print a report with all information about the power analysis you performed.
</p>
</div>
<p>Providing a reproducible report is sufficient to clarify the power calculation, but not the reasons behind the power calculations. Your decision for the desired Type 1 and Type 2 error rate needs a justification, and most importantly, the effect size you have powered for needs to be justified. If your effect size estimate is based on the existing literature, provide a full citation, and preferably a direct quote from the article. If your effect size is based on an empirical estimate from the scientific literature, you will need to address 1) uncertainty, and 2) bias <span class="citation">(Anderson et al., <a href="#ref-anderson_sample-size_2017" role="doc-biblioref">2017</a>; Taylor &amp; Muller, <a href="#ref-taylor_bias_1996" role="doc-biblioref">1996</a>)</span>. If your effect size is based on a smallest effect size of interest, this value should not just be stated, but <a href="equivalencetest.html#justifysesoi">justified</a> (e.g., based on theoretical predictions, practical implications, or effect sizes observed or detectable in the literature).</p>
<table>
<caption>
<span id="tab:table-pow-rec-2">Table 2.5: </span>Overview of recommendations when reporting an a-prior power analysis.
</caption>
<thead>
<tr>
<th style="text-align:left;">
What to address?
</th>
<th style="text-align:left;">
How to address it?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
List all primary analyses you plan to do.
</td>
<td style="text-align:left;">
Following JARS guidelines, specify all primary analyses for which you want to control Type 1 and Type 2 error rates
</td>
</tr>
<tr>
<td style="text-align:left;">
Specify the alpha level for each analysis
</td>
<td style="text-align:left;">
List and justify the chosen alpha level for each analysis. Make sure to correct for multiple comparisons where needed.
</td>
</tr>
<tr>
<td style="text-align:left;">
What is the desired power?
</td>
<td style="text-align:left;">
List and justify the desired power for each analysis
</td>
</tr>
<tr>
<td style="text-align:left;">
For each power analysis, specify the effect size metric, the effect size, and the justification for powering for the effect size.
</td>
<td style="text-align:left;">
Report the effect size metric (e.g., Cohen’s <span class="math inline">\(d_z\)</span>, Cohen’s f), the effect size (e.g., 0.3). and the justification for the effect size, whether it is based on a smallest effect size of interest, a meta-analytic effect size estimate, or the estimate of a single previous study.
</td>
</tr>
<tr>
<td style="text-align:left;">
Make sure the power analysis is reproducible.
</td>
<td style="text-align:left;">
Include the code used to run the power analysis, or print a report containing the details about the power analyses you performed.
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="compromisepower" class="section level2">
<h2><span class="header-section-number">2.4</span> Compromise power analysis</h2>
<p>Sometimes researchers are brave enough <em>not</em> to fix their alpha level to 0.05. There are two situations where it is sensible to use a different alpha level, even if you want to follow current conventions. The first situation is when you are fortunate enough to be able to collect so many observations that the statistical power for your test is very high. For example, imagine you have access to 2000 employees who are all required to answer questions during a yearly evaluation in a company where you are testing an intervention that should reduce subjectively reported stress levels. You are quite confident that an effect smaller than d = 0.2 is not large enough to be subjectively noticeable for individuals <span class="citation">(Jaeschke et al., <a href="#ref-jaeschke_measurement_1989" role="doc-biblioref">1989</a>)</span>. With an alpha level of 0.05 you would have a statistical power of 0.994, or a Type 2 error rate of 0.006. This means that for a smallest effect size of interest of d = 0.2 we are 8.3 times more likely to make a Type 1 error than a Type 2 error.</p>
<p>This is a reversal of the normal balance of Type 1 and Type 2 error rates, where the minimum desired power is 0.8, and a Type 1 error (0.05) is 4 times as unlikely as a Type 2 error (20%). The default use of 80% power (or a 20% Type 2, or beta (<span class="math inline">\(\beta\)</span>) error) is based on nothing more than a personal preference by <span class="citation">Cohen (<a href="#ref-cohen_statistical_1988" role="doc-biblioref">1988</a>)</span>, who writes:</p>
<blockquote>
<p>It is proposed here as a convention that, when the investigator has no other basis for setting the desired power value, the value .80 be used. This means that <span class="math inline">\(\beta\)</span> is set at .20. This arbitrary but reasonable value is offered for several reasons (Cohen, 1965, pp. 98-99). The chief among them takes into consideration the implicit convention for <span class="math inline">\(\alpha\)</span> of .05. The <span class="math inline">\(\beta\)</span> of .20 is chosen with the idea that the general relative seriousness of these two kinds of errors is of the order of .20/.05, i.e., that Type I errors are of the order of four times as serious as Type II errors. This .80 desired power convention is offered with the hope that it will be ignored whenever an investigator can find a basis in his substantive concerns in his specific research investigation to choose a value ad hoc.</p>
</blockquote>
<p>We see that conventions are built on conventions: the norm to aim for 80% power is built on the norm to set the alpha level at 5%. What we should take away from Cohen is not that we should aim for 90% power, but that we should justify our error rates based on the relative seriousness of each error. If our Type 1 error is 4 times as serious as a Type 2 error, and our Type 2 error is very low for all effects we care about, we should adjust our Type 1 error rate <span class="citation">(Erdfelder et al., <a href="#ref-erdfelder_gpower_1996" role="doc-biblioref">1996</a>)</span>. G*Power allows us to perform such a <strong>compromise power analysis</strong>, as illustrated in In Figure <a href="power.html#fig:gpowcompromise">2.20</a></p>
<div class="figure"><span id="fig:gpowcompromise"></span>
<img src="images/compromise1.png" alt="Compromise power analysis in G\*Power." width="378" />
<p class="caption">
Figure 2.20: Compromise power analysis in G*Power.
</p>
</div>
<p>Of course you do not need to follow conventions. If you believe Type 1 errors and Type 2 errors are equally problematic (which is often at least as defensible as arguing a Type 1 error is exactly 4 times as bad as a Type 2 error) you would weigh both types of errors equally, and use α = 0.01785.</p>
<p>As Faul, Erdfelder, Lang, and Buchner <span class="citation">(<a href="#ref-faul_gpower_2007" role="doc-biblioref">2007</a>)</span> write:</p>
<blockquote>
<p>Of course, compromise power analyses can easily result in unconventional significance levels greater than <span class="math inline">\(\alpha\)</span> = .05 (in the case of small samples or effect sizes) or less than <span class="math inline">\(\alpha\)</span> = .001 (in the case of large samples or effect sizes). However, we believe that the benefit of balanced Type I and Type II error risks often offsets the costs of violating significance level conventions</p>
</blockquote>
<p>This brings us to the second situation where we want to deviate from α = 0.05, while still following the underlying convention proposed by Cohen to weigh a Type 1 error 4 times as serious as a Type 2 error: The situation where power is lower than 80%. Although it is highly undesireable to make decisions when error rates are so very high, if one finds oneself in a situation where a decision must be made based on little data, <span class="citation">Winer (<a href="#ref-winer_statistical_1962" role="doc-biblioref">1962</a>)</span> writes:</p>
<blockquote>
<p>The frequent use of the .05 and .01 levels of significance is a matter of convention having little scientific or logical basis. When the power of tests is likely to be low under these levels of significance, and when Type 1 and Type 2 errors are of approximately equal importance, the .30 and .20 levels of significance may be more appropriate than the .05 and .01 levels.</p>
</blockquote>
<p>If we plan to perform a two-sided <em>t</em>-test, and can collect at most 50 observations in each independent group, and we want to have 90% power, and expect a population effect size of 0.5, we would have 70% power if we set our alpha level to 0.05. If we can not increase our sample size beyond 50 per group, and we need to make a decision based on the data we will collect, we could set our alpha level to 0.065 to have a Type 1 error rate 4 times as high as our Type 2 error rate (0.262). Alternatively, we can choose to weigh both types of error equally, and set the alpha level to 0.149. The choice of α and β can be further improved by taking priors probabilities of H0 and H1 into account <span class="citation">(Miller &amp; Ulrich, <a href="#ref-miller_quest_2019" role="doc-biblioref">2019</a>)</span> In the end, as Neyman and Pearson <span class="citation">Neyman &amp; Pearson (<a href="#ref-neyman_problem_1933" role="doc-biblioref">1933</a>)</span> write:</p>
<blockquote>
<p>The use of these statistical tools in any given case, in determining just how the balance should be struck, must be left to the investigator.</p>
</blockquote>
<div id="reporting-a-compromise-power-analysis" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Reporting a compromise power analysis</h3>
<p>A compromise power analysis requires you to specify the sample size. This sample size itself requires a justification, so a compromise power analysis will typically be performed together with a feasibility justification for a sample size. It is especially important to perform a compromise power analysis if your feasibility justification is strongly based on the fact that a decision is made, in which case you will want to think carefully about the Type 1 and Type 2 error rates you are willing to accept. However, a compromise power analysis also makes sense if the sample size is very large, but you did not have the freedom to set the sample size. This might happen if, for example, your research is part of a larger international survey and the sample size is based on other research questions.</p>
<p>Furthermore, a compromise power analysis still needs a <a href="power.html#justifyeffectsize">justification for the effect size</a>. After all, it computes the levels for the Type 1 and Type 2 error rate, based on a specific sample size, effect size, and relative seriousness of both Types of errors.</p>
<table>
<caption>
<span id="tab:table-compromise-just">Table 2.6: </span>Overview of recommendations when justifying error rates based on a compromise power analysis.
</caption>
<thead>
<tr>
<th style="text-align:left;">
What to take into account
</th>
<th style="text-align:left;">
How to take it into account?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
What is the justification for the sample size?
</td>
<td style="text-align:left;">
Specify the justification for the sample size, for example based on feasibility, or that the sample size was fixed based on reasons outside of your control
</td>
</tr>
<tr>
<td style="text-align:left;">
What is the justification for the effect size?
</td>
<td style="text-align:left;">
Justify the effect size, whether it is based on a smallest effect size of interest, a meta-analytic effect size estimate, or the estimate of a single previous study.
</td>
</tr>
<tr>
<td style="text-align:left;">
What is the relative seriousness of Type 1 vs Type 2 error rates?
</td>
<td style="text-align:left;">
How much more serious are the consequences of making one type of error, compared to the other type of error? Cohen believed a Type 1 error was 4 times as serious as a Type 2 error, but both types of errors can also be equally serious, or a Type 2 error can be more problematic than a Type 1 error.
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="observedpower" class="section level2">
<h2><span class="header-section-number">2.5</span> Observed (post-hoc) power analysis</h2>
<p>Observed power (or post-hoc power) is the statistical power of the test you have performed, based on the effect size estimate from your data. <strong>Observed power</strong> differs from the <strong>true power</strong> of your test, because the true power depends on the (true)unknown) population effect size, while observed power is computed based on the (unlikely) assumption that the effect size you observed in your sample is the true effect size. SPSS (which still hasn’t included useful statistics such as effect sizes for <em>t</em>-tests) provides users with the option to report observed power by clicking a checkbox. You should never calculate the observed power. Observed power, computed based on the observed effect size, is a useless statistical concept. Despite this fact, editors and reviewers often ask authors to perform post-hoc power analysis to make a statement about the statistical power a study had. You should never comply with this request. The correct approach to evaluate the statistical power of a study after the data is collected is a <a href="power.html#sensitivitypower">sensitivity power analysis</a>.</p>
<p>Observed (or post-hoc) power and <em>p</em>-values are directly related <span class="citation">(Hoenig &amp; Heisey, <a href="#ref-hoenig_abuse_2001" role="doc-biblioref">2001</a>)</span>. For a <em>Z</em>-test where the <em>p</em>-value is exactly 0.05, the perfectly symmetric alternative distribution falls exactly on top of the critical value. This means that half the distribution falls to the right of the critical value, and half falls on the left, and we have exactly 50% power.</p>
<!-- ```{r obs-power-plot-1, echo = FALSE, fig.width = 8, fig.height = 8, fig.cap="Relationship between p-values and power for a Z-test."} -->
<!-- # For simplicity, take a one-sided test -->
<!-- # compute z value from p: -->
<!-- # p_val = 0.05 -->
<!-- # z <- qnorm(1-p_val) -->
<!-- # z -->
<!-- #  -->
<!-- # # compute p-value from z -->
<!-- # 1-pnorm(z) -->
<!-- # computing the Type 1 error rate: -->
<!-- # old, two-sided: 1-pnorm(q = 1.959964) + pnorm(q = -1.959964) -->
<!-- # Moving the mean from 0.  -->
<!-- # Because the normal distribution is symmetric, if we observe a p-value on top of the critical value (p = 0.05) we have 50% power. -->
<!-- # pnorm(q = 1.644854, mean = 1.644854) -->
<!-- # We can plot this across a range of observe p-values -->
<!-- plot_obs_pow <- (function(alpha_level, p_val) { -->
<!--   1 - pnorm(q = qnorm(1-alpha_level), mean = qnorm(1-p_val)) -->
<!-- }) -->
<!-- par(bg = "aliceblue", pty = "s") -->
<!-- plot(-10, -->
<!--   xlab = "p-value", ylab = "Observed power", axes = FALSE, -->
<!--   main = substitute(paste("Relationship between p-value and observed power")), xlim = c(0, 1), ylim = c(0, 1) -->
<!-- ) -->
<!-- abline(v = seq(0, 1, 0.1), h = seq(0, 1, 0.1), col = "lightgray", lty = 1) -->
<!-- axis(side = 1, at = seq(0, 1, 0.1), labels = seq(0, 1, 0.1)) -->
<!-- axis(side = 2, at = seq(0, 1, 0.1), labels = seq(0, 1, 0.1)) -->
<!-- curve(plot_obs_pow(alpha_level = 0.05, p_val = x), 0, 1, add = TRUE, lwd = 2) -->
<!-- points(x = 0.05, y = 0.5, cex = 2, pch = 19, col = rgb(1, 0, 0, 0.5)) -->
<!-- abline(v = 0.05, h = 0.5, col = rgb(1, 0, 0, 0.5), lty = 1) -->
<!-- ``` -->
<p>For an independent <em>t</em>-test the noncentral <em>t</em>-distribution is not perfectly symmetric. We can compute observe power in R based on the formula below, where <code>alpha_level</code> is the alpha level, <code>n</code>is the sample size in each group, and <code>p_val</code> is the observed <em>p</em>-value. In Figure <a href="#fig:obs-power-plot-2"><strong>??</strong></a> we see that for a <em>p</em> = 0.05 observed power is ever so slightly larger than 50%, but the observed power value is very close.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="power.html#cb24-1"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pt</span>(<span class="dt">q =</span> <span class="kw">qt</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>alpha_level<span class="op">/</span><span class="dv">2</span>, <span class="dv">2</span> <span class="op">*</span><span class="st"> </span>n <span class="op">-</span><span class="st"> </span><span class="dv">2</span>), </span>
<span id="cb24-2"><a href="power.html#cb24-2"></a>       <span class="dt">df =</span> <span class="dv">2</span> <span class="op">*</span><span class="st"> </span>n <span class="op">-</span><span class="st"> </span><span class="dv">2</span>, </span>
<span id="cb24-3"><a href="power.html#cb24-3"></a>       <span class="dt">ncp =</span> <span class="kw">qt</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>p_val<span class="op">/</span><span class="dv">2</span>, <span class="dv">2</span> <span class="op">*</span><span class="st"> </span>n <span class="op">-</span><span class="st"> </span><span class="dv">2</span>))</span></code></pre></div>
<p>Plotting observe power for the <em>p</em>-value across the range from 0 to 1, we see that observed power is completely determined, and provides no additional value beyond, reporting the <em>p</em>-value. If your <em>p</em>-value is non-significant, observed power will be less than approximately 50% in a <em>Z</em>-test and <em>t</em>-test. As Lenth <span class="citation">(<a href="#ref-lenth_post_2007" role="doc-biblioref">2007</a>)</span> shows, observed power is also completely determined by the observed <em>p</em>-value for <em>F</em>-tests, although the relationship between <em>p</em> = 0.05 and 50% power no longer holds.</p>
<div class="figure"><span id="fig:unnamed-chunk-9"></span>
<img src="Statistical_Inferences_files/figure-html/unnamed-chunk-9-1.png" alt="Relationship between p-values and power for an independent t-test." width="768" />
<p class="caption">
Figure 2.21: Relationship between p-values and power for an independent t-test.
</p>
</div>
<div id="what-to-do-if-your-editor-asks-for-post-hoc-power" class="section level3">
<h3><span class="header-section-number">2.5.1</span> What to do if your editor asks for post-hoc power?</h3>
<p>Editors sometimes ask researchers to report post-hoc power analyses when authors report a test result of <em>p</em> &gt; 0.05, and when authors want to conclude there is no effect. In such situations, editors would like to distinguish between true negatives (concluding there is no effect, when there is no effect) and false negatives (concluding there is no effect, when there actually is an effect, or a Type 2 error). As the preceding explanation of post-hoc power illustrates, reporting post-hoc power is nothing more than a different way of reporting the <em>p</em>-value, and will therefore not answer the question editors want to know <span class="citation">(Hoenig &amp; Heisey, <a href="#ref-hoenig_abuse_2001" role="doc-biblioref">2001</a>; Lenth, <a href="#ref-lenth_post_2007" role="doc-biblioref">2007</a>; Yuan &amp; Maxwell, <a href="#ref-yuan_post_2005" role="doc-biblioref">2005</a>)</span>.</p>
<p>What you should do instead is report a <a href="power.html#sensitivitypower">sensitivity power analysis</a>, preferably by plotting power across a wide range of possible true effect sizes. Many of the recommendations in Table <a href="power.html#tab:table-pow-rec">2.2</a> apply if one wants to evaluate power after the data has been collected. The best solution is, not surprisingly, to design a study that will yield informative results regardless of whether the alternative hypothesis is true or the null hypothesis is true, by performing an a-priori power analysis both for the NHST and for an equivalence test.</p>
</div>
</div>
<div id="designing-efficient-studies" class="section level2">
<h2><span class="header-section-number">2.6</span> Designing efficient studies</h2>
<p>So far, we have focused on how to perform a power analysis based on assumptions about what the true effect size is. Although the true effect size is unknown, there is a true effect size in the population, and it has an impact on our statistical power. It is therefore useful to consider how we can design studies that will be optimally efficient to answer our research question. There are some ways in which we can increase the power of our test that are worth exploring.</p>
<div id="use-directional-tests-where-relevant." class="section level3">
<h3><span class="header-section-number">2.6.1</span> Use directional tests where relevant.</h3>
<p>Researchers often make directional predictions, such as ‘we predict X is larger than Y’. The statistical test that logically follows from this prediction is a directional (or one-sided) <em>t</em>-test. A directional test moves the Type 1 error rate to one side of the tail, which lowers the critical value, and requires less observations to achieve the same statistical power. Although there is some discussion about when directional tests are appropriate, they are perfectly defensible from a Neyman-Pearson perspective on hypothesis testing. However, there might be situations where you do not want to ask a directional test. Sometimes it might be important for an effect opposite to your prediction to also reach statistical significance. For example, when you are evaluating a recently introduced educational intervention, and you predict the intervention will increase the performence of students, you might want to remain open to the possibility that students perform worse, to be able to recommend abandoning the new intervention. It is also possible to distribute the error rate in a ‘lop-sided’ manner, for example assigning a stricter error rate to effects in the negative than in the positive direction <span class="citation">(Rice &amp; Gaines, <a href="#ref-rice_heads_1994" role="doc-biblioref">1994</a>)</span>.</p>
</div>
<div id="use-sequential-analysis-whenever-possible" class="section level3">
<h3><span class="header-section-number">2.6.2</span> Use sequential analysis whenever possible</h3>
<p><a href="##sequential">Sequential analyses</a> greatly increase the efficiency of tests <span class="citation">(Lakens, <a href="#ref-lakens_performing_2014" role="doc-biblioref">2014</a>)</span>. For any of the ways in which you determined the sample size of your study that have been discussed here, a sequential design, where error rates are controlled as you repeatedly analyze the data that comes in, will on average decrease the sample size you will collect.</p>
</div>
<div id="increase-your-alpha-level" class="section level3">
<h3><span class="header-section-number">2.6.3</span> Increase your alpha level</h3>
<p>As explained in the section on <a href="power.html#compromisepower">compromise power analysis</a> balancing error rates by increasing your alpha level also increases the statistical power (or reduces the Type 2 error rate). Obviously this comes at an increased probability of fooling yourself. The risk of doing so should be carefully weighed, which typically requires taking into account the prior probability that the null-hypothesis is true <span class="citation">(Miller &amp; Ulrich, <a href="#ref-miller_quest_2019" role="doc-biblioref">2019</a>)</span>. If you <em>have</em> to make a decision, and the data you can feasibly collect is limited, a compromise power analysis is justified, and so is increasing the alpha level.</p>
</div>
<div id="use-within-designs-where-possible" class="section level3">
<h3><span class="header-section-number">2.6.4</span> Use within designs where possible</h3>
<p>One widely recommended approach to increase power is using a within subject design. Indeed, you need fewer observations to detect a mean difference between two conditions in a within-subjects design (in a dependent <em>t</em>-test) than in a between-subjects design (in an independent t-test). The reason is straightforward, but not always explained, and even less often expressed in the easy equation below. The sample size needed in within-designs (NW) relative to the sample needed in between-designs (NB), assuming normal distributions, is (from Maxwell &amp; Delaney, 2004, p. 561, formula 45):</p>
<p>NW = NB (1-ρ)/2</p>
<p>The “/2” part of the equation is due to the fact that in a two-condition within design every participant provides two data-points. The extent to which this reduces the sample size compared to a between-subject design depends on the correlation between the two dependent variables, as indicated by the (1-ρ) part of the equation. If the correlation is 0, a within-subject design simply needs half as many observations as a between-subject design (e.g., 64 instead 128 observations). The higher the correlation, the larger the relative benefit of within designs, and whenever the correlation is negative (up to -1) the relative benefit disappears. Note than when the correlation is -1, you need 128 observations in a within-design and 128 observations in a between-design, but in a within-design you will need to collect two measurements from each participant, making a within design more work than a between-design. However, negative correlations between dependent variables in psychology are rare, and perfectly negative correlations will probably never occur.</p>
<p>So what does the correlation do so that it increases the power of within designs, or reduces the number of observations you need? Let’s see what effect the correlation has on power by simulating and plotting correlated data. In the R script below, I’m simulating two measurements of IQ scores with a specific sample size (i.e., 10000), mean (i.e., 100 vs 106), standard deviation (i.e., 15), and correlation between the two measurements. The script generates three plots.</p>
<p>We will start with a simulation where the correlation between measurements is 0. First, we see the two normally distributed IQ measurements, with means of 100 and 106, and standard deviations of 15 (due to the large sample size, the numbers equal the input in the simulation, although small variation might still occur).</p>
<div class="figure"><span id="fig:plot-1"></span>
<img src="Statistical_Inferences_files/figure-html/plot-1-1.png" alt="Distributions of two dependent groups with means 100 and 106 and a standard deviation of 15." width="672" />
<p class="caption">
Figure 2.22: Distributions of two dependent groups with means 100 and 106 and a standard deviation of 15.
</p>
</div>
In the scatter plot, we can see that the correlation between the measurements is indeed 0.
<div class="figure"><span id="fig:plot-2"></span>
<img src="Statistical_Inferences_files/figure-html/plot-2-1.png" alt="Correlation between two dependent groups." width="672" />
<p class="caption">
Figure 2.23: Correlation between two dependent groups.
</p>
</div>
<p>Now, let’s look at the distribution of the mean differences. The mean difference is -6 (in line with the simulation settings), and the standard deviation is 21. This is also as expected. The standard deviation of the difference scores is √2 times as large as the standard deviation in each measurement, and indeed, 15*√2 = 21.21, which is rounded to 21. This situation where the correlation between measurements is zero equals the situation in an independent t-test, where the correlation between measurements is not taken into account.</p>
<div class="figure"><span id="fig:plot-3"></span>
<img src="Statistical_Inferences_files/figure-html/plot-3-1.png" alt="Distributions of difference scores between two dependent groups." width="672" />
<p class="caption">
Figure 2.24: Distributions of difference scores between two dependent groups.
</p>
</div>
<p>Now let’s increase the correlation between dependent variables to 0.7.</p>
<p>Nothing has changed when we plot the means:</p>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  x and y
## t = -27.932, df = 19998, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -6.271842 -5.449339
## sample estimates:
## mean of x mean of y 
##  100.1621  106.0227</code></pre>
<div class="figure"><span id="fig:plot-4"></span>
<img src="Statistical_Inferences_files/figure-html/plot-4-1.png" alt="Distributions of two independent groups with means 100 and 106 and a standard deviation of 15." width="672" />
<p class="caption">
Figure 2.25: Distributions of two independent groups with means 100 and 106 and a standard deviation of 15.
</p>
</div>
<p>The correlation between measurements is now strongly positive:</p>
<div class="figure"><span id="fig:plot-5"></span>
<img src="Statistical_Inferences_files/figure-html/plot-5-1.png" alt="Correlation between two dependent groups." width="672" />
<p class="caption">
Figure 2.26: Correlation between two dependent groups.
</p>
</div>
<p>The important difference lies in the standard deviation of the difference scores. The SD = 11 instead of 21 in the simulation above. Because the standardized effect size is the difference divided by the standard deviation, the effect size (Cohen’s dz in within designs) is larger in this test than in the test above.</p>
<div class="figure"><span id="fig:plot-6"></span>
<img src="Statistical_Inferences_files/figure-html/plot-6-1.png" alt="Difference scores between two dependent groups." width="672" />
<p class="caption">
Figure 2.27: Difference scores between two dependent groups.
</p>
</div>
<p>if you set the correlation to a negative value, the standard deviation of the difference scores actually increases.</p>
<p>I like to think of dependent variables in within-designs as dance partners. If they are well-coordinated (or highly correlated), one person steps to the left, and the other person steps to the left the same distance. If there is no coordination (or no correlation), when one dance partner steps to the left, the other dance partner is just as likely to move to the wrong direction as to the right direction. Such a dance couple will take up a lot more space on the dance floor.</p>
<p>You see that the correlation between dependent variables is an important aspect of within designs. I recommend explicitly reporting the correlation between dependent variables in within designs (e.g., participants responded significantly slower (M = 390, SD = 44) when they used their feet than when they used their hands (M = 371, SD = 44, r = .953), t(17) = 5.98, p &lt; 0.001, Hedges’ g = 0.43, Mdiff = 19, 95% CI [12; 26]).</p>
<p>Since most dependent variables in within designs in psychology are positively correlated, within designs will greatly increase the power you can achieve given the sample size you have available. Use within-designs when possible, but weigh the benefits of higher power against the downsides of order effects or carryover effects that might be problematic in a within-subject design. Maxwell and Delaney’s book (Chapter 11) has a good discussion of this topic.</p>
<!-- You can use this Shiny app to play around with different means, sd's, and correlations, and see the effect of the distribution of the difference scores. -->
<!-- ```{r shiny2, echo=F} -->
<!-- knitr::include_app('http://shiny.ieis.tue.nl/within_between/', height = '4000px') -->
<!-- ``` -->
</div>
<div id="remove-statistical-variation-where-possible" class="section level3">
<h3><span class="header-section-number">2.6.5</span> Remove statistical variation where possible</h3>
<p>The smaller the variation, the larger the standardized effect size (because we are dividing the raw effect by a smaller denominator) and thus the higher the power given the same number of observations. For an overview of different approaches to reduce the variance, see <span class="citation">Allison et al. (<a href="#ref-allison_power_1997" role="doc-biblioref">1997</a>)</span>. They discuss:</p>
<ol style="list-style-type: decimal">
<li>Better ways to screen participants for studies where participants need to be screened before participation.</li>
<li>Assigning participants unequally to conditions (if the control condition is much cheaper than the experimental condition, for example).</li>
<li>Using multiple measurements to increase measurement reliability (or use well-validated measures, if I may add).</li>
<li>Smart use of (preregistered, I’d recommend) covariates.</li>
</ol>
<p>Another approach they do not mention is to, where possible, collect multiple observations from the same participant. This can also increase power, especially if there is variation at the individual level, and you analyze data with hierarchical models.</p>
</div>
<div id="use-bayesian-statistics-with-informed-priors" class="section level3">
<h3><span class="header-section-number">2.6.6</span> Use Bayesian statistics with informed priors</h3>
<p>Regrettably, almost all approaches to statistical inferences become very limited when the number of observations is small. If you are very confident in your predictions (and your peers agree), incorporating prior information will give you a benefit. For a discussion of the benefits and risks of such an approach, see <span class="citation">van de Schoot et al. (<a href="#ref-van_de_schoot_analyzing_2015" role="doc-biblioref">2015</a>)</span>.</p>
</div>
</div>
<div id="what-to-do-if-best-practices-in-study-design-wont-save-you" class="section level2">
<h2><span class="header-section-number">2.7</span> What to do if best practices in study design won’t save you?</h2>
<p>In the end, getting an informative answer requires designing an informative experiment, and sometimes no matter how efficient you design your experiment, you will need to collect more data. Sometimes. there are no secret tricks or magical solutions. So what should we do then? The solutions below are, regrettably, a lot more work than making a small change to the design of your study. But it is about time we start to take them seriously.</p>
<div id="ask-for-a-lot-more-money-in-your-grant-proposals" class="section level3">
<h3><span class="header-section-number">2.7.1</span> Ask for a lot more money in your grant proposals</h3>
<p>Some grant organizations distribute funds to be awarded as a function of how much money is requested. If you need more money to collect informative data, ask for it. Obviously grants are incredibly difficult to get, but if you ask for money, include a budget that acknowledges that data collection is not as cheap as you hoped some years ago. In my experience, psychologists are often asking for much less money to collect data than other scientists. Increasing the requested funds for participant payment by a factor of 10 is often reasonable, given the requirements of journals to provide a solid sample size justification, and the more realistic effect size estimates that are emerging from preregistered studies.</p>
</div>
<div id="improve-management" class="section level3">
<h3><span class="header-section-number">2.7.2</span> Improve management</h3>
<p>If the implicit or explicit goals that you should meet are still the same now as they were 10 years ago, and you did not receive a miraculous increase in money and time to do research, then an update of the evaluation criteria is long overdue. I sincerely hope your manager is capable of this, but some ‘upward management’ might be needed. In the coda of Lakens &amp; Evers (2014) we wrote:</p>
<blockquote>
<p>All else being equal, a researcher running properly powered studies will clearly contribute more to cumulative science than a researcher running underpowered studies, and if researchers take their science seriously, it should be the former who is rewarded in tenure systems and reward procedures, not the latter.</p>
</blockquote>
</div>
<div id="change-what-is-expected-from-phd-students" class="section level3">
<h3><span class="header-section-number">2.7.3</span> Change what is expected from PhD students</h3>
<p>When I did my PhD, there was the assumption that you performed enough research in the 4 years you are employed as a full-time researcher to write a thesis with 3 to 5 empirical chapters (with some chapters having multiple studies). These studies were ideally published, but at least publishable. If we consider it important for PhD students to produce multiple publishable scientific articles during their PhD’s, this will greatly limit the types of research they can do. Instead of evaluating PhD students based on their publications, we can see the PhD as a time where researchers learn skills to become an independent researcher, and evaluate them not based on publishable units, but in terms of clearly identifiable skills. I personally doubt data collection is particularly educational after the 20th participant, and I would probably prefer to hire a post-doc who had well-developed skills in programming, statistics, and who broadly read the literature, then someone who used that time to collect participant 21 to 200. If we make it easier for PhD students to demonstrate their skills level we can evaluate what they have learned in a more sensible manner than by counting the number of publications they wrote. Currently, difference in the resources PhD students have at their disposal are a huge confound as we try to judge their skill based on their resume. Researchers at rich universities obviously have more resources – it should not be difficult to develop tools that allow us to judge the skills of people where resources are much less of a confound.</p>
</div>
<div id="think-about-the-questions-we-collectively-want-answered-instead-of-the-questions-we-can-individually-answer" class="section level3">
<h3><span class="header-section-number">2.7.4</span> Think about the questions we collectively want answered, instead of the questions we can individually answer</h3>
<p>Our society has some serious issues that psychologists can help address. These questions are incredibly complex. I have long lost faith in the idea that a bottom-up organized scientific discipline that rewards individual scientists will manage to generate reliable and useful knowledge that can help to solve these societal issues. For some of these questions we need well-coordinated research lines where hundreds of scholars work together, pool their resources and skills, and collectively pursuit answers to these important questions. And if we are going to limit ourselves in our research to the questions we can answer in our own small labs, these big societal challenges are not going to be solved. Call me a pessimist.</p>
<p>There is a reason we resort to forming unions and organizations that have to goal to collectively coordinate what we do. If you greatly dislike team science, don’t worry – there will always be options to make scientific contributions by yourself. But now, there are almost no ways for scientists who want to pursue huge challenges in large well-organized collectives of hundreds or thousands of scholars (for a recent exception that proves my rule by remaining unfunded: see the <a href="https://psysciacc.org/">Psychological Science Accelerator</a>). If you honestly believe your research question is important enough to be answered, then get together with everyone who also thinks so, and pursue answers collectively.</p>
</div>
</div>
<div id="planning-for-precision" class="section level2">
<h2><span class="header-section-number">2.8</span> Planning for precision</h2>
<p>NOT COMPLETED YET.</p>
<!-- Imagine we want to learn about the average reading speed. This is important information when we present written information on dynamic displays (e.g., subtitles under movies, transit information in subways). We want to make sure that most people will be able to read the text we present before it is gone. The number of words we read isn't fixed, but depends on what we read, and individual differences [@brysbaert_how_2019].  -->

</div>
</div>
<h3> References</h3>
<div id="refs" class="references">
<div id="ref-aberson_applied_2019">
<p>Aberson, C. L. (2019). <em>Applied Power Analysis for the Behavioral Sciences: 2nd Edition</em> (2 edition). Routledge.</p>
</div>
<div id="ref-albers_credible_2018">
<p>Albers, C. J., Kiers, H. A. L., &amp; Ravenzwaaij, D. van. (2018). Credible Confidence: A Pragmatic View on the Frequentist vs Bayesian Debate. <em>Collabra: Psychology</em>, <em>4</em>(1), 31. <a href="https://doi.org/10.1525/collabra.149">https://doi.org/10.1525/collabra.149</a></p>
</div>
<div id="ref-albers_when_2018">
<p>Albers, C. J., &amp; Lakens, D. (2018). When power analyses based on pilot data are biased: Inaccurate effect size estimators and follow-up bias. <em>Journal of Experimental Social Psychology</em>, <em>74</em>, 187–195. <a href="https://doi.org/10.1016/j.jesp.2017.09.004">https://doi.org/10.1016/j.jesp.2017.09.004</a></p>
</div>
<div id="ref-allison_power_1997">
<p>Allison, D. B., Allison, R. L., Faith, M. S., Paultre, F., &amp; Pi-Sunyer, F. X. (1997). Power and money: Designing statistically powerful studies while minimizing financial costs. <em>Psychological Methods</em>, <em>2</em>(1), 20–33. <a href="https://doi.org/10.1037/1082-989X.2.1.20">https://doi.org/10.1037/1082-989X.2.1.20</a></p>
</div>
<div id="ref-anderson_sample-size_2017">
<p>Anderson, S. F., Kelley, K., &amp; Maxwell, S. E. (2017). Sample-size planning for more accurate statistical power: A method adjusting sample effect sizes for publication bias and uncertainty. <em>Psychological Science</em>, <em>28</em>(11), 1547–1562.</p>
</div>
<div id="ref-bakker_recommendations_2020">
<p>Bakker, M., Veldkamp, C. L. S., Akker, O. R. van den, Assen, M. A. L. M. van, Crompvoets, E., Ong, H. H., &amp; Wicherts, J. M. (2020). Recommendations in pre-registrations and internal review board proposals promote formal power analyses but do not increase sample size. <em>PLOS ONE</em>, <em>15</em>(7), e0236079. <a href="https://doi.org/10.1371/journal.pone.0236079">https://doi.org/10.1371/journal.pone.0236079</a></p>
</div>
<div id="ref-brysbaert_how_2019-1">
<p>Brysbaert, M. (2019). How many participants do we have to include in properly powered experiments? A tutorial of power analysis with reference tables. <em>Journal of Cognition</em>, <em>2</em>(1), 16. <a href="https://doi.org/10.5334/joc.72">https://doi.org/10.5334/joc.72</a></p>
</div>
<div id="ref-button_power_2013">
<p>Button, K. S., Ioannidis, J. P. A., Mokrysz, C., Nosek, B. A., Flint, J., Robinson, E. S. J., &amp; Munafò, M. R. (2013). Power failure: Why small sample size undermines the reliability of neuroscience. <em>Nature Reviews Neuroscience</em>, <em>14</em>(5), 365–376. <a href="https://doi.org/10.1038/nrn3475">https://doi.org/10.1038/nrn3475</a></p>
</div>
<div id="ref-cohen_statistical_1988">
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed). L. Erlbaum Associates.</p>
</div>
<div id="ref-correll_avoid_2020">
<p>Correll, J., Mellinger, C., McClelland, G. H., &amp; Judd, C. M. (2020). Avoid Cohen’s “Small”, “Medium”, and “Large” for Power Analysis. <em>Trends in Cognitive Sciences</em>, <em>24</em>(3), 200–207. <a href="https://doi.org/10.1016/j.tics.2019.12.009">https://doi.org/10.1016/j.tics.2019.12.009</a></p>
</div>
<div id="ref-cousineau_superb_2019">
<p>Cousineau, D., &amp; Chiasson, F. (2019). <em>Superb: Computes standard error and confidence interval of means under various designs and sampling schemes</em> [Manual].</p>
</div>
<div id="ref-cumming_understanding_2013">
<p>Cumming, G. (2013). <em>Understanding the new statistics: Effect sizes, confidence intervals, and meta-analysis</em>. Routledge.</p>
</div>
<div id="ref-eckermann_value_2010">
<p>Eckermann, S., Karnon, J., &amp; Willan, A. R. (2010). The Value of Value of Information. <em>PharmacoEconomics</em>, <em>28</em>(9), 699–709. <a href="https://doi.org/10.2165/11537370-000000000-00000">https://doi.org/10.2165/11537370-000000000-00000</a></p>
</div>
<div id="ref-erdfelder_gpower_1996">
<p>Erdfelder, E., Faul, F., &amp; Buchner, A. (1996). GPOWER: A general power analysis program. <em>Behavior Research Methods, Instruments, &amp; Computers</em>, <em>28</em>(1), 1–11. <a href="https://doi.org/10.3758/BF03203630">https://doi.org/10.3758/BF03203630</a></p>
</div>
<div id="ref-faul_gpower_2007">
<p>Faul, F., Erdfelder, E., Lang, A.-G., &amp; Buchner, A. (2007). GPower 3: A flexible statistical power analysis program for the social, behavioral, and biomedical sciences. <em>Behavior Research Methods</em>, <em>39</em>(2), 175–191. <a href="https://doi.org/10.3758/BF03193146">https://doi.org/10.3758/BF03193146</a></p>
</div>
<div id="ref-hoenig_abuse_2001">
<p>Hoenig, J. M., &amp; Heisey, D. M. (2001). The abuse of power: The pervasive fallacy of power calculations for data analysis. <em>The American Statistician</em>, <em>55</em>(1), 19–24.</p>
</div>
<div id="ref-jaeschke_measurement_1989">
<p>Jaeschke, R., Singer, J., &amp; Guyatt, G. H. (1989). Measurement of health status: Ascertaining the minimal clinically important difference. <em>Controlled Clinical Trials</em>, <em>10</em>(4), 407–415. <a href="https://doi.org/10.1016/0197-2456(89)90005-6">https://doi.org/10.1016/0197-2456(89)90005-6</a></p>
</div>
<div id="ref-joseph_manipulation_2020">
<p>Joseph, D. L., Chan, M. Y., Heintzelman, S. J., Tay, L., Diener, E., &amp; Scotney, V. S. (2020). The manipulation of affect: A meta-analysis of affect induction procedures. <em>Psychological Bulletin</em>, <em>146</em>(4), 355–375. <a href="https://doi.org/10.1037/bul0000224">https://doi.org/10.1037/bul0000224</a></p>
</div>
<div id="ref-lakens_calculating_2013">
<p>Lakens, D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: A practical primer for t-tests and ANOVAs. <em>Frontiers in Psychology</em>, <em>4</em>. <a href="https://doi.org/10.3389/fpsyg.2013.00863">https://doi.org/10.3389/fpsyg.2013.00863</a></p>
</div>
<div id="ref-lakens_performing_2014">
<p>Lakens, D. (2014). Performing high-powered studies efficiently with sequential analyses: Sequential analyses. <em>European Journal of Social Psychology</em>, <em>44</em>(7), 701–710. <a href="https://doi.org/10.1002/ejsp.2023">https://doi.org/10.1002/ejsp.2023</a></p>
</div>
<div id="ref-lenth_post_2007">
<p>Lenth, R. V. (2007). Post hoc power: Tables and commentary. <em>Iowa City: Department of Statistics and Actuarial Science, University of Iowa</em>.</p>
</div>
<div id="ref-leon_role_2011">
<p>Leon, A. C., Davis, L. L., &amp; Kraemer, H. C. (2011). The Role and Interpretation of Pilot Studies in Clinical Research. <em>Journal of Psychiatric Research</em>, <em>45</em>(5), 626–629. <a href="https://doi.org/10.1016/j.jpsychires.2010.10.008">https://doi.org/10.1016/j.jpsychires.2010.10.008</a></p>
</div>
<div id="ref-miller_quest_2019">
<p>Miller, J., &amp; Ulrich, R. (2019). The quest for an optimal alpha. <em>PLOS ONE</em>, <em>14</em>(1), e0208631. <a href="https://doi.org/10.1371/journal.pone.0208631">https://doi.org/10.1371/journal.pone.0208631</a></p>
</div>
<div id="ref-neyman_problem_1933">
<p>Neyman, J., &amp; Pearson, E. S. (1933). On the problem of the most efficient tests of statistical hypotheses. <em>Philosophical Transactions of the Royal Society of London A: Mathematical, Physical and Engineering Sciences</em>, <em>231</em>(694-706), 289–337. <a href="https://doi.org/10.1098/rsta.1933.0009">https://doi.org/10.1098/rsta.1933.0009</a></p>
</div>
<div id="ref-perugini_safeguard_2014">
<p>Perugini, M., Gallucci, M., &amp; Costantini, G. (2014). Safeguard power as a protection against imprecise power estimates. <em>Perspectives on Psychological Science</em>, <em>9</em>(3), 319–332.</p>
</div>
<div id="ref-rice_heads_1994">
<p>Rice, W. R., &amp; Gaines, S. D. (1994). ’Heads I win, tails you lose’: Testing directional alternative hypotheses in ecological and evolutionary research. <em>Trends in Ecology &amp; Evolution</em>, <em>9</em>(6), 235–237. <a href="https://doi.org/10.1016/0169-5347(94)90258-5">https://doi.org/10.1016/0169-5347(94)90258-5</a></p>
</div>
<div id="ref-richard_one_2003">
<p>Richard, F. D., Bond, C. F., &amp; Stokes-Zoota, J. J. (2003). One Hundred Years of Social Psychology Quantitatively Described. <em>Review of General Psychology</em>, <em>7</em>(4), 331–363. <a href="https://doi.org/10.1037/1089-2680.7.4.331">https://doi.org/10.1037/1089-2680.7.4.331</a></p>
</div>
<div id="ref-schulz_sample_2005">
<p>Schulz, K. F., &amp; Grimes, D. A. (2005). Sample size calculations in randomised trials: Mandatory and mystical. <em>The Lancet</em>, <em>365</em>(9467), 1348–1353.</p>
</div>
<div id="ref-smithson_confidence_2003">
<p>Smithson, M. (2003). <em>Confidence intervals</em>. Sage Publications.</p>
</div>
<div id="ref-taylor_bias_1996">
<p>Taylor, D. J., &amp; Muller, K. E. (1996). Bias in linear model power and sample size calculation due to estimating noncentrality. <em>Communications in Statistics-Theory and Methods</em>, <em>25</em>(7), 1595–1610.</p>
</div>
<div id="ref-thompson_sampling_2012">
<p>Thompson, S. K. (2012). <em>Sampling</em> (3rd ed). Wiley.</p>
</div>
<div id="ref-van_de_schoot_analyzing_2015">
<p>van de Schoot, R., Broere, J. J., Perryck, K. H., Zondervan-Zwijnenburg, M., &amp; van Loey, N. E. (2015). Analyzing small data sets using Bayesian estimation: The case of posttraumatic stress symptoms following mechanical ventilation in burn survivors. <em>European Journal of Psychotraumatology</em>, <em>6</em>. <a href="https://doi.org/10.3402/ejpt.v6.25216">https://doi.org/10.3402/ejpt.v6.25216</a></p>
</div>
<div id="ref-winer_statistical_1962">
<p>Winer, B. J. (1962). <em>Statistical principles in experimental design</em>. New York : McGraw-Hill.</p>
</div>
<div id="ref-yuan_post_2005">
<p>Yuan, K.-H., &amp; Maxwell, S. (2005). On the Post Hoc Power in Testing Mean Differences. <em>Journal of Educational and Behavioral Statistics</em>, <em>30</em>(2), 141–167. <a href="https://doi.org/10.3102/10769986030002141">https://doi.org/10.3102/10769986030002141</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="pvalue.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="questions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
