<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Power analysis for interactions | Improving Your Statistical Inferences</title>
  <meta name="description" content="Online textbook to Improve Your Statistical Inferences" />
  <meta name="generator" content="bookdown 0.20.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Power analysis for interactions | Improving Your Statistical Inferences" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://themethodsection.com/ebook/" />
  <meta property="og:image" content="http://themethodsection.com/ebook/images/cover.jpg" />
  <meta property="og:description" content="Online textbook to Improve Your Statistical Inferences" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Power analysis for interactions | Improving Your Statistical Inferences" />
  
  <meta name="twitter:description" content="Online textbook to Improve Your Statistical Inferences" />
  <meta name="twitter:image" content="http://themethodsection.com/ebook/images/cover.jpg" />

<meta name="author" content="Daniel Lakens" />


<meta name="date" content="2020-07-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="why-within-subject-designs-typically-require-fewer-participants-than-between-subject-designs.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Improving Your Statistical Inferences</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li><a href="what-is-a-p-value-mathematically.html#what-is-a-p-value-mathematically">What is a <em>p</em>-value (mathematically)</a></li>
<li class="chapter" data-level="" data-path="what-is-power-analysis.html"><a href="what-is-power-analysis.html"><i class="fa fa-check"></i>What is power analysis?</a></li>
<li class="chapter" data-level="" data-path="how-to-justify-your-sample-size-based-on-a-power-analysis-.html"><a href="how-to-justify-your-sample-size-based-on-a-power-analysis-.html"><i class="fa fa-check"></i>How to justify your sample size based on a power analysis.</a></li>
<li class="chapter" data-level="" data-path="why-within-subject-designs-typically-require-fewer-participants-than-between-subject-designs.html"><a href="why-within-subject-designs-typically-require-fewer-participants-than-between-subject-designs.html"><i class="fa fa-check"></i>Why Within-Subject Designs Typically Require Fewer Participants than Between-Subject Designs</a></li>
<li class="chapter" data-level="" data-path="power-analysis-for-interactions.html"><a href="power-analysis-for-interactions.html"><i class="fa fa-check"></i>Power analysis for interactions</a></li>
<li class="divider"></li>
<li><a href="https://sites.google.com/site/lakens2/Home" target="blank">Daniel Lakens</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Improving Your Statistical Inferences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="power-analysis-for-interactions" class="section level1 unnumbered">
<h1>Power analysis for interactions</h1>
<p>Based on our recent <a href="https://psyarxiv.com/baxsf/">preprint</a> explaining power analysis for ANOVA designs, in this post I want provide a step-by-step mathematical overview of power analysis for interactions. These details often do not make it into tutorial papers because of word limitations, and few good free resources are available (for a paid resource worth your money, see <a href="https://designingexperiments.com/">Maxwell, Delaney, &amp; Kelley, 2018</a>). This post is a bit technical, but nothing in this post requires more knowedge than multiplying and dividing numbers, and I believe that for anyone willing to really understand effect sizes and power in ANOVA designs digging in to these details will be quite beneficial. There are three take-home messages in this section.</p>
<ol style="list-style-type: decimal">
<li>In power analyses for ANOVA designs, you should always think of the predicted pattern of means. Different patterns of means will have the same effect size, and your intuition can not be relied on when predicting an effect size for ANOVA designs.</li>
<li>Understanding how patterns of means relate to the effect you predict is essential to design an informative study.</li>
<li>Always perform a power analysis if you want to test a predicted interaction effect, and always calculate the effect size based on means, sd’s, and correlations, instead of plugging in a ‘medium’ partial eta squared.</li>
<li>Crossover interaction effects have large effects and can thus be studies with high power in smaller samples, and if your theory can predict crossover interactions, such experiments might be worthwhile to design.</li>
<li>There are some additional benefits of examining interactions (risky predictions, generalizability, efficiently examining multiple main effects) and it would be a shame if the field is turned away from examining interactions because they sometimes require large samples.</li>
</ol>
<p><strong>Getting started: Comparing two groups</strong></p>
<p>We are planning a two independent group experiment. We are using a validated measure, and we know the standard deviation of our measure is approximately 2. Psychologists are generaly horribly bad at knowing the standard deviation of their measures, even though a very defensible position is that you are not ready to perform a power analysis without solid knowledge of the standard deviation of your measure. We are interested in observing a mean difference of 1 or more, because smaller effects would not be practically meaningful. We expect the mean in the control condition to be 0, and therefore want the mean in the intervention group to be 1 or higher.</p>
<p>This means the standardized effect size is the mean difference, divided by the standard deviation, or 1/2 = 0.5. This is the Cohen’s d we want to be able to detect in our study:</p>
<p><span class="math display">\[\begin{equation}
d = \frac{m_1-m_2}{\sigma} =  \frac{1-0}{2} = 0.5.
\end{equation}\]</span></p>
<p>An independent <em>t</em>-test is mathematically identical to an <em>F</em>-test with two groups. For an <em>F</em>-test, the effect size used for power analyses is Cohen’s <em>f</em>, which is a generalization
of Cohen’s d to more than two groups (Cohen, 1988). It is calculated based on the standard deviation of the population means divided by the population standard deviation which we know for our measure is 2), or:</p>
<p><span class="math display">\[\begin{equation}
f = \frac{\sigma _{ m }}{\sigma}
\end{equation}\]</span>
where for equal sample sizes,
<span class="math display">\[\begin{equation}
\sigma _{ m } = \sqrt { \frac { \sum_ { i = 1 } ^ { k } ( m _ { i } - m ) ^ { 2 } } { k } }.
\end{equation}\]</span></p>
<p>In this formula <em>m</em> is the grand mean, k is the number of means, and m_i is the mean in each group. The formula above might look a bit daunting, but calculating Cohen’s f is not that difficult for two groups.</p>
<p>If we take the expected means of 0 and 1, and a standard deviation of 2, the grand mean (the <em>m</em> in the formula above) is (0 + 1)/2 = 0.5. The formula says we should subtract this grand mean from the mean of each group, square this value, and sum them. So we have (0-0.5)^2 and (1-0.5)^2, which are both 0.25. We sum these values (0.25 + 0.25 = 0.5), divide them by the number of groups (0.5/2 = 0.25) and take the square root, we find that <span class="math inline">\(\sigma_{ m }\)</span> = 0.5. We can now calculate Cohen’s f (remember than we know <span class="math inline">\(\sigma\)</span> = 2 for our measure):</p>
<p><span class="math display">\[\begin{equation}
f = \frac{\sigma _{ m }}{\sigma} = \frac{0.5}{2} = 0.25
\end{equation}\]</span></p>
<p>We see that for two groups Cohen’s f is half as large as Cohen’s d, or <span class="math inline">\(f = \frac{1}{2}d\)</span>, which always holds for an <em>F</em>-test with two independent groups.</p>
<p>Although calculating effect sizes by hand is obviously an incredibly enjoyable thing to do, you might prefer using software that performs these calculations for you. Here, I will use our Superpower power analysis package (developed by Aaron Caldwell and me). The code below uses a function from the package that computes power analytically for a one-way ANOVA where all conditions are manipulated between participants. In addition to the effect size, the function will compute power for any sample size per condition you enter. Let’s assume you have a friend who told you that they heard from someone else that you now need to use 50 observations in each condition (n = 50), so you plan to follow this trustworthy advice. We see the code below returns a Cohen’s <em>f</em> of 0.25, and also tells us we would have 61.78% power if we use a preregistered alpha level of 0.03.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="power-analysis-for-interactions.html#cb9-1"></a><span class="kw">library</span>(Superpower)</span>
<span id="cb9-2"><a href="power-analysis-for-interactions.html#cb9-2"></a></span>
<span id="cb9-3"><a href="power-analysis-for-interactions.html#cb9-3"></a>design &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(</span>
<span id="cb9-4"><a href="power-analysis-for-interactions.html#cb9-4"></a>  <span class="dt">design =</span> <span class="st">&quot;2b&quot;</span>, </span>
<span id="cb9-5"><a href="power-analysis-for-interactions.html#cb9-5"></a>  <span class="dt">n =</span> <span class="dv">50</span>, </span>
<span id="cb9-6"><a href="power-analysis-for-interactions.html#cb9-6"></a>  <span class="dt">mu =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), </span>
<span id="cb9-7"><a href="power-analysis-for-interactions.html#cb9-7"></a>  <span class="dt">sd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="power-analysis-for-interactions.html#cb10-1"></a><span class="kw">power_oneway_between</span>(design, <span class="dt">alpha_level =</span> <span class="fl">0.03</span>)<span class="op">$</span>Cohen_f</span></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="power-analysis-for-interactions.html#cb12-1"></a><span class="kw">power_oneway_between</span>(design, <span class="dt">alpha_level =</span> <span class="fl">0.03</span>)<span class="op">$</span>power</span></code></pre></div>
<pre><code>## [1] 61.78474</code></pre>
<p>We therefore might want to increase our sample size for our planned study. Using the <code>plot_power</code> function, we can see we would pass 90% power with 100 observations per condition.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="power-analysis-for-interactions.html#cb14-1"></a><span class="kw">plot_power</span>(design, <span class="dt">alpha_level =</span> <span class="fl">0.03</span>, <span class="dt">min_n =</span> <span class="dv">45</span>, <span class="dt">max_n =</span> <span class="dv">150</span>)<span class="op">$</span>plot_ANOVA</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre><code>## Achieved Power and Sample Size for ANOVA-level effects
##   variable                  label  n achieved_power desired_power
## 1        a Desired Power Achieved 96          90.13            90</code></pre>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<p><strong>Interaction Effects</strong></p>
<p>So far we have explained the basics for effect size calculations (and we have looked at statistical power) for 2 group ANOVA designs. Now we have the basis to look at interaction effects.</p>
<p>One of the main points in this blog post is that it is better to talk about interactions in ANOVAs in terms of the pattern of means, standard deviations, and correlations, than in terms of a standarized effect size. The reason for this is that, while for two groups a difference between means directly relates to a Cohen’s d, wildly different patterns of means in an ANOVA will have the same Cohen’s <em>f</em>. In my experience helping colleagues out their with power analyses for ANOVA designs, talking about effects in terms of a Cohen’s <em>f</em> is rarely a good place to start when thinking about what your hypothesis predicts. Instead, you need to specify the predicted pattern of means, have some knowledge about the standard deviation of your measure, and then calculate your predicted effect size.</p>
<p>There are two types of interactions, as visualized below. In an ordinal interaction, the mean of one group (“B1”) is always higher than the mean for the other group (“B2”). Disordinal interactions are also known as ‘cross-over’ interactions, and occur when the group with the larger mean switches over. The difference is important, since another main takeaway of this blog post is that, in two studies where the largest simple comparison has the same effect size, a study with a disordinal interaction has much higher power than a study with an ordinal interaction. Thus, if possible, you will want to design experiments where an effect in one condition flips around in the other condition, instead of an experiment where the effect in the other condition just disappears. I personally never realized this before I learned how to compute power for interactions, and never took this simple but important fact into account. Let’s see why it is important.</p>
<p><strong>Calculating effect sizes for interactions</strong></p>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Mathematically the interaction effect is computed as the cell mean minus the sum of the grand mean, the marginal mean in each condition of one factor minus the grand mean, and the marginal mean in each condition for the other factor minus grand mean (see Maxwell et al., 2017).</p>
<p>Let’s consider two cases comparable to the figure above, one where we have a perfect disordinal interaction (the means of 0 and 1 flip around in the other condition, and are 1 and 0) or an ordinal interaction (the effect is present in one condition, with means of 0 and 1, but there is no effect in the other condition, and both means are 0). We can calcuate the interaction effect as follows. First, let’s look at the interaction in a 2x2 matrix:</p>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre><code>##    a1 a2
## b1  1  0
## b2  0  1</code></pre>
<p>The grand mean is (1 + 0 + 0 + 1) / 4 = 0.5.</p>
<p>We can compute the marginal means for A1, A2, B1, and B2, which is simply averaging per row and column, which gets us for the A1 column (1+0)/2=0.5. For this perfect disordinal interaction, all marginal means are 0.5. This means there are no main effects. There is no main effect of factor A (because the marginal means for A1 and A2 are both exactly 0.5), nor is there a main effect of B.</p>
<p>We can also calculate the interaction effect. For each cell we take the value in the cell (e.g., for a1b1 this is 1) and compute the difference between the cell mean and the additive effect of the two factors as:</p>
<p>1 - (the grand mean of 0.5 + (the marginal mean of a1 minus the grand mean, or 0.5 - 0.5 = 0) + (the marginal mean of b1 minus the grand mean, or 0.5 - 0.5 = 0)). Thus, for each cell we get:</p>
<p>a1b1: 1 - (0.5 + (0.5 -0.5) + (0.5 -0.5)) = 0.5</p>
<p>a1b2: 0 - (0.5 + (0.5 -0.5) + (0.5 -0.5)) = -0.5</p>
<p>a2b1: 0 - (0.5 + (0.5 -0.5) + (0.5 -0.5)) = -0.5</p>
<p>a2b2: 1 - (0.5 + (0.5 -0.5) + (0.5 -0.5)) = 0.5</p>
<p>Cohen’s <span class="math inline">\(f\)</span> is then <span class="math inline">\(f = \frac { \sqrt { \frac { 0.5^2 +-0.5^2 + -0.5^2 + 0.5^2 } { 4 } }}{ 2 } = 0.25\)</span></p>
<p>or in R code: <code>sqrt(((0.5)^2 +(-0.5)^2 + (-0.5)^2 + (0.5)^2)/4)/2 = 0.25</code>.</p>
<p>For the ordinal interaction the grand mean is (1 + 0 + 0 + 0) / 4, or 0.25. The marginal means are a1: 0.5, a2: 0, b1: 0.5, and b2: 0.</p>
<p>Completing the calculation for all four cells for the ordinal interaction gives:</p>
<p>a1b1: 1 - (0.25 + (0.5 -0.25) + (0.5 -0.25)) = 0.25</p>
<p>a1b2: 0 - (0.25 + (0.5 -0.25) + (0.0 -0.25)) = -0.25</p>
<p>a2b1: 0 - (0.25 + (0.0 -0.25) + (0.5 -0.25)) = -0.25</p>
<p>a2b2: 0 - (0.25 + (0.0 -0.25) + (0.0 -0.25)) = 0.25</p>
<p>Cohen’s <span class="math inline">\(f\)</span> is then <span class="math inline">\(f = \frac { \sqrt { \frac { 0.25^2 +-0.25^2 + -0.25^2 + 0.25^2 } { 4 } }}{ 2 } = 0.125\)</span>.</p>
<p>or in R code: <code>sqrt(((0.25)^2 +(-0.25)^2 + (-0.25)^2 + (0.25)^2)/4)/2 = 0.125</code>.</p>
<p>We see the effect size of the cross-over interaction (<em>f</em> = 0.25) is twice as large as the effect size of the ordinal interaction (<em>f</em> = 0.125).</p>
<p>If the math so far was a bit too much to follow, there is an easier way to think of why the effect sizes are halved. In the disordinal interaction we are comparing cells a1b1 and a2b2 against a1b2 and a2b1, or (1+1)/2 vs. (0+0)/2. Thus, if we see this as a <em>t</em>-test for a contrast, it is clear the mean difference is 1, as it was in the simple effect we started with. For the ordinal interaction, we have (1+0)/2 vs. (0+0)/2, so the mean difference is halved, namely 0.5.</p>
<p><strong>Power for interactions</strong></p>
<p>All of the above obviously matters for the statistical power we will have when we examine interaction effects in our experiments. Let’s use Superpower to perform power analyses for the disordinal interaction first, if we would collect 50 participants in each condition.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="power-analysis-for-interactions.html#cb17-1"></a>design &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(</span>
<span id="cb17-2"><a href="power-analysis-for-interactions.html#cb17-2"></a>  <span class="dt">design =</span> <span class="st">&quot;2b*2b&quot;</span>, </span>
<span id="cb17-3"><a href="power-analysis-for-interactions.html#cb17-3"></a>  <span class="dt">n =</span> <span class="dv">50</span>, </span>
<span id="cb17-4"><a href="power-analysis-for-interactions.html#cb17-4"></a>  <span class="dt">mu =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb17-5"><a href="power-analysis-for-interactions.html#cb17-5"></a>  <span class="dt">sd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="power-analysis-for-interactions.html#cb18-1"></a><span class="kw">ANOVA_exact</span>(design, <span class="dt">alpha_level =</span> <span class="fl">0.03</span>)</span></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##      power partial_eta_squared cohen_f non_centrality
## a    3.000                0.00  0.0000            0.0
## b    3.000                0.00  0.0000            0.0
## a:b 91.055                0.06  0.2525           12.5
## 
## Power and Effect sizes for pairwise comparisons (t-tests)
##                       power effect_size
## p_a_a1_b_b1_a_a1_b_b2 61.78        -0.5
## p_a_a1_b_b1_a_a2_b_b1 61.78        -0.5
## p_a_a1_b_b1_a_a2_b_b2  3.00         0.0
## p_a_a1_b_b2_a_a2_b_b1  3.00         0.0
## p_a_a1_b_b2_a_a2_b_b2 61.78         0.5
## p_a_a2_b_b1_a_a2_b_b2 61.78         0.5</code></pre>
<p>First let’s look at the Power and Effect size for the pairwise comparisons. Not surprisingly, these are just the same as our original t-test, given that we have 50 observations per condition, and our mean difference is either 1, or a Cohen’s d of 0.5 (in which case we have 61.78% power) or the mean difference is 0, and we have no power (because there is no true effect) but we wil observe significant results 3% of the time because we set our alpha level to 0.03.</p>
<p>Then, let’s look at the results for the ANOVA. Since there are no main effects in a perfect crossover interaction, we have a 3% Type 1 error rate. We see the power for the crossover interaction between factor a and b is 91.06%. This is much larger than the power for the simple effects. The reason is that the contrast that is equal to the test of the interaction is based on all 200 observations. Unlike the pairwise comparisons with 50 vs 50 observations, the contrast for the interaction has 100 vs 100 observations. Given that the effect size is the same (<em>f</em> = 0.25) we end up with much higher power.</p>
<p>If you current think it is impossible to find a statistically significant interaction without a huge sample size, you clearly see this is wrong. Power <em>can</em> be higher for an interaction than for the simpe effect - but this depends on the pattern of means underlying the interaction. If possible, design studies where your theory predicts a perfect crossover interaction.</p>
<p>For the ordinal interaction, our statistical power does not look that good based on an a-priori power analysis. Superpower tells us we have 33.99% power for the main effects and interaction (yes, we have exactly the same power for all three - if you think about the three contrasts that are tested, these have the same effect size).</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="power-analysis-for-interactions.html#cb20-1"></a>design &lt;-<span class="st"> </span><span class="kw">ANOVA_design</span>(</span>
<span id="cb20-2"><a href="power-analysis-for-interactions.html#cb20-2"></a>  <span class="dt">design =</span> <span class="st">&quot;2b*2b&quot;</span>, </span>
<span id="cb20-3"><a href="power-analysis-for-interactions.html#cb20-3"></a>  <span class="dt">n =</span> <span class="dv">50</span>, </span>
<span id="cb20-4"><a href="power-analysis-for-interactions.html#cb20-4"></a>  <span class="dt">mu =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), </span>
<span id="cb20-5"><a href="power-analysis-for-interactions.html#cb20-5"></a>  <span class="dt">sd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistical_Inferences_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="power-analysis-for-interactions.html#cb21-1"></a><span class="kw">ANOVA_exact</span>(design, <span class="dt">alpha_level =</span> <span class="fl">0.03</span>)</span></code></pre></div>
<pre><code>## Power and Effect sizes for ANOVA tests
##       power partial_eta_squared cohen_f non_centrality
## a   33.9869              0.0157  0.1263          3.125
## b   33.9869              0.0157  0.1263          3.125
## a:b 33.9869              0.0157  0.1263          3.125
## 
## Power and Effect sizes for pairwise comparisons (t-tests)
##                       power effect_size
## p_a_a1_b_b1_a_a1_b_b2 61.78        -0.5
## p_a_a1_b_b1_a_a2_b_b1 61.78        -0.5
## p_a_a1_b_b1_a_a2_b_b2 61.78        -0.5
## p_a_a1_b_b2_a_a2_b_b1  3.00         0.0
## p_a_a1_b_b2_a_a2_b_b2  3.00         0.0
## p_a_a2_b_b1_a_a2_b_b2  3.00         0.0</code></pre>
<p>If you have heard people say you should be careful when designing studies predicting interaction patterns because you might have very low power, this is the type of pattern of means they are warning about. Maxwell, Delaney, and Kelley (2018) discuss why power for interactions is often smaller, and note interactions effects are often smaller in the real world, and we often examine ordinal interactions. This might be true. But in experimental psychology it might be possile to think about hypotheses that predict disordinal interactions. In addition to the fact that such predictions are often theoretically riskier and more impressive (after all, many things can make an effect go away, but without your theory it might be difficult to explain why an effect flips around) they also have larger effects and are easier to test with high power.</p>
<p>Some years ago other blog posts by <a href="http://datacolada.org/17">Uri Simonsohn</a> and <a href="https://approachingblog.wordpress.com/2018/01/24/powering-your-interaction-2/">Roger Giner-Sorolla</a> did a great job in warning researchers they need large sample sizes for ordinal interactions, and my post repeats this warning. But it would be a shame if researchers would stop examining interaction effects. There are some nice benefits studying interactions, such as 1) making riskier theoretical predictions, 2) greater generalizability (if there is no interaction effect, you might show a main effect operates across different conditions of a second factor) and 3) if you want to study two main effects it is more efficient to do this in a 2x2 design than in two seperate designs (Maxwell, Delaney, &amp; Kelley, 2018). So maybe this blog post has been able to highlight some scenarios where examining interaction effects is still beneficial.</p>

<div id="refs" class="references">
<div>
<p>Aberson, Christopher L. 2019. <em>Applied Power Analysis for the Behavioral Sciences: 2nd Edition</em>. 2 edition. New York: Routledge.</p>
</div>
<div>
<p>Cohen, Jacob. 1988. <em>Statistical Power Analysis for the Behavioral Sciences</em>. 2nd ed. Hillsdale, N.J: L. Erlbaum Associates.</p>
</div>
<div>
<p>Neyman, Jerzy, and E. S. Pearson. 1933. “On the Problem of the Most Efficient Tests of Statistical Hypotheses.” <em>Philosophical Transactions of the Royal Society of London A: Mathematical, Physical and Engineering Sciences</em> 231 (694-706): 289–337. <a href="https://doi.org/10.1098/rsta.1933.0009">https://doi.org/10.1098/rsta.1933.0009</a>.</p>
</div>
<div>
<p>Schulz, Kenneth F., and David A. Grimes. 2005. “Sample Size Calculations in Randomised Trials: Mandatory and Mystical.” <em>The Lancet</em> 365 (9467): 1348–53.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="why-within-subject-designs-typically-require-fewer-participants-than-between-subject-designs.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
