<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Chapter 13 Alpha spending functions | Improving Your Statistical Inferences</title>

    <meta name="author" content="Daniel Lakens" />
  
   <meta name="description" content="Open education resource to improve statistical inferences based on the work by Daniel Lakens." />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="Chapter 13 Alpha spending functions | Improving Your Statistical Inferences" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Open education resource to improve statistical inferences based on the work by Daniel Lakens." />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Alpha spending functions | Improving Your Statistical Inferences" />
  
  <meta name="twitter:description" content="Open education resource to improve statistical inferences based on the work by Daniel Lakens." />
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.3.1/transition.js"></script>
    <script src="libs/bs3compat-0.3.1/tabs.js"></script>
    <script src="libs/bs3compat-0.3.1/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="bs4_style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Improving Your Statistical Inferences</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="alpha-spending-functions" class="section level1" number="13">
<h1><span class="header-section-number">Chapter 13</span> Alpha spending functions</h1>
<p>The approaches to specify the shape of decision boundaries across looks discussed so far have an important limitation <span class="citation">(<a href="references.html#ref-proschan_statistical_2006" role="doc-biblioref">Proschan et al., 2006</a>)</span>. They require a pre-specified number of looks (e.g., 4), and the sample size for the interim looks need to be pre-specified as well (e.g., after 25%, 50%, 75%, and 100% of observations). It is logistically not always feasible to stop the data collection exactly at 25% of the planned total sample size. An important contribution to the sequential testing literature was made by Lan and DeMets -<span class="citation">Lan &amp; DeMets (<a href="references.html#ref-lan_discrete_1983" role="doc-biblioref">1983</a>)</span> who introduced the alpha spending approach to correct the alpha level. In this approach the cumulative Type I error rate spent across the looks is pre-specified through a function (the <em>alpha spending function</em>) in order to control the overall significance level <span class="math inline">\(\alpha\)</span> at the end of the study.</p>
<p>The main benefit of these alpha spending functions is that error rates at interim analyses can be controlled, while neither the number nor the timing of the looks needs to be specified in advance. This makes alpha spending approaches much more flexible than earlier approaches to controlling the Type 1 error in group sequential designs. When using an alpha spending function it is important that the decision to perform an interim analysis is not based on collected data, as this can still increase the Type I error rate. As long as this assumption is met, it is possible to update the alpha levels at each look during a study.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-6"></span>
<img src="11-sequential_files/figure-html/unnamed-chunk-6-1.png" alt="Comparison of Pocock and O'Brien-Fleming correction, and Pocock-like and O'Brien-Fleming like alpha spending function, for 5 looks." width="100%" />
<p class="caption">
Figure 13.1: Comparison of Pocock and O'Brien-Fleming correction, and Pocock-like and O'Brien-Fleming like alpha spending function, for 5 looks.
</p>
</div>
<p>It can be useful to explicitly compare different types of designs. As explained before, the Pocock correction maintains a fixed alpha level at each look. The O'Brien-Fleming correction uses a higher threshold for early looks, but has the advantage that the final look occurs closer to the uncorrected alpha level. Because the alpha level is very similar at the last look, so is the total required sample size. Lowering the alpha level means the sample size needs to be increased to maintain the same desired level of statistical power, so different spending functions also require a different increase in the final sample size (to compensate for the lower alpha level, while maintaining the same statistical power). Sequential designs always need to be planned for a slightly larger total sample size at the final look, although as we will see below, because we can expect to stop at earlier looks, on average sample size will be smaller when using sequential designs compared to fixed designs.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="alpha-spending-functions.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#O&#39;Brien &amp; Fleming design, 3 equally spaced stages</span></span>
<span id="cb5-2"><a href="alpha-spending-functions.html#cb5-2" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">typeOfDesign =</span> <span class="st">&quot;OF&quot;</span>, <span class="at">kMax =</span> <span class="dv">5</span>) </span>
<span id="cb5-3"><a href="alpha-spending-functions.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Pocock design</span></span>
<span id="cb5-4"><a href="alpha-spending-functions.html#cb5-4" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>, <span class="at">kMax =</span> <span class="dv">5</span>)</span>
<span id="cb5-5"><a href="alpha-spending-functions.html#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="alpha-spending-functions.html#cb5-6" aria-hidden="true" tabindex="-1"></a>designSet <span class="ot">&lt;-</span><span class="fu">getDesignSet</span>(<span class="at">designs =</span> <span class="fu">c</span>(d1, d2), </span>
<span id="cb5-7"><a href="alpha-spending-functions.html#cb5-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">variedParameters =</span> <span class="st">&quot;typeOfDesign&quot;</span>)</span>
<span id="cb5-8"><a href="alpha-spending-functions.html#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(designSet, <span class="at">type =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:spending-comparison"></span>
<img src="11-sequential_files/figure-html/spending-comparison-1.png" alt="Comparison of the Pocock and O'Brien-Fleming boundaries." width="100%" />
<p class="caption">
Figure 13.2: Comparison of the Pocock and O'Brien-Fleming boundaries.
</p>
</div>
<p>We see that at each of the 5 looks the critical value for our test is higher than 1.96 (the critical value without correcting for multiple looks, assuming a normal distribution, indicated by the black dashed line). The Pocock correction (P, blue line) has the same critical value at each look: 2.4131803, 2.4131803, 2.4131803, 2.4131803, 2.4131803, while the critical values decrease for each look with the O'Brien-Fleming correction (OF, red line): 4.5617423, 3.2256389, 2.6337232, 2.2808712, 2.0400732. The first three looks use an alpha level that is stricter than the Pocock spending function, but the last two use a much less strict threshold, and the last look occurs at a level quite close to an alpha level without any correction. As we will see below, this is quite efficient, without requiring a noticeable increase in the sample size due to a lower alpha level at the last look.</p>
<p>Another design, not discussed in the rest of this test, is the design proposed by Haybittle and Peto. Adjust the plot code (changing OF to HP) to see what it looks like.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="alpha-spending-functions.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb6-2"><a href="alpha-spending-functions.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb6-3"><a href="alpha-spending-functions.html#cb6-3" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">typeOfDesign =</span> <span class="st">&quot;HP&quot;</span>,</span>
<span id="cb6-4"><a href="alpha-spending-functions.html#cb6-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">kMax =</span> <span class="dv">5</span>) </span>
<span id="cb6-5"><a href="alpha-spending-functions.html#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Pocock</span></span>
<span id="cb6-6"><a href="alpha-spending-functions.html#cb6-6" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb6-7"><a href="alpha-spending-functions.html#cb6-7" aria-hidden="true" tabindex="-1"></a>                               <span class="at">kMax =</span> <span class="dv">5</span>)</span>
<span id="cb6-8"><a href="alpha-spending-functions.html#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="alpha-spending-functions.html#cb6-9" aria-hidden="true" tabindex="-1"></a>designSet <span class="ot">&lt;-</span><span class="fu">getDesignSet</span>(<span class="at">designs =</span> <span class="fu">c</span>(d1, d2), </span>
<span id="cb6-10"><a href="alpha-spending-functions.html#cb6-10" aria-hidden="true" tabindex="-1"></a>                         <span class="at">variedParameters =</span> <span class="st">&quot;typeOfDesign&quot;</span>)</span>
<span id="cb6-11"><a href="alpha-spending-functions.html#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(designSet, <span class="at">type =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="11-sequential_files/figure-html/unnamed-chunk-7-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div id="sample-size-for-sequential-designs" class="section level2" number="13.1">
<h2><span class="header-section-number">13.1</span> Sample Size for Sequential Designs</h2>
<p>Sequential designs require somewhat more participants than a fixed design at the final look, depending on how much the alpha level at this look is lowered due to the correction for multiple comparisons. Due to early stopping, sequential designs will on average require less participants.</p>
<p>Let's first examine how many participants we would need in a fixed design, where we only analyze our data once. We have an alpha level of 0.05, and a Type 2 (beta) error of 0.1 - in other words, the desired power is 90%. We will perform one test, and assuming a normal distribution our critical Z-score would be 1.96, for an alpha level of 5%.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="alpha-spending-functions.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify the design</span></span>
<span id="cb7-2"><a href="alpha-spending-functions.html#cb7-2" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb7-3"><a href="alpha-spending-functions.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">1</span>,</span>
<span id="cb7-4"><a href="alpha-spending-functions.html#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb7-5"><a href="alpha-spending-functions.html#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb7-6"><a href="alpha-spending-functions.html#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb7-7"><a href="alpha-spending-functions.html#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb7-8"><a href="alpha-spending-functions.html#cb7-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-9"><a href="alpha-spending-functions.html#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># print a summary</span></span>
<span id="cb7-10"><a href="alpha-spending-functions.html#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(seq_design)</span></code></pre></div>
<pre><code>## Fixed sample analysis
## 
## Pocock design, two-sided significance level 5%, power 90%, undefined endpoint.
## 
## Stage                             Fixed 
## Efficacy boundary (z-value scale) 1.960</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="alpha-spending-functions.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform a power analysis using rpact</span></span>
<span id="cb9-2"><a href="alpha-spending-functions.html#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># By setting the alternative to 0.5 and the stDev to 1, we assume a Cohen&#39;s d of 0.5 for the alternative hypothesis.</span></span>
<span id="cb9-3"><a href="alpha-spending-functions.html#cb9-3" aria-hidden="true" tabindex="-1"></a>power_res <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb9-4"><a href="alpha-spending-functions.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb9-5"><a href="alpha-spending-functions.html#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb9-6"><a href="alpha-spending-functions.html#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb9-7"><a href="alpha-spending-functions.html#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb9-8"><a href="alpha-spending-functions.html#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb9-9"><a href="alpha-spending-functions.html#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-10"><a href="alpha-spending-functions.html#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="alpha-spending-functions.html#cb9-11" aria-hidden="true" tabindex="-1"></a>power_res</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Critical values                              : 1.96 
##   Two-sided power                              : FALSE 
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1000 
##   Test                                         : two-sided 
## 
## User defined parameters:
##   Alternatives                                 : 0.5 
## 
## Default parameters:
##   Mean ratio                                   : FALSE 
##   Theta H0                                     : 0 
##   Normal approximation                         : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Number of subjects fixed                     : 170.1 
##   Number of subjects fixed (1)                 : 85 
##   Number of subjects fixed (2)                 : 85 
##   Lower critical values (treatment effect scale) : -0.303 
##   Upper critical values (treatment effect scale) : 0.303 
##   Local two-sided significance levels          : 0.0500 
## 
## Legend:
##   (i): values of treatment arm i</code></pre>
<p>We see we need 85 participants in each group, (or 86, since we always round the number of observations up, as we can not collect 0.03 of a participant), and so we need 172 participants in total (see G*Power, which rounds up values correctly). Because this is a fixed design, we can also compute this sample size using the <code>pwr</code> package in R or any other power analysis software.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="alpha-spending-functions.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(</span>
<span id="cb11-2"><a href="alpha-spending-functions.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">d =</span> <span class="fl">0.5</span>,</span>
<span id="cb11-3"><a href="alpha-spending-functions.html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb11-4"><a href="alpha-spending-functions.html#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">power =</span> <span class="fl">0.9</span>,</span>
<span id="cb11-5"><a href="alpha-spending-functions.html#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">type=</span><span class="st">&quot;two.sample&quot;</span>,</span>
<span id="cb11-6"><a href="alpha-spending-functions.html#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative=</span><span class="st">&quot;two.sided&quot;</span></span>
<span id="cb11-7"><a href="alpha-spending-functions.html#cb11-7" aria-hidden="true" tabindex="-1"></a>)<span class="sc">$</span>n</span></code></pre></div>
<pre><code>## [1] 85.03128</code></pre>
<p>We can now examine our design above with 2 looks, a Pocock correction, a 2 sided test with an alpha of 0.05. We will look 2 times, and expect a true effect of d = 0.5.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="alpha-spending-functions.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb13-2"><a href="alpha-spending-functions.html#cb13-2" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb13-3"><a href="alpha-spending-functions.html#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb13-4"><a href="alpha-spending-functions.html#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb13-5"><a href="alpha-spending-functions.html#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb13-6"><a href="alpha-spending-functions.html#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb13-7"><a href="alpha-spending-functions.html#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb13-8"><a href="alpha-spending-functions.html#cb13-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-9"><a href="alpha-spending-functions.html#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="alpha-spending-functions.html#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the sample size we need</span></span>
<span id="cb13-11"><a href="alpha-spending-functions.html#cb13-11" aria-hidden="true" tabindex="-1"></a>power_res <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb13-12"><a href="alpha-spending-functions.html#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb13-13"><a href="alpha-spending-functions.html#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb13-14"><a href="alpha-spending-functions.html#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb13-15"><a href="alpha-spending-functions.html#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb13-16"><a href="alpha-spending-functions.html#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb13-17"><a href="alpha-spending-functions.html#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-18"><a href="alpha-spending-functions.html#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="alpha-spending-functions.html#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(power_res)</span></code></pre></div>
<pre><code>## Sample size calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 2 looks (group sequential design), overall 
## significance level 5% (two-sided).
## The sample size was calculated for a two-sample t-test, H0: mu(1) - mu(2) = 0, 
## H1: effect = 0.5, standard deviation = 1, power 90%.
## 
## Stage                                         1      2 
## Information rate                            50%   100% 
## Efficacy boundary (z-value scale)         2.178  2.178 
## Overall power                            0.5893 0.9000 
## Expected number of subjects               132.0 
## Number of subjects                         93.5  187.1 
## Cumulative alpha spent                   0.0294 0.0500 
## Two-sided local significance level       0.0294 0.0294 
## Lower efficacy boundary (t)              -0.458 -0.321 
## Upper efficacy boundary (t)               0.458  0.321 
## Exit probability for efficacy (under H0) 0.0294 
## Exit probability for efficacy (under H1) 0.5893 
## 
## Legend:
##   (t): treatment effect scale</code></pre>
<p>It is important to know that <code>rpact</code> returns the <em>total</em> number of subjects at look 1 (94, so 94/2 = 47 in each group), and the total sample size at look 2 (188, so 188/2 = 94 in each group). This means that at the second look, we are now collecting 188 instead of 172 participants. This is a consequence of lowering our alpha level at each look (from 0.05 to 0.0294). To compensate for the loss of power, we need to increase our sample size. HOwever, this is compensated by the fact that sometimes we will stop after look 1, and thus on average we will collect less participants (even though we might sometimes collect more participants than we would have, had we not used a sequential design). <code>rpact</code> also computes the expected number of participants, in the long run, if the true effect size is d = 0.5.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="alpha-spending-functions.html#cb15-1" aria-hidden="true" tabindex="-1"></a>power_res<span class="sc">$</span>expectedNumberOfSubjectsH1</span></code></pre></div>
<pre><code>## [1] 131.9571</code></pre>
<p>So, in the long run, if the true effect size is d = 0.5, we will collect 132 observations (66 per condition), instead of 172 in total (or 86 per condition).</p>
<p>If we had expected an effect size of d = 0.4, what would the total sample size we needed to collect for 90% power be?</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="alpha-spending-functions.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb17-2"><a href="alpha-spending-functions.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb17-3"><a href="alpha-spending-functions.html#cb17-3" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb17-4"><a href="alpha-spending-functions.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb17-5"><a href="alpha-spending-functions.html#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb17-6"><a href="alpha-spending-functions.html#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb17-7"><a href="alpha-spending-functions.html#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb17-8"><a href="alpha-spending-functions.html#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb17-9"><a href="alpha-spending-functions.html#cb17-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-10"><a href="alpha-spending-functions.html#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="alpha-spending-functions.html#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the sample size we need</span></span>
<span id="cb17-12"><a href="alpha-spending-functions.html#cb17-12" aria-hidden="true" tabindex="-1"></a>power_res <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb17-13"><a href="alpha-spending-functions.html#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb17-14"><a href="alpha-spending-functions.html#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb17-15"><a href="alpha-spending-functions.html#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.4</span>, </span>
<span id="cb17-16"><a href="alpha-spending-functions.html#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb17-17"><a href="alpha-spending-functions.html#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb17-18"><a href="alpha-spending-functions.html#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-19"><a href="alpha-spending-functions.html#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="alpha-spending-functions.html#cb17-20" aria-hidden="true" tabindex="-1"></a>power_res<span class="sc">$</span>expectedNumberOfSubjectsH1</span></code></pre></div>
<pre><code>## [1] 205.328</code></pre>
<p>Because power is a curve, and the true effect size is always unknown, it is useful to plot power across a range of possible effect sizes, so that we can explore the expected sample size, in the long run, if we use a sequential design, for different true effect sizes.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="alpha-spending-functions.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use getPowerMeans and set max N to 188 based on analysis above</span></span>
<span id="cb19-2"><a href="alpha-spending-functions.html#cb19-2" aria-hidden="true" tabindex="-1"></a>sample_res <span class="ot">&lt;-</span> <span class="fu">getPowerMeans</span>(</span>
<span id="cb19-3"><a href="alpha-spending-functions.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb19-4"><a href="alpha-spending-functions.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb19-5"><a href="alpha-spending-functions.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.1</span>), </span>
<span id="cb19-6"><a href="alpha-spending-functions.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb19-7"><a href="alpha-spending-functions.html#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb19-8"><a href="alpha-spending-functions.html#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfSubjects =</span> <span class="dv">188</span>, <span class="co">#rounded up from 187.0829</span></span>
<span id="cb19-9"><a href="alpha-spending-functions.html#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-10"><a href="alpha-spending-functions.html#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="alpha-spending-functions.html#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_res, <span class="at">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<p><img src="11-sequential_files/figure-html/unnamed-chunk-13-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>The blue line indicates the expected number of observations we need to collect. Not surprisingly, when the true effect size is 0, we will almost always continue data collection to the end. We will only stop if we observe a Type 1 error, which is rare, and thus the expected number of observations is very close to 120. On the other side of the graph we see the scenario for when the true effect size is d = 1. With such a large effect size, we will have high power at our first look, and we will almost always be able to stop at the first look. If the true effect size is 0.5, we see we can expect to collect 132 participants on average.</p>
<p>The Pocock correction leads to a substantially lower alpha level at the last look, which requires an increase in sample size to compensate. As we saw before, the O'Brien-Fleming spending function does not require such a severe reduction in the alpha level at the last look. Let's see how well this performs. With 2 looks, this design would not need an increase in sample size at all, yet lower the expected number of observations we would collect to 145. However, let's add 2 additional looks at the data, for 4 looks in total.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="alpha-spending-functions.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now a 4 look OF design</span></span>
<span id="cb20-2"><a href="alpha-spending-functions.html#cb20-2" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb20-3"><a href="alpha-spending-functions.html#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">4</span>,</span>
<span id="cb20-4"><a href="alpha-spending-functions.html#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;OF&quot;</span>,</span>
<span id="cb20-5"><a href="alpha-spending-functions.html#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb20-6"><a href="alpha-spending-functions.html#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb20-7"><a href="alpha-spending-functions.html#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb20-8"><a href="alpha-spending-functions.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-9"><a href="alpha-spending-functions.html#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(seq_design)</span></code></pre></div>
<pre><code>## Sequential analysis with a maximum of 4 looks (group sequential design)
## 
## O&#39;Brien &amp; Fleming design, two-sided overall significance level 5%, power 90%, 
## undefined endpoint.
## 
## Stage                                   1       2       3       4 
## Information rate                      25%     50%     75%    100% 
## Efficacy boundary (z-value scale)   4.049   2.863   2.337   2.024 
## Cumulative alpha spent            &lt;0.0001  0.0042  0.0209  0.0500 
## Overall power                      0.0080  0.2930  0.6960  0.9000</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="alpha-spending-functions.html#cb22-1" aria-hidden="true" tabindex="-1"></a>power_res <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb22-2"><a href="alpha-spending-functions.html#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb22-3"><a href="alpha-spending-functions.html#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb22-4"><a href="alpha-spending-functions.html#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb22-5"><a href="alpha-spending-functions.html#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb22-6"><a href="alpha-spending-functions.html#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb22-7"><a href="alpha-spending-functions.html#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-8"><a href="alpha-spending-functions.html#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="alpha-spending-functions.html#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(power_res)</span></code></pre></div>
<pre><code>## Sample size calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 4 looks (group sequential design), overall 
## significance level 5% (two-sided).
## The sample size was calculated for a two-sample t-test, H0: mu(1) - mu(2) = 0, 
## H1: effect = 0.5, standard deviation = 1, power 90%.
## 
## Stage                                          1       2       3       4 
## Information rate                             25%     50%     75%    100% 
## Efficacy boundary (z-value scale)          4.049   2.863   2.337   2.024 
## Overall power                             0.0080  0.2930  0.6960  0.9000 
## Expected number of subjects                130.5 
## Number of subjects                          43.5    86.9   130.4   173.8 
## Cumulative alpha spent                   &lt;0.0001  0.0042  0.0209  0.0500 
## Two-sided local significance level       &lt;0.0001  0.0042  0.0194  0.0429 
## Lower efficacy boundary (t)               -1.370  -0.631  -0.415  -0.309 
## Upper efficacy boundary (t)                1.370   0.631   0.415   0.309 
## Exit probability for efficacy (under H0) &lt;0.0001  0.0042  0.0167 
## Exit probability for efficacy (under H1)  0.0080  0.2850  0.4031 
## 
## Legend:
##   (t): treatment effect scale</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="alpha-spending-functions.html#cb24-1" aria-hidden="true" tabindex="-1"></a>sample_res <span class="ot">&lt;-</span> <span class="fu">getPowerMeans</span>(</span>
<span id="cb24-2"><a href="alpha-spending-functions.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb24-3"><a href="alpha-spending-functions.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb24-4"><a href="alpha-spending-functions.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.1</span>), </span>
<span id="cb24-5"><a href="alpha-spending-functions.html#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb24-6"><a href="alpha-spending-functions.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb24-7"><a href="alpha-spending-functions.html#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfSubjects =</span> <span class="dv">174</span>, </span>
<span id="cb24-8"><a href="alpha-spending-functions.html#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>We see that with 4 looks, we will not need to increase the maximum sample size a lot, as we only need 174 instead of 172 participants.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="alpha-spending-functions.html#cb25-1" aria-hidden="true" tabindex="-1"></a>power_res<span class="sc">$</span>maxNumberOfSubjects</span></code></pre></div>
<pre><code>## [1] 173.8317</code></pre>
<p>There is a noticeable reduction in the average number of samples we can expect to collect, if the true effect size is d = 0.5.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="alpha-spending-functions.html#cb27-1" aria-hidden="true" tabindex="-1"></a>power_res<span class="sc">$</span>expectedNumberOfSubjectsH1</span></code></pre></div>
<pre><code>## [1] 130.5056</code></pre>
<p>If we plot this expected sample size across different true effect sizes, we see that we become more efficient - only at the cost of 1) analyzing our data 4 times, and 2) needing to preregister our analysis plan. Preregistration is required, because sequential analyses give a lot of additional freedom that can possibly inflate error rates substantially. So performing computations as performed here, and preregistering your analysis plan, is required - but worth it.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="alpha-spending-functions.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample_res, <span class="at">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<p><img src="11-sequential_files/figure-html/unnamed-chunk-17-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>We can redo the power analysis in for the original 2 look design in gsDesign. The graph shows that if the true effect size is d = 0.5 we have approximately 59% power after the first look, and 90% power after the second look, given our adjusted alpha level.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="alpha-spending-functions.html#cb30-1" aria-hidden="true" tabindex="-1"></a>seqdesign <span class="ot">&lt;-</span> <span class="fu">gsDesign</span>(</span>
<span id="cb30-2"><a href="alpha-spending-functions.html#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> <span class="dv">2</span>, <span class="co"># k = number of looks = 2</span></span>
<span id="cb30-3"><a href="alpha-spending-functions.html#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">test.type =</span> <span class="dv">2</span>,</span>
<span id="cb30-4"><a href="alpha-spending-functions.html#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> .<span class="dv">025</span>,</span>
<span id="cb30-5"><a href="alpha-spending-functions.html#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb30-6"><a href="alpha-spending-functions.html#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sfu =</span> <span class="st">&quot;Pocock&quot;</span>,</span>
<span id="cb30-7"><a href="alpha-spending-functions.html#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># gsDesign calculates d as a within subjects d. </span></span>
<span id="cb30-8"><a href="alpha-spending-functions.html#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># We need the /sqrt(2) to turn it from d_z into d</span></span>
<span id="cb30-9"><a href="alpha-spending-functions.html#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">delta =</span> <span class="fl">0.5</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">2</span>), </span>
<span id="cb30-10"><a href="alpha-spending-functions.html#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">delta0 =</span> <span class="dv">0</span>,</span>
<span id="cb30-11"><a href="alpha-spending-functions.html#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">delta1 =</span> <span class="fl">0.5</span></span>
<span id="cb30-12"><a href="alpha-spending-functions.html#cb30-12" aria-hidden="true" tabindex="-1"></a>) <span class="co"># spending function = Pocock</span></span>
<span id="cb30-13"><a href="alpha-spending-functions.html#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="alpha-spending-functions.html#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co"># All required info is in:</span></span>
<span id="cb30-15"><a href="alpha-spending-functions.html#cb30-15" aria-hidden="true" tabindex="-1"></a>seqdesign</span></code></pre></div>
<pre><code>## Symmetric two-sided group sequential design with
## 90 % power and 2.5 % Type I Error.
## Spending computations assume trial stops
## if a bound is crossed.
## 
##              
##   Analysis N   Z   Nominal p  Spend
##          1 47 2.18    0.0147 0.0147
##          2 93 2.18    0.0147 0.0103
##      Total                   0.0250 
## 
## ++ alpha spending:
##  Pocock boundary.
## 
## Boundary crossing probabilities and expected sample size
## assume any cross stops the trial
## 
## Upper boundary (power or Type I Error)
##           Analysis
##    Theta      1      2 Total E{N}
##   0.0000 0.0147 0.0103 0.025 91.1
##   0.3536 0.5893 0.3107 0.900 65.2
## 
## Lower boundary (futility or Type II Error)
##           Analysis
##    Theta      1      2 Total
##   0.0000 0.0147 0.0103 0.025
##   0.3536 0.0000 0.0000 0.000</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="alpha-spending-functions.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can look at the sample sizes as expected compared to a fixed design</span></span>
<span id="cb32-2"><a href="alpha-spending-functions.html#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(seqdesign, <span class="at">plottype =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="11-sequential_files/figure-html/unnamed-chunk-18-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div id="alpha-spending-functions-1" class="section level3" number="13.1.1">
<h3><span class="header-section-number">13.1.1</span> Alpha spending functions</h3>
<p>The Pocock and O'Brien-Fleming spending functions we discussed so far have an important limitation <span class="citation">(<a href="references.html#ref-proschan_statistical_2006" role="doc-biblioref">Proschan et al., 2006</a>)</span>. They require a pre-specified number of looks (e.g., 4) that is equally spaced (e.g., after 25%, 50%, 75%, and 100%). It is not always possible to stop data collection exactly after for example the 50th participant, because you need to pause data collection to analyze the data, which might not be possible if additional sessions are scheduled on the day the 50th observation is collected. An important contribution to the sequential testing literature was made by Lan and DeMets -<span class="citation">Lan &amp; DeMets (<a href="references.html#ref-lan_discrete_1983" role="doc-biblioref">1983</a>)</span> who created <strong>alpha spending functions</strong>, where the boundary at the decision time does not depend on the future decision times or the total number of decision times.</p>
<p>We see the O'Brien-Fleming-like alpha spending function is quite similar to the discrete O'Brien-Fleming bounds.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:spending-comparison-2"></span>
<img src="11-sequential_files/figure-html/spending-comparison-2-1.png" alt="Comparison of the O'Brien-Fleming boundaries and the O'Brien-FLiming-like alpha spending function." width="100%" />
<p class="caption">
Figure 13.3: Comparison of the O'Brien-Fleming boundaries and the O'Brien-FLiming-like alpha spending function.
</p>
</div>
<p>There is a wide range of alpha spending functions possible. In addition to a Pocock-type and O'Brien-Fleming-type alpha spending function <code>rpact</code> has the Kim &amp; DeMets alpha spending function and the Hwang, Shi &amp; DeCani alpha spending function, but users can also specify a custom spending function. Again, the main benefit of these spending functions is that neither the number nor the timing of the looks needs to be specified in advance, which makes alpha spending approaches much more flexible. However, it is important that the decision to perform an interim analysis is not based on collected data, as this can still increase the Type 1 error rate.</p>
<!-- ```{r spending-comparison-3, fig.margin=FALSE, echo=FALSE, fig.cap="Comparison of different alpha spending functions."} -->
<!-- #Pocock type -->
<!-- d1 <- getDesignGroupSequential(typeOfDesign = "asP", -->
<!--                                kMax = 5)  -->
<!-- # OF-like continuous spending function -->
<!-- d2 <- getDesignGroupSequential(typeOfDesign = "asOF", -->
<!--                                kMax = 5) -->
<!-- d3 <- getDesignGroupSequential(typeOfDesign = "asKD", -->
<!--                                kMax = 5) -->
<!-- d4 <- getDesignGroupSequential(typeOfDesign = "asHSD", -->
<!--                                kMax = 5) -->
<!-- designSet <-getDesignSet(designs = c(d1, d2, d3, d4),  -->
<!--                          variedParameters = "typeOfDesign") -->
<!-- plot(designSet, -->
<!--      type = 1) -->
<!-- ``` -->
</div>
<div id="updating-boundaries-during-an-experiment" class="section level3" number="13.1.2">
<h3><span class="header-section-number">13.1.2</span> Updating Boundaries During an Experiment</h3>
<p>Although alpha spending functions control the Type 1 error rate even when there are deviations from the pre-planned looks, this does require recalculating the boundaries based on the amount of information that has been observed. In this example, we follow an <a href="https://vignettes.rpact.org/html/rpact_boundary_update_example.html">rpact vignette</a>. Imagine a two-sided design with an O'Brien-Fleming-type alpha-spending function, and alpha of 0.025, a desired power of 90%, with 3 looks, planned when 50%, 75%, and 100% of our maximum sample has been collected.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="alpha-spending-functions.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Original design:</span></span>
<span id="cb33-2"><a href="alpha-spending-functions.html#cb33-2" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb33-3"><a href="alpha-spending-functions.html#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb33-4"><a href="alpha-spending-functions.html#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb33-5"><a href="alpha-spending-functions.html#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb33-6"><a href="alpha-spending-functions.html#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb33-7"><a href="alpha-spending-functions.html#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb33-8"><a href="alpha-spending-functions.html#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;asOF&quot;</span></span>
<span id="cb33-9"><a href="alpha-spending-functions.html#cb33-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-10"><a href="alpha-spending-functions.html#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="alpha-spending-functions.html#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial sample size calculation</span></span>
<span id="cb33-12"><a href="alpha-spending-functions.html#cb33-12" aria-hidden="true" tabindex="-1"></a>sampleSizeResult <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb33-13"><a href="alpha-spending-functions.html#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb33-14"><a href="alpha-spending-functions.html#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb33-15"><a href="alpha-spending-functions.html#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.5</span>,</span>
<span id="cb33-16"><a href="alpha-spending-functions.html#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb33-17"><a href="alpha-spending-functions.html#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb33-18"><a href="alpha-spending-functions.html#cb33-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span></span>
<span id="cb33-19"><a href="alpha-spending-functions.html#cb33-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-20"><a href="alpha-spending-functions.html#cb33-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-21"><a href="alpha-spending-functions.html#cb33-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize design</span></span>
<span id="cb33-22"><a href="alpha-spending-functions.html#cb33-22" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sampleSizeResult)</span></code></pre></div>
<pre><code>## Sample size calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 3 looks (group sequential design), overall 
## significance level 5% (two-sided).
## The sample size was calculated for a two-sample t-test, H0: mu(1) - mu(2) = 0, 
## H1: effect = 0.5, standard deviation = 1, power 90%.
## 
## Stage                                         1      2      3 
## Information rate                            50%    75%   100% 
## Efficacy boundary (z-value scale)         2.963  2.359  2.014 
## Overall power                            0.2580 0.6853 0.9000 
## Expected number of subjects               132.3 
## Number of subjects                         86.6  129.9  173.2 
## Cumulative alpha spent                   0.0031 0.0193 0.0500 
## Two-sided local significance level       0.0031 0.0183 0.0440 
## Lower efficacy boundary (t)              -0.656 -0.419 -0.308 
## Upper efficacy boundary (t)               0.656  0.419  0.308 
## Exit probability for efficacy (under H0) 0.0031 0.0162 
## Exit probability for efficacy (under H1) 0.2580 0.4273 
## 
## Legend:
##   (t): treatment effect scale</code></pre>
<p>The a-priori power analysis shows that, assuming an effect size of 0.5, we plan to look after 87, 130, 174 observations. Now imagine that due to logistical issues, we do not have to ability to analyze the data until we have collected data from 95, instead of 87, participants. So our first look at the data does not occur at 50% of our sample, but at 95/174 = 54.6%. We can recalculate the alpha levels we should use for this and future looks, and update our sample size calculation. This reveals we should use an alpha level of 0.0048 for the current look (instead of 0.0031). and the next look should occur after 131 participants in total, not 130. We see the differences are not very substantial, but if the deviation from the planned looks increases, the changes might become more impactful. Note that even if the number of looks was not pre-planned, we would use similar calculations at each look, but instead increase the number of looks (e.g., perform an analysis with 1 interim look at time = 95/174, and if the second look occurs after 146 participants, we would run an analysis with two interim looks, one at 95/174 and a second at 146/174, see Proschan et al., 2006, chapter 5).</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="alpha-spending-functions.html#cb35-1" aria-hidden="true" tabindex="-1"></a>seq_design_2 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb35-2"><a href="alpha-spending-functions.html#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb35-3"><a href="alpha-spending-functions.html#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb35-4"><a href="alpha-spending-functions.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb35-5"><a href="alpha-spending-functions.html#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb35-6"><a href="alpha-spending-functions.html#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">informationRates =</span> <span class="fu">c</span>(<span class="dv">95</span><span class="sc">/</span><span class="dv">174</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb35-7"><a href="alpha-spending-functions.html#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;asOF&quot;</span></span>
<span id="cb35-8"><a href="alpha-spending-functions.html#cb35-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-9"><a href="alpha-spending-functions.html#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="alpha-spending-functions.html#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(seq_design_2)</span></code></pre></div>
<pre><code>## Sequential analysis with a maximum of 3 looks (group sequential design)
## 
## O&#39;Brien &amp; Fleming type alpha spending design, two-sided overall 
## significance level 5%, power 90%, undefined endpoint.
## 
## Stage                                  1      2      3 
## Information rate                   54.6%    75%   100% 
## Efficacy boundary (z-value scale)  2.818  2.370  2.015 
## Cumulative alpha spent            0.0048 0.0193 0.0500 
## Overall power                     0.3445 0.6838 0.9000</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="alpha-spending-functions.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Update power analysis</span></span>
<span id="cb37-2"><a href="alpha-spending-functions.html#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="alpha-spending-functions.html#cb37-3" aria-hidden="true" tabindex="-1"></a>power_update_1 <span class="ot">&lt;-</span> <span class="fu">getPowerMeans</span>(</span>
<span id="cb37-4"><a href="alpha-spending-functions.html#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design_2,</span>
<span id="cb37-5"><a href="alpha-spending-functions.html#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb37-6"><a href="alpha-spending-functions.html#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb37-7"><a href="alpha-spending-functions.html#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb37-8"><a href="alpha-spending-functions.html#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb37-9"><a href="alpha-spending-functions.html#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfSubjects =</span> <span class="dv">174</span>, </span>
<span id="cb37-10"><a href="alpha-spending-functions.html#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-11"><a href="alpha-spending-functions.html#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(power_update_1)</span></code></pre></div>
<pre><code>## Power calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 3 looks (group sequential design), overall 
## significance level 5% (two-sided).
## The results were calculated for a two-sample t-test (normal approximation), 
## H0: mu(1) - mu(2) = 0, H1: effect = 0.5, standard deviation = 1, 
## maximum number of subjects = 174.
## 
## Stage                                         1      2      3 
## Information rate                          54.6%    75%   100% 
## Efficacy boundary (z-value scale)         2.818  2.370  2.015 
## Overall power                            0.3516 0.6917 0.9045 
## Expected number of subjects               131.4 
## Number of subjects                         95.0  130.5  174.0 
## Cumulative alpha spent                   0.0048 0.0193 0.0500 
## Two-sided local significance level       0.0048 0.0178 0.0439 
## Lower efficacy boundary (t)              -0.578 -0.415 -0.306 
## Upper efficacy boundary (t)               0.578  0.415  0.306 
## Exit probability for efficacy (under H0) 0.0048 0.0145 
## Exit probability for efficacy (under H1) 0.3516 0.3401 
## 
## Legend:
##   (t): treatment effect scale</code></pre>
<p>What if we had look even later, after 105 participants? Which alpha level should we have used for the first interim test?"</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="alpha-spending-functions.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb39-2"><a href="alpha-spending-functions.html#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb39-3"><a href="alpha-spending-functions.html#cb39-3" aria-hidden="true" tabindex="-1"></a>seq_design_2 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb39-4"><a href="alpha-spending-functions.html#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb39-5"><a href="alpha-spending-functions.html#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">3</span>,</span>
<span id="cb39-6"><a href="alpha-spending-functions.html#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb39-7"><a href="alpha-spending-functions.html#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb39-8"><a href="alpha-spending-functions.html#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">informationRates =</span> <span class="fu">c</span>(<span class="dv">105</span><span class="sc">/</span><span class="dv">174</span>, <span class="fl">0.75</span>, <span class="dv">1</span>),</span>
<span id="cb39-9"><a href="alpha-spending-functions.html#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;asOF&quot;</span></span>
<span id="cb39-10"><a href="alpha-spending-functions.html#cb39-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-11"><a href="alpha-spending-functions.html#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="alpha-spending-functions.html#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Update power analysis</span></span>
<span id="cb39-13"><a href="alpha-spending-functions.html#cb39-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-14"><a href="alpha-spending-functions.html#cb39-14" aria-hidden="true" tabindex="-1"></a>power_update_1 <span class="ot">&lt;-</span> <span class="fu">getPowerMeans</span>(</span>
<span id="cb39-15"><a href="alpha-spending-functions.html#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design_2,</span>
<span id="cb39-16"><a href="alpha-spending-functions.html#cb39-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">groups =</span> <span class="dv">2</span>,</span>
<span id="cb39-17"><a href="alpha-spending-functions.html#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.5</span>, </span>
<span id="cb39-18"><a href="alpha-spending-functions.html#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>, </span>
<span id="cb39-19"><a href="alpha-spending-functions.html#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">allocationRatioPlanned =</span> <span class="dv">1</span>,</span>
<span id="cb39-20"><a href="alpha-spending-functions.html#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfSubjects =</span> <span class="dv">174</span>, </span>
<span id="cb39-21"><a href="alpha-spending-functions.html#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-22"><a href="alpha-spending-functions.html#cb39-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-23"><a href="alpha-spending-functions.html#cb39-23" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(power_update_1)</span></code></pre></div>
<pre><code>## Power calculation for a continuous endpoint
## 
## Sequential analysis with a maximum of 3 looks (group sequential design), overall 
## significance level 5% (two-sided).
## The results were calculated for a two-sample t-test (normal approximation), 
## H0: mu(1) - mu(2) = 0, H1: effect = 0.5, standard deviation = 1, 
## maximum number of subjects = 174.
## 
## Stage                                         1      2      3 
## Information rate                          60.3%    75%   100% 
## Efficacy boundary (z-value scale)         2.660  2.388  2.016 
## Overall power                            0.4610 0.6894 0.9043 
## Expected number of subjects               132.3 
## Number of subjects                        105.0  130.5  174.0 
## Cumulative alpha spent                   0.0078 0.0193 0.0500 
## Two-sided local significance level       0.0078 0.0170 0.0438 
## Lower efficacy boundary (t)              -0.519 -0.418 -0.306 
## Upper efficacy boundary (t)               0.519  0.418  0.306 
## Exit probability for efficacy (under H0) 0.0078 0.0115 
## Exit probability for efficacy (under H1) 0.4610 0.2284 
## 
## Legend:
##   (t): treatment effect scale</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="alpha-spending-functions.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># So the answer is 0.0078</span></span></code></pre></div>
</div>
</div>
<div id="test-for-non-inferiority" class="section level2" number="13.2">
<h2><span class="header-section-number">13.2</span> Test for (non-)inferiority</h2>
<p>In an equivalence test, it is common to compare the observed effect against an upper and lower bound of the equivalence range. <code>rpact</code> supports <strong>non-inferiority and inferiority tests</strong>, where the null hypothesis is one of the equivalence bound (e.g., d = 0.5) and the alternative hypothesis is an effect of 0. In essence, this is a directional equivalence test where we consider an effect too small to be meaningful (inferior) if it is smaller than the upper bound of the equivalence range, for example d = 0.5 - also when the effect is on the opposite direction (e.g., d = 0.7). Alternatively, we can be interested in showing an effect is not smaller than the lower equivalence bound, for example d = -0.5, which allows us to conclude the effect is not more negative (non-inferior) than the smallest effect we care about. We can first examine a normal power analysis for a non-inferiority test for a fixed design for 90% power.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="alpha-spending-functions.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First for no sequential design</span></span>
<span id="cb42-2"><a href="alpha-spending-functions.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Corresponds to PASS software</span></span>
<span id="cb42-3"><a href="alpha-spending-functions.html#cb42-3" aria-hidden="true" tabindex="-1"></a>sampleSizeNoninf <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb42-4"><a href="alpha-spending-functions.html#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">thetaH0 =</span> <span class="sc">-</span><span class="fl">0.5</span>,</span>
<span id="cb42-5"><a href="alpha-spending-functions.html#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.0</span>,</span>
<span id="cb42-6"><a href="alpha-spending-functions.html#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb42-7"><a href="alpha-spending-functions.html#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb42-8"><a href="alpha-spending-functions.html#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb42-9"><a href="alpha-spending-functions.html#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">1</span>,</span>
<span id="cb42-10"><a href="alpha-spending-functions.html#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span></span>
<span id="cb42-11"><a href="alpha-spending-functions.html#cb42-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-12"><a href="alpha-spending-functions.html#cb42-12" aria-hidden="true" tabindex="-1"></a>sampleSizeNoninf</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Critical values                              : 1.645 
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1000 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Theta H0                                     : -0.5 
##   Alternatives                                 : 0 
## 
## Default parameters:
##   Mean ratio                                   : FALSE 
##   Normal approximation                         : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Number of subjects fixed                     : 138.4 
##   Number of subjects fixed (1)                 : 69.2 
##   Number of subjects fixed (2)                 : 69.2 
##   Critical values (treatment effect scale)     : -0.218 
## 
## Legend:
##   (i): values of treatment arm i</code></pre>
<p>Now, we can repeat the analysis, but first specify our original sequential design, with the small deviation that we need to specify a one-sided test. In practice, this will yield identical results as a power analysis for an equivalence test with symmetrical equivalence bounds and an expected true effect size of zero. However, the use of one-sided test often also directly reflects our hypothesis interest, so it might often be the test that reflects your research question.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="alpha-spending-functions.html#cb44-1" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb44-2"><a href="alpha-spending-functions.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb44-3"><a href="alpha-spending-functions.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb44-4"><a href="alpha-spending-functions.html#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">1</span>,</span>
<span id="cb44-5"><a href="alpha-spending-functions.html#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb44-6"><a href="alpha-spending-functions.html#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb44-7"><a href="alpha-spending-functions.html#cb44-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-8"><a href="alpha-spending-functions.html#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="alpha-spending-functions.html#cb44-9" aria-hidden="true" tabindex="-1"></a>sampleSizeNoninf <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb44-10"><a href="alpha-spending-functions.html#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb44-11"><a href="alpha-spending-functions.html#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">thetaH0 =</span> <span class="sc">-</span><span class="fl">0.5</span>,</span>
<span id="cb44-12"><a href="alpha-spending-functions.html#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.0</span>,</span>
<span id="cb44-13"><a href="alpha-spending-functions.html#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb44-14"><a href="alpha-spending-functions.html#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span></span>
<span id="cb44-15"><a href="alpha-spending-functions.html#cb44-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-16"><a href="alpha-spending-functions.html#cb44-16" aria-hidden="true" tabindex="-1"></a>sampleSizeNoninf</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Information rates                            : 0.500, 1.000 
##   Critical values                              : 1.875, 1.875 
##   Futility bounds (non-binding)                : -Inf 
##   Cumulative alpha spending                    : 0.03037, 0.05000 
##   Local one-sided significance levels          : 0.03037, 0.03037 
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1000 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Theta H0                                     : -0.5 
##   Alternatives                                 : 0 
## 
## Default parameters:
##   Mean ratio                                   : FALSE 
##   Normal approximation                         : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Reject per stage [1]                         : 0.6195 
##   Reject per stage [2]                         : 0.2805 
##   Early stop                                   : 0.6195 
##   Maximum number of subjects                   : 153.6 
##   Maximum number of subjects (1)               : 76.8 
##   Maximum number of subjects (2)               : 76.8 
##   Number of subjects [1]                       : 76.8 
##   Number of subjects [2]                       : 153.6 
##   Expected number of subjects under H0         : 151.2 
##   Expected number of subjects under H0/H1      : 137 
##   Expected number of subjects under H1         : 106 
##   Critical values (treatment effect scale) [1] : -0.0654 
##   Critical values (treatment effect scale) [2] : -0.1950 
## 
## Legend:
##   (i): values of treatment arm i
##   [k]: values at stage k</code></pre>
<p>We see that compared to a fixed design, our maximum sample size has increased from 139 to 154. However, if there really is no effect (d = 0, the alternative hypothesis of our non-inferiority test is true) then we should expect to collect on average 106 observations, in the long run. Of course, as we have seen above, more efficient designs can be designed.</p>
<p>If we had tested against a lower bound of d = -0.3, which sample size would we need?</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="alpha-spending-functions.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb46-2"><a href="alpha-spending-functions.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb46-3"><a href="alpha-spending-functions.html#cb46-3" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb46-4"><a href="alpha-spending-functions.html#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb46-5"><a href="alpha-spending-functions.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb46-6"><a href="alpha-spending-functions.html#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">1</span>,</span>
<span id="cb46-7"><a href="alpha-spending-functions.html#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb46-8"><a href="alpha-spending-functions.html#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb46-9"><a href="alpha-spending-functions.html#cb46-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-10"><a href="alpha-spending-functions.html#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="alpha-spending-functions.html#cb46-11" aria-hidden="true" tabindex="-1"></a>sampleSizeNoninf <span class="ot">&lt;-</span> <span class="fu">getSampleSizeMeans</span>(</span>
<span id="cb46-12"><a href="alpha-spending-functions.html#cb46-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">design =</span> seq_design,</span>
<span id="cb46-13"><a href="alpha-spending-functions.html#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">thetaH0 =</span> <span class="sc">-</span><span class="fl">0.3</span>,</span>
<span id="cb46-14"><a href="alpha-spending-functions.html#cb46-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="fl">0.0</span>,</span>
<span id="cb46-15"><a href="alpha-spending-functions.html#cb46-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDev =</span> <span class="dv">1</span>,</span>
<span id="cb46-16"><a href="alpha-spending-functions.html#cb46-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalApproximation =</span> <span class="cn">FALSE</span></span>
<span id="cb46-17"><a href="alpha-spending-functions.html#cb46-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-18"><a href="alpha-spending-functions.html#cb46-18" aria-hidden="true" tabindex="-1"></a>sampleSizeNoninf</span></code></pre></div>
<pre><code>## Design plan parameters and output for means:
## 
## Design parameters:
##   Information rates                            : 0.500, 1.000 
##   Critical values                              : 1.875, 1.875 
##   Futility bounds (non-binding)                : -Inf 
##   Cumulative alpha spending                    : 0.03037, 0.05000 
##   Local one-sided significance levels          : 0.03037, 0.03037 
##   Significance level                           : 0.0500 
##   Type II error rate                           : 0.1000 
##   Test                                         : one-sided 
## 
## User defined parameters:
##   Theta H0                                     : -0.3 
##   Alternatives                                 : 0 
## 
## Default parameters:
##   Mean ratio                                   : FALSE 
##   Normal approximation                         : FALSE 
##   Standard deviation                           : 1 
##   Treatment groups                             : 2 
##   Planned allocation ratio                     : 1 
## 
## Sample size and output:
##   Reject per stage [1]                         : 0.6195 
##   Reject per stage [2]                         : 0.2805 
##   Early stop                                   : 0.6195 
##   Maximum number of subjects                   : 423.8 
##   Maximum number of subjects (1)               : 211.9 
##   Maximum number of subjects (2)               : 211.9 
##   Number of subjects [1]                       : 211.9 
##   Number of subjects [2]                       : 423.8 
##   Expected number of subjects under H0         : 417.4 
##   Expected number of subjects under H0/H1      : 378 
##   Expected number of subjects under H1         : 292.5 
##   Critical values (treatment effect scale) [1] : -0.0409 
##   Critical values (treatment effect scale) [2] : -0.1173 
## 
## Legend:
##   (i): values of treatment arm i
##   [k]: values at stage k</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="alpha-spending-functions.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># So the answer is 424 in total, 212 in each group</span></span></code></pre></div>
</div>
<div id="stopping-for-futility" class="section level2" number="13.3">
<h2><span class="header-section-number">13.3</span> Stopping for futility</h2>
<p>To declare that a meaningful effect is absent, one should specify a smallest effect size of interest, and perform an equivalence test. However, sometimes you might not be able to justify a choice for a smallest effect size of interest. In such study designs, it is still possible to decide to stop a study at an interim look because continuing data collection is impossible of unlikely to yield a significant effect.</p>
<p>In the most extreme case, it will be impossible for the additional data you collect to lead to a statistically significant result. To illustrate this in a hypothetical scenario, imagine that after collecting 90 out of 100 observations, the observed effect size is very close to zero. The critical effect size in an independent <em>t</em>-test with 50 participants in each group and an alpha level of, say, 0.02, is d = 0.47. If your primary dependent variable is measured on a 7 point Likert scale, it might be that even if every of the remaining 5 participants in group 1 answer 1, and every of the remaining participants in group 2 answers 7, the effect size in the total group of 100 participants can never reach the critical effect size. If the goal of your study was to detect significant effect, at this point you know for a fact that goal will not be reached. Stopping a study at an interim analysis because the final result will not yield a significant effect is called <strong>curtailment</strong>.</p>
<p>In less extreme cases, it might still be possible for the study to observe a significant effect, but the probability is extremely low. The probability of finding a significant result, given the data that have been observed up to an interim analysis, is called <strong>conditional power</strong>. Let's imagine that in our previous example, after 50 observations, we also observed an effect zero close to zero, and we would have 25% power to find a significant result, for some expected effect size. Wassmer and Brannath -<span class="citation">Wassmer &amp; Brannath (<a href="references.html#ref-wassmer_group_2016" role="doc-biblioref">2016</a>)</span> write, due to the direct relation between conditional power and p-values, stopping the trial if the conditional power is lower than some desired threshold is equivalent to stopping a study if the <em>p</em>-value is larger than some critical level. <code>rpact</code> allows us to compute conditional power. Let's assume that in our 2-stage design, after the first interim analysis, we observe an effect of d = 0.1, while we expected d = 0.5. What is the probability that, if the true effect size is d = 0.5, we find a significant result after adding the second batch of 94 participants?</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="alpha-spending-functions.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb49-2"><a href="alpha-spending-functions.html#cb49-2" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb49-3"><a href="alpha-spending-functions.html#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb49-4"><a href="alpha-spending-functions.html#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb49-5"><a href="alpha-spending-functions.html#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb49-6"><a href="alpha-spending-functions.html#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb49-7"><a href="alpha-spending-functions.html#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb49-8"><a href="alpha-spending-functions.html#cb49-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-9"><a href="alpha-spending-functions.html#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="alpha-spending-functions.html#cb49-10" aria-hidden="true" tabindex="-1"></a>dataMeans <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(</span>
<span id="cb49-11"><a href="alpha-spending-functions.html#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="fu">c</span>(<span class="dv">94</span>), </span>
<span id="cb49-12"><a href="alpha-spending-functions.html#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="fu">c</span>(<span class="dv">94</span>), </span>
<span id="cb49-13"><a href="alpha-spending-functions.html#cb49-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">means1 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>), <span class="co">#for directional test, means 1 &gt; means 2</span></span>
<span id="cb49-14"><a href="alpha-spending-functions.html#cb49-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">means2 =</span> <span class="fu">c</span>(<span class="dv">1</span>),</span>
<span id="cb49-15"><a href="alpha-spending-functions.html#cb49-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs1 =</span><span class="fu">c</span>(<span class="dv">1</span>), </span>
<span id="cb49-16"><a href="alpha-spending-functions.html#cb49-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs2 =</span><span class="fu">c</span>(<span class="dv">1</span>))</span>
<span id="cb49-17"><a href="alpha-spending-functions.html#cb49-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-18"><a href="alpha-spending-functions.html#cb49-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Get analysis results</span></span>
<span id="cb49-19"><a href="alpha-spending-functions.html#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect sizes are raw effect sizes, not standardized.</span></span>
<span id="cb49-20"><a href="alpha-spending-functions.html#cb49-20" aria-hidden="true" tabindex="-1"></a>stage_res <span class="ot">&lt;-</span> <span class="fu">getStageResults</span>(seq_design, </span>
<span id="cb49-21"><a href="alpha-spending-functions.html#cb49-21" aria-hidden="true" tabindex="-1"></a>                   <span class="at">equalVariances =</span> <span class="cn">TRUE</span>,</span>
<span id="cb49-22"><a href="alpha-spending-functions.html#cb49-22" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dataInput =</span> dataMeans)</span>
<span id="cb49-23"><a href="alpha-spending-functions.html#cb49-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-24"><a href="alpha-spending-functions.html#cb49-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute conditional power after the first look</span></span>
<span id="cb49-25"><a href="alpha-spending-functions.html#cb49-25" aria-hidden="true" tabindex="-1"></a><span class="fu">getConditionalPower</span>(<span class="at">design =</span> seq_design,</span>
<span id="cb49-26"><a href="alpha-spending-functions.html#cb49-26" aria-hidden="true" tabindex="-1"></a>                    <span class="at">stageResults =</span> stage_res, </span>
<span id="cb49-27"><a href="alpha-spending-functions.html#cb49-27" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nPlanned =</span> <span class="fu">c</span>(<span class="dv">94</span>),</span>
<span id="cb49-28"><a href="alpha-spending-functions.html#cb49-28" aria-hidden="true" tabindex="-1"></a>                    <span class="at">thetaH1 =</span> <span class="fl">0.5</span>,</span>
<span id="cb49-29"><a href="alpha-spending-functions.html#cb49-29" aria-hidden="true" tabindex="-1"></a>                    <span class="at">assumedStDev =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Conditional power results means:
## 
## User defined parameters:
##   Planned sample size                          : NA, 94 
##   Assumed effect under alternative             : 0.5 
##   Assumed standard deviation                   : 1 
## 
## Default parameters:
##   Planned allocation ratio                     : 1 
## 
## Output:
##   Conditional power                            : NA, 0.511</code></pre>
<p>We see the answer if that we have 51% power. At this point, one might decide to stop for <strong>futility</strong>. You might decide it is not worth continuing the data collection. One the one hand, 51% power is not nothing, but on the other hand, your expectation that the true effect size is d = 0.5 has become somewhat less likely. One might choose to perform a <strong>conditional power analysis</strong>, and increase the sample size you were willing to collect. Given that we have already collected data, it seems intuitive to calculate condition power not based on the effect size we originally expected, but by updating our prior belief about the true effect size given the observed data. This Bayesian alternative is called <strong>predictive power</strong> <span class="citation">(<a href="references.html#ref-spiegelhalter_monitoring_1986" role="doc-biblioref">Spiegelhalter et al., 1986</a>)</span>. You will probably want to consult a statistician before making these choices.</p>
<p>Repeat the conditional power analysis above, assuming you now think the true effect size is d = 0.3, instead of d = 0.5.")</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="alpha-spending-functions.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure you have rpact installed</span></span>
<span id="cb51-2"><a href="alpha-spending-functions.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb51-3"><a href="alpha-spending-functions.html#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb51-4"><a href="alpha-spending-functions.html#cb51-4" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb51-5"><a href="alpha-spending-functions.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb51-6"><a href="alpha-spending-functions.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb51-7"><a href="alpha-spending-functions.html#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb51-8"><a href="alpha-spending-functions.html#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb51-9"><a href="alpha-spending-functions.html#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb51-10"><a href="alpha-spending-functions.html#cb51-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-11"><a href="alpha-spending-functions.html#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="alpha-spending-functions.html#cb51-12" aria-hidden="true" tabindex="-1"></a>dataMeans <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(</span>
<span id="cb51-13"><a href="alpha-spending-functions.html#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="fu">c</span>(<span class="dv">94</span>), </span>
<span id="cb51-14"><a href="alpha-spending-functions.html#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="fu">c</span>(<span class="dv">94</span>), </span>
<span id="cb51-15"><a href="alpha-spending-functions.html#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">means1 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>), <span class="co">#for directional test, means 1 &gt; means 2</span></span>
<span id="cb51-16"><a href="alpha-spending-functions.html#cb51-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">means2 =</span> <span class="fu">c</span>(<span class="dv">1</span>),</span>
<span id="cb51-17"><a href="alpha-spending-functions.html#cb51-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs1 =</span><span class="fu">c</span>(<span class="dv">1</span>), </span>
<span id="cb51-18"><a href="alpha-spending-functions.html#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs2 =</span><span class="fu">c</span>(<span class="dv">1</span>))</span>
<span id="cb51-19"><a href="alpha-spending-functions.html#cb51-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-20"><a href="alpha-spending-functions.html#cb51-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Get analysis results</span></span>
<span id="cb51-21"><a href="alpha-spending-functions.html#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect sizes are raw effect sizes, not standardized.</span></span>
<span id="cb51-22"><a href="alpha-spending-functions.html#cb51-22" aria-hidden="true" tabindex="-1"></a>stage_res <span class="ot">&lt;-</span> <span class="fu">getStageResults</span>(seq_design, </span>
<span id="cb51-23"><a href="alpha-spending-functions.html#cb51-23" aria-hidden="true" tabindex="-1"></a>                   <span class="at">equalVariances =</span> <span class="cn">TRUE</span>,</span>
<span id="cb51-24"><a href="alpha-spending-functions.html#cb51-24" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dataInput =</span> dataMeans)</span>
<span id="cb51-25"><a href="alpha-spending-functions.html#cb51-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-26"><a href="alpha-spending-functions.html#cb51-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute conditional power after the first look</span></span>
<span id="cb51-27"><a href="alpha-spending-functions.html#cb51-27" aria-hidden="true" tabindex="-1"></a><span class="fu">getConditionalPower</span>(<span class="at">design =</span> seq_design,</span>
<span id="cb51-28"><a href="alpha-spending-functions.html#cb51-28" aria-hidden="true" tabindex="-1"></a>                    <span class="at">stageResults =</span> stage_res, </span>
<span id="cb51-29"><a href="alpha-spending-functions.html#cb51-29" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nPlanned =</span> <span class="fu">c</span>(<span class="dv">94</span>),</span>
<span id="cb51-30"><a href="alpha-spending-functions.html#cb51-30" aria-hidden="true" tabindex="-1"></a>                    <span class="at">thetaH1 =</span> <span class="fl">0.3</span>,</span>
<span id="cb51-31"><a href="alpha-spending-functions.html#cb51-31" aria-hidden="true" tabindex="-1"></a>                    <span class="at">assumedStDev =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Conditional power results means:
## 
## User defined parameters:
##   Planned sample size                          : NA, 94 
##   Assumed effect under alternative             : 0.3 
##   Assumed standard deviation                   : 1 
## 
## Default parameters:
##   Planned allocation ratio                     : 1 
## 
## Output:
##   Conditional power                            : NA, 0.1731</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="alpha-spending-functions.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># So the answer is conditional power is 17.31%</span></span></code></pre></div>
<p>Stopping for futility has benefits and downsides <span class="citation">(<a href="references.html#ref-schoenfeld_procon_2005" role="doc-biblioref">Schoenfeld &amp; Meade, 2005</a>)</span>. The biggest problem with stopping for futility is that it makes it impossible to interpret negative results. We do not learn whether the effect is too small to be meaningful, as we would learn in an equivalence test. Clearly, designing a study is most informative if we specify a smallest effect of interest, and perform a formal equivalence test. However, when specifying a smallest effect size of interest is not possible, stopping for futility might be an alternative to carefully consider. Stopping for futility does not impact the Type 1 error rate of a study because we are not declaring an effect if no effect is present.</p>
<p>As an illustration of a simple stopping rule for futility. let's imagine a researcher is willing to stop for futility because the observed effect size is zero or in the wrong direction. This is only possible in a directional (one-sided) test. In other words, if we predict an effect larger than zero (e.g., d = 0.5), and we observe an effect ≤ 0, we will stop the data collection . Note that it is perfectly possible, due to random variation, that we observe an effect size smaller than 0, especially in small noisy samples where the true effect size is large. But this simple stopping rule will illustrate the basic idea of stopping for futility. In Figure <a href="alpha-spending-functions.html#fig:futility1">13.4</a> the red line indicates critical values to declare a significant effect. For example if we observe a <em>Z</em>-value larger than 2.134 at the second interim analysis, we can stop the study and reject the null hypothesis. However, if at the second interim analysis we observe a <em>Z</em>-score smaller than or equal to 0, the observed effect size is either 0 or smaller, and we can stop the trial for futility.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:futility1"></span>
<img src="11-sequential_files/figure-html/futility1-1.png" alt="O'Brien-Fleming-type boundaries for 3 looks to declare a significant effect (red line) or to stop for futility (blue line)." width="100%" />
<p class="caption">
Figure 13.4: O'Brien-Fleming-type boundaries for 3 looks to declare a significant effect (red line) or to stop for futility (blue line).
</p>
</div>
<p>Instead of setting the <em>z</em>-scores for futility manually, we can also compute bounds based on a beta-spending function. At the last look in our sequential design, which we designed to have 90% power, we are willing to accept the null-hypothesis with a 10% error rate. Just as we are willing to distribute our Type 1 error rate across interim analyses, we might be willing to stop for futility at earlier looks, even if we are then making a Type 2 error. If there actually is no effect, such designs are more efficient. One can choose binding and non-binding beta-spending functions (meaning one has to stop, or one can continue on) - the latter is typically recommended. Adding futility bounds based on beta-spending functions reduce power, and increase the required sample size to reach a desired power, but this is on average compensated by the fact you studies stop earlier due to futility, and can thus make designs more efficient. In the plot below, we use an O'Brien-Fleming type design for both the alpha-spending function and the beta-spending function.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="alpha-spending-functions.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Formal beta spending function</span></span>
<span id="cb54-2"><a href="alpha-spending-functions.html#cb54-2" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb54-3"><a href="alpha-spending-functions.html#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">1</span>,</span>
<span id="cb54-4"><a href="alpha-spending-functions.html#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb54-5"><a href="alpha-spending-functions.html#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb54-6"><a href="alpha-spending-functions.html#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.33</span>, <span class="fl">0.67</span>, <span class="dv">1</span>),</span>
<span id="cb54-7"><a href="alpha-spending-functions.html#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;asOF&quot;</span>,</span>
<span id="cb54-8"><a href="alpha-spending-functions.html#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeBetaSpending=</span><span class="st">&quot;bsOF&quot;</span>,</span>
<span id="cb54-9"><a href="alpha-spending-functions.html#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">bindingFutility =</span> <span class="cn">FALSE</span></span>
<span id="cb54-10"><a href="alpha-spending-functions.html#cb54-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-11"><a href="alpha-spending-functions.html#cb54-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-12"><a href="alpha-spending-functions.html#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(design)</span></code></pre></div>
<p><img src="11-sequential_files/figure-html/unnamed-chunk-27-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div id="sequential-analyses-using-bayes-factors." class="section level3" number="13.3.1">
<h3><span class="header-section-number">13.3.1</span> Sequential analyses using Bayes factors.</h3>
<p>There is a discussion in the literature about when optional stopping is a problem for Bayesians. The answer, as always, depends on what type of Bayesian you are. Subjective Bayesians are not interested in error rates. They continuously update personal beliefs based on the data, and they never make a dichotomous claim or decision purely based on the data. Empirical Bayesians often stress that Bayes factors are continuous measures of evidence, but also introduce dichotomous thresholds. For example, <a href="https://media.nature.com/original/nature-cms/uploads/ckeditor/attachments/4825/RegisteredReportsGuidelines_NatureHumanBehaviour.pdf">submission guidelines</a> for Nature Human Behavior state "For inference by Bayes factors, authors must be able to guarantee data collection until the Bayes factor is at least 10 times in favour of the experimental hypothesis over the null hypothesis (or vice versa)." If you aim to claim your statistical hypothesis is supported or not based on the on whether the Bayes factors is high or low, you can make erroneous claims, and optional stopping can inflate error rates.</p>
<p>Controlling long run error rates is always a frequentist procedure (even if the statistic that is computed to make dichotomous claims is a Bayes factor). Unlike in the case of frequentist sequential analyses, there are no analytical solutions to control error rates when Bayes factors are computed at each interim analysis, but simulation approaches have been developed for sequential hypothesis testing with Bayes factors <span class="citation">(<a href="references.html#ref-schonbrodt_sequential_2017" role="doc-biblioref">Schönbrodt et al., 2017</a>)</span>. In these approaches, one still needs to make an assumption about the true effect size, as the true effect size impacts the error rates, but one also needs to specify the number of looks in advance (or compute error rates for a worst case scenario where you analyse data after every look), and (as always when using Bayes factors) make a decision about the prior. A downside of Bayesian sequential analyses is that if you commit to continuing data collection until you read a Bayes factor threshold of for example 10, you might need to collect hundreds, or even thousands, of observations, depending on the true effect size. This can make studies difficult to plan. One can specify a maximum sample size, but then studies will remain inconclusive. An online app to examine the sample sizes required in sequential hypothesis tests using Bayes factors is available <a href="http://shinyapps.org/apps/BFDA/">online</a>, and accompanies a tutorial paper <span class="citation">(<a href="references.html#ref-stefan_tutorial_2019" role="doc-biblioref">Stefan et al., 2019</a>)</span>.</p>
</div>
<div id="reporting-results-after-a-sequential-analysis." class="section level3" number="13.3.2">
<h3><span class="header-section-number">13.3.2</span> Reporting results after a sequential analysis.</h3>
<p>When reporting results for a sequential analyses, there are two things to keep in mind. First, whenever we stop a study early because of a significant effect, there is a risk that we stopped on a random high estimate. This means the effect sizes is larger than the true effect size. Approaches have been developed to correct effect size estimates for single studies. These correction aim to retrieve an accurate effect size estimate from a study that was designed with the goal to examine whether the null hypothesis could be rejected. As <span class="citation">Schönbrodt et al. (<a href="references.html#ref-schonbrodt_sequential_2017" role="doc-biblioref">2017</a>)</span> show, a meta-analysis of studies that used sequential designs will yield an accurate effect size, because studies that stop early, and have smaller sample sizes, are weighed less and are compensated by the larger studies that did not stop early. Although researchers are free to report adjusted effect size estimates after a sequential design, it might be more important not to confuse the question a study is designed to answer. If you want to accurately estimate an effect size, design a study based on parameter accuracy. If you want to efficiently examined whether you can reject the null hypothesis, design a study where you perform a sequential analysis.</p>
<p>The same issue occurs when reporting <em>p</em>-values. A <em>p</em>-value is the probability of observing a result at least as extreme as the result that was observed, given that the null hypothesis is true. When using sequential analyses, more than
one analysis is performed, and the definition of a result “at least as extreme” needs to be redefined. The recommended procedure to determine what “at least as extreme” means is to order the outcomes of a series of sequential analyses in terms of the stage at which the study was stopped, where earlier stopping is more extreme than later stopping, and where studies with higher Z-values are more extreme, when different studies are stopped at the same time <span class="citation">(<a href="references.html#ref-proschan_statistical_2006" role="doc-biblioref">Proschan et al., 2006</a>)</span>. This is referred to as <strong>stagewise ordering</strong>. Similalry, procedures exist to compute adjusted confidence intervals for sequential designs. <code>rpact</code> allows one to compute stagewise ordered <em>p</em>-values for some designs (e.g., <em>t</em>-tests). For practical purposes, reporting these adjusted estimates might be less important in studies design to test a hypothesis efficiently, while controlling error rates, and reporting a normal <em>p</em>-value, effect size estimate, and confidence interval will most likely suffice, as long as one keeps in mind that the sequential design has a small impact on these values, and that accurate effect size estimates require a meta-analytic estimate from multiple studies, some of which stopped earlier, and some at the final look.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="alpha-spending-functions.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Our 2 look design</span></span>
<span id="cb55-2"><a href="alpha-spending-functions.html#cb55-2" aria-hidden="true" tabindex="-1"></a>seq_design <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(</span>
<span id="cb55-3"><a href="alpha-spending-functions.html#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">kMax =</span> <span class="dv">2</span>,</span>
<span id="cb55-4"><a href="alpha-spending-functions.html#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">typeOfDesign =</span> <span class="st">&quot;P&quot;</span>,</span>
<span id="cb55-5"><a href="alpha-spending-functions.html#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sided =</span> <span class="dv">2</span>,</span>
<span id="cb55-6"><a href="alpha-spending-functions.html#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="fl">0.05</span>,</span>
<span id="cb55-7"><a href="alpha-spending-functions.html#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">beta =</span> <span class="fl">0.1</span></span>
<span id="cb55-8"><a href="alpha-spending-functions.html#cb55-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-9"><a href="alpha-spending-functions.html#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="alpha-spending-functions.html#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify our observed data after N = 188</span></span>
<span id="cb55-11"><a href="alpha-spending-functions.html#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Note, you enter the means and sd for each batch.</span></span>
<span id="cb55-12"><a href="alpha-spending-functions.html#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="co"># So for the second look, you ignore the 94 observations from look 1</span></span>
<span id="cb55-13"><a href="alpha-spending-functions.html#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternatively use overallN1 etc, see help file</span></span>
<span id="cb55-14"><a href="alpha-spending-functions.html#cb55-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-15"><a href="alpha-spending-functions.html#cb55-15" aria-hidden="true" tabindex="-1"></a>dataMeans <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(</span>
<span id="cb55-16"><a href="alpha-spending-functions.html#cb55-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="fu">c</span>(<span class="dv">94</span>,<span class="dv">94</span>), </span>
<span id="cb55-17"><a href="alpha-spending-functions.html#cb55-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="fu">c</span>(<span class="dv">94</span>,<span class="dv">94</span>), </span>
<span id="cb55-18"><a href="alpha-spending-functions.html#cb55-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">means1 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>,<span class="fl">1.5</span>), <span class="co">#for directional test, means 1 &gt; means 2</span></span>
<span id="cb55-19"><a href="alpha-spending-functions.html#cb55-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">means2 =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb55-20"><a href="alpha-spending-functions.html#cb55-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs1 =</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb55-21"><a href="alpha-spending-functions.html#cb55-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs2 =</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb55-22"><a href="alpha-spending-functions.html#cb55-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-23"><a href="alpha-spending-functions.html#cb55-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Get analysis results</span></span>
<span id="cb55-24"><a href="alpha-spending-functions.html#cb55-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Effect sizes are raw effect sizes, not standardized.</span></span>
<span id="cb55-25"><a href="alpha-spending-functions.html#cb55-25" aria-hidden="true" tabindex="-1"></a><span class="fu">getAnalysisResults</span>(seq_design, </span>
<span id="cb55-26"><a href="alpha-spending-functions.html#cb55-26" aria-hidden="true" tabindex="-1"></a>                   <span class="at">equalVariances =</span> <span class="cn">TRUE</span>,</span>
<span id="cb55-27"><a href="alpha-spending-functions.html#cb55-27" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dataInput =</span> dataMeans)</span></code></pre></div>
<pre><code>## [PROGRESS] Stage results calculated [0.0479 secs] 
## [PROGRESS] Conditional power calculated [0.0459 secs] 
## [PROGRESS] Conditional rejection probabilities (CRP) calculated [0.0021 secs] 
## [PROGRESS] Repeated confidence interval of stage 1 calculated [0.9621 secs] 
## [PROGRESS] Repeated confidence interval of stage 2 calculated [1.2 secs] 
## [PROGRESS] Repeated confidence interval calculated [2.17 secs] 
## [PROGRESS] Repeated p-values of stage 1 calculated [0.3504 secs] 
## [PROGRESS] Repeated p-values of stage 2 calculated [0.3072 secs] 
## [PROGRESS] Repeated p-values calculated [0.6606 secs] 
## [PROGRESS] Final p-value calculated [0.0036 secs] 
## [PROGRESS] Final confidence interval calculated [0.1496 secs]</code></pre>
<pre><code>## Analysis results (means of 2 groups, group sequential design):
## 
## Design parameters:
##   Information rates                            : 0.500, 1.000 
##   Critical values                              : 2.178, 2.178 
##   Futility bounds (non-binding)                : -Inf 
##   Cumulative alpha spending                    : 0.02939, 0.05000 
##   Local one-sided significance levels          : 0.01469, 0.01469 
##   Significance level                           : 0.0500 
##   Test                                         : two-sided 
## 
## User defined parameters: not available
## 
## Default parameters:
##   Normal approximation                         : FALSE 
##   Direction upper                              : TRUE 
##   Theta H0                                     : 0 
##   Equal variances                              : TRUE 
## 
## Stage results:
##   Cumulative effect sizes                      : 0.1, 0.3 
##   Cumulative (pooled) standard deviations      : 1.000, 1.007 
##   Stage-wise test statistics                   : 0.686, 3.428 
##   Stage-wise p-values                          : 0.2469204, 0.0003745 
##   Overall test statistics                      : 0.686, 2.887 
##   Overall p-values                             : 0.246920, 0.002055 
## 
## Analysis results:
##   Assumed standard deviation                   : 1.007 
##   Actions                                      : continue, reject 
##   Conditional rejection probability            : 0.01656, NA 
##   Conditional power                            : NA, NA 
##   Repeated confidence intervals (lower)        : -0.2202, 0.0728 
##   Repeated confidence intervals (upper)        : 0.4202, 0.5272 
##   Repeated p-values                            : &gt;0.5, 0.007427 
##   Final stage                                  : 2 
##   Final p-value                                : NA, 0.03132 
##   Final CIs (lower)                            : NA, 0.02666 
##   Final CIs (upper)                            : NA, 0.4864 
##   Median unbiased estimate                     : NA, 0.2702</code></pre>

</div>
</div>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Improving Your Statistical Inferences</strong>" was written by Daniel Lakens. It was last built on 2022-03-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
